/*
Report Name: ERE Table Hits by Staff Assigned to DDERE
Category: Audit Reports  

See docs/audit-reports/ere-table-hits-by-staff-assigned-ddere.md for full documentation.
*/

SELECT HRFORM.EMPLOYEENUMBER,
	HRFORM.FAMCAREUSERID,
	LOG.USERID,
	SUM(
		CASE
			WHEN LOG.[TABLE] IN ('CLIENT','Client')
			THEN 1
			ELSE 0 
		END
	) AS [CLIENT FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'ClientPassport'
			THEN 1
			ELSE 0 
		END
	) AS [CLIENT IDENTIFYING INFORMATION FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'RELATIONSHIP'
			THEN 1
			ELSE 0 
		END
	) AS [RELATIONSHIP FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PROVIDERPLACEMENT'
			THEN 1
			ELSE 0 
		END
	) AS [ENROLLMENT FORM FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PATHWAYCLIENT'
			THEN 1
			ELSE 0 
		END
	) AS [PATHWAY ASSIGNMENT FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PrimaryProviderCodeHistory'
			THEN 1
			ELSE 0 
		END
	) AS [PRIMARY PROVIDER CODE HISTORY FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PlacementProgramWorkerHistory'
			THEN 1
			ELSE 0 
		END
	) AS [PROGRAM WORKER HISTORY FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'CASENOTEDETAIL'
			THEN 1
			ELSE 0 
		END
	) AS [CASE NOTE FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PWEREHospitalVisitNote'
			THEN 1
			ELSE 0 
	END
	) AS [HOSPITAL VISIT NOTE FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PWEREReferral'
			THEN 1
			ELSE 0 
		END
	) AS [REFERRAL FORM HITS],
	SUM(
		CASE 
			WHEN LOG.[TABLE] = 'PWEREIHNA'
			THEN 1 
			ELSE 0 
		END
	) AS [IHNA FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PWEREThreeMonthFollowUp'
			THEN 1
			ELSE 0
		END
	) AS [THREE-MONTH FOLLOW-UP FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PWERESixMonthFollowUp' 
			THEN 1 
			ELSE 0 
		END
	) AS [SIX-MONTH FOLLOW-UP FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PWEREBehavioralHealthService'
			THEN 1
			ELSE 0
		END
	) AS [BEHAVIORAL HEALTH SERVICE FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PWEREClientNeeds'
			THEN 1
			ELSE 0 
		END
	) AS [CLIENT NEEDS FORM HITS],
	SUM(
		CASE
			WHEN LOG.[TABLE] = 'PWHousingStatus'
			THEN 1 
			ELSE 0 
		END
	) AS [HOUSING STATUS FORM HITS],
	SUM(
		CASE 
			WHEN LOG.[TABLE] = 'PWPayorSource'
			THEN 1
			ELSE 0 
		END
	) AS [PAYOR SOURCE FORM HITS]
FROM Q_HRFORM AS [HRFORM]
LEFT JOIN LOG AS [LOG]
	ON HRFORM.FAMCAREUSERID = LOG.Userid
WHERE HRFORM.DDERE = 'ON'
	AND HRFORM.EMPSTATUS = 'Active'
GROUP BY HRFORM.EMPLOYEENUMBER, HRFORM.FAMCAREUSERID, LOG.USERID