/*
Report Name: BCR Caseload Report
Category: Program Management Reports  

See docs/program-management-reports/bcr-caseload-report.md for full documentation.
*/

SELECT BENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST AS [CLIENT LAST],
	C.CLIENT_FIRST AS [CLIENT FIRST],
	C.ZIP_CODE AS [ZIP CODE],
	C.BIRTH_DATE AS [DOB],
	BENROLL.PROGRAM_WORKER_FIRST + ' ' + BENROLL.PROGRAM_WORKER_LAST AS [WORKER],
	BENROLL.ENROLLMENT_STARTING_DATE AS [ENROLLMENT_DATE],
	--	CAST(PWY_START_DATE AS DATE) AS [PWY_START_DATE],
	--	MAX(CASE WHEN PWY_EVENT = 'BCR Referral' THEN CAST(FORM_START_DATE AS DATE) END) AS [REF_START_DATE],
	--	MAX(CASE WHEN PWY_EVENT = 'BCR Referral' AND DAYS_UNTIL_FORM_DUE >= 0 THEN DAYS_UNTIL_FORM_DUE END) AS [DAYS_UNTIL_REF_DUE],
	--	MAX(CASE WHEN PWY_EVENT = 'BCR Referral' AND DAYS_UNTIL_FORM_DUE < 0 THEN DAYS_UNTIL_FORM_DUE END) AS [REF_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN BENROLL.PWY_EVENT = 'BCR Initial Contact' 
			THEN BCRGRANT.DESCRIPTION
		END
	) AS [GRANT_FROM_IC],
	MAX(
		CASE
			WHEN BENROLL.PWY_EVENT = 'BCR Initial Contact' 
			THEN CAST(BENROLL.PE_DATE_ACCOMPLISHED AS DATE)
		END
	) AS [IC_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN BENROLL.PWY_EVENT = 'BCR Initial Contact' 
			THEN BENROLL.PROGRAM_PARTICIPATION
		END
	) AS [IC_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN BENROLL.PWY_EVENT = 'BCR Referrals Placed'
			AND BENROLL.DAYS_UNTIL_FORM_DUE >= 0 
			THEN BENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_BCR_REF_PLACED_DUE],
	MAX(
		CASE
			WHEN BENROLL.PWY_EVENT = 'BCR Referrals Placed'
			AND BENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN BENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [BCR_REF_PLACED_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN BENROLL.PWY_EVENT = 'BCR Referrals Placed' 
			THEN CAST(BENROLL.PE_DATE_ACCOMPLISHED AS DATE)
		END
	) AS [BCR_REF_PLACED_DATE_ACCOMPLISHED],
	MAX(
		CASE 
			WHEN BPAY.PAYOR_SOURCE_UNINSURED = 1 
			THEN 'Yes'
			WHEN BPAY.PAYOR_SOURCE_UNINSURED = 0 
			THEN 'No'
			ELSE NULL
		END
	) AS [UNINSURED],

	MAX(
		CASE 
			WHEN BHOUSE.HOUSING_STATUS_UNHOUSED = 1 
			THEN 'Yes'
			WHEN BHOUSE.HOUSING_STATUS_UNHOUSED = 0 
			THEN 'No'
			ELSE NULL
		END
	) AS [UNHOUSED]
FROM BEHAVHEALT_LIVE.DBO.Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL] 
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON BENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_BCR_IC AS [BIC]
	ON BIC.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.BCR_GRANT AS [BCRGRANT]
	ON BCRGRANT.CODE = BIC.BCR_GRANT
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_BCR_ACTIVE_PAYOR_SOURCE AS [BPAY] 
	ON BENROLL.CLIENT_NUMBER = BPAY.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_BCR_ACTIVE_HOUSING_STATUS AS [BHOUSE] 
	ON BENROLL.CLIENT_NUMBER = BHOUSE.CLIENT_NUMBER
WHERE BENROLL.PWY_EVENT LIKE 'BCR%'
	AND BENROLL.ENROLLMENT_ENDING_DATE IS NULL
	AND (
		CASE
			WHEN BENROLL.ENROLLMENT_ENDING_DATE IS NULL THEN '12-31-2099'
			ELSE BENROLL.ENROLLMENT_ENDING_DATE
		END >= '^^START RANGE|DATEPICKER^^'
		AND BENROLL.ENROLLMENT_STARTING_DATE >= '^^START RANGE|DATEPICKER^^'
		)
GROUP BY BENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	C.ZIP_CODE,
	C.BIRTH_DATE,
	BENROLL.PROGRAM_WORKER_FIRST,
	BENROLL.PROGRAM_WORKER_LAST,
	BENROLL.ENROLLMENT_STARTING_DATE
ORDER BY WORKER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST;