/*
Report Name: BCR Events
Category: Program Management Reports  

See docs/program-management-reports/bcr-events.md for full documentation.
*/

SELECT [EVENT].USERID,
	[EVENT].PATHWAY_DATE,
	[EVENT].EVENT_TYPE,
	[EVENT].EVENT_NAME,
	[EVENT].EVENT_TOPIC,
	[EVENT].EVENT_FORMAT,
	[EVENT].TOTAL_NUM_ATTENDEES,
	[EVENT].NUM_ADULTS,
	[EVENT].NUM_YOUTH,
	[EVENT].NUM_PASTORS,
	[EVENT].NUM_REQUESTED_FU,
	[EVENT].NUM_COMPLETED_SCREENS,
	[EVENT].NUM_INC_KNOWLEDGE,
	[EVENT].EVENT_GRANT_CODE,
	[EVENT].EVENT_GRANT_DESCRIPTION,
	[EVENT].ADDTL_NOTES_EVENT
FROM BEHAVHEALT_LIVE.DBO.Q_BCR_EVENTS AS [EVENT]
WHERE (
		(
				(
				[EVENT].PATHWAY_DATE >= '^^BEGINNING START DATE|DATEPICKER^^' 
					OR '^^BEGINNING START DATE^^' = ''
					)
					AND (
						[EVENT].PATHWAY_DATE <= '^^ENDING START DATE|DATEPICKER^^' 
							OR '^^ENDING START DATE^^' = ''
					)
		)
	AND (
		[EVENT].EVENT_TOPIC = '^^TOPIC|SELECT DISTINCT EVENT_TOPIC AS TOPIC_VALUE, EVENT_TOPIC AS TOPIC_DISPLAY FROM Q_BCR_EVENTS AS EV WHERE EVENT_TOPIC IS NOT NULL AND LTRIM(RTRIM(EVENT_TOPIC)) <> '' ORDER BY EVENT_TOPIC^^'
			OR '^^TOPIC^^' = ''
		)
	AND (
		[EVENT].EVENT_GRANT_DESCRIPTION = '^^GRANT|SELECT DISTINCT EVENT_GRANT_DESCRIPTION AS GRANT_VALUE, EV.EVENT_GRANT_DESCRIPTION AS GRANT_DISPLAY FROM Q_BCR_EVENTS AS EV WHERE EVENT_GRANT_DESCRIPTION IS NOT NULL AND LTRIM(RTRIM(EVENT_GRANT_DESCRIPTION)) <> '' ORDER BY EVENT_GRANT_DESCRIPTION^^'
			OR '^^GRANT^^' = ''
		)
	AND (
		[EVENT].EVENT_TYPE = '^^TYPE|SELECT DISTINCT EVENT_TYPE AS TYPE_VALUE, EVENT_TYPE AS TYPE_DISPLAY FROM Q_BCR_EVENTS AS EV WHERE EVENT_TYPE IS NOT NULL AND LTRIM(RTRIM(EVENT_TYPE)) <> '' ORDER BY EVENT_TYPE^^'
			OR '^^TYPE^^' = ''
		)
	)
UNION ALL
SELECT
	'TOTAL' AS [USERID],
	CAST(NULL AS DATE) AS [PATHWAY_DATE],
	CAST(NULL AS VARCHAR(50)) AS [EVENT_TYPE], 
	CAST(NULL AS VARCHAR(50)) AS [EVENT_NAME], 
	CAST(NULL AS VARCHAR(50)) AS [EVENT_TOPIC], 
	CAST(NULL AS VARCHAR(50)) AS [EVENT_FORMAT],
	SUM(TRY_CAST([EVENT].TOTAL_NUM_ATTENDEES AS INT)),
	SUM(TRY_CAST([EVENT].NUM_ADULTS AS INT)),
	SUM(TRY_CAST([EVENT].NUM_YOUTH AS INT)),
	SUM(TRY_CAST([EVENT].NUM_PASTORS AS INT)),
	SUM(TRY_CAST([EVENT].NUM_REQUESTED_FU AS INT)),
	SUM(TRY_CAST([EVENT].NUM_COMPLETED_SCREENS AS INT)),
	SUM(TRY_CAST([EVENT].NUM_INC_KNOWLEDGE AS INT)),
	CAST(NULL AS VARCHAR(50)) AS [EVENT_GRANT_CODE],
	CAST(NULL AS VARCHAR(100)) AS [EVENT_GRANT_DESCRIPTION],
	CAST(NULL AS VARCHAR(MAX)) AS [ADDTL_NOTES_EVENT]
FROM BEHAVHEALT_LIVE.DBO.Q_BCR_EVENTS AS [EVENT]
WHERE (
		(
				(
				[EVENT].PATHWAY_DATE >= '^^BEGINNING START DATE|DATEPICKER^^' 
					OR '^^BEGINNING START DATE^^' = ''
					)
					AND (
						[EVENT].PATHWAY_DATE <= '^^ENDING START DATE|DATEPICKER^^' 
							OR '^^ENDING START DATE^^' = ''
					)
		)
	AND (
		[EVENT].EVENT_TOPIC = '^^TOPIC|SELECT DISTINCT EVENT_TOPIC AS TOPIC_VALUE, EVENT_TOPIC AS TOPIC_DISPLAY FROM Q_BCR_EVENTS AS EV WHERE EVENT_TOPIC IS NOT NULL AND LTRIM(RTRIM(EVENT_TOPIC)) <> '' ORDER BY EVENT_TOPIC^^'
			OR '^^TOPIC^^' = ''
		)
	AND (
		[EVENT].EVENT_GRANT_DESCRIPTION = '^^GRANT|SELECT DISTINCT EVENT_GRANT_DESCRIPTION AS GRANT_VALUE, EV.EVENT_GRANT_DESCRIPTION AS GRANT_DISPLAY FROM Q_BCR_EVENTS AS EV WHERE EVENT_GRANT_DESCRIPTION IS NOT NULL AND LTRIM(RTRIM(EVENT_GRANT_DESCRIPTION)) <> '' ORDER BY EVENT_GRANT_DESCRIPTION^^'
			OR '^^GRANT^^' = ''
		)
	AND (
		[EVENT].EVENT_TYPE = '^^TYPE|SELECT DISTINCT EVENT_TYPE AS TYPE_VALUE, EVENT_TYPE AS TYPE_DISPLAY FROM Q_BCR_EVENTS AS EV WHERE EVENT_TYPE IS NOT NULL AND LTRIM(RTRIM(EVENT_TYPE)) <> '' ORDER BY EVENT_TYPE^^'
			OR '^^TYPE^^' = ''
		)
	)