/*
Report Name: EPICC EMS Report
Category: Program Management Reports  

See docs/program-management-reports/epicc-ems-report.md for full documentation.
*/

SELECT EENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	C.BIRTH_DATE,
	DATEDIFF(YEAR, C.BIRTH_DATE, 
		MAX(
			CASE 
				WHEN EENROLL.PWY_EVENT = 'EPICC Referral' 
					AND EREF.PATHWAY_DATE IS NOT NULL 
				THEN EREF.PATHWAY_DATE 
			END
		)
	)
	- CASE 
		WHEN DATEADD(
			YEAR,
			DATEDIFF(YEAR, C.BIRTH_DATE, 
				MAX(
					CASE 
						WHEN EENROLL.PWY_EVENT = 'EPICC Referral' 
							AND EREF.PATHWAY_DATE IS NOT NULL 
						THEN EREF.PATHWAY_DATE 
					END
				)
			),
			C.BIRTH_DATE
		) > 
		MAX(
			CASE 
				WHEN EENROLL.PWY_EVENT = 'EPICC Referral' 
					AND EREF.PATHWAY_DATE IS NOT NULL 
				THEN EREF.PATHWAY_DATE 
			END
		) 
		THEN 1 ELSE 0 
	END AS [AGE_AT_REFERRAL],
	C.GENDER_DESCRIPTION AS [GENDER],
	C.RACE_DESCRIPTION AS [RACE],
	C.ETHNICITY_DESCRIPTION AS [ETHNICITY],
	EENROLL.ENROLLMENT_STARTING_DATE AS [ENROLLMENT_DATE],
	EREF.EPICC_REFERRING_AGENCY_DESCRIPTION AS [REFERRING_AGENCY],
	EREF.EMS_FIRE_DISTRICT_PLACE_REFERRAL_IN_TRANSIT [EMS_PLACE_REFERAL_IN_TRANSIT],
	EREF.EMS_FIRE_DISTRICT_DESCRIPTION AS [EMS_FIRE_DISTRICT],
	EREF.EMERGENCY_RESPONSE_CALL,
	EREF.SUBOXONE_EMS,
	EREF.WHO_ADMINISTERED_SUBOXONE,
	EREF.MILLIGRAMS_SUBOXONE,
	EREF.EMS_TRANSPORT_TO_HOSPITAL_DESCRIPTION AS [EMS_TRANSPORT_TO_HOSPITAL],
	EREF.REFERRER_NAME AS [REFERRER],
	EREF.REFERRER_PHONE,
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
		) AS [REF_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [IC_PROGRAM_PARTICIPATION],
	EIC.TREATMENT_PATH_IC,
	EIC.OVERDOSE_EVENT_REFERRAL,
	ESUTX.EPICC_SU_TX_AGENCY_DESCRIPTION,
	ESUTX.VISITDT,
	EIC.CURRENT_SU_TREATMENT,
	MAX(EPAY.MANAGED_MEDICAID_PROVIDER_DESCRIPTION) AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
	MAX(EPAY.PAYOR_SOURCE_DUAL_ELIGIBLE) AS [PAYOR_SOURCE_DUAL_ELIGIBLE],
	MAX(EPAY.PAYOR_SOURCE_MANAGED_MEDICAID) AS [PAYOR_SOURCE_MANAGED_MEDICAID],
	MAX(EPAY.PAYOR_SOURCE_MEDICAID) AS [PAYOR_SOURCE_MEDICAID],
	MAX(EPAY.PAYOR_SOURCE_MEDICAID_IN_PROGRESS) AS [PAYOR_SOURCE_MEDICAID_IN_PROGRESS],
	MAX(EPAY.PAYOR_SOURCE_MEDICAID_CHP) AS [PAYOR_SOURCE_MEDICAID_CHP],
	MAX(EPAY.PAYOR_SOURCE_MEDICARE) AS [PAYOR_SOURCE_MEDICARE],
	MAX(EPAY.PAYOR_SOURCE_PRIVATE_INSURANCE) AS [PAYOR_SOURCE_PRIVATE_INSURANCE],
	MAX(EPAY.PAYOR_SOURCE_UNINSURED) AS [PAYOR_SOURCE_UNINSURED],
	MAX(EPAY.PAYOR_SOURCE_UNKNOWN_REFUSED) AS [PAYOR_SOURCE_UNKNOWN_REFUSED],
	MAX(EPAY.PAYOR_SOURCE_VA_BENEFITS) AS [PAYOR_SOURCE_VA_BENEFITS],
	MAX(EHOUSE.HOUSING_STATUS_INSTITUTIONALLY_HOUSED) AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	MAX(EHOUSE.HOUSING_STATUS_PRECARIOUSLY_HOUSED) AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	MAX(EHOUSE.HOUSING_STATUS_STABLY_HOUSED) AS [HOUSING_STATUS_STABLY_HOUSED],
	MAX(EHOUSE.HOUSING_STATUS_UNHOUSED) AS [HOUSING_STATUS_UNHOUSED],
	MAX(EHOUSE.HOUSING_STATUS_UNKNOWN) AS [HOUSING_STATUS_UNKNOWN]
FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL] 
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON EENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_REFERRAL AS [EREF]
	ON EREF.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_IC AS [EIC]
	ON EIC.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_LATEST_SU_TX_AGENCY AS [ESUTX]
	ON ESUTX.CLIENT_NUMBER = EENROLL.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_ACTIVE_PAYOR_SOURCE AS [EPAY] 
	ON EENROLL.CLIENT_NUMBER = EPAY.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_ACTIVE_HOUSING_STATUS AS [EHOUSE]
	ON EENROLL.CLIENT_NUMBER = EHOUSE.CLIENT_NUMBER
WHERE EENROLL.PWY_EVENT LIKE 'EPICC%'
	AND (
		EREF.EPICC_REFERRING_AGENCY_CODE = '073'
		OR EREF.EMS_INVOLVED_REF = 'Yes'
		)
		AND (
				(
				EENROLL.ENROLLMENT_STARTING_DATE >= '^^BEGNINNING ENROLLMENT START DATE|DATEPICKER^^' 
					OR '^^BEGNINNING ENROLLMENT START DATE^^' = ''
					)
					AND (
						EENROLL.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT START DATE|DATEPICKER^^' 
							OR '^^ENDING ENROLLMENT START DATE^^' = ''
					)
		)
GROUP BY EENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	C.BIRTH_DATE,
	C.GENDER_DESCRIPTION,
	C.RACE_DESCRIPTION,
	C.ETHNICITY_DESCRIPTION,
	EENROLL.ENROLLMENT_STARTING_DATE,
	EREF.EPICC_REFERRING_AGENCY_DESCRIPTION,
	EREF.EMS_FIRE_DISTRICT_PLACE_REFERRAL_IN_TRANSIT,
	EREF.EMS_FIRE_DISTRICT_DESCRIPTION,
	EREF.EMERGENCY_RESPONSE_CALL,
	EREF.SUBOXONE_EMS,
	EREF.WHO_ADMINISTERED_SUBOXONE,
	EREF.MILLIGRAMS_SUBOXONE,
	EREF.EMS_TRANSPORT_TO_HOSPITAL_DESCRIPTION,
	EREF.REFERRER_NAME,
	EREF.REFERRER_PHONE,
	EIC.TREATMENT_PATH_IC,
	EIC.OVERDOSE_EVENT_REFERRAL,
	ESUTX.EPICC_SU_TX_AGENCY_DESCRIPTION,
	ESUTX.VISITDT,
	EIC.CURRENT_SU_TREATMENT
HAVING 
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) IS NOT NULL;