/*
Report Name: EPICC Candidates for Dismissal
Category: Program Management Reports  

See docs/program-management-reports/epicc-candidates-for-dismissal.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

SELECT PP.CLIENTNUMBER AS [CLIENT_NUMBER],
	HR.LASTNAME AS [STAFF_LAST],
	HR.FIRSTNAME AS [STAFF_FIRST],
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	C.CLIENT_LAST AS [LAST_NAME],
	C.CLIENT_FIRST AS [FIRST_NAME],
	MAX(
		CASE
			WHEN ETHIRTYD.TREATMENT_PATH_THIRTY_DAY IS NOT NULL
			THEN ETHIRTYD.TREATMENT_PATH_THIRTY_DAY
			WHEN ETWOW.TREATMENT_PATH_TWO_WEEK IS NOT NULL
			THEN ETWOW.TREATMENT_PATH_TWO_WEEK
			ELSE EIC.TREATMENT_PATH_IC
		END
	) AS [MOST_RECENT_TREATMENT_PATH],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
			THEN EREF.EPICC_PROGRAM_PARTICIPATION_REFERRAL_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_REFERRAL],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
			THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_IC],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
			THEN EIC.STATUS_UNABLE_CONTACT_TRANSFER
		END
	) AS [STATUS_UNABLE_CONTACT_TRANSFER],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
			THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_TWO_WEEK],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
			THEN ETWOW.CLIENT_STATUS_TWO_WEEK
		END
	) AS [CLIENT_STATUS_TWO_WEEK],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
			THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_THIRTY_DAY],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
			THEN ETHIRTYD.CLIENT_STATUS_THIRTY_DAY
		END
	) AS [CLIENT_STATUS_THIRTY_DAY],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
			THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_THREE_MONTH],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
			THEN ETHREEM.CLIENT_STATUS_THREE_MONTH
		END
	) AS [CLIENT_STATUS_THREE_MONTH],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
			THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_SIX_MONTH]
FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.CLOSINGREASONS AS [CR] 
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN (
	SELECT 
		PC.*,
		'DOCSERNO Join' AS JOIN_TYPE
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS PC_DOCSERNO
	ON PP.CLIENTNUMBER = PC_DOCSERNO.CLIENTNUMBER
	AND PC_DOCSERNO.DOCSERNO = PP.DOCSERNO
LEFT JOIN (
	SELECT 
		PC.*,
		'Enrollment/Pathway Start Date Join' AS JOIN_TYPE
	FROM PATHWAYCLIENT AS PC
	WHERE PC.DOCREVNO = ' 0 '
) AS PC_START
	ON PP.CLIENTNUMBER = PC_START.CLIENTNUMBER
	AND PP.STARTINGDATE = PC_START.STARTDATE
	AND PP.PATHWAY = PC_START.PARENTDOCSERNO
LEFT JOIN PATHWAYEVENTCLIENT AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.PATHCLIENTDOCSERNO = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENT AS [PE] 
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAY AS [PWY] 
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDER AS [P] 
	ON PP.PRIMARYPROVIDERCODE = P.PROVIDERCODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR] 
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HRR] 
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_REFERRAL AS [EREF]
	ON EREF.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND EREF.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND EREF.EVENT_NAME = 'EPICC Referral'
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_IC AS [EIC] 
	ON EIC.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND EIC.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND EIC.EVENT_NAME = 'EPICC Initial Contact'
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_TWO_WEEK AS [ETWOW] 
	ON ETWOW.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ETWOW.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND ETWOW.EVENT_NAME = 'EPICC 2 Week'
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_THIRTY_DAY AS [ETHIRTYD] 
	ON ETHIRTYD.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ETHIRTYD.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND ETHIRTYD.EVENT_NAME = 'EPICC 30 Day'
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_THREE_MONTH AS [ETHREEM] 
	ON ETHREEM.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ETHREEM.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND ETHREEM.EVENT_NAME = 'EPICC 3 Month'
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_SIX_MONTH AS [ESIXM] 
	ON ESIXM.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ESIXM.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND ESIXM.EVENT_NAME = 'EPICC 6 Month'
WHERE PP.PATHWAY = 55320240807113504583
	AND PP.DOCREVNO = ' 0 '
	AND PP.ENDINGDATE IS NULL
GROUP BY PP.CLIENTNUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE),
	CAST(PP.ENDINGDATE AS DATE),
	P.PROVIDERNAME,
	HR.LASTNAME,
	HR.FIRSTNAME
HAVING
(
	MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month'
			THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
	   END) IS NOT NULL
	OR
	(
	MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month'
			THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
		END) IS NULL

	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
				THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
			END) IS NOT NULL
	 AND 
		MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
				THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
			END) <> 'Engaged'
			AND NOT (
					MAX(
						CASE
							WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
							THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
						END) = 'Not Engaged'
						AND MAX(
								CASE 
									WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
									THEN ETHREEM.CLIENT_STATUS_THREE_MONTH
								END) IN ('Outreaching', 'Transfer To Re-Engagement Specialist'
							)
					)
	)
	OR
	(
	MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month'
			THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
		 END) IS NULL
	AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
			THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
		END) IS NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day'
				THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
			END) IS NOT NULL
	AND 
		MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day'
				THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
			END) <> 'Engaged'
			AND NOT (
					MAX(
						CASE 
							WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day'
							THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
						END) = 'Not Engaged'
						AND MAX(
							CASE 
								WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day'
								THEN ETHIRTYD.CLIENT_STATUS_THIRTY_DAY
							END) IN ('Outreaching', 'Transfer To Re-Engagement Specialist'
						)
				)
	)
	OR
	(
	MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month'
			THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
		END) IS NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
				THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
			END) IS NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day'
				THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
			END) IS NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week'
				THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
			END) IS NOT NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week'
				THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
			END) NOT IN ('Engaged', 'Not Engaged')
	)
	OR
	(
	MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month'
			THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
		END) IS NULL
	AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
			THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
		END) IS NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day'
				THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
			END) IS NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week'
				THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
			END) IS NULL
	AND MAX(
			CASE 
				WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact'
				THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
			END) <> 'Enrolled With EPICC'
	)
	OR
	(
	MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month'
			THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
		END) IS NULL
	AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month'
			THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
		END) IS NULL
	AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day'
			THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
		END) IS NULL
	AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week'
			THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
		END) IS NULL
	AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact'
			THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
		END) IS NULL
	AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC Referral'
			THEN EREF.EPICC_PROGRAM_PARTICIPATION_REFERRAL_DESCRIPTION
		END) <> 'Eligible For Services'
	)
)