/*
Report Name: EPICC Caseload Report
Category: Program Management Reports  

See docs/program-management-reports/epicc-caseload-report.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

SELECT EENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST AS [CLIENT LAST],
	C.CLIENT_FIRST AS [CLIENT FIRST],
	EENROLL.PROGRAM_WORKER_FIRST + ' ' + EENROLL.PROGRAM_WORKER_LAST AS [WORKER],
	EENROLL.AGENCY_DESCRIPTION AS [AGENCY],
	EENROLL.ENROLLMENT_STARTING_DATE AS [ENROLLMENT_DATE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact'
			THEN EENROLL.PRO_OR_CORE
		END
		) AS [PRO_OR_CORE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact' 
			THEN EENROLL.TREATMENT_PATH
		END
	) AS [IC_TREATMENT_PATH],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact' 
			THEN CAST(EENROLL.PE_DATE_ACCOMPLISHED AS DATE)
		END
	) AS [IC_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [IC_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 2 Week' 
			THEN EENROLL.TREATMENT_PATH
		END
	) AS [2_WEEK_TREATMENT_PATH],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 2 Week'
			AND EENROLL.DAYS_UNTIL_FORM_DUE >= 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_2_WEEK_DUE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 2 Week'
			AND EENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [2_WEEK_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 2 Week' 
			THEN CAST(EENROLL.PE_DATE_ACCOMPLISHED AS DATE)
		END
	) AS [2_WEEK_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 2 Week' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [2_WEEK_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 30 Day' 
			THEN EENROLL.TREATMENT_PATH
		END
	) AS [30_DAY_TREATMENT_PATH],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 30 Day'
			AND EENROLL.DAYS_UNTIL_FORM_DUE >= 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_30_DAY_DUE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 30 Day'
			AND EENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [30_DAY_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 30 Day' 
			THEN CAST(EENROLL.PE_DATE_ACCOMPLISHED AS DATE)
		END
	) AS [30_DAY_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 30 Day' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [30_DAY_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 3 Month' 
			THEN EENROLL.TREATMENT_PATH
		END
	) AS [3_MONTH_TREATMENT_PATH],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 3 Month'
			AND EENROLL.DAYS_UNTIL_FORM_DUE >= 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_3_MONTH_DUE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 3 Month'
			AND EENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [3_MONTH_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 3 Month' 
			THEN CAST(PE_DATE_ACCOMPLISHED AS DATE)
		END
	) AS [3_MONTH_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 3 Month' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [3_MONTH_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 6 Month'
			AND EENROLL.DAYS_UNTIL_FORM_DUE >= 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_6_MONTH_DUE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 6 Month'
			AND EENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN EENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [6_MONTH_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 6 Month' 
			THEN CAST(EENROLL.PE_DATE_ACCOMPLISHED AS DATE)
		END
	) AS [6_MONTH_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 6 Month' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [6_MONTH_PROGRAM_PARTICIPATION]
FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL] 
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON EENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
WHERE EENROLL.PWY_EVENT LIKE 'EPICC%'
	AND EENROLL.ENROLLMENT_ENDING_DATE IS NULL
	AND (
		CASE
			WHEN EENROLL.ENROLLMENT_ENDING_DATE IS NULL THEN '12-31-2099'
			ELSE EENROLL.ENROLLMENT_ENDING_DATE
		END >= '^^START RANGE|DATEPICKER^^'
		AND EENROLL.ENROLLMENT_STARTING_DATE >= '^^START RANGE|DATEPICKER^^'
		)
GROUP BY EENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	EENROLL.PROGRAM_WORKER_FIRST,
	EENROLL.PROGRAM_WORKER_LAST,
	EENROLL.ENROLLMENT_STARTING_DATE,
	EENROLL.AGENCY_DESCRIPTION
ORDER BY AGENCY_DESCRIPTION,
	WORKER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST;