/*
Report Name: EPICC EMS Report
Category: Program Management Reports  

See docs/program-management-reports/epicc-ems-report.md for full documentation.
*/

SELECT EENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	C.BIRTH_DATE,
	DATEDIFF(YEAR, C.BIRTH_DATE, 
		MAX(
			CASE 
				WHEN EENROLL.PWY_EVENT = 'EPICC Referral' 
					AND EREF.PATHWAY_DATE IS NOT NULL 
				THEN EREF.PATHWAY_DATE 
			END
		)
	)
	- CASE 
		WHEN DATEADD(
			YEAR,
			DATEDIFF(YEAR, C.BIRTH_DATE, 
				MAX(
					CASE 
						WHEN EENROLL.PWY_EVENT = 'EPICC Referral' 
							AND EREF.PATHWAY_DATE IS NOT NULL 
						THEN EREF.PATHWAY_DATE 
					END
				)
			),
			C.BIRTH_DATE
		) > 
		MAX(
			CASE 
				WHEN EENROLL.PWY_EVENT = 'EPICC Referral' 
					AND EREF.PATHWAY_DATE IS NOT NULL 
				THEN EREF.PATHWAY_DATE 
			END
		) 
		THEN 1 ELSE 0 
	END AS [AGE_AT_REFERRAL],
	C.GENDER_DESCRIPTION AS [GENDER],
	C.RACE_DESCRIPTION AS [RACE],
	C.ETHNICITY_DESCRIPTION AS [ETHNICITY],
	EENROLL.PROGRAM_WORKER_LAST,
	EENROLL.PROGRAM_WORKER_FIRST,
	EENROLL.ENROLLMENT_STARTING_DATE AS [ENROLLMENT_DATE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.EPICC_REFERRING_AGENCY_DESCRIPTION
			END
		) AS [REFERRING_AGENCY],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.EMS_FIRE_DISTRICT_PLACE_REFERRAL_IN_TRANSIT
			END
		) AS [EMS_PLACE_REFERRAL_IN_TRANSIT],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.EMS_FIRE_DISTRICT_DESCRIPTION
			END
		) AS [EMS_FIRE_DISTRICT],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.OTHER_EMS_FIRE_DISTRICT
			END
		) AS [OTHER_EMS_FIRE_DISTRICT],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.EMERGENCY_RESPONSE_CALL
			END
		) AS [EMERGENCY_RESPONSE_CALL],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.SUBOXONE_EMS
			END
		) AS [SUBOXONE_EMS],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.WHO_ADMINISTERED_SUBOXONE
			END
		) AS [WHO_ADMINISTERED_SUBOXONE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.MILLIGRAMS_SUBOXONE
			END
		) AS [MILLIGRAMS_SUBOXONE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.EMS_TRANSPORT_TO_HOSPITAL_DESCRIPTION
			END
		) AS [EMS_TRANSPORT_TO_HOSPITAL],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.REFERRER_NAME
			END
		) AS [REFERRER],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EREF.REFERRER_PHONE
			END
		) AS [REFERRER_PHONE],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
		) AS [REF_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [IC_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 2 Week' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [TWO_WEEK_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 30 Day' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [THIRTY_DAY_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 3 Month' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [THREE_MONTH_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC 6 Month' 
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) AS [SIX_MONTH_PROGRAM_PARTICIPATION],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact'
			THEN EIC.TREATMENT_PATH_IC
			END
		) AS [TREATMENT_PATH_IC],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact'
			THEN EIC.OVERDOSE_EVENT_REFERRAL
			END
		) AS [OVERDOSE_EVENT_REFERRAL],
	ESUTX.EPICC_SU_TX_AGENCY_DESCRIPTION,
	ESUTX.VISITDT AS [EPICC_SU_TX_AGENCY_VISITDT],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Initial Contact'
			THEN EIC.CURRENT_SU_TREATMENT
			END
		) AS [CURRENT_SU_TREATMENT],
	MAX(EPAY.MANAGED_MEDICAID_PROVIDER_DESCRIPTION) AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
	MAX(EPAY.PAYOR_SOURCE_DUAL_ELIGIBLE) AS [PAYOR_SOURCE_DUAL_ELIGIBLE],
	MAX(EPAY.PAYOR_SOURCE_MANAGED_MEDICAID) AS [PAYOR_SOURCE_MANAGED_MEDICAID],
	MAX(EPAY.PAYOR_SOURCE_MEDICAID) AS [PAYOR_SOURCE_MEDICAID],
	MAX(EPAY.PAYOR_SOURCE_MEDICAID_IN_PROGRESS) AS [PAYOR_SOURCE_MEDICAID_IN_PROGRESS],
	MAX(EPAY.PAYOR_SOURCE_MEDICAID_CHP) AS [PAYOR_SOURCE_MEDICAID_CHP],
	MAX(EPAY.PAYOR_SOURCE_MEDICARE) AS [PAYOR_SOURCE_MEDICARE],
	MAX(EPAY.PAYOR_SOURCE_PRIVATE_INSURANCE) AS [PAYOR_SOURCE_PRIVATE_INSURANCE],
	MAX(EPAY.PAYOR_SOURCE_UNINSURED) AS [PAYOR_SOURCE_UNINSURED],
	MAX(EPAY.PAYOR_SOURCE_UNKNOWN_REFUSED) AS [PAYOR_SOURCE_UNKNOWN_REFUSED],
	MAX(EPAY.PAYOR_SOURCE_VA_BENEFITS) AS [PAYOR_SOURCE_VA_BENEFITS],
	MAX(EHOUSE.HOUSING_STATUS_INSTITUTIONALLY_HOUSED) AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	MAX(EHOUSE.HOUSING_STATUS_PRECARIOUSLY_HOUSED) AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	MAX(EHOUSE.HOUSING_STATUS_STABLY_HOUSED) AS [HOUSING_STATUS_STABLY_HOUSED],
	MAX(EHOUSE.HOUSING_STATUS_UNHOUSED) AS [HOUSING_STATUS_UNHOUSED],
	MAX(EHOUSE.HOUSING_STATUS_UNKNOWN) AS [HOUSING_STATUS_UNKNOWN]
FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL] 
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON EENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_REFERRAL AS [EREF]
	ON EREF.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_IC AS [EIC]
	ON EIC.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_TWO_WEEK AS [ETWOW]
	ON ETWOW.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_THIRTY_DAY AS [ETHIRTYD]
	ON ETHIRTYD.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_THREE_MONTH AS [ETHREEM]
	ON ETHREEM.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_SIX_MONTH AS [ESIXM]
	ON ESIXM.DOCSERNO = EENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_LATEST_SU_TX_AGENCY AS [ESUTX]
	ON ESUTX.CLIENT_NUMBER = EENROLL.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_ACTIVE_PAYOR_SOURCE AS [EPAY] 
	ON EENROLL.CLIENT_NUMBER = EPAY.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_ACTIVE_HOUSING_STATUS AS [EHOUSE]
	ON EENROLL.CLIENT_NUMBER = EHOUSE.CLIENT_NUMBER
WHERE EENROLL.PWY_EVENT LIKE 'EPICC%'
		AND (
				(
				EENROLL.ENROLLMENT_STARTING_DATE >= '^^BEGNINNING ENROLLMENT START DATE|DATEPICKER^^' 
					OR '^^BEGNINNING ENROLLMENT START DATE^^' = ''
					)
					AND (
						EENROLL.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT START DATE|DATEPICKER^^' 
							OR '^^ENDING ENROLLMENT START DATE^^' = ''
					)
		)
GROUP BY EENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	C.BIRTH_DATE,
	C.GENDER_DESCRIPTION,
	C.RACE_DESCRIPTION,
	C.ETHNICITY_DESCRIPTION,
	EENROLL.PROGRAM_WORKER_LAST,
	EENROLL.PROGRAM_WORKER_FIRST,
	EENROLL.ENROLLMENT_STARTING_DATE,
	ESUTX.EPICC_SU_TX_AGENCY_DESCRIPTION,
	ESUTX.VISITDT
HAVING 
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
			THEN EENROLL.PROGRAM_PARTICIPATION
		END
	) IS NOT NULL
	AND MAX(
			CASE 
				WHEN EENROLL.PWY_EVENT = 'EPICC Referral'
				THEN 
					CASE 
						WHEN EREF.EPICC_REFERRING_AGENCY_CODE = '073'
							OR EREF.EMS_INVOLVED_REF = 'Yes'
						THEN 1 
						ELSE 0 
					END
			END
		) = 1