/*
Report Name: EPICC Candidates for Re-Engagement or Dismissal
Category: Program Management Reports  

See docs/program-management-reports/epicc-candidates-for-re-engagement-or-dismissal.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

SELECT C.CLIENT_NUMBER,
	HR.LASTNAME AS [STAFF_LAST],
	HR.FIRSTNAME AS [STAFF_FIRST],
	CAST(PP.ENROLLMENT_STARTING_DATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	MAX(
		CASE
			WHEN ETHIRTYD.TREATMENT_PATH_THIRTY_DAY IS NOT NULL
			THEN ETHIRTYD.TREATMENT_PATH_THIRTY_DAY
			WHEN ETWOW.TREATMENT_PATH_TWO_WEEK IS NOT NULL
			THEN ETWOW.TREATMENT_PATH_TWO_WEEK
			ELSE EIC.TREATMENT_PATH_IC
		END
	) AS [MOST_RECENT_TREATMENT_PATH],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
			THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_IC],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
			THEN EIC.STATUS_UNABLE_CONTACT_TRANSFER
		END
	) AS [STATUS_UNABLE_CONTACT_TRANSFER],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
			THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_TWO_WEEK],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
			THEN ETWOW.CLIENT_STATUS_TWO_WEEK
		END
	) AS [CLIENT_STATUS_TWO_WEEK],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
			THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
		END
	) AS [PROGRAM_PARTICIPATION_THIRTY_DAY],
	MAX(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
			THEN ETHIRTYD.CLIENT_STATUS_THIRTY_DAY
		END
	) AS [CLIENT_STATUS_THIRTY_DAY]
FROM BEHAVHEALT_LIVE.DBO.Q_PROVIDERPLACEMENT_BHN AS [PP]
	INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
		ON C.CLIENT_NUMBER = PP.CLIENT_NUMBER
	LEFT JOIN BEHAVHEALT_LIVE.DBO.CLOSINGREASONS AS [CR] 
		ON PP.DISMISSAL_REASON_CODE = CR.CODE
	INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYCLIENT AS [PC] 
		ON PP.CLIENT_NUMBER = PC.CLIENTNUMBER
		AND PC.DOCREVNO = ' 0 '
	INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENTCLIENT AS [PEC] 
		ON PC.DOCSERNO = PEC.PATHCLIENTDOCSERNO
		AND PEC.DOCREVNO = ' 0 '
	INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENT AS [PE] 
		ON PEC.EVENTDOCSERNO = PE.DOCSERNO
		AND PE.DOCREVNO = ' 0 '
	INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAY AS [PWY] 
		ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
		AND PWY.DOCREVNO = ' 0 '
	INNER JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDER AS [P] 
		ON PP.AGENCY_CODE = P.PROVIDERCODE
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR] 
		ON HR.EMPLOYEENUMBER = PP.PROGRAM_WORKER
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HRR] 
		ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_IC AS [EIC] 
		ON EIC.CLIENT_NUMBER = PP.CLIENT_NUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND EIC.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND EIC.EVENT_NAME = 'EPICC Initial Contact'
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_TWO_WEEK AS [ETWOW] 
		ON ETWOW.CLIENT_NUMBER = PP.CLIENT_NUMBER
		AND PP.PATHWAY = 55320240807113504583
		AND ETWOW.PATHWAY_DATE = PEC.DATEACCOMPLISHED
		AND ETWOW.EVENT_NAME = 'EPICC 2 Week'
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_THIRTY_DAY AS [ETHIRTYD] 
		ON ETHIRTYD.CLIENT_NUMBER = PP.CLIENT_NUMBER
		AND PP.PATHWAY = 55320240807113504583
		AND ETHIRTYD.PATHWAY_DATE = PEC.DATEACCOMPLISHED
		AND ETHIRTYD.EVENT_NAME = 'EPICC 30 Day'
WHERE PP.PATHWAY = 55320240807113504583
	AND PP.ENROLLMENT_ENDING_DATE IS NULL
GROUP BY PP.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.ENROLLMENT_STARTING_DATE AS DATE),
	CAST(PP.ENROLLMENT_ENDING_DATE AS DATE),
	P.PROVIDERNAME,
	HR.LASTNAME,
	HR.FIRSTNAME
HAVING (
		(
			MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
					THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
				END
			) IS NOT NULL
			AND MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
					THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
				END
			) IS NOT NULL
			AND MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
					THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
				END
			) IS NOT NULL
		)
		OR (
			MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
					THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
				END
			) IS NULL
			AND MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
					THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
				END
			) IS NOT NULL
			AND MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
					THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
				END
			) IS NOT NULL
		)
		OR (
			MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
					THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
				END
			) IS NULL
			AND MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
					THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
				END
			) IS NULL
			AND MAX(
				CASE
					WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
					THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
				END
			) IS NOT NULL
		)
	)
AND MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
			THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION 
		END
		) LIKE 'Enrolled%'
OR MAX(
		CASE 
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
			THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION 
		END
		) LIKE 'Unable%';