/*
Report Name: ERE Completer And Contact Report
Category: Program Management Reports  

See docs/program-management-reports/ere-completer-and-contact-report.md for full documentation.
*/

SELECT DISTINCT 
   EREENROLL.CLIENT_NUMBER, 
   EREENROLL.CLIENT_LAST, 
   EREENROLL.CLIENT_FIRST, 
   EREENROLL.ENROLLMENT_STARTING_DATE, 
   EREENROLL.ENROLLMENT_ENDING_DATE,
   EREENROLL.PROGRAM_WORKER_LAST, 
   EREENROLL.PROGRAM_WORKER_FIRST, 
   EREIHNA.PATHWAY_DATE AS [IHNA_PATHWAY_DATE],
   EREIHNA.COMPLETION_HELPER_IHNA AS [IHNA_COMPLETION_HELPER], 
   EREIHNA.OTHER_COMPLETION_HELPER_IHNA AS [IHNA_OTHER_COMPLETION_HELPER], 
   EREIHNA.METHOD_OF_CONTACT_IHNA AS [IHNA_METHOD_OF_CONTACT], 
   EREIHNA.METHOD_OF_CONTACT_OTHER_IHNA AS [IHNA_METHOD_OF_CONTACT_OTHER]
FROM Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
INNER JOIN Q_ERE_IHNA AS [EREIHNA]
	ON EREENROLL.TIEDENROLLMENT = EREIHNA.TIEDENROLLMENT
-- WHERE 
	-- (
		-- (EREENROLL.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
		 -- OR '^^BEGINNING ENROLLMENT DATE^^' = '')
	-- )
-- AND (
		-- (EREENROLL.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
		 -- OR '^^ENDING ENROLLMENT DATE^^' = '')
	-- )
-- AND (
		-- (EREENROLL.ENROLLMENT_ENDING_DATE >= '^^BEGINNING DISMISSAL DATE|DATEPICKER^^'
		 -- OR '^^BEGINNING DISMISSAL DATE^^' = '')
	-- )
-- AND (
		-- (EREENROLL.ENROLLMENT_ENDING_DATE <= '^^ENDING DISMISSAL DATE|DATEPICKER^^'
		 -- OR '^^ENDING DISMISSAL DATE^^' = '')
	-- )
-- AND (
		-- (EREENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER =
			-- '^^PROGRAM WORKER|SELECT DISTINCT HR.EMPLOYEENUMBER, HR.EMPLOYEENAME
			  -- FROM Q_PROVIDERPLACEMENT_BHN AS PP
			  -- INNER JOIN Q_HRFORM HR ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER
			  -- WHERE PP.PATHWAY = '55320250326123001961'
				-- AND PP.PROGRAM_WORKER IS NOT NULL
			  -- ORDER BY HR.EMPLOYEENAME^^'
		 -- OR '^^PROGRAM WORKER^^' = '')
	-- )
	;