/*
Report Name: ERE Needs Report
Category: Program Management Reports  

See docs/program-management-reports/ere-needs-report.md for full documentation.
*/

SELECT *
FROM Q_ERE_NEEDS_REPORT AS ENEEDS
WHERE 
	(
		(ENEEDS.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
		 OR '^^BEGINNING ENROLLMENT DATE^^' = '')
	)
AND (
		(ENEEDS.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
		 OR '^^ENDING ENROLLMENT DATE^^' = '')
	)
AND (
		(ENEEDS.ENROLLMENT_ENDING_DATE >= '^^BEGINNING DISMISSAL DATE|DATEPICKER^^'
		 OR '^^BEGINNING DISMISSAL DATE^^' = '')
	)
AND (
		(ENEEDS.ENROLLMENT_ENDING_DATE <= '^^ENDING DISMISSAL DATE|DATEPICKER^^'
		 OR '^^ENDING DISMISSAL DATE^^' = '')
	)
AND (
		(ENEEDS.PROGRAM_WORKER_EMPLOYEE_NUMBER =
			'^^PROGRAM WORKER|SELECT DISTINCT HR.EMPLOYEENUMBER, HR.EMPLOYEENAME
			  FROM Q_PROVIDERPLACEMENT_BHN AS PP
			  INNER JOIN Q_HRFORM HR ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER
			  WHERE PP.PATHWAY = ''55320250326123001961''
				AND PP.PROGRAM_WORKER IS NOT NULL
			  ORDER BY HR.EMPLOYEENAME^^'
		 OR '^^PROGRAM WORKER^^' = '')
	);