-- Mental Health Conditions
WITH [MH] AS (
	SELECT ROW_NUMBER() OVER (
			ORDER BY (
					SELECT NULL
				)
		) AS [RN],
		'ADD/ADHD' AS [MH_CONDITION],
		COUNT(*) AS [MH_COUNT]
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_ADD_ADHD = 1
	UNION ALL
	SELECT 2,
		'Alzheimer’s',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_ALZHEIMERS = 1
	UNION ALL
	SELECT 3,
		'Antisocial Personality Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_ANTISOCIAL_PERSONALITY_DISORDER = 1
	UNION ALL
	SELECT 4,
		'Autism Spectrum Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_AUTISM_SPECTRUM_DISORDER = 1
	UNION ALL
	SELECT 5,
		'Bipolar Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_BIPOLAR_DISORDER = 1
	UNION ALL
	SELECT 6,
		'Borderline Personality Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_BORDERLINE_PERSONALITY_DISORDER = 1
	UNION ALL
	SELECT 7,
		'Developmental/Intellectual Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_DD_INTELLECTUAL_DISORDER = 1
	UNION ALL
	SELECT 8,
		'Delusional Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_DELUSIONAL = 1
	UNION ALL
	SELECT 9,
		'Dementia',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_DEMENTIA = 1
	UNION ALL
	SELECT 10,
		'Depression',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_DEPRESSION = 1
	UNION ALL
	SELECT 11,
		'Eating Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_EATING_DISORDER = 1
	UNION ALL
	SELECT 12,
		'OCD',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_OCD = 1
	UNION ALL
	SELECT 13,
		'Panic/Anxiety',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_PANIC_ANXIETY = 1
	UNION ALL
	SELECT 14,
		'PTSD',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_PTSD = 1
	UNION ALL
	SELECT 15,
		'Schizophrenia',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_SCHIZOPHRENIA = 1
	UNION ALL
	SELECT 16,
		'Sleep Disorder',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_SLEEP_DISORDER = 1
	UNION ALL
	SELECT 17,
		'Other Psychiatric',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_OTHER_PSYCHIOTIC_DISORDER = 1
	UNION ALL
	SELECT 18,
		'Other (Unspecified)',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_OTHER = 1
	UNION ALL
	SELECT 19,
		'Unknown/Refused',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_UNKNOWN_REFUSED = 1
	UNION ALL
	SELECT 20,
		'None Reported',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.MH_HX_NONE = 1
),
-- Substance Use Conditions
[SU] AS (
	SELECT ROW_NUMBER() OVER (
			ORDER BY (
					SELECT NULL
				)
		) AS [RN],
		'Alcohol' AS [SU_CONDITION],
		COUNT(*) AS [SU_COUNT]
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_ALCOHOL = 1
	UNION ALL
	SELECT 2,
		'Cocaine',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_COCAINE = 1
	UNION ALL
	SELECT 3,
		'Hallucinogens',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_HALLUCINOGENS = 1
	UNION ALL
	SELECT 4,
		'Heroin',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_HEROIN = 1
	UNION ALL
	SELECT 5,
		'Inhalants',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_INHALANTS = 1
	UNION ALL
	SELECT 6,
		'Marijuana',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_MARIJUANA = 1
	UNION ALL
	SELECT 7,
		'Methamphetamine',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_METHAMPHETAMINE = 1
	UNION ALL
	SELECT 8,
		'Prescription Opioids',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_PRESCRIPTION_OPIOIDS = 1
	UNION ALL
	SELECT 9,
		'Prescription Sedatives',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_PRESCRIPTION_SEDATIVES = 1
	UNION ALL
	SELECT 10,
		'Prescription Stimulants',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_PRESCRIPTION_STIMULANTS = 1
	UNION ALL
	SELECT 11,
		'Synthetic Drugs',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_SYNTHETIC_DRUGS = 1
	UNION ALL
	SELECT 12,
		'Fentanyl',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_FENTANYL = 1
	UNION ALL
	SELECT 13,
		'Other Substance Use',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_OTHER = 1
	UNION ALL
	SELECT 14,
		'Unknown Substances',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_UNKNOWN_SUBSTANCES = 1
	UNION ALL
	SELECT 15,
		'No Substance Use History',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.SU_HX_NO_SUBSTANCE_USE_HISTORY = 1
),
-- Physical Health Conditions
[PH] AS (
	SELECT ROW_NUMBER() OVER (
			ORDER BY (
					SELECT NULL
				)
		) AS [RN],
		'BMI' AS [PH_CONDITION],
		COUNT(*) AS [PH_COUNT]
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_BMI = 1
	UNION ALL
	SELECT 2,
		'Chronic Pain',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_CHRONIC_PAIN = 1
	UNION ALL
	SELECT 3,
		'Congestive Heart Failure',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_CONGESTIVE_HEART_FAILURE = 1
	UNION ALL
	SELECT 4,
		'COPD/Asthma',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_COPD_ASTHMA = 1
	UNION ALL
	SELECT 5,
		'Dental Care',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_DENTAL_CARE = 1
	UNION ALL
	SELECT 6,
		'Diabetes',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_DIABETES = 1
	UNION ALL
	SELECT 7,
		'Hepatitis C',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_HEPATITIS_C = 1
	UNION ALL
	SELECT 8,
		'Hypertension',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_HYPERTENTION = 1
	UNION ALL
	SELECT 9,
		'Tobacco Use',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_TOBACCO_USE = 1
	UNION ALL
	SELECT 10,
		'Other Physical Health',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_OTHER = 1
	UNION ALL
	SELECT 11,
		'No Physical Health History',
		COUNT(*)
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	WHERE IHNA.PHY_HX_NO_PHYSICAL_HEALTH_HISTORY = 1
),
-- Client Needs
[NEEDS] AS (
	SELECT ROW_NUMBER() OVER (
			ORDER BY (
					SELECT NULL
				)
		) AS [RN],
		'Basic Needs Assistance' AS [NEEDS],
		COUNT(*) AS [NEEDS_COUNT]
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_BASIC_NEEDS_ASSISTANCE = 1
	UNION ALL
	SELECT 2,
		'Birth Certificate',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_BIRTH_CERTIFICATE = 1
	UNION ALL
	SELECT 3,
		'Child Care',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_CHILD_CARE = 1
	UNION ALL
	SELECT 4,
		'Community-Based Assistance',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_COMMUNITY_BASED_ASSISTANCE = 1
	UNION ALL
	SELECT 5,
		'Crisis Services',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_CRISIS_SERVICES = 1
	UNION ALL
	SELECT 6,
		'Dental Care',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_DENTAL_CARE = 1
	UNION ALL
	SELECT 7,
		'Developmental Disabilities Services',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_DEVELOPMENTAL_DISABILITIES_SERVICES = 1
	UNION ALL
	SELECT 8,
		'Employment Services',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_EMPLOYMENT_SERVICES = 1
	UNION ALL
	SELECT 9,
		'Food Assistance',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_FOOD_ASSISTANCE = 1
	UNION ALL
	SELECT 10,
		'Housing',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_HOUSING = 1
	UNION ALL
	SELECT 11,
		'ID',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_ID = 1
	UNION ALL
	SELECT 12,
		'Legal Assistance',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_LEGAL_ASSISTANCE = 1
	UNION ALL
	SELECT 13,
		'Mental Health Services',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_MENTAL_HEALTH_SERVICES = 1
	UNION ALL
	SELECT 14,
		'Payer Assistance',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_PAYER_ASSISTANCE = 1
	UNION ALL
	SELECT 15,
		'Physical Health Services',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_PHYSICAL_HEALTH_SERVICES = 1
	UNION ALL
	SELECT 16,
		'Psychiatry',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_PSYCHIATRY = 1
	UNION ALL
	SELECT 17,
		'Social Security Card',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_SOCIAL_SECURITY_CARD = 1
	UNION ALL
	SELECT 18,
		'Substance Use Services',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_SUBSTANCE_USE_SERVICES = 1
	UNION ALL
	SELECT 19,
		'Transportation Assistance',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_TRANSPORTATION_ASSISTANCE = 1
	UNION ALL
	SELECT 20,
		'Medication Assistance',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_MEDICATION_ASSISTANCE = 1
	UNION ALL
	SELECT 21,
		'None Reported',
		COUNT(*)
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS]
	WHERE NEEDS.NEED_NONE = 1
)
-- Final Unified Output
SELECT MH.MH_CONDITION,
	MH.MH_COUNT,
	SU.SU_CONDITION,
	SU.SU_COUNT,
	PH.PH_CONDITION,
	PH.PH_COUNT,
	N.NEEDS,
	N.NEEDS_COUNT
FROM MH
	FULL OUTER JOIN SU
		ON MH.RN = SU.RN
	FULL OUTER JOIN PH
		ON COALESCE(MH.RN, SU.RN) = PH.RN
	FULL OUTER JOIN NEEDS N
		ON COALESCE(MH.RN, SU.RN, PH.RN) = N.RN
ORDER BY COALESCE(MH.RN, SU.RN, PH.RN, N.RN)