/*
Report Name: ERE Latest Payor Source Unknown Report
Category: Program Management Reports  

See docs/program-management-reports/ere-latest-payor-source-unknown-report.md for full documentation.
*/

SELECT EILPS.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	PP.ENROLLMENT_STARTING_DATE,
	PP.ENROLLMENT_ENDING_DATE,
	PP.DISMISSAL_REASON_DESCRIPTION,
	HR.EmployeeName AS [PROGRAM_WORKER],
	PP.AGENCY_DESCRIPTION,
	EREF.REFERRING_AGENCY_DESCRIPTION,
	EILPS.LATEST_PAYOR_SOURCE_DESCRIPTION,
	EILPS.INITIAL_PAYOR_SOURCE_START_DATE,
	EILPS.STATUS_CHANGED_FLAG
FROM DBO.Q_ERE_INITIAL_LATEST_PAYOR_SOURCE AS [EILPS]
LEFT JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = EILPS.CLIENT_NUMBER
LEFT JOIN DBO.Q_PROVIDERPLACEMENT_BHN AS [PP]
	ON PP.DOCSERNO = EILPS.TIEDENROLLMENT
LEFT JOIN DBO.Q_HRFORM AS [HR]
	ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER
LEFT JOIN DBO.Q_ERE_REFERRAL AS [EREF]
	ON EREF.TIEDENROLLMENT = EILPS.TIEDENROLLMENT
WHERE EILPS.LATEST_PAYOR_SOURCE_DESCRIPTION = 'Unknown/Refused'
--      AND (
--           (PP.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^BEGINNING ENROLLMENT DATE^^' = '')
-- )
-- AND (
-- 	 (PP.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^ENDING ENROLLMENT DATE^^' = '')
-- )