/*
Report Name: ERE Caseload Report
Category: Program Management Reports  

See docs/program-management-reports/ere-caseload-report.md for full documentation.
*/

SELECT EREENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST AS [CLIENT LAST],
	C.CLIENT_FIRST AS [CLIENT FIRST],
	EREENROLL.PROGRAM_WORKER_FIRST + ' ' + EREENROLL.PROGRAM_WORKER_LAST AS [WORKER],
	EREENROLL.ENROLLMENT_STARTING_DATE AS [ENROLLMENT_DATE],
	EREENROLL.AGENCY_DESCRIPTION,
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE IHNA' 
			THEN EREENROLL.EVENT_END_DATE
		END
	) AS [IHNA_DUE_DATE],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE IHNA' 
			THEN EREENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [IHNA_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 3 Month' 
			THEN EREENROLL.EVENT_END_DATE
		END
	) AS [3_MONTH_DUE_DATE],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 3 Month'
				AND EREENROLL.PE_DATE_ACCOMPLISHED IS NULL 
			THEN EREENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_3_MONTH_DUE],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 3 Month'
				AND EREENROLL.PE_DATE_ACCOMPLISHED IS NULL
				AND EREENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN EREENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [3_MONTH_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 3 Month' 
			THEN EREENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [3_MONTH_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 6 Month' 
			THEN EREENROLL.EVENT_END_DATE
		END
	) AS [6_MONTH_DUE_DATE],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 6 Month'
				AND EREENROLL.PE_DATE_ACCOMPLISHED IS NULL 
			THEN EREENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_6_MONTH_DUE],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 6 Month'
				AND EREENROLL.PE_DATE_ACCOMPLISHED IS NULL
				AND EREENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN EREENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [6_MONTH_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE 6 Month' 
			THEN EREENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [6_MONTH_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN EREENROLL.PWY_EVENT = 'ERE Behavioral Health Service' 
			THEN EREENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [BHS_DATE_ACCOMPLISHED],
	MAX(EREPAY.MANAGED_MEDICAID_PROVIDER_DESCRIPTION) AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION]
FROM DBO.Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
LEFT JOIN DBO.PWYEREREFERRAL AS [EREREF]
	ON EREREF.DOCSERNO = EREENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN DBO.Q_ERE_ACTIVE_PAYOR_SOURCE AS [EREPAY] 
	ON EREENROLL.CLIENT_NUMBER = EREPAY.CLIENT_NUMBER
LEFT JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON EREENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.Q_HRFORM AS [HRR] 
	ON HRR.EMPLOYEENUMBER = (
		SELECT TOP 1 HR2.EMPSUPERVISOR
		FROM DBO.Q_HRFORM AS [HR2]
		WHERE HR2.EMPLOYEENUMBER = (
			SELECT TOP 1 HR1.EMPLOYEENUMBER
			FROM DBO.Q_HRFORM AS [HR1]
			WHERE HR1.FIRSTNAME = EREENROLL.PROGRAM_WORKER_FIRST
				AND HR1.LASTNAME = EREENROLL.PROGRAM_WORKER_LAST
				)
		)
LEFT JOIN DBO.Q_ERE_HOSPITAL_VISIT AS [EREHOSP]
	ON EREENROLL.CLIENT_NUMBER = EREHOSP.CLIENT_NUMBER
WHERE EREENROLL.PWY_EVENT LIKE 'ERE%'
	AND EREENROLL.ENROLLMENT_ENDING_DATE IS NULL
	AND (
		CASE
			WHEN EREENROLL.ENROLLMENT_ENDING_DATE IS NULL 
			THEN '12-31-2099'
			ELSE EREENROLL.ENROLLMENT_ENDING_DATE
		END >= '^^START RANGE|DATEPICKER^^'
		AND EREENROLL.ENROLLMENT_STARTING_DATE >= '^^START RANGE|DATEPICKER^^'
		)
GROUP BY EREENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	EREENROLL.PROGRAM_WORKER_FIRST,
	EREENROLL.PROGRAM_WORKER_LAST,
	EREENROLL.ENROLLMENT_STARTING_DATE,
	EREENROLL.ENROLLMENT_ENDING_DATE,
	EREENROLL.AGENCY_DESCRIPTION
ORDER BY AGENCY_DESCRIPTION,
	WORKER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST;