/*
Report Name: ERE Hospital Visit Note Report
Category: Program Management Reports  

See docs/program-management-reports/ere-hospital-visit-note-report.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

SELECT EREENROLL.CLIENT_NUMBER,
	EREENROLL.ENROLLMENT_STARTING_DATE,
	EREENROLL.ENROLLMENT_ENDING_DATE,
	EREENROLL.PROGRAM_WORKER_LAST,
	EREENROLL.PROGRAM_WORKER_FIRST,
	EREREF.PATHWAY_DATE AS [REF_PATHWAY_DATE],
	EREREF.REFERRING_AGENCY_DESCRIPTION,
	EREREF.PATIENT_LOCATION_REFERRAL,
	EREHOSP.PATHWAY_DATE AS [HVN_PATHWAY_DATE],
	EREHOSP.VISITDT AS [HVN_VISITDT],
	EREHOSP.VISITTM AS [HVN_VISITTM],
	EREHOSP.ERE_VISIT_HOSP,
	EREHOSP.VISIT_HOSP_NO_OUTCOME,
	EREHOSP.VISIT_HOSP_NO_OUTCOME_OTHER
FROM Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
INNER JOIN Q_ERE_REFERRAL AS [EREREF]
	ON EREENROLL.TIEDENROLLMENT = EREREF.TIEDENROLLMENT
LEFT JOIN Q_ERE_HOSPITAL_VISIT_NOTE AS [EREHOSP]
	ON EREENROLL.TIEDENROLLMENT = EREHOSP.TIEDENROLLMENT
WHERE EREENROLL.TIEDENROLLMENT IS NOT NULL
	AND EREENROLL.PWY_EVENT = 'ERE Referral'
--AND (
--	(EREHOSP.PATHWAY_DATE >= '^^BEGINNING HOSPITAL VISIT NOTE PATHWAY DATE|DATEPICKER^^'
--	 OR '^^BEGINNING HOSPITAL VISIT NOTE PATHWAY DATE^^' = '')
--)
--AND (
--	(EREHOSP.PATHWAY_DATE <= '^^ENDING HOSPITAL VISIT NOTE PATHWAY DATE|DATEPICKER^^'
--	 OR '^^ENDING HOSPITAL VISIT NOTE PATHWAY DATE^^' = '')
--)
--AND (
--	EREENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER = '^^PROGRAM WORKER|SELECT DISTINCT HR.EMPLOYEENUMBER, HR.EMPLOYEENAME FROM Q_PROVIDERPLACEMENT_BHN AS PP INNER JOIN Q_HRFORM HR ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER WHERE PP.PATHWAY = '55320250326123001961' AND PP.PROGRAM_WORKER IS NOT NULL ORDER BY HR.EMPLOYEENAME^^'
--	OR '^^PROGRAM WORKER^^' = ''
--)