/*
Report Name: ERE Latest Housing Status Unknown Report
Category: Program Management Reports  

See docs/program-management-reports/ere-latest-housing-status-unknown-report.md for full documentation.
*/

SELECT EILHS.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	PP.ENROLLMENT_STARTING_DATE,
	PP.ENROLLMENT_ENDING_DATE,
	PP.DISMISSAL_REASON_DESCRIPTION,
	HR.EmployeeName AS [PROGRAM_WORKER],
	PP.AGENCY_DESCRIPTION,
	EREF.REFERRING_AGENCY_DESCRIPTION,
	EILHS.LATEST_HOUSING_STATUS_DESCRIPTION,
	EILHS.LATEST_HOUSING_START_DATE,
	EILHS.STATUS_CHANGED_FLAG
FROM DBO.Q_ERE_INITIAL_LATEST_HOUSING_STATUS AS [EILHS]
LEFT JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = EILHS.CLIENT_NUMBER
LEFT JOIN DBO.Q_PROVIDERPLACEMENT_BHN AS [PP]
	ON PP.DOCSERNO = EILHS.TIEDENROLLMENT
LEFT JOIN DBO.Q_HRFORM AS [HR]
	ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER
LEFT JOIN DBO.Q_ERE_REFERRAL AS [EREF]
	ON EREF.TIEDENROLLMENT = EILHS.TIEDENROLLMENT
WHERE EILHS.LATEST_HOUSING_STATUS_DESCRIPTION = 'Unknown'
--      AND (
--           (PP.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^BEGINNING ENROLLMENT DATE^^' = '')
-- )
-- AND (
-- 	 (PP.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^ENDING ENROLLMENT DATE^^' = '')
-- )