/*
Report Name: YERE Dismissal Report
Category: Program Management Reports  

See docs/program-management-reports/yere-dismissal-report.md for full documentation.
*/

SELECT YENROLL.CLIENT_NUMBER,
	YENROLL.CLIENT_LAST,
	YENROLL.CLIENT_FIRST,
	YENROLL.ENROLLMENT_STARTING_DATE,
	YENROLL.ENROLLMENT_ENDING_DATE,
	YENROLL.DISMISSAL_REASON_DESCRIPTION,
	YENROLL.PROGRAM_WORKER_LAST,
	YENROLL.PROGRAM_WORKER_FIRST,
	YENROLL.AGENCY_DESCRIPTION,
	YENROLL.PATHWAY_DATE AS [IA_DATE],
	YTHIRTYD.PATHWAY_DATE AS [30_DAY_DATE],
	YTHREEM.PATHWAY_DATE AS [3_MONTH_DATE],
	YSIXM.PATHWAY_DATE AS [6_MONTH_DATE]
FROM BEHAVHEALT_LIVE.DBO.Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_YERE_THIRTY_DAY AS [YTHIRTYD]
	ON YENROLL.TIEDENROLLMENT = YTHIRTYD.TIEDENROLLMENT
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_YERE_THREE_MONTH AS [YTHREEM]
	ON YENROLL.TIEDENROLLMENT = YTHREEM.TIEDENROLLMENT
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_YERE_SIX_MONTH AS [YSIXM]
	ON YENROLL.TIEDENROLLMENT = YSIXM.TIEDENROLLMENT
WHERE YENROLL.PWY_EVENT = 'YERE Initial Assessment'
	AND YENROLL.ENROLLMENT_ENDING_DATE IS NOT NULL
	AND YENROLL.ENROLLMENT_STARTING_DATE >= '2025-07-01'
AND (
	(YENROLL.ENROLLMENT_ENDING_DATE >= '^^BEGINNING DISMISSAL DATE|DATEPICKER^^'
	 OR '^^BEGINNING DISMISSAL DATE^^' = '')
)
AND (
	(YENROLL.ENROLLMENT_ENDING_DATE <= '^^ENDING DISMISSAL DATE|DATEPICKER^^'
	 OR '^^ENDING DISMISSAL DATE^^' = '')
)
AND (
	YENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER = '^^PROGRAM WORKER|SELECT DISTINCT HR.EMPLOYEENUMBER, HR.EMPLOYEENAME FROM Q_PROVIDERPLACEMENT_BHN AS PP INNER JOIN Q_HRFORM HR ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER WHERE PP.PATHWAY = '55320240807125033701' AND PP.PROGRAM_WORKER IS NOT NULL ORDER BY HR.EMPLOYEENAME^^'
	OR '^^PROGRAM WORKER^^' = ''
)