/*
Report Name: YERE Caseload Report
Category: Program Management Reports  

See docs/program-management-reports/yere-caseload-report.md for full documentation.
*/

SELECT YENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST AS [CLIENT LAST],
	C.CLIENT_FIRST AS [CLIENT FIRST],
	YENROLL.PROGRAM_WORKER_FIRST + ' ' + YENROLL.PROGRAM_WORKER_LAST AS [WORKER],
	YENROLL.ENROLLMENT_STARTING_DATE AS [ENROLLMENT_DATE],
	YENROLL.ENROLLMENT_ENDING_DATE AS [DISMISSAL_DATE],
	YENROLL.AGENCY_DESCRIPTION,
	MAX(YREF.WAS_SUICIDE_ATTEMPT) AS [SUICIDE_ATTEMPT],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE Initial Assessment' 
			THEN YENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [IA_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 30 Day' 
			THEN YENROLL.EVENT_END_DATE
		END
	) AS [30_DAY_DUE_DATE],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 30 Day'
				AND YENROLL.PE_DATE_ACCOMPLISHED IS NULL 
			THEN YENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_30_DAY_DUE],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 30 Day'
				AND YENROLL.PE_DATE_ACCOMPLISHED IS NULL
				AND YENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN YENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [30_DAY_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 30 Day' 
			THEN YENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [30_DAY_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 3 Month' 
			THEN YENROLL.EVENT_END_DATE
		END
	) AS [3_MONTH_DUE_DATE],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 3 Month'
				AND YENROLL.PE_DATE_ACCOMPLISHED IS NULL 
			THEN YENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_3_MONTH_DUE],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 3 Month'
				AND YENROLL.PE_DATE_ACCOMPLISHED IS NULL
				AND YENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN YENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [3_MONTH_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 3 Month' 
			THEN YENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [3_MONTH_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 6 Month' 
			THEN YENROLL.EVENT_END_DATE
		END
	) AS [6_MONTH_DUE_DATE],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 6 Month'
				AND YENROLL.PE_DATE_ACCOMPLISHED IS NULL 
			THEN YENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [DAYS_UNTIL_6_MONTH_DUE],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 6 Month'
				AND YENROLL.PE_DATE_ACCOMPLISHED IS NULL
				AND YENROLL.DAYS_UNTIL_FORM_DUE < 0 
			THEN YENROLL.DAYS_UNTIL_FORM_DUE
		END
	) AS [6_MONTH_OVERDUE_DAYS],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE 6 Month' 
			THEN YENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [6_MONTH_DATE_ACCOMPLISHED],
	MAX(
		CASE
			WHEN YENROLL.PWY_EVENT = 'YERE Behavioral Health Services' 
			THEN YENROLL.PE_DATE_ACCOMPLISHED
		END
	) AS [BHS_DATE_ACCOMPLISHED],
	MAX(YPAY.MANAGED_MEDICAID_PROVIDER_DESCRIPTION) AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
	MAX(YPAY.SHOWME_HEALTHY_KIDS) AS [SHOWME_HEALTHY_KIDS]
FROM BEHAVHEALT_LIVE.DBO.Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
LEFT JOIN BEHAVHEALT_LIVE.DBO.PWYEREREFERRAL AS [YREF]
	ON YREF.DOCSERNO = YENROLL.PWY_FORMS_DOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_YERE_ACTIVE_PAYOR_SOURCE AS [YPAY] 
	ON YENROLL.CLIENT_NUMBER = YPAY.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON YENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HRR] 
	ON HRR.EMPLOYEENUMBER = (
		SELECT TOP 1 HR2.EMPSUPERVISOR
		FROM BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR2]
		WHERE HR2.EMPLOYEENUMBER = (
			SELECT TOP 1 HR1.EMPLOYEENUMBER
			FROM BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR1]
			WHERE HR1.FIRSTNAME = YENROLL.PROGRAM_WORKER_FIRST
				AND HR1.LASTNAME = YENROLL.PROGRAM_WORKER_LAST
				)
		)
WHERE YENROLL.PWY_EVENT LIKE 'YERE%'
	AND YENROLL.ENROLLMENT_ENDING_DATE IS NULL
	AND (
		CASE
			WHEN YENROLL.ENROLLMENT_ENDING_DATE IS NULL 
			THEN '12-31-2099'
			ELSE YENROLL.ENROLLMENT_ENDING_DATE
		END >= '^^START RANGE|DATEPICKER^^'
		AND YENROLL.ENROLLMENT_STARTING_DATE >= '^^START RANGE|DATEPICKER^^'
		)
GROUP BY YENROLL.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	YENROLL.PROGRAM_WORKER_FIRST,
	YENROLL.PROGRAM_WORKER_LAST,
	YENROLL.ENROLLMENT_STARTING_DATE,
	YENROLL.ENROLLMENT_ENDING_DATE,
	YENROLL.AGENCY_DESCRIPTION
ORDER BY AGENCY_DESCRIPTION,
	WORKER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST;