/*
Report Name: YERE Latest Housing Status Unknown Report
Category: Program Management Reports  

See docs/program-management-reports/yere-latest-housing-status-unknown-report.md for full documentation.
*/

SELECT YILHS.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	PP.ENROLLMENT_STARTING_DATE,
	PP.ENROLLMENT_ENDING_DATE,
	PP.DISMISSAL_REASON_DESCRIPTION,
	HR.EmployeeName AS [PROGRAM_WORKER],
	PP.AGENCY_DESCRIPTION,
	YREF.YERE_REFERRING_HOSPITAL_DESCRIPTION,
	YILHS.LATEST_HOUSING_STATUS_DESCRIPTION,
	YILHS.LATEST_HOUSING_START_DATE,
	YILHS.STATUS_CHANGED_FLAG
FROM Q_YERE_INITIAL_LATEST_HOUSING_STATUS AS [YILHS]
LEFT JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YILHS.CLIENT_NUMBER
LEFT JOIN Q_PROVIDERPLACEMENT_BHN AS [PP]
	ON PP.DOCSERNO = YILHS.TIEDENROLLMENT
LEFT JOIN Q_HRFORM AS [HR]
	ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER
LEFT JOIN Q_YERE_REFERRAL AS [YREF]
	ON YREF.TIEDENROLLMENT = YILHS.TIEDENROLLMENT
WHERE YILHS.LATEST_HOUSING_STATUS_DESCRIPTION = 'Unknown'
--      AND (
--           (PP.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^BEGINNING ENROLLMENT DATE^^' = '')
-- )
-- AND (
-- 	 (PP.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^ENDING ENROLLMENT DATE^^' = '')
-- )