/*
Report Name: YERE Completer And Contact Report
Category: Program Management Reports  

See docs/program-management-reports/yere-completer-and-contact-report.md for full documentation.
*/

SELECT
   YEREENROLL.CLIENT_NUMBER, 
   YEREENROLL.CLIENT_LAST, 
   YEREENROLL.CLIENT_FIRST, 
   YEREENROLL.ENROLLMENT_STARTING_DATE, 
   YEREENROLL.ENROLLMENT_ENDING_DATE,
   YEREENROLL.PROGRAM_WORKER_LAST, 
   YEREENROLL.PROGRAM_WORKER_FIRST, 
   YEREIA.PATHWAY_DATE AS [IA_PATHWAY_DATE],
   YEREIA.COMPLETION_HELPER_IA AS [IA_COMPLETION_HELPER], 
   YEREIA.OTHER_COMPLETION_HELPER_IA AS [IA_OTHER_COMPLETION_HELPER], 
   YEREIA.METHOD_CONTACT_IA AS [IA_METHOD_OF_CONTACT], 
   YEREIA.OTHER_CONTACT_METHOD_IA AS [IA_METHOD_OF_CONTACT_OTHER],
   YERETHREEM.PATHWAY_DATE AS [THREEM_PATHWAY_DATE],
   YERETHREEM.COMPLETION_HELPER_THREE_MONTH AS [THREEM_COMPLETION_HELPER],
   YERETHREEM.OTHER_COMPLETION_HELPER_THREE_MONTH AS [THREEM_OTHER_COMPLETION_HELPER], 
   YERETHREEM.METHOD_CONTACT_THREE_MONTH AS [THREEM_METHOD_OF_CONTACT], 
   YERETHREEM.OTHER_CONTACT_METHOD_THREE_MONTH AS [THREEM_METHOD_OF_CONTACT_OTHER],
   YERESIXM.PATHWAY_DATE AS [SIXM_PATHWAY_DATE],
   YERESIXM.COMPLETION_HELPER_SIX_MONTH AS [SIXM_COMPLETION_HELPER],
   YERESIXM.OTHER_COMPLETION_HELPER_SIX_MONTH AS [SIXM_OTHER_COMPLETION_HELPER], 
   YERESIXM.METHOD_CONTACT_SIX_MONTH AS [SIXM_METHOD_OF_CONTACT], 
   YERESIXM.OTHER_CONTACT_METHOD_SIX_MONTH AS [SIXM_METHOD_OF_CONTACT_OTHER]
FROM DBO.Q_YERE_PATHCLIENT_ENROLLMENTS AS [YEREENROLL]
INNER JOIN Q_YERE_IA AS [YEREIA]
	ON YEREENROLL.TIEDENROLLMENT = YEREIA.TIEDENROLLMENT
LEFT JOIN Q_YERE_THREE_MONTH AS [YERETHREEM]
	ON YEREENROLL.TIEDENROLLMENT = YERETHREEM.TIEDENROLLMENT
LEFT JOIN Q_YERE_SIX_MONTH AS [YERESIXM]
	ON YEREENROLL.TIEDENROLLMENT = YERESIXM.TIEDENROLLMENT
WHERE YEREENROLL.PWY_EVENT = 'YERE Referral'
AND
	(
		(YEREENROLL.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
		 OR '^^BEGINNING ENROLLMENT DATE^^' = '')
	)
AND (
		(YEREENROLL.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
		 OR '^^ENDING ENROLLMENT DATE^^' = '')
	)
AND (
		(YEREENROLL.ENROLLMENT_ENDING_DATE >= '^^BEGINNING DISMISSAL DATE|DATEPICKER^^'
		 OR '^^BEGINNING DISMISSAL DATE^^' = '')
	)
AND (
		(YEREENROLL.ENROLLMENT_ENDING_DATE <= '^^ENDING DISMISSAL DATE|DATEPICKER^^'
		 OR '^^ENDING DISMISSAL DATE^^' = '')
	)
AND (
		(YEREENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER =
			'^^PROGRAM WORKER|SELECT DISTINCT HR.EMPLOYEENUMBER, HR.EMPLOYEENAME
			  FROM Q_PROVIDERPLACEMENT_BHN AS PP
			  INNER JOIN Q_HRFORM HR ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER
			  WHERE PP.PATHWAY = '55320240807125033701'
				AND PP.PROGRAM_WORKER IS NOT NULL
			  ORDER BY HR.EMPLOYEENAME^^'
		 OR '^^PROGRAM WORKER^^' = '')
	);