/*
Report Name: YERE Latest Payor Source Unknown Report
Category: Program Management Reports  

See docs/program-management-reports/yere-latest-payor-source-unknown-report.md for full documentation.
*/

SELECT YILPS.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	PP.ENROLLMENT_STARTING_DATE,
	PP.ENROLLMENT_ENDING_DATE,
	PP.DISMISSAL_REASON_DESCRIPTION,
	HR.EmployeeName AS [PROGRAM_WORKER],
	PP.AGENCY_DESCRIPTION,
	YREF.YERE_REFERRING_HOSPITAL_DESCRIPTION,
	YILPS.LATEST_PAYOR_SOURCE_DESCRIPTION,
	YILPS.INITIAL_PAYOR_SOURCE_START_DATE,
	YILPS.STATUS_CHANGED_FLAG
FROM Q_YERE_INITIAL_LATEST_PAYOR_SOURCE AS [YILPS]
LEFT JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YILPS.CLIENT_NUMBER
LEFT JOIN Q_PROVIDERPLACEMENT_BHN AS [PP]
	ON PP.DOCSERNO = YILPS.TIEDENROLLMENT
LEFT JOIN Q_HRFORM AS [HR]
	ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER
LEFT JOIN Q_YERE_REFERRAL AS [YREF]
	ON YREF.TIEDENROLLMENT = YILPS.TIEDENROLLMENT
WHERE YILPS.LATEST_PAYOR_SOURCE_DESCRIPTION = 'Unknown/Refused'
--      AND (
--           (PP.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^BEGINNING ENROLLMENT DATE^^' = '')
-- )
-- AND (
-- 	 (PP.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
-- 	  OR '^^ENDING ENROLLMENT DATE^^' = '')
-- )