/*
Report Name: YERE Hospital Visit Note Report
Category: Program Management Reports  

See docs/program-management-reports/yere-hospital-visit-note-report.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

SELECT YENROLL.CLIENT_NUMBER,
	YENROLL.ENROLLMENT_STARTING_DATE,
	YENROLL.ENROLLMENT_ENDING_DATE,
	YENROLL.PROGRAM_WORKER_LAST,
	YENROLL.PROGRAM_WORKER_FIRST,
	YREF.PATHWAY_DATE AS [REF_PATHWAY_DATE],
	YREF.YERE_REFERRING_HOSPITAL_DESCRIPTION,
	YREF.REFERRED_FROM,
	YHOSP.PATHWAY_DATE AS [HVN_PATHWAY_DATE],
	YHOSP.VISITDT AS [HVN_VISITDT],
	YHOSP.VISITTM AS [HVN_VISITTM],
	YHOSP.YERE_VISIT_HOSP,
	YHOSP.NO_HOSP_VISIT_REASON,
	YHOSP.OTHER_REASON_NOT_FTF
FROM Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
INNER JOIN Q_YERE_REFERRAL AS [YREF]
	ON YENROLL.TIEDENROLLMENT = YREF.TIEDENROLLMENT
LEFT JOIN Q_YERE_HOSPITAL_VISIT AS [YHOSP]
	ON YENROLL.TIEDENROLLMENT = YHOSP.TIEDENROLLMENT
WHERE YENROLL.TIEDENROLLMENT IS NOT NULL
	AND YENROLL.PWY_EVENT = 'YERE Referral'
AND (
	(YHOSP.PATHWAY_DATE >= '^^BEGINNING HOSPITAL VISIT NOTE PATHWAY DATE|DATEPICKER^^'
	 OR '^^BEGINNING HOSPITAL VISIT NOTE PATHWAY DATE^^' = '')
)
AND (
	(YHOSP.PATHWAY_DATE <= '^^ENDING HOSPITAL VISIT NOTE PATHWAY DATE|DATEPICKER^^'
	 OR '^^ENDING HOSPITAL VISIT NOTE PATHWAY DATE^^' = '')
)
AND (
	YENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER = '^^PROGRAM WORKER|SELECT DISTINCT HR.EMPLOYEENUMBER, HR.EMPLOYEENAME FROM Q_PROVIDERPLACEMENT_BHN AS PP INNER JOIN Q_HRFORM HR ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER WHERE PP.PATHWAY = '55320240807125033701' AND PP.PROGRAM_WORKER IS NOT NULL ORDER BY HR.EMPLOYEENAME^^'
	OR '^^PROGRAM WORKER^^' = ''
)