/*
Report Name: YERE Needs Report
Category: Program Management Reports  

See docs/program-management-reports/yere-needs-report.md for full documentation.
*/

SELECT *
FROM Q_YERE_NEEDS_REPORT
WHERE 
	(
	(YNEEDS.ENROLLMENT_STARTING_DATE >= '^^BEGINNING ENROLLMENT DATE|DATEPICKER^^'
	 OR '^^BEGINNING ENROLLMENT DATE^^' = '')
)
AND (
	(YNEEDS.ENROLLMENT_STARTING_DATE <= '^^ENDING ENROLLMENT DATE|DATEPICKER^^'
	 OR '^^ENDING ENROLLMENT DATE^^' = '')
)
AND (
	(YNEEDS.ENROLLMENT_ENDING_DATE >= '^^BEGINNING DISMISSAL DATE|DATEPICKER^^'
	 OR '^^BEGINNING DISMISSAL DATE^^' = '')
)
AND (
	(YNEEDS.ENROLLMENT_ENDING_DATE <= '^^ENDING DISMISSAL DATE|DATEPICKER^^'
	 OR '^^ENDING DISMISSAL DATE^^' = '')
)
AND (
	YNEEDS.PROGRAM_WORKER_EMPLOYEE_NUMBER = '^^PROGRAM WORKER|SELECT DISTINCT HR.EMPLOYEENUMBER, HR.EMPLOYEENAME FROM Q_PROVIDERPLACEMENT_BHN AS PP INNER JOIN Q_HRFORM HR ON PP.PROGRAM_WORKER = HR.EMPLOYEENUMBER WHERE PP.PATHWAY = '55320240807125033701' AND PP.PROGRAM_WORKER IS NOT NULL ORDER BY HR.EMPLOYEENAME^^'
	OR '^^PROGRAM WORKER^^' = ''
)