BEGIN TRANSACTION;

-- Backup
SELECT * INTO BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BACKUP
FROM BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BASE
WHERE ID IN (349, 350, 351)
    AND USERID = 'Kayla-Dairaghi';

-- Delete
DELETE FROM BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BASE
WHERE ID IN (349, 350, 351)
    AND USERID = 'Kayla-Dairaghi';

-- Confirm Deletion
SELECT ID,
    DOCSERNO,
    DOCREVNO,
    VISITDT,
    VISITTM,
    USERID,
    QUERYNAME,
    PRIVATE,
    QUERYTITLE,
    QUERYSQL,
    QUERYPROMPTS,
    QUERYCOMMENT
FROM BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BASE
WHERE QUERYNAME LIKE ('%Extract]%')
ORDER BY ID DESC;

-- COMMIT or ROLLBACK as needed
--COMMIT;
--ROLLBACK;