BEGIN TRY
	BEGIN TRANSACTION;

	SET IDENTITY_INSERT BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BACKUP ON;

	INSERT INTO BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BACKUP (
			ID,
			DOCSERNO,
			DOCREVNO,
			STATUS,
			VISITDT,
			VISITTM,
			TIMESTAMP,
			CHECKSUM,
			USERID,
			SIGNATURES,
			PRIVATEPROVIDER,
			SAVEDBYPROVIDER,
			PARENTDOCSERNO,
			AUTOCLOSE,
			CONFIRMSCREEN,
			SUMMATION,
			CODE,
			DESCRIPTION,
			STATUSDESC,
			QUERYNAME,
			PRIVATE,
			QUERYTITLE,
			QUERYSQL,
			QUERYHEADINGS,
			QUERYPROMPTS,
			QUERYCATEGORY,
			QUERYHTML,
			QUERYVALUES,
			SPECIALDATA,
			QUERYCOMMENT
	)
	SELECT
			ID,
			DOCSERNO,
			DOCREVNO,
			STATUS,
			VISITDT,
			VISITTM,
			TIMESTAMP,
			CHECKSUM,
			USERID,
			SIGNATURES,
			PRIVATEPROVIDER,
			SAVEDBYPROVIDER,
			PARENTDOCSERNO,
			AUTOCLOSE,
			CONFIRMSCREEN,
			SUMMATION,
			CODE,
			DESCRIPTION,
			STATUSDESC,
			QUERYNAME,
			PRIVATE,
			QUERYTITLE,
			QUERYSQL,
			QUERYHEADINGS,
			QUERYPROMPTS,
			QUERYCATEGORY,
			QUERYHTML,
			QUERYVALUES,
			SPECIALDATA,
			QUERYCOMMENT
	FROM BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BASE
	WHERE ID IN (365, 309)
		AND USERID = 'bradley-wing';

	SET IDENTITY_INSERT BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BACKUP OFF;

	DELETE FROM BEHAVHEALT_LIVE.DBO.SAVEDQUERIES_BASE
	OUTPUT DELETED.*
	WHERE ID IN (365, 309)
		AND USERID = 'bradley-wing';

	COMMIT;
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK;

	THROW;
END CATCH;