/*
Script Name: update-providerplacement-bulk-dismiss-ere-admitted-or-three-months-elapsed.sql  
Category: Maintenance Scripts  

See docs/maintenance-scripts/update-providerplacement-bulk-dismiss-ere-admitted-or-three-months-elapsed.md for full documentation.
*/

-- add hidden fields
ALTER TABLE DBO.PROVIDERPLACEMENT
ADD BULK_DISMISSAL_FLAG VARCHAR(1) NULL,
    BULK_DISMISSAL_SOURCE VARCHAR(20) NULL,
	BULK_DISMISSAL_NOTE VARCHAR(150) NULL;

-- create working table
SELECT *
INTO DBO.ERE_BULK_DISMISS_WORK
FROM (
	SELECT C.CLIENT_NUMBER,
		C.CLIENT_LAST,
		C.CLIENT_FIRST,
		PP.DOCSERNO,
		CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
		CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
			CASE
				WHEN EREBHS.ADMITTED_TO_SERVICES = 'Yes' THEN EREBHS.MIN_BHS_DATE
				ELSE ERETHREEM.PATHWAY_DATE
			END AS [NEW_ENROLLMENT_ENDING_DATE],
			CASE 
				WHEN EREBHS.ADMITTED_TO_SERVICES = 'Yes' THEN 'BHS Date'
				ELSE '3-Month Date'
			END AS [DISMISSAL_SOURCE],
		PP.CLOSINGREASON, 
		CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
		EREBHS.ADMITTED_TO_SERVICES,
		EREBHS.BH_ADMISSION_DATE, 
		EREBHS.SU_ADMISSION_DATE,
		EREBHS.MIN_BHS_DATE,
		ERETHREEM.PATHWAY_DATE AS [THREEM_PATHWAY_DATE]
	FROM DBO.PROVIDERPLACEMENT AS [PP]
	INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
		ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
	LEFT JOIN DBO.CLOSINGREASONS AS [CR] 
		ON PP.CLOSINGREASON = CR.CODE
	LEFT JOIN ( SELECT *, 
					CASE 
						WHEN BH_ADMISSION_DATE IS NULL THEN SU_ADMISSION_DATE
						WHEN SU_ADMISSION_DATE IS NULL THEN BH_ADMISSION_DATE
						WHEN BH_ADMISSION_DATE < SU_ADMISSION_DATE THEN BH_ADMISSION_DATE 
						ELSE SU_ADMISSION_DATE
					END AS [MIN_BHS_DATE]
				FROM DBO.Q_ERE_BHS) AS [EREBHS] 
					ON EREBHS.CLIENT_NUMBER = PP.CLIENTNUMBER
					AND EREBHS.TIEDENROLLMENT = PP.DOCSERNO
	LEFT JOIN DBO.Q_ERE_THREE_MONTH AS [ERETHREEM] 
		ON ERETHREEM.CLIENT_NUMBER = PP.CLIENTNUMBER
		AND ERETHREEM.TIEDENROLLMENT = PP.DOCSERNO
	WHERE PP.PATHWAY = 55320250326123001961
		AND C.CLIENT_NUMBER IS NOT NULL
		AND PP.DOCREVNO = ' 0 '
		AND PP.ENDINGDATE IS NULL
		AND (EREBHS.ADMITTED_TO_SERVICES = 'Yes' OR ERETHREEM.PATHWAY_DATE IS NOT NULL)
		AND C.CLIENT_NUMBER NOT IN (
			'000010376',
			'000012886',
			'000014806',
			'000017340',
			'000019540',
			'000021359',
			'000026215',
			'000029166',
			'000034746',
			'000035549',
			'000035845',
			'000035925',
			'000035956',
			'000036112',
			'000036113',
			'000036500',
			'000036546',
			'000036788',
			'000036790',
			'000036852',
			'000036903',
			'000037372',
			'000037462',
			'000037559',
			'000037592',
			'000037617',
			'000037704',
			'000037757',
			'000037819',
			'000037822',
			'000037868',
			'000038023',
			'000037909',
			'000037982',
			'000038117',
			'000037841',
			'000028909',
			'000022293',
			'000023931'
			)
		) AS [X];

-- back up affected rows
SELECT PP.*
INTO DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_DISMISS_WORK AS [W]
    ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
   AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE PP
    SET 
        PP.ENDINGDATE = W.NEW_ENROLLMENT_ENDING_DATE,
        PP.CLOSINGREASON = CASE 
                               WHEN W.DISMISSAL_SOURCE = 'BHS Date' THEN '049'
                               ELSE '050'
                           END,
        PP.VISITDT = CAST(GETDATE() AS DATE),
        PP.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        PP.USERID = 'bradley-wing',
        PP.BULK_DISMISSAL_FLAG = 'Y',
        PP.BULK_DISMISSAL_SOURCE = W.DISMISSAL_SOURCE,
		PP.BULK_DISMISSAL_NOTE = 'ERE Bulk Dismissal Interim State-wide'
    FROM DBO.PROVIDERPLACEMENT AS [PP]
    INNER JOIN DBO.ERE_BULK_DISMISS_WORK AS [W]
        ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
       AND W.DOCSERNO = PP.DOCSERNO
    WHERE PP.ENDINGDATE IS NULL
      AND PP.DOCREVNO = ' 0 '
      AND PP.PATHWAY = 55320250326123001961;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate enrollments (should return zero rows)
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
    W.NEW_ENROLLMENT_ENDING_DATE,
    W.DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_DISMISS_WORK AS [W]
	ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
    AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';

-- VALIDATE AGAIN
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE
FROM DBO.PROVIDERPLACEMENT AS [PP]
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';
