/*
Script Name: update-providerplacement-bulk-update-dismissals-ere-admitted.sql  
Category: Maintenance Scripts  

See docs/maintenance-scripts/update-providerplacement-bulk-update-dismissals-ere-admitted.md for full documentation.
*/

-- add hidden fields
ALTER TABLE DBO.PROVIDERPLACEMENT
ADD BULK_UPDATE_CLOSINGREASON VARCHAR(75) NULL,
    BULK_UPDATE_ENDINGDATE DATETIME NULL;

-- create working table
SELECT *
INTO DBO.ERE_BULK_UPDATE_WORK
FROM (SELECT C.CLIENT_NUMBER,
    PP.DOCSERNO,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
    EREBHS.MIN_BHS_DATE AS [NEW_ENROLLMENT_ENDING_DATE],
    PP.CLOSINGREASON, 
    CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
    EREBHS.ADMITTED_TO_SERVICES,
    EREBHS.BH_ADMISSION_DATE, 
    EREBHS.SU_ADMISSION_DATE,
    EREBHS.MIN_BHS_DATE
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN CLOSINGREASONS AS [CR] 
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN ( SELECT *, 
              CASE WHEN BH_ADMISSION_DATE IS NULL THEN SU_ADMISSION_DATE
                WHEN SU_ADMISSION_DATE IS NULL THEN BH_ADMISSION_DATE
                WHEN BH_ADMISSION_DATE < SU_ADMISSION_DATE THEN BH_ADMISSION_DATE 
               ELSE SU_ADMISSION_DATE END AS MIN_BHS_DATE
            FROM DBO.Q_ERE_BHS) AS [EREBHS] 
	ON EREBHS.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND EREBHS.TIEDENROLLMENT = PP.DOCSERNO
WHERE PP.PATHWAY = 55320250326123001961
	AND C.CLIENT_NUMBER IS NOT NULL
	AND PP.DOCREVNO = ' 0 '
    AND EREBHS.ADMITTED_TO_SERVICES = 'Yes'
    AND PP.ENDINGDATE >= '2026-07-01'
	AND PP.CLOSINGREASON NOT IN ('049', '050')

			) AS [X];

-- back up affected rows
SELECT PP.*
INTO DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
    ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
   AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.DOCREVNO = ' 0 ';

-- back up affected rows TEST
SELECT PP.*
INTO DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006_TEST
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
    ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
   AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

  UPDATE PP
    SET 
        PP.BULK_UPDATE_CLOSINGREASON = PP.CLOSINGREASON,
		PP.BULK_UPDATE_ENDINGDATE = PP.ENDINGDATE,
		PP.ENDINGDATE = W.NEW_ENROLLMENT_ENDING_DATE,
        PP.CLOSINGREASON = '049',
        PP.VISITDT = CAST(GETDATE() AS DATE),
        PP.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        PP.USERID = 'rob-margherio',
        PP.BULK_DISMISSAL_FLAG = 'Y',
        PP.BULK_DISMISSAL_SOURCE = 'BHS Date',
		PP.BULK_DISMISSAL_NOTE = 'ERE Bulk Update Interim State-wide'
    FROM DBO.PROVIDERPLACEMENT AS [PP]
    INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
        ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
       AND W.DOCSERNO = PP.DOCSERNO
    WHERE PP.ENDINGDATE IS NOT NULL
      AND PP.DOCREVNO = ' 0 '
      AND PP.PATHWAY = 55320250326123001961;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate enrollments (should return zero rows)
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
    W.NEW_ENROLLMENT_ENDING_DATE,
	PP.CLOSINGREASON,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	PP.BULK_UPDATE_CLOSINGREASON,
	PP.BULK_UPDATE_ENDINGDATE
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
	ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
    AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';

-- VALIDATE AGAIN
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.CLOSINGREASON,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE
FROM DBO.PROVIDERPLACEMENT  AS [PP]
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND BULK_DISMISSAL_NOTE = 'ERE Bulk Update Interim State-wide'
	AND PP.DOCREVNO = ' 0 ';

SELECT *
FROM DBO.ERE_BULK_UPDATE_WORK;

SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.CLOSINGREASON,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	PP.BULK_UPDATE_CLOSINGREASON,
	PP.BULK_UPDATE_ENDINGDATE
FROM DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006_TEST AS [PP]
ORDER BY BULK_UPDATE_ENDINGDATE