/*
Script Name: update-providerplacement-bulk-dismiss-ere-admitted-or-three-months-elapsed.sql  
Category: Maintenance Scripts  

See docs/maintenance-scripts/update-providerplacement-bulk-dismiss-ere-admitted-or-three-months-elapsed.md for full documentation.
*/

----- BULK DISMISS ACTIVE ERE CLIENTS USING BHS ADMISSION OR THREE-MONTH FORM DATE -----

/*
Performs an interim dismissal of clients who have been admitted to Behavioral
Health Services (BHS) or have been in the program for three months or more after
filtering out a list of clients the outreach team wishes to continue outreaching
for now. It is possible that subsequent adjustments to client enrollments will
be necessary pending changes from the Missouri Behavioral Health Council to the
statewide ERE program. This script updates the `PROVIDERPLACEMENT` table to set
the `endingdate` and `closingreason` fields, as well as the `visitdt`,
`visittm`, and `userid` fields to reflect the dismissal. The `docrevno` field is
explicitly not updated due to the complications inherent in updating all prior
versions of each enrollment record for each client. The script also creates a
backup of the affected rows in the `PROVIDERPLACEMENT` table before performing
the update. For those bulk dismissed using the query, adds a flag to the
`PROVIDERPLACEMENT` table to indicate that the dismissal was a bulk dismissal,
as well as a note and source for the dismissal.
*/

-- add hidden fields
ALTER TABLE DBO.PROVIDERPLACEMENT
ADD BULK_DISMISSAL_FLAG VARCHAR(1) NULL,
    BULK_DISMISSAL_SOURCE VARCHAR(20) NULL,
	BULK_DISMISSAL_NOTE VARCHAR(150) NULL;

-- create working table
SELECT *
INTO DBO.ERE_BULK_DISMISS_WORK
FROM (
	SELECT C.CLIENT_NUMBER,
		C.CLIENT_LAST,
		C.CLIENT_FIRST,
		PP.DOCSERNO,
		CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
		CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
			CASE
				WHEN EREBHS.ADMITTED_TO_SERVICES = 'Yes' THEN EREBHS.MIN_BHS_DATE
				ELSE ERETHREEM.PATHWAY_DATE
			END AS [NEW_ENROLLMENT_ENDING_DATE],
			CASE 
				WHEN EREBHS.ADMITTED_TO_SERVICES = 'Yes' THEN 'BHS Date'
				ELSE '3-Month Date'
			END AS [DISMISSAL_SOURCE],
		PP.CLOSINGREASON, 
		CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
		EREBHS.ADMITTED_TO_SERVICES,
		EREBHS.BH_ADMISSION_DATE, 
		EREBHS.SU_ADMISSION_DATE,
		EREBHS.MIN_BHS_DATE,
		ERETHREEM.PATHWAY_DATE AS [THREEM_PATHWAY_DATE]
	FROM DBO.PROVIDERPLACEMENT AS [PP]
	INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
		ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
	LEFT JOIN DBO.CLOSINGREASONS AS [CR] 
		ON PP.CLOSINGREASON = CR.CODE
	LEFT JOIN ( SELECT *, 
					CASE 
						WHEN BH_ADMISSION_DATE IS NULL THEN SU_ADMISSION_DATE
						WHEN SU_ADMISSION_DATE IS NULL THEN BH_ADMISSION_DATE
						WHEN BH_ADMISSION_DATE < SU_ADMISSION_DATE THEN BH_ADMISSION_DATE 
						ELSE SU_ADMISSION_DATE
					END AS [MIN_BHS_DATE]
				FROM DBO.Q_ERE_BHS) AS [EREBHS] 
					ON EREBHS.CLIENT_NUMBER = PP.CLIENTNUMBER
					AND EREBHS.TIEDENROLLMENT = PP.DOCSERNO
	LEFT JOIN DBO.Q_ERE_THREE_MONTH AS [ERETHREEM] 
		ON ERETHREEM.CLIENT_NUMBER = PP.CLIENTNUMBER
		AND ERETHREEM.TIEDENROLLMENT = PP.DOCSERNO
	WHERE PP.PATHWAY = 55320250326123001961
		AND C.CLIENT_NUMBER IS NOT NULL
		AND PP.DOCREVNO = ' 0 '
		AND PP.ENDINGDATE IS NULL
		AND (EREBHS.ADMITTED_TO_SERVICES = 'Yes' OR ERETHREEM.PATHWAY_DATE IS NOT NULL)
		AND C.CLIENT_NUMBER NOT IN (
			'000010376',
			'000012886',
			'000014806',
			'000017340',
			'000019540',
			'000021359',
			'000026215',
			'000029166',
			'000034746',
			'000035549',
			'000035845',
			'000035925',
			'000035956',
			'000036112',
			'000036113',
			'000036500',
			'000036546',
			'000036788',
			'000036790',
			'000036852',
			'000036903',
			'000037372',
			'000037462',
			'000037559',
			'000037592',
			'000037617',
			'000037704',
			'000037757',
			'000037819',
			'000037822',
			'000037868',
			'000038023',
			'000037909',
			'000037982',
			'000038117',
			'000037841',
			'000028909',
			'000022293',
			'000023931'
			)
		) AS [X];

-- back up affected rows
SELECT PP.*
INTO DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_DISMISS_WORK AS [W]
    ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
   AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE PP
    SET 
        PP.ENDINGDATE = W.NEW_ENROLLMENT_ENDING_DATE,
        PP.CLOSINGREASON = CASE 
                               WHEN W.DISMISSAL_SOURCE = 'BHS Date' THEN '049'
                               ELSE '050'
                           END,
        PP.VISITDT = CAST(GETDATE() AS DATE),
        PP.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        PP.USERID = 'bradley-wing',
        PP.BULK_DISMISSAL_FLAG = 'Y',
        PP.BULK_DISMISSAL_SOURCE = W.DISMISSAL_SOURCE,
		PP.BULK_DISMISSAL_NOTE = 'ERE Bulk Dismissal Interim State-wide'
    FROM DBO.PROVIDERPLACEMENT AS [PP]
    INNER JOIN DBO.ERE_BULK_DISMISS_WORK AS [W]
        ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
       AND W.DOCSERNO = PP.DOCSERNO
    WHERE PP.ENDINGDATE IS NULL
      AND PP.DOCREVNO = ' 0 '
      AND PP.PATHWAY = 55320250326123001961;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate enrollments (should return zero rows)
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
    W.NEW_ENROLLMENT_ENDING_DATE,
    W.DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_DISMISS_WORK AS [W]
	ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
    AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';

-- validate again
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE
FROM DBO.PROVIDERPLACEMENT AS [PP]
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';

----- BULK UPDATE ALREADY DISMISSED ENROLLMENTS USING BHS DATE OF ADMISSION -----

/*
Performs an update on the `endingdate` in the `PROVIDERPLACEMENT` table to
reflect the BHS date of admission for clients who had already been dismissed but
have an `endingdate` that is greater than the BHS date of admission. This will
ensure that the enrollment reflects updated protocol for dismissal based on a
BHS admission date, removing these clients from the current fiscal year
reporting based on program enrollment dismissals. This explicitly excludes any
clients who were dismissed but already had a `closingreason` of '049' or '050',
as those clients were already dismissed using the bulk dismissal query above.
The script also creates a backup of the affected rows in the `PROVIDERPLACEMENT`
table before performing the update. For those whose dismissal was bulk updated
using the query, adds a flag to the `PROVIDERPLACEMENT` table to indicate that
the dismissal was a bulk dismissal, as well as a note and source for the
dismissal.
*/

-- add hidden fields
ALTER TABLE DBO.PROVIDERPLACEMENT
ADD BULK_UPDATE_CLOSINGREASON VARCHAR(75) NULL,
    BULK_UPDATE_ENDINGDATE DATETIME NULL;

-- create working table
SELECT *
INTO DBO.ERE_BULK_UPDATE_WORK
FROM (SELECT C.CLIENT_NUMBER,
    PP.DOCSERNO,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
    EREBHS.MIN_BHS_DATE AS [NEW_ENROLLMENT_ENDING_DATE],
    PP.CLOSINGREASON, 
    CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
    EREBHS.ADMITTED_TO_SERVICES,
    EREBHS.BH_ADMISSION_DATE, 
    EREBHS.SU_ADMISSION_DATE,
    EREBHS.MIN_BHS_DATE
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN CLOSINGREASONS AS [CR] 
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN ( SELECT *, 
              CASE WHEN BH_ADMISSION_DATE IS NULL THEN SU_ADMISSION_DATE
                WHEN SU_ADMISSION_DATE IS NULL THEN BH_ADMISSION_DATE
                WHEN BH_ADMISSION_DATE < SU_ADMISSION_DATE THEN BH_ADMISSION_DATE 
               ELSE SU_ADMISSION_DATE END AS MIN_BHS_DATE
            FROM DBO.Q_ERE_BHS) AS [EREBHS] 
	ON EREBHS.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND EREBHS.TIEDENROLLMENT = PP.DOCSERNO
WHERE PP.PATHWAY = 55320250326123001961
	AND C.CLIENT_NUMBER IS NOT NULL
	AND PP.DOCREVNO = ' 0 '
    AND EREBHS.ADMITTED_TO_SERVICES = 'Yes'
    AND PP.ENDINGDATE >= '2026-07-01'
	AND PP.CLOSINGREASON NOT IN ('049', '050')

			) AS [X];

-- back up affected rows
SELECT PP.*
INTO DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
    ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
   AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.DOCREVNO = ' 0 ';

-- back up affected rows TEST
SELECT PP.*
INTO DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006_TEST
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
    ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
   AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

  UPDATE PP
    SET 
        PP.BULK_UPDATE_CLOSINGREASON = PP.CLOSINGREASON,
		PP.BULK_UPDATE_ENDINGDATE = PP.ENDINGDATE,
		PP.ENDINGDATE = W.NEW_ENROLLMENT_ENDING_DATE,
        PP.CLOSINGREASON = '049',
        PP.VISITDT = CAST(GETDATE() AS DATE),
        PP.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        PP.USERID = 'rob-margherio',
        PP.BULK_DISMISSAL_FLAG = 'Y',
        PP.BULK_DISMISSAL_SOURCE = 'BHS Date',
		PP.BULK_DISMISSAL_NOTE = 'ERE Bulk Update Interim State-wide'
    FROM DBO.PROVIDERPLACEMENT AS [PP]
    INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
        ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
       AND W.DOCSERNO = PP.DOCSERNO
    WHERE PP.ENDINGDATE IS NOT NULL
      AND PP.DOCREVNO = ' 0 '
      AND PP.PATHWAY = 55320250326123001961;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate enrollments (should return zero rows)
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
    W.NEW_ENROLLMENT_ENDING_DATE,
	PP.CLOSINGREASON,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	PP.BULK_UPDATE_CLOSINGREASON,
	PP.BULK_UPDATE_ENDINGDATE
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.ERE_BULK_UPDATE_WORK AS [W]
	ON W.CLIENT_NUMBER = PP.CLIENTNUMBER
    AND W.DOCSERNO = PP.DOCSERNO
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';

-- validate again
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.CLOSINGREASON,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE
FROM DBO.PROVIDERPLACEMENT  AS [PP]
WHERE PP.ENDINGDATE IS NOT NULL
	AND PP.BULK_DISMISSAL_FLAG IS NOT NULL
	AND BULK_DISMISSAL_NOTE = 'ERE Bulk Update Interim State-wide'
	AND PP.DOCREVNO = ' 0 ';

SELECT *
FROM DBO.ERE_BULK_UPDATE_WORK;

SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.CLOSINGREASON,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	PP.BULK_UPDATE_CLOSINGREASON,
	PP.BULK_UPDATE_ENDINGDATE
FROM DBO.ERE_PROVIDERPLACEMENT_BACKUP_20261006_TEST AS [PP]
ORDER BY BULK_UPDATE_ENDINGDATE

----- BULK UPDATE PRIMARYPROVIDERCODEHISTORY -----

/*
Performs an update to the `end_date` in the `PRIMARYPROVIDERCODEHISTORY` table
 to reflect the new `endingdate` from the `PROVIDERPLACEMENT` table to end the
 program assignment with the provider.
*/

-- create working table
SELECT *
INTO DBO.ERE_BULK_UPDATE_PRIMARYPROVIDERCODE
FROM (SELECT
   PP.CLIENTNUMBER,
   PP.DOCSERNO,
   PP.STARTINGDATE, 
   PP.ENDINGDATE, -- use this date to update PPCH.ENDINGDATE
   PP.CLOSINGREASON,
   PP.BULK_DISMISSAL_SOURCE,
   PPCH.PARENTDOCSERNO,
   PPCH.ID,
   PPCH.VISITDT,     --Update this date
   PPCH.VISITTM,     --Update this time
   PPCH.USERID,      --Update this userid
   PPCH.PRIMARYPROVIDERCODE, 
   PPCH.STARTINGDATE AS [PPCH_STARTINGDATE], 
   PPCH.ENDINGDATE AS [PPCH_ENDINGDATE]   --Update this date
FROM DBO.PRIMARYPROVIDERCODEHISTORY AS [PPCH]
   INNER JOIN (SELECT CLIENTNUMBER, 
                PARENTDOCSERNO, 
                MAX(ID) AS [ID] 
              FROM DBO.PRIMARYPROVIDERCODEHISTORY 
              WHERE DOCREVNO = ' 0 ' 
              GROUP BY CLIENTNUMBER, 
                      PARENTDOCSERNO
       ) AS [LATEST]
      ON LATEST.CLIENTNUMBER = PPCH.CLIENTNUMBER
        AND LATEST.PARENTDOCSERNO = PPCH.PARENTDOCSERNO
        AND LATEST.ID = PPCH.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON PPCH.CLIENTNUMBER = PP.CLIENTNUMBER
      AND PPCH.PARENTDOCSERNO = PP.DOCSERNO
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PPCH.DOCREVNO = ' 0 '
   AND PP.DOCREVNO = ' 0 '		
) AS [X];

-- back up affected rows
SELECT PPCH.*
INTO DBO.ERE_PRIMARYPROVIDERCODE_BACKUP_20261008
FROM DBO.PRIMARYPROVIDERCODEHISTORY AS [PPCH]
   INNER JOIN ERE_BULK_UPDATE_PRIMARYPROVIDERCODE AS [TEMP]
      ON TEMP.CLIENTNUMBER = PPCH.CLIENTNUMBER
      AND TEMP.PARENTDOCSERNO = PPCH.PARENTDOCSERNO
      AND TEMP.ID = PPCH.ID
WHERE PPCH.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE PPCH
    SET 
        PPCH.ENDINGDATE = TEMP.ENDINGDATE,
        PPCH.VISITDT = CAST(GETDATE() AS DATE),
        PPCH.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        PPCH.USERID = 'bradley-wing'
    FROM DBO.PRIMARYPROVIDERCODEHISTORY AS [PPCH]
   INNER JOIN ERE_BULK_UPDATE_PRIMARYPROVIDERCODE AS [TEMP]
      ON TEMP.CLIENTNUMBER = PPCH.CLIENTNUMBER
      AND TEMP.PARENTDOCSERNO = PPCH.PARENTDOCSERNO
      AND TEMP.ID = PPCH.ID
WHERE PPCH.DOCREVNO = ' 0 ';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate changes
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	PPCH.ENDINGDATE, 
	PPCH.VISITDT,
	PPCH.VISITTM,
	PPCH.USERID
FROM DBO.PRIMARYPROVIDERCODEHISTORY AS [PPCH]
   INNER JOIN (SELECT CLIENTNUMBER, 
                PARENTDOCSERNO, 
                MAX(ID) AS [ID] 
              FROM DBO.PRIMARYPROVIDERCODEHISTORY 
              WHERE DOCREVNO = ' 0 ' 
              GROUP BY CLIENTNUMBER, 
                      PARENTDOCSERNO
       ) AS [LATEST]
      ON LATEST.CLIENTNUMBER = PPCH.CLIENTNUMBER
      AND LATEST.PARENTDOCSERNO = PPCH.PARENTDOCSERNO
      AND LATEST.ID = PPCH.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON PPCH.CLIENTNUMBER = PP.CLIENTNUMBER
      AND PPCH.PARENTDOCSERNO = PP.DOCSERNO
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PPCH.DOCREVNO = ' 0 '
   AND PP.DOCREVNO = ' 0 '	;


----- BULK UPDATE PLACEMENTPROGRAMWORKERHISTORY -----

/*
Performs an update to the `end_date` in the `PLACEMENTPROGRAMWORKERHISTORY`
 table to reflect the new `endingdate` from the `PROVIDERPLACEMENT` table to end
 the program worker assignment. This update is made in addition to the update of
 program worker assignment in the `USERCASELOAD` table, which is what controls
 adding and removing clients from workers' caseload. Updating
 `PLACEMENTPROGRAMWORKERHISTORY` does not update the users' caseloads.
*/

-- create working table
SELECT *
INTO DBO.ERE_BULK_UPDATE_PLACEMENTPROGRAMWORKER
FROM (SELECT 
   PP.CLIENTNUMBER,
   PP.DOCSERNO,
   PP.STARTINGDATE, 
   PP.ENDINGDATE, -- use this date to update PPWH.END_DATE
   PP.CLOSINGREASON,
   PP.BULK_DISMISSAL_SOURCE,
   PPWH.PARENTDOCSERNO, 
   PPWH.ID,
   PPWH.VISITDT,     --Update this date
   PPWH.VISITTM,     --Update this time
   PPWH.USERID,      --Update this userid
   PPWH.PROGRAM_WORKER, 
   PPWH.BEGIN_DATE, 
   PPWH.END_DATE      --Update this date
FROM DBO.PLACEMENTPROGRAMWORKERHISTORY AS [PPWH]
   INNER JOIN (SELECT CLIENTNUMBER, 
                PARENTDOCSERNO, 
                MAX(ID) AS [ID] 
              FROM DBO.PLACEMENTPROGRAMWORKERHISTORY
              WHERE DOCREVNO = ' 0 ' 
              GROUP BY CLIENTNUMBER, 
                      PARENTDOCSERNO
       ) AS [LATEST] 
      ON LATEST.CLIENTNUMBER = PPWH.CLIENTNUMBER
      AND LATEST.PARENTDOCSERNO = PPWH.PARENTDOCSERNO
      AND LATEST.ID = PPWH.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON PPWH.CLIENTNUMBER = PP.CLIENTNUMBER
      AND PPWH.PARENTDOCSERNO = PP.DOCSERNO
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PP.DOCREVNO = ' 0 '
   AND PPWH.DOCREVNO = ' 0 '
) AS [X];

-- back up affected rows
SELECT PPWH.*
INTO DBO.ERE_PLACEMENTPROGRAMWORKERH_BACKUP_20261008
FROM DBO.PLACEMENTPROGRAMWORKERHISTORY AS [PPWH]
   INNER JOIN DBO.ERE_BULK_UPDATE_PLACEMENTPROGRAMWORKER AS [TEMP]
      ON TEMP.CLIENTNUMBER = PPWH.CLIENTNUMBER
      AND TEMP.PARENTDOCSERNO = PPWH.PARENTDOCSERNO
      AND TEMP.ID = PPWH.ID
WHERE PPWH.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE PPWH
    SET 
        PPWH.END_DATE = TEMP.ENDINGDATE,
        PPWH.VISITDT = CAST(GETDATE() AS DATE),
        PPWH.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        PPWH.USERID = 'bradley-wing'
    FROM DBO.PLACEMENTPROGRAMWORKERHISTORY AS [PPWH]
   INNER JOIN DBO.ERE_BULK_UPDATE_PLACEMENTPROGRAMWORKER AS [TEMP] 
      ON TEMP.CLIENTNUMBER = PPWH.CLIENTNUMBER
      AND TEMP.PARENTDOCSERNO = PPWH.PARENTDOCSERNO
      AND TEMP.ID = PPWH.ID
WHERE PPWH.DOCREVNO = ' 0 ';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate changes
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	PPWH.END_DATE, 
	PPWH.VISITDT,
	PPWH.VISITTM,
	PPWH.USERID
FROM DBO.PLACEMENTPROGRAMWORKERHISTORY AS [PPWH]
   INNER JOIN (SELECT CLIENTNUMBER, 
                PARENTDOCSERNO, 
                MAX(ID) AS [ID] 
              FROM DBO.PLACEMENTPROGRAMWORKERHISTORY
              WHERE DOCREVNO = ' 0 ' 
              GROUP BY CLIENTNUMBER, 
                      PARENTDOCSERNO
       ) AS [LATEST] 
      ON LATEST.CLIENTNUMBER = PPWH.CLIENTNUMBER
      AND LATEST.PARENTDOCSERNO = PPWH.PARENTDOCSERNO
      AND LATEST.ID = PPWH.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON PPWH.CLIENTNUMBER = PP.CLIENTNUMBER
      AND PPWH.PARENTDOCSERNO = PP.DOCSERNO
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PP.DOCREVNO = ' 0 '
   AND PPWH.DOCREVNO = ' 0 ';


----- BULK UPDATE USERCASELOAD -----

/*
Performs an update to the `enddate` in the `USERCASELOAD` table to remove
dismissed clients from program workers' caseloads. As noted in the
`PLACEMENTPROGRAMWORKERHISTORY` update, this is a necessary separate step
because ending program worker assignment to an enrollment there does not impact
the caseload.
 */

-- create working table
SELECT *
INTO DBO.ERE_BULK_UPDATE_USERCASELOAD
FROM (SELECT 
   PP.CLIENTNUMBER,
   PP.DOCSERNO,
   PP.STARTINGDATE, 
   PP.ENDINGDATE, -- strip the time and use this date to update U.ENDDATE
   PP.CLOSINGREASON,
   PP.BULK_DISMISSAL_SOURCE,
   U.ID,
   U.USERID,      --Update this userid
   U.BEGINDATE, 
   U.BEGINTIME,
   U.ENDDATE,     --Update this date
   U.ENDTIME      --Update this time 
FROM DBO.USERCASELOAD AS [U]
   INNER JOIN (SELECT CLIENTNUMBER, 
                MAX(ID) AS [ID] 
              FROM DBO.USERCASELOAD
              GROUP BY CLIENTNUMBER
       ) AS [LATEST] 
      ON LATEST.CLIENTNUMBER = U.CLIENTNUMBER
      AND LATEST.ID = U.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON U.CLIENTNUMBER = PP.CLIENTNUMBER 
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PP.DOCREVNO = ' 0 '
) AS [X];

-- back up affected rows
SELECT U.*
INTO DBO.ERE_USERCASELOAD_BACKUP_20261008
FROM DBO.USERCASELOAD AS [U]
   INNER JOIN ERE_BULK_UPDATE_USERCASELOAD AS [TEMP] 
      ON TEMP.CLIENTNUMBER = U.CLIENTNUMBER
      AND TEMP.ID = U.ID;

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE U
    SET 
        U.ENDDATE = CAST(TEMP.ENDINGDATE AS DATE), 
        U.ENDTIME = CONVERT(VARCHAR(8), TEMP.ENDINGDATE, 108), 
        U.USERID = 'bradley-wing'
    FROM DBO.USERCASELOAD AS [U]
   INNER JOIN DBO.ERE_BULK_UPDATE_USERCASELOAD AS [TEMP] 
      ON TEMP.CLIENTNUMBER = U.CLIENTNUMBER
      AND TEMP.ID = U.ID;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate changes
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	U.ENDDATE, 
	U.ENDTIME,
	U.USERID
FROM DBO.USERCASELOAD AS [U]
   INNER JOIN (SELECT CLIENTNUMBER, 
                MAX(ID) AS [ID] 
              FROM DBO.USERCASELOAD
              GROUP BY CLIENTNUMBER
       ) AS [LATEST] 
      ON LATEST.CLIENTNUMBER = U.CLIENTNUMBER
      AND LATEST.ID = U.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON U.CLIENTNUMBER = PP.CLIENTNUMBER 
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PP.DOCREVNO = ' 0 ';

----- BULK UPDATE CLIENT STATUS -----

/*
Performs an update to the `client_status` to change it to 'InActive' from
'Active' on the `CLIENT` table when currently active clients have been bulk
dismissed. Excludes those whose discharge date was bulk updated because the
already dismissed clients whose dismissal date was updated to the BHS date of
admission may legitimately be currently 'Active' based on a subsequent
re-referral given the length of time elapsed since their initial dismissal from
the program. Therefore, this includes only those who were active until dismissed
based on BHS admission or three months elapsed. 
 */

-- create working table
SELECT *
INTO DBO.ERE_BULK_UPDATE_CLIENT
FROM (SELECT 
   PP.CLIENTNUMBER,
   PP.DOCSERNO,
   PP.STARTINGDATE, 
   PP.ENDINGDATE,
   PP.CLOSINGREASON,
   PP.BULK_DISMISSAL_SOURCE,
   C.VISITDT,     --Update this date
   C.VISITTM,     --Update this time
   C.USERID,      --Update this userid
   C.CLIENTSTATUS     --Update to 'InActive'
FROM DBO.CLIENT AS [C]
INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
	ON C.CLIENTNUMBER = PP.CLIENTNUMBER
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
	AND BULK_DISMISSAL_NOTE = 'ERE Bulk Dismissal Interim State-wide'
	AND PP.DOCREVNO = ' 0 '
	AND C.DOCREVNO = ' 0 '
) AS [X];

-- back up affected rows
SELECT C.*
INTO DBO.ERE_CLIENT_BACKUP_20261008
FROM DBO.CLIENT AS [C]
INNER JOIN DBO.ERE_BULK_UPDATE_CLIENT AS [TEMP]
	ON C.CLIENTNUMBER = TEMP.CLIENTNUMBER
WHERE C.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE C
    SET 
        C.CLIENTSTATUS = 'InActive',
        C.VISITDT = CAST(GETDATE() AS DATE),
        C.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        C.USERID = 'bradley-wing'
    FROM DBO.CLIENT AS [C]
INNER JOIN DBO.ERE_BULK_UPDATE_CLIENT AS [TEMP]
	ON C.CLIENTNUMBER = TEMP.CLIENTNUMBER
WHERE C.DOCREVNO = ' 0 ';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate changes
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	C.CLIENTSTATUS,
	C.VISITDT,
	C.VISITTM,
	C.USERID
FROM DBO.CLIENT AS [C]
INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
	ON C.CLIENTNUMBER = PP.CLIENTNUMBER
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
	AND BULK_DISMISSAL_NOTE = 'ERE Bulk Dismissal Interim State-wide'
	AND PP.DOCREVNO = ' 0 '
	AND C.DOCREVNO = ' 0 ';

----- BULK UPDATE PATHWAYCLIENT -----

/*
Performs an update to close the Pathway in the `PATHWAYCLIENT` tablewhen
dismissing the enrollment. Updates `enddate` using the `endingdate` from
`PROVIDERPLACEMENT`.
 */

-- create working table
SELECT *
INTO DBO.ERE_BULK_UPDATE_PATHWAYCLIENT
FROM (SELECT 
   PP.CLIENTNUMBER,
   PP.DOCSERNO,
   PP.STARTINGDATE, 
   PP.ENDINGDATE, -- Use this ENDINGDATE as DATETIME to update PC.ENDDATE
   PP.CLOSINGREASON,
   PP.BULK_DISMISSAL_SOURCE,
   PC.ID,
   PC.VISITDT,     --Update this date
   PC.VISITTM,     --Update this time
   PC.USERID,      --Update this userid
   PC.STARTDATE,
   PC.ENDDATE      --Update this date
FROM DBO.PATHWAYCLIENT AS [PC]
   INNER JOIN (SELECT CLIENTNUMBER, 
                DOCSERNO, 
                MAX(ID) AS [ID] 
              FROM DBO.PATHWAYCLIENT
              WHERE DOCREVNO = ' 0 ' 
              GROUP BY CLIENTNUMBER, 
                      DOCSERNO
       ) AS [LATEST] 
      ON LATEST.CLIENTNUMBER = PC.CLIENTNUMBER
      AND LATEST.DOCSERNO = PC.DOCSERNO
      AND LATEST.ID = PC.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON PC.CLIENTNUMBER = PP.CLIENTNUMBER
      AND PC.DOCSERNO = PP.DOCSERNO
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PP.DOCREVNO = ' 0 '
   AND PC.DOCREVNO = ' 0 '
) AS [X];

-- back up affected rows
SELECT PC.*
INTO DBO.ERE_PATHWAYCLIENT_BACKUP_20261008
FROM DBO.PATHWAYCLIENT AS [PC]
   INNER JOIN DBO.ERE_BULK_UPDATE_PATHWAYCLIENT AS [TEMP] 
      ON TEMP.CLIENTNUMBER = PC.CLIENTNUMBER
      AND TEMP.DOCSERNO = PC.DOCSERNO
      AND TEMP.ID = PC.ID
WHERE PC.DOCREVNO = ' 0 ';

-- bulk update
BEGIN TRY
    BEGIN TRANSACTION;

    UPDATE PC
    SET 
        PC.ENDDATE = TEMP.ENDINGDATE,
        PC.VISITDT = CAST(GETDATE() AS DATE),
        PC.VISITTM = CONVERT(VARCHAR(8), GETDATE(), 108),
        PC.USERID = 'bradley-wing'
    FROM DBO.PATHWAYCLIENT AS [PC]
   INNER JOIN DBO.ERE_BULK_UPDATE_PATHWAYCLIENT AS [TEMP] 
      ON TEMP.CLIENTNUMBER = PC.CLIENTNUMBER
      AND TEMP.DOCSERNO = PC.DOCSERNO
      AND TEMP.ID = PC.ID
WHERE PC.DOCREVNO = ' 0 ';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;

    SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_MESSAGE() AS ErrorMessage,
        ERROR_LINE() AS ErrorLine;
END CATCH;

-- validate changes
SELECT PP.CLIENTNUMBER,
	PP.DOCSERNO,
	PP.VISITDT,
	PP.VISITTM,
	PP.USERID,
    PP.STARTINGDATE,
    PP.ENDINGDATE,
	PP.BULK_DISMISSAL_FLAG,
	PP.BULK_DISMISSAL_SOURCE,
	PP.BULK_DISMISSAL_NOTE,
	PC.ENDDATE, 
	PC.VISITDT,
	PC.VISITTM,
	PC.USERID
FROM DBO.PATHWAYCLIENT AS [PC]
   INNER JOIN (SELECT CLIENTNUMBER, 
                DOCSERNO, 
                MAX(ID) AS [ID] 
              FROM DBO.PATHWAYCLIENT
              WHERE DOCREVNO = ' 0 ' 
              GROUP BY CLIENTNUMBER, 
                      DOCSERNO
       ) AS [LATEST] 
      ON LATEST.CLIENTNUMBER = PC.CLIENTNUMBER
      AND LATEST.DOCSERNO = PC.DOCSERNO
      AND LATEST.ID = PC.ID
   INNER JOIN DBO.PROVIDERPLACEMENT AS [PP]
      ON PC.CLIENTNUMBER = PP.CLIENTNUMBER
      AND PC.DOCSERNO = PP.DOCSERNO
WHERE PP.BULK_DISMISSAL_FLAG = 'Y'
   AND PP.DOCREVNO = ' 0 '
   AND PC.DOCREVNO = ' 0 ';
