/*
Report Name: bhn-wide-client-service-summary-fy2025
Category: Ad Hoc Analytics Reports  

See docs/ad-hoc-analytics/bhn-wide-client-service-summary-fy2025.md for full documentation.
*/

WITH [ENROLLMENTS] AS
(
	SELECT *
	FROM Q_BHNWIDE_PATHCLIENT_ENROLLMENTS
	WHERE PWY_EVENT LIKE ('%Referral')
		OR PWY_EVENT LIKE ('%Roster')
),
[CLIENT_DEMO] AS
(
	SELECT
		ID,
		CLIENT_NUMBER,
		CLIENT_LAST,
		CLIENT_FIRST,
		DOCSERNO,
		VISITDT,
		VISITTM,
		USERID,
		BIRTH_DATE,
		STREET,
		STREET2,
		CITY,
		STATE,
		ZIP_CODE,
		COUNTY_CODE,
		COUNTY_DESCRIPTION,
		LONGITUDE,
		LATITUDE
	FROM Q_CLIENT_BHN
),
[ENROLL_DEMO] AS 
(
	SELECT
		C.CLIENT_NUMBER,
		C.CLIENT_LAST,
		C.CLIENT_FIRST,
		C.BIRTH_DATE,
		C.STREET,
		C.CITY,
		C.ZIP_CODE,
		C.COUNTY_DESCRIPTION,
		DATEDIFF(
			YEAR,
			C.BIRTH_DATE,
			ENROLL.ENROLLMENT_STARTING_DATE
			) - CASE 
					WHEN DATEADD(
						YEAR, 
						DATEDIFF(
							YEAR,
							C.BIRTH_DATE,
							ENROLL.ENROLLMENT_STARTING_DATE
							),
							C.BIRTH_DATE
					) > ENROLL.ENROLLMENT_STARTING_DATE 
			THEN 1 
			ELSE 0 
		END AS [AGE_AT_ENROLLMENT],
		ENROLL.ENROLLMENT_STARTING_DATE,
		ENROLL.ENROLLMENT_ENDING_DATE,
		ENROLL.DISMISSAL_REASON_DESCRIPTION,
		ENROLL.PATHWAY_ID,
		ENROLL.AGENCY_DESCRIPTION,
		ENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER,
		ENROLL.PROGRAM_WORKER_LAST,
		ENROLL.PROGRAM_WORKER_FIRST
	FROM ENROLLMENTS AS [ENROLL]
	LEFT JOIN CLIENT_DEMO AS [C]
		ON C.CLIENT_NUMBER = ENROLL.CLIENT_NUMBER
),
-- limit to fiscal year window
[ENROLL_FY] AS
(
	SELECT *
	FROM ENROLL_DEMO
	WHERE ENROLLMENT_STARTING_DATE >= '2024-07-01'
		AND ENROLLMENT_STARTING_DATE <  '2025-07-01'
),
[CLIENT_FY] AS
(
	SELECT
		CLIENT_NUMBER,

		-- basic reference fields (optional)
		MIN(CLIENT_LAST)  AS [CLIENT_LAST],
		MIN(CLIENT_FIRST) AS [CLIENT_FIRST],

		MAX(ZIP_CODE) AS [ZIP_CODE],

		-- residence snapshot for reporting (not SCD-precise, but good enough for this ask)
		MAX(
			CASE
				WHEN COUNTY_DESCRIPTION IS NOT NULL
				THEN COUNTY_DESCRIPTION
				END
		) AS [COUNTY_DESCRIPTION],
		MAX(
			CASE
				WHEN COUNTY_DESCRIPTION = 'ST. LOUIS CITY'
				THEN ZIP_CODE
				END
		) AS [ANY_CITY_ZIP_CODE],

		-- flags
		MAX(
			CASE
				WHEN COUNTY_DESCRIPTION = 'ST. LOUIS CITY'
				THEN 1
				ELSE 0
				END
		) AS [IS_CITY_RESIDENT],
		MAX(
			CASE
			WHEN AGE_AT_ENROLLMENT >= 60
			THEN 1
			ELSE 0
			END
		) AS [EVER_60_PLUS],

		-- optional: earliest enrollment in FY
		MIN(ENROLLMENT_STARTING_DATE) AS [FIRST_ENROLLMENT_FY]
	FROM ENROLL_FY
	GROUP BY CLIENT_NUMBER
)
SELECT
	-- 1. Total distinct clients
	COUNT(*) AS [TOTAL_CLIENTS],

	-- 2. City residents
	SUM(CASE WHEN IS_CITY_RESIDENT = 1 THEN 1 ELSE 0 END) AS [CITY_CLIENTS],
	SUM(CASE WHEN IS_CITY_RESIDENT = 1 THEN 1 ELSE 0 END) * 1.0
		/ COUNT(*) AS [CITY_CLIENTS_PCT],

	-- 3. City residents age 60+
	SUM(CASE WHEN IS_CITY_RESIDENT = 1 AND EVER_60_PLUS = 1 THEN 1 ELSE 0 END)
		AS CITY_60PLUS_CLIENTS,
	SUM(CASE WHEN IS_CITY_RESIDENT = 1 AND EVER_60_PLUS = 1 THEN 1 ELSE 0 END) * 1.0
		/ NULLIF(SUM(CASE WHEN IS_CITY_RESIDENT = 1 THEN 1 END), 0) AS [CITY_60PLUS_CLIENTS_PCT],

	-- 4. Distinct ZIP codes served within St. Louis City - SQL Server 2019 does not allow DISTINCT inside STRING_AGG, so subquery instead
	(
		SELECT STRING_AGG(ZIP_CODE, ', ')
		FROM (
			SELECT DISTINCT ZIP_CODE
			FROM CLIENT_FY
			WHERE IS_CITY_RESIDENT = 1
			AND ZIP_CODE IS NOT NULL
		) AS [Z]
	) AS [CITY_ZIP_CODES],

	-- 5. County list (comma‑separated)
	(
		SELECT STRING_AGG(COUNTY_DESCRIPTION, ', ')
		FROM (
			SELECT DISTINCT COALESCE(COUNTY_DESCRIPTION,'UNKNOWN') AS [COUNTY_DESCRIPTION]
			FROM CLIENT_FY
		) AS [C]
) AS [COUNTIES_SERVED]
FROM CLIENT_FY;