/*
Report Name: BCR Enrolled No Referral  
Category: Exception Reports  

See docs/exception-reports/bcr-enrolled-no-referral.md for full documentation.
*/

SELECT BENROLL.CLIENT_NUMBER,
	BENROLL.CLIENT_LAST,
	BENROLL.CLIENT_FIRST,
	BENROLL.ENROLLMENT_STARTING_DATE,
	BENROLL.ENROLLMENT_ENDING_DATE
FROM Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
LEFT JOIN Q_BCR_REFERRAL AS [BREF]
	ON BENROLL.TIEDENROLLMENT = BREF.TIEDENROLLMENT
WHERE BENROLL.PWY_EVENT = 'BCR Referral'
	AND BENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND BENROLL.TIEDENROLLMENT IS NULL;