/*
Report Name: BCR Referrals Placed Hidden Fields Null  
Category: Exception Reports  

See docs/exception-reports/bcr-referrals-placed-hidden-fields-null.md for full documentation.
*/

SELECT BRP.ID,
	BRP.DOCSERNO,
	BRP.DOCREVNO,
	BRP.VISITDT,
	BRP.VISITTM,
	BRP.USERID,
	C.CLIENT_NUMBER,
	BRP.PATHWAY_DATE,
	BRP.BCR_TYPE_REF_PLACED,
	BRP.BH_REF_PLACED,
	BRP.PHYSICAL_HEALTH_REF_PLACED,
	BRP.HOUSING_REF_PLACED,
	BRP.MAT_HEALTH_REF_PLACED,
	BRP.OTHER_REF_PLACED,
	BRP.SOC_SERVICES_REF_PLACED,
	BRP.SPIRITUAL_CARE_REF_PLACED,
	BRP.BCR_REF_PLACED_BH_SUBTYPE,
	BRP.CMHC_REF_PLACED,
	BRP.COUNSELING_REF_PLACED,
	BRP.GROUP_PEER_SUPPORT_REF_PLACED,
	BRP.INDIVIDUAL_PEER_SUPPORT_REF_PLACED,
	BRP.SU_REF_PLACED,
	BRP.BCR_REF_PLACED_HOUSING_SUBTYPE,
	BRP.FURNITURE_REF_PLACED,
	BRP.HOME_REPAIR_REF_PLACED,
	BRP.HOMELESS_SERVICES_REF_PLACED,
	BRP.LANDLORD_MED_REF_PLACED,
	BRP.RENT_ASSIST_REF_PLACED,
	BRP.UTILITY_ASSIST_REF_PLACED,
	BRP.BCR_REF_PLACED_PHYS_HEALTH_SUBTYPE,
	BRP.PRIMARY_CARE_REF_PLACED,
	BRP.DENTAL_REF_PLACED,
	BRP.BCR_REF_PLACED_SOCIAL_SUBTYPE,
	BRP.CHILD_CARE_REF_PLACED,
	BRP.CLOTHING_REF_PLACED,
	BRP.DD_REF_PLACED,
	BRP.DV_REF_PLACED,
	BRP.EMPLOYMENT_REF_PLACED,
	BRP.FOOD_REF_PLACED,
	BRP.INSURANCE_REF_PLACED,
	BRP.LEGAL_REF_PLACED,
	BRP.LGBTQ_REF_PLACED,
	BRP.TRANSPORT_REF_PLACED
FROM BEHAVHEALT_LIVE.DBO.PWBCRREFERRALSPLACED AS [BRP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON BRP.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE BRP.DOCREVNO = ' 0 '
	AND (
		(
			BRP.BCR_TYPE_REF_PLACED IS NOT NULL
			AND (
				BRP.BH_REF_PLACED IS NULL
				OR BRP.PHYSICAL_HEALTH_REF_PLACED IS NULL
				OR BRP.HOUSING_REF_PLACED IS NULL
				OR BRP.MAT_HEALTH_REF_PLACED IS NULL
				OR BRP.OTHER_REF_PLACED IS NULL
				OR BRP.SOC_SERVICES_REF_PLACED IS NULL
				OR BRP.SPIRITUAL_CARE_REF_PLACED IS NULL
			)
		)
		OR (
			BRP.BCR_REF_PLACED_BH_SUBTYPE IS NOT NULL
			AND (
				BRP.CMHC_REF_PLACED IS NULL
				OR BRP.COUNSELING_REF_PLACED IS NULL
				OR BRP.GROUP_PEER_SUPPORT_REF_PLACED IS NULL
				OR BRP.INDIVIDUAL_PEER_SUPPORT_REF_PLACED IS NULL
				OR BRP.SU_REF_PLACED IS NULL
			)
		)
		OR (
			BRP.BCR_REF_PLACED_HOUSING_SUBTYPE IS NOT NULL
			AND (
				BRP.FURNITURE_REF_PLACED IS NULL
				OR BRP.HOME_REPAIR_REF_PLACED IS NULL
				OR BRP.HOMELESS_SERVICES_REF_PLACED IS NULL
				OR BRP.LANDLORD_MED_REF_PLACED IS NULL
				OR BRP.RENT_ASSIST_REF_PLACED IS NULL
				OR BRP.UTILITY_ASSIST_REF_PLACED IS NULL
			)
		)
		OR (
			BRP.BCR_REF_PLACED_PHYS_HEALTH_SUBTYPE IS NOT NULL
			AND (
				BRP.PRIMARY_CARE_REF_PLACED IS NULL
				OR BRP.DENTAL_REF_PLACED IS NULL
			)
		)
		OR (
			BRP.BCR_REF_PLACED_SOCIAL_SUBTYPE IS NOT NULL
			AND (
				BRP.CHILD_CARE_REF_PLACED IS NULL
				OR BRP.CLOTHING_REF_PLACED IS NULL
				OR BRP.DD_REF_PLACED IS NULL
				OR BRP.DV_REF_PLACED IS NULL
				OR BRP.EMPLOYMENT_REF_PLACED IS NULL
				OR BRP.FOOD_REF_PLACED IS NULL
				OR BRP.INSURANCE_REF_PLACED IS NULL
				OR BRP.LEGAL_REF_PLACED IS NULL
				OR BRP.LGBTQ_REF_PLACED IS NULL
				OR BRP.TRANSPORT_REF_PLACED IS NULL
			)
		)
	);