/*
Report Name: BCR Pathway Added Client Never Enrolled  
Category: Exception Reports  

See docs/exception-reports/bcr-pathway-added-client-never-enrolled.md for full documentation.
*/

SELECT PC.ID,
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(C.BIRTH_DATE AS DATE) AS [BIRTH_DATE],
	RACE.DESCRIPTION AS [RACE_DESCRIPTION],
	C.CLIENT_STATUS,
	CASE
		WHEN PP.STARTINGDATE IS NULL THEN 'Missing Enrollment'
	END AS [ENROLLMENT_STARTING_DATE],
	CAST(PC.VISITDT AS DATE) AS [VISITDT],
	PC.VISITTM,
	PC.USERID,
	PC.DOCSERNO AS [PC_DOCSERNO],
	PEC.PATHCLIENTDOCSERNO AS [PATHCLIENT_DOCSERNO],
	PP.DOCSERNO AS [PP_DOCSERNO],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	CAST(PC.STARTDATE AS DATE) AS [PWY_START_DATE],
	CAST(PC.GENDATE AS DATE) AS [PWY_GEN_DATE],
	CAST(PC.ENDDATE AS DATE) AS [PWY_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [DATE_ACCOMPLISHED]
FROM BEHAVHEALT_LIVE.DBO.PATHWAYCLIENT AS [PC]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON PC.CLIENTNUMBER = C.CLIENT_NUMBER
FULL OUTER JOIN (
	SELECT PEC1.CLIENTNUMBER,
		PEC1.USERID,
		PEC1.STARTDATE,
		PEC1.PARENTDOCSERNO,
		PEC1.PATHCLIENTDOCSERNO,
		PEC1.EVENTDOCSERNO,
		PEC1.DATEACCOMPLISHED
	FROM BEHAVHEALT_LIVE.DBO.PATHWAYEVENTCLIENT AS [PEC1]
	WHERE PEC1.ID = (
		SELECT MIN(PEC2.ID)
		FROM BEHAVHEALT_LIVE.DBO.PATHWAYEVENTCLIENT AS [PEC2]
		WHERE PEC2.CLIENTNUMBER = PEC1.CLIENTNUMBER
			AND PEC1.STARTDATE = PEC2.STARTDATE
			)
	) AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PC.DOCSERNO = PEC.PATHCLIENTDOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP] 
	ON PP.CLIENTNUMBER = C.CLIENT_NUMBER
	AND (
		(PP.DOCSERNO = PC.DOCSERNO)
		OR (PP.STARTINGDATE = PC.STARTDATE)
	)
	AND PP.DOCREVNO = ' 0 '
LEFT JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENT AS [PE]
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
LEFT JOIN BEHAVHEALT_LIVE.DBO.RACE AS [RACE]
	ON C.RACE_CODE = RACE.CODE
WHERE PC.DOCREVNO = ' 0 '
	AND PP.STARTINGDATE IS NULL
	AND PC.PARENTDOCSERNO = 55320240917145557321
	AND PE.SHORTDESCRIPTION = 'BCR Referral'
ORDER BY PC.VISITDT,
	PC.VISITTM;