/*
Report Name: BCR Duplicate Pathway Forms Per Enrollment  
Category: Exception Reports  

See docs/exception-reports/bcr-duplicate-pathway-forms-per-enrollment.md for full documentation.
*/

SELECT BENROLL.CLIENT_NUMBER,
	BENROLL.PWY_START_DATE,
	BENROLL.PWY_EVENT,
	BENROLL.EVENT_START_DATE,
	BENROLL.TIEDENROLLMENT,
	COUNT(BENROLL.PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
FROM BEHAVHEALT_LIVE.DBO.Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
WHERE BENROLL.TIEDENROLLMENT IS NOT NULL
GROUP BY BENROLL.CLIENT_NUMBER,
	BENROLL.PWY_START_DATE,
	BENROLL.PWY_EVENT,
	BENROLL.EVENT_START_DATE,
	BENROLL.TIEDENROLLMENT
HAVING COUNT(BENROLL.PWY_FORMS_DOCSERNO) > 1;