/*
Report Name: BCR Grant Missing  
Category: Exception Reports  

See docs/exception-reports/bcr-grant-missing.md for full documentation.
*/

SELECT C.ID,
	C.CLIENT_NUMBER,
	C.CLIENT_NAME AS [CLIENT],
	C.ZIP_CODE AS [ZIP CODE FROM CLIENT],
	BIC.ZIP_OF_INITIAL_CONTACT AS [ZIP CODE FROM IC],
	C.USERID AS [WHODUNIT],
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT DATE],
	CAST(BIC.PATHWAY_DATE AS DATE) AS [PATHWAY DATE],
	BCRGRANT.DESCRIPTION AS [GRANT]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
INNER JOIN BEHAVHEALT_LIVE.DBO.PWBCRINITIALCONTACT AS [BIC] 
	ON C.CLIENT_NUMBER = BIC.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.BCR_GRANT AS [BCRGRANT] 
	ON BIC.BCR_GRANT = BCRGRANT.CODE
WHERE BIC.DOCREVNO = ' 0 '
	AND PP.DOCREVNO = ' 0 '
	AND BIC.BCR_GRANT IS NULL;