/*
Report Name: BCR Multiple Referrals Per Enrollment  
Category: Exception Reports  

See docs/exception-reports/bcr-multiple-referrals-per-enrollment.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

SELECT C.ID,
	C.CLIENT_NUMBER,
	C.CLIENT_NAME AS [CLIENT],
	C.USERID AS [WHODUNIT],
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT DATE],
	CAST(BREF.PATHWAY_DATE AS DATE) AS [PATHWAY DATE],
	COUNT(BREF.PATHWAY_DATE) AS [COUNT REFERRALS]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
INNER JOIN BEHAVHEALT_LIVE.DBO.PWBCRREFERRAL AS [BREF] 
	ON C.CLIENT_NUMBER = BREF.CLIENTNUMBER
WHERE BREF.DOCREVNO = ' 0 '
	AND PP.DOCREVNO = ' 0 '
GROUP BY C.ID,
	C.CLIENT_NUMBER,
	C.CLIENT_NAME,
	C.USERID,
	PP.STARTINGDATE,
	BREF.PATHWAY_DATE
HAVING COUNT(BREF.PATHWAY_DATE) > 1;