/*
Report Name: BCR Client Active 90 Days or Longer  
Category: Exception Reports  

See docs/exception/bcr-client-active-90-days-or-longer.md for full documentation.
*/

SELECT DISTINCT C.CLIENT_NUMBER,
	C.CLIENT_LAST AS [CLIENT_LAST],
	C.CLIENT_FIRST AS [CLIENT_FIRST],
	CAST(PP.ENROLLMENT_STARTING_DATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(DATEADD(DAY, 90, PP.ENROLLMENT_STARTING_DATE) AS DATE) AS [90_DAY_DATE]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN (
	SELECT CLIENTNUMBER,
		MIN(STARTINGDATE) AS [ENROLLMENT_STARTING_DATE]
	FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT
	WHERE DOCREVNO = ' 0 '
		AND ENDINGDATE IS NULL
	GROUP BY CLIENTNUMBER
) AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYCLIENT AS [PC] 
	ON C.CLIENT_NUMBER = PC.CLIENTNUMBER
	AND PC.STARTDATE = PP.ENROLLMENT_STARTING_DATE
	AND PC.DOCREVNO = ' 0 '
WHERE DATEDIFF(DAY, PP.ENROLLMENT_STARTING_DATE, GETDATE()) >= 90
ORDER BY C.CLIENT_LAST,
	C.CLIENT_FIRST,
	[ENROLLMENT_STARTING_DATE];