/*
Report Name: Client Dismissed But Client Status Still Active
Category: Exception Reports  

See docs/exception-reports/clients-dismissed-but-client-status-still-active.md for full documentation.
*/

SELECT C.CLIENT_STATUS AS [CLIENT_STATUS],
	C.CLIENT_FIRST AS [FIRST_NAME],
	C.CLIENT_LAST AS [LAST_NAME],
	C.CLIENT_NUMBER AS [CLIENT_NUMBER],
	CAST(C.VISITDT AS DATE) AS [DATE_ENTERED],
	C.VISITTM AS [TIME_ENTERED],
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [DISMISSAL_DATE],
	C.USERID AS [CLIENT_USERID],
	PP.USERID AS [PROVIDERPLACEMENT_USERID]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDERPLACEMENT AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
WHERE C.CLIENT_STATUS = 'Active'
	AND NOT EXISTS (
		SELECT 1
			FROM BEHAVHEALT_LIVE.DBO.Q_PROVIDERPLACEMENT AS [PP2]
			WHERE PP2.CLIENTNUMBER = C.CLIENT_NUMBER
			AND PP2.ENDINGDATE IS NULL
		)
	AND PP.ENDINGDATE IS NOT NULL;