/*
Report Name: Client With Missing Demographics  
Category: Exception Reports  

See docs/exception/client-with-missing-demographics.md for full documentation.
*/

SELECT C.CLIENT_STATUS AS [CLIENT STATUS],
	C.CLIENT_FIRST AS [FIRST NAME],
	C.CLIENT_LAST AS [LAST NAME],
	C.CLIENT_NUMBER AS [CLIENT NUMBER],
	CASE 
		WHEN C.RACE_DESCRIPTION IS NULL 
		THEN '??????' 
		ELSE NULL 
	END AS [RACE],
	CASE 
		WHEN C.GENDER_DESCRIPTION IS NULL 
		THEN '??????' 
		ELSE NULL 
	END AS [GENDER],
	CASE 
		WHEN C.ETHNICITY_DESCRIPTION IS NULL 
		THEN '??????' 
		ELSE NULL 
	END AS [ETHNICITY],
	CASE 
		WHEN C.ZIP_CODE IS NULL 
		THEN '??????' 
		ELSE NULL 
	END AS [ZIP CODE MISSING],
	CASE 
		WHEN C.BIRTH_DATE IS NULL 
		THEN '??????' 
		ELSE NULL 
	END AS [DOB],
	C.VISITDT AS [DATE ENTERED],
	C.VISITTM AS [TIME ENTERED],
	C.USERID AS [WHODUNIT]
FROM [behavhealt_live].dbo.Q_CLIENT_BHN AS [C]
WHERE C.RACE_CODE IS NULL 
	OR C.GENDER_CODE IS NULL 
	OR C.ETHNICITY_CODE IS NULL 
	OR C.BIRTH_DATE IS NULL 
	OR C.ZIP_CODE IS NULL;