/*
Report Name: Clients With Multiple Active Enrollments  
Category: Exception Reports  

See docs/exception-reports/clients-with-multiple-active-enrollments.md for full documentation.
*/

SELECT C.ID,
	C.CLIENT_NUMBER,
	C.CLIENT_NAME AS [CLIENT],
	COUNT(PP.ENROLLMENT_STARTING_DATE) AS [COUNT ENROLLMENTS]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDERPLACEMENT_BHN AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENT_NUMBER
	AND PP.ENROLLMENT_ENDING_DATE IS NULL
GROUP BY C.ID,
	C.CLIENT_NUMBER,
	C.CLIENT_NAME
HAVING COUNT(PP.ENROLLMENT_STARTING_DATE) > 1;