/*
Report Name: Complex Care BEACN Enrolled No Roster  
Category: Exception Reports  

See docs/exception-reports/complex-care-beacn-enrolled-no-roster.md for full documentation.
*/

SELECT  CENROLL.CLIENT_NUMBER,
	CENROLL.CLIENT_LAST,
	CENROLL.CLIENT_FIRST,
	CENROLL.ENROLLMENT_STARTING_DATE,
	CENROLL.ENROLLMENT_ENDING_DATE
FROM Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS [CENROLL]
LEFT JOIN Q_COMPLEX_CARE_ROSTER AS [ROSTER]
	ON CENROLL.TIEDENROLLMENT = ROSTER.TIEDENROLLMENT
WHERE CENROLL.PWY_EVENT = 'Complex Care Roster'
	AND CENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND CENROLL.TIEDENROLLMENT IS NULL;