/*
Report Name: Complex Care BEACN Duplicate PWY Forms Per Enrollment
Category: Exception Reports  

See docs/exception-reports/complex-care-beacn-duplicate-pwy-forms-per-enrollment.md for full documentation.
*/

SELECT CENROLL.CLIENT_NUMBER,
	CENROLL.PWY_START_DATE,
	CENROLL.PWY_EVENT,
	CENROLL.EVENT_START_DATE,
	CENROLL.TIEDENROLLMENT,
	COUNT(CENROLL.PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
FROM BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS [CENROLL]
WHERE CENROLL.TIEDENROLLMENT IS NOT NULL
GROUP BY CENROLL.CLIENT_NUMBER,
	CENROLL.PWY_START_DATE,
	CENROLL.PWY_EVENT,
	CENROLL.EVENT_START_DATE,
	CENROLL.TIEDENROLLMENT
HAVING COUNT(CENROLL.PWY_FORMS_DOCSERNO) > 1;