/*
Report Name: Dup YERE Client Family Needs Records Per TIEDENROLLMENT
Category: Exception Reports  

See docs/exception-reports/dup-yere-client-family-needs-records-per-tiedenrollment.md for full documentation.
*/

SELECT
	C.CLIENT_NUMBER,
	YENROLL.TIEDENROLLMENT,
	COUNT(YFNEEDS.DOCSERNO) AS [COUNT_NEEDS_DOCSERNO]
FROM Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON YENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
INNER JOIN Q_YERE_CLIENT_FAMILY_NEEDS AS [YFNEEDS]
	ON YENROLL.CLIENT_NUMBER = YFNEEDS.CLIENT_NUMBER
	AND YENROLL.PWY_FORMS_DOCSERNO = YFNEEDS.PARENT_DOCSERNO
GROUP BY C.CLIENT_NUMBER, YENROLL.TIEDENROLLMENT
HAVING COUNT(YFNEEDS.DOCSERNO) > 1
ORDER BY C.CLIENT_NUMBER