/*
Report Name: Dup YERE Needs Forms Youth Family Client Or Caregiver
Category: Exception Reports  

See docs/exception-reports/dup-yere-needs-forms-youth-family-vs-client-caregiver.md for full documentation.
*/

SELECT C.CLIENT_NUMBER,
	YENROLL.TIEDENROLLMENT AS [TIEDENROLLMENT],
	MAX(YNEEDS.DOCSERNO) as [Client Needs Present],
    MAX(CNEEDS.DOCSERNO) as [Caregiver Needs Present],
    MAX(YFNEEDS.DOCSERNO) as [Youth / Family Needs Present]
FROM Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON YENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN Q_YERE_CLIENT_NEEDS AS [YNEEDS]
	ON YENROLL.CLIENT_NUMBER = YNEEDS.CLIENT_NUMBER
	AND YENROLL.PWY_FORMS_DOCSERNO = YNEEDS.PARENT_DOCSERNO
LEFT JOIN Q_YERE_CAREGIVER_NEEDS AS [CNEEDS]
	ON YENROLL.CLIENT_NUMBER = CNEEDS.CLIENT_NUMBER
	AND YENROLL.PWY_FORMS_DOCSERNO = CNEEDS.PARENT_DOCSERNO
LEFT JOIN Q_YERE_CLIENT_FAMILY_NEEDS AS [YFNEEDS]
	ON YENROLL.CLIENT_NUMBER = YFNEEDS.CLIENT_NUMBER
	AND YENROLL.PWY_FORMS_DOCSERNO = YFNEEDS.PARENT_DOCSERNO
GROUP BY C.CLIENT_NUMBER, YENROLL.TIEDENROLLMENT
HAVING (MAX(YNEEDS.DOCSERNO) IS NOT NULL OR MAX(CNEEDS.DOCSERNO) IS NOT NULL)
    AND MAX (YFNEEDS.DOCSERNO) IS NOT NULL
ORDER BY YENROLL.TIEDENROLLMENT;