/*
Report Name: Duplicate ERE Needs Records Per TIEDENROLLMENT
Category: Exception Reports  

See docs/exception-reports/duplicate-ere-needs-records-per-tiedenrollment.md for full documentation.
*/

SELECT
	C.CLIENT_NUMBER,
	EREENROLL.TIEDENROLLMENT,
	COUNT(ERENEEDS.DOCSERNO) AS [COUNT_NEEDS_DOCSERNO]
FROM Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON EREENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
INNER JOIN Q_ERE_CLIENT_NEEDS AS [ERENEEDS]
	ON EREENROLL.CLIENT_NUMBER = ERENEEDS.CLIENT_NUMBER
	AND EREENROLL.PWY_FORMS_DOCSERNO = ERENEEDS.PARENT_DOCSERNO
GROUP BY C.CLIENT_NUMBER, EREENROLL.TIEDENROLLMENT
HAVING COUNT(ERENEEDS.DOCSERNO) > 1
ORDER BY C.CLIENT_NUMBER