/*
Report Name: Duplicate YERE Client Needs Records Per TIEDENROLLMENT
Category: Exception Reports  

See docs/exception-reports/duplicate-yere-client-needs-records-per-tiedenrollment.md for full documentation.
*/

SELECT
	C.CLIENT_NUMBER,
	YENROLL.TIEDENROLLMENT,
	COUNT(YNEEDS.DOCSERNO) AS [COUNT_NEEDS_DOCSERNO]
FROM Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON YENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
INNER JOIN Q_YERE_CLIENT_NEEDS AS [YNEEDS]
	ON YENROLL.CLIENT_NUMBER = YNEEDS.CLIENTNUMBER
	AND YENROLL.PWY_FORMS_DOCSERNO = YNEEDS.PARENTDOCSERNO
GROUP BY C.CLIENT_NUMBER, YENROLL.TIEDENROLLMENT
HAVING COUNT(YNEEDS.DOCSERNO) > 1
ORDER BY C.CLIENT_NUMBER