/*
Report Name: Duplicate YERE Cargivr Needs Records Per TIEDENROLLMENT
Category: Exception Reports  

See docs/exception-reports/duplicate-yere-cargivr-needs-records-per-tiedenrollment.md for full documentation.
*/

SELECT C.CLIENT_NUMBER,
	YENROLL.TIEDENROLLMENT,
	COUNT(YCARE.DOCSERNO) AS [COUNT_NEEDS_DOCSERNO]
FROM Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON YENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
INNER JOIN Q_YERE_CAREGIVER_NEEDS AS [YCARE]
	ON YENROLL.CLIENT_NUMBER = YCARE.CLIENT_NUMBER
	AND YENROLL.PWY_FORMS_DOCSERNO = YCARE.PARENT_DOCSERNO
GROUP BY C.CLIENT_NUMBER, YENROLL.TIEDENROLLMENT
HAVING COUNT(YCARE.DOCSERNO) > 1
ORDER BY C.CLIENT_NUMBER