/*
Report Name: EPICC ENROLLED NO REFERRAL
Category: Exception Reports

See docs/exception-reports/epicc-enrolled-no-referral.md for full documentation.
*/

SELECT EENROLL.CLIENT_NUMBER,
	EENROLL.CLIENT_LAST,
	EENROLL.CLIENT_FIRST,
	EENROLL.ENROLLMENT_STARTING_DATE,
	EENROLL.ENROLLMENT_ENDING_DATE,
	EENROLL.TIEDENROLLMENT
FROM Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL]
LEFT JOIN Q_EPICC_REFERRAL AS [EREF]
	ON EENROLL.TIEDENROLLMENT = EREF.TIEDENROLLMENT
WHERE EENROLL.PWY_EVENT = 'EPICC Referral'
	AND EENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND EENROLL.TIEDENROLLMENT IS NULL;