/*
Report Name: EPICC Duplicate PWY Forms Per Enrollment
Category: Exception Reports  

See docs/exception-reports/epicc-duplicate-pwy-forms-per-enrollment.md for full documentation.
*/

SELECT EENROLL.CLIENT_NUMBER,
	EENROLL.PWY_START_DATE,
	EENROLL.PWY_EVENT,
	EENROLL.EVENT_START_DATE,
	EENROLL.TIEDENROLLMENT,
	COUNT(EENROLL.PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL]
WHERE EENROLL.TIEDENROLLMENT IS NOT NULL
GROUP BY EENROLL.CLIENT_NUMBER,
	EENROLL.PWY_START_DATE,
	EENROLL.PWY_EVENT,
	EENROLL.EVENT_START_DATE,
	EENROLL.TIEDENROLLMENT
HAVING COUNT(EENROLL.PWY_FORMS_DOCSERNO) > 1;