/*
Report Name: EPICC IC Opioids of Use Hidden Fields Null
Category: Exception Reports

See docs/exception-reports/epicc-ic-opioids-of-use-hidden-fields-null.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

SELECT IC.ID,
	IC.DOCSERNO,
	IC.DOCREVNO,
	IC.VISITDT,
	IC.VISITTM,
	IC.USERID,
	IC.CLIENTNUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	IC.PATHWAY_DATE,
	IC.EPICC_OPIOIDS_OF_USE,
	IC.OPIOID_OF_USE_FENTANYL,
	IC.OPIOID_OF_USE_HEROIN,
	IC.OPIOID_OF_USE_PRESCRIPTION_OPIATES,
	IC.OPIOID_OF_USE_SUBOXONE_MAT,
	IC.OPIOID_OF_USE_OTHER
FROM BEHAVHEALT_LIVE.DBO.PWEPICCINITIALCONTACT AS [IC]
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON IC.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE IC.DOCREVNO = ' 0 '
	AND IC.EPICC_OPIOIDS_OF_USE IS NOT NULL
	AND (
		IC.OPIOID_OF_USE_FENTANYL IS NULL
		OR IC.OPIOID_OF_USE_PRESCRIPTION_OPIATES IS NULL
		OR IC.OPIOID_OF_USE_HEROIN IS NULL
		OR IC.OPIOID_OF_USE_SUBOXONE_MAT IS NULL
	)