/*
Report Name: EPICC IC PWY Date Outside Same Day Enrollment Range  
Category: Exception Reports  

See docs/exception/epicc-ic-pwy-date-outside--enrollment-range.md for full documentation.
*/


SELECT CLIENT_NUMBER,
	CLIENT_LAST,
	CLIENT_FIRST,
	PWY_EVENT,
	PATHWAY_DATE,
	ENROLLMENT_STARTING_DATE,
	ENROLLMENT_ENDING_DATE,
	DISMISSAL_REASON_DESCRIPTION
FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS
WHERE ENROLLMENT_STARTING_DATE = ENROLLMENT_ENDING_DATE
	AND PATHWAY_DATE <> ENROLLMENT_STARTING_DATE
	AND ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND PWY_EVENT = 'EPICC Initial Contact'
ORDER BY CLIENT_LAST,
	CLIENT_FIRST;