/*
Report Name: ERE Enrolled No Referral  
Category: Exception Reports  

See docs/exception-reports/ere-enrolled-no-referral.md for full documentation.
*/

SELECT EREENROLL.CLIENT_NUMBER,
	EREENROLL.CLIENT_LAST,
	EREENROLL.CLIENT_FIRST,
	EREENROLL.ENROLLMENT_STARTING_DATE,
	EREENROLL.ENROLLMENT_ENDING_DATE
FROM Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
LEFT JOIN Q_ERE_REFERRAL AS [EREREF]
	ON EREENROLL.TIEDENROLLMENT = EREREF.TIEDENROLLMENT
WHERE EREENROLL.PWY_EVENT = 'ERE Referral'
	AND EREENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND EREENROLL.TIEDENROLLMENT IS NULL;