/*
Report Name: ERE Duplicate PWY Forms Per Enrollment
Category: Exception Reports  

See docs/exception-reports/ere-duplicate-pwy-forms-per-enrollment.md for full documentation.
*/

SELECT EREENROLL.CLIENT_NUMBER,
	EREENROLL.PWY_START_DATE,
	EREENROLL.PWY_EVENT,
	EREENROLL.EVENT_START_DATE,
	EREENROLL.PEC_PATHCLIENT_DOCSERNO,
	COUNT(EREENROLL.PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
FROM BEHAVHEALT_LIVE.DBO.Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
WHERE EREENROLL.PE_DATE_ACCOMPLISHED IS NOT NULL
GROUP BY EREENROLL.CLIENT_NUMBER,
	EREENROLL.PWY_START_DATE,
	EREENROLL.PWY_EVENT,
	EREENROLL.EVENT_START_DATE,
	EREENROLL.PEC_PATHCLIENT_DOCSERNO
HAVING COUNT(EREENROLL.PWY_FORMS_DOCSERNO) > 1;