/*
Report Name: Orphaned PWPAYORSOURCE Summation Records
Category: Exception Reports  

See docs/exception-reports/orphaned-pwpayorsource-summation-records.md for full documentation.
*/

SELECT C.CLIENT_NUMBER,
	CAST(HOUSE.PATHWAY_DATE AS DATE) AS [HOUSE_PATHWAY_DATE],
	HOUSE.DOCSERNO AS [HOUSE_DOCSERNO],
	HOUSE.PARENTDOCSERNO AS [HOUSE_PARENT_DOCSERNO],
	ALLPF.PATHWAY_DATE AS [PARENT_PATHWAY_DATE],
	ALLPF.DOCSERNO AS [PARENT_DOCSERNO],
	ALLPF.FORM_TYPE AS [PARENT_FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWHOUSINGSTATUS AS [HOUSE]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON HOUSE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN  Q_ALL_PATHWAY_FORM_DOCSERNOS AS [ALLPF]
	ON HOUSE.PARENTDOCSERNO = ALLPF.DOCSERNO
WHERE HOUSE.DOCREVNO = ' 0 '
	AND ALLPF.FORM_TYPE IS NULL
	AND HOUSE.PARENTDOCSERNO <> ''
	AND HOUSE.PARENTDOCSERNO IS NOT NULL;