/*
Report Name: Orphaned PWPAYORSOURCE Summation Records
Category: Exception Reports  

See docs/exception-reports/orphaned-pwpayorsource-summation-records.md for full documentation.
*/

SELECT C.CLIENT_NUMBER,
	CAST(PAY.PATHWAY_DATE AS DATE) AS [PAY_PATHWAY_DATE],
	PAY.DOCSERNO AS [PAY_DOCSERNO],
	PAY.PARENTDOCSERNO AS [PAY_PARENT_DOCSERNO],
	DELPF.FORM_TYPE AS [DELETED_PARENT_FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWPAYORSOURCE AS [PAY]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON PAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN  Q_ALL_PATHWAY_FORM_DOCSERNOS AS [ALLPF]
	ON PAY.PARENTDOCSERNO = ALLPF.DOCSERNO
LEFT JOIN Q_ALL_DELETED_PATHWAY_FORM_DOCSERNOS AS [DELPF]
    ON PAY.PARENTDOCSERNO = DELPF.DOCSERNO
WHERE PAY.DOCREVNO = ' 0 '
	AND ALLPF.FORM_TYPE IS NULL
	AND PAY.PARENTDOCSERNO <> ''
	AND PAY.PARENTDOCSERNO IS NOT NULL