/*
Report Name: Pathway Still Open Enrollment Closed
Category: Exception Reports  

See docs/exception-reports/pathway-still-open-enrollment-closed.md for full documentation.
*/

SELECT P.PROVIDERNAME AS [PROGRAM_DESCRIPTION],
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	HR.FIRSTNAME + ' ' + HR.LASTNAME AS [WORKER],
	HRR.LASTNAME + ', ' + HRR.FIRSTNAME AS [SUPERVISOR],
	CAST(PP.ENROLLMENT_STARTING_DATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENROLLMENT_ENDING_DATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CAST(PC.STARTDATE AS DATE) AS [PWY_START_DATE],
	CAST(PC.ENDDATE AS DATE) AS [PWY_END_DATE]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN PATHWAYEVENTCLIENT AS [PEC] 
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN PATHWAYCLIENT AS [PC] 
	ON PEC.PATHCLIENTDOCSERNO = PC.DOCSERNO
	AND PC.DOCREVNO = ' 0 '
	AND PC.ENDDATE IS NULL
INNER JOIN PATHWAYEVENT AS [PE] 
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN PATHWAY AS [PWY] 
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
INNER JOIN Q_PROVIDERPLACEMENT_BHN AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENT_NUMBER
	AND PP.PATHWAY = PWY.DOCSERNO
	AND (
		(
			PP.DOCSERNO = PEC.PATHCLIENTDOCSERNO
			) 
		OR (
			PP.ENROLLMENT_STARTING_DATE = PC.STARTDATE
		)
	)
	AND PP.ENROLLMENT_ENDING_DATE IS NOT NULL
INNER JOIN Q_PROVIDER AS [P] 
	ON PP.PROGRAM_CODE = P.PROVIDERCODE
LEFT JOIN Q_HRFORM AS [HR] 
	ON HR.EMPLOYEENUMBER = PP.PROGRAM_WORKER
LEFT JOIN Q_HRFORM AS [HRR] 
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
WHERE 
	(
		P.PROVIDERCODE IN (
		'^^PROGRAM|SELECT P.PROVIDERCODE, P.PROVIDERNAME FROM Q_PROVIDER AS [P] WHERE P.ORGANIZATIONTYPE = 'PO' AND P.MASTERPROVIDER <> 'Yes' AND P.PROVIDERSTATUS = 'ACTIVE' ORDER BY P.PROVIDERNAME^^'
		)
		OR '^^PROGRAM^^' = ''
	)
GROUP BY P.PROVIDERNAME,
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	HR.FIRSTNAME,
	HR.LASTNAME,
	HRR.LASTNAME,
	HRR.FIRSTNAME,
	PP.ENROLLMENT_STARTING_DATE,
	PP.ENROLLMENT_ENDING_DATE,
	PC.STARTDATE,
	PC.ENDDATE
ORDER BY [PROGRAM_DESCRIPTION],
	[WORKER],
	[CLIENT_LAST];