/*
Report Name: Pathway Closed Enrollment Still Active
Category: Exception Reports  

See docs/exception-reports/pathway-closed-enrollment-still-active.md for full documentation.
*/

SELECT P.PROVIDERNAME AS [PROGRAM_DESCRIPTION],
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	HR.FIRSTNAME + ' ' + HR.LASTNAME AS [WORKER],
	HRR.LASTNAME + ', ' + HRR.FIRSTNAME AS [SUPERVISOR],
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PC.STARTDATE AS DATE) AS [PWY_START_DATE],
	CAST(PC.ENDDATE AS DATE) AS [PWY_END_DATE]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENTCLIENT AS [PEC] 
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYCLIENT AS [PC] 
	ON PEC.PATHCLIENTDOCSERNO = PC.DOCSERNO
	AND PC.DOCREVNO = ' 0 '
	AND PC.ENDDATE IS NOT NULL
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENT AS [PE] 
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAY AS [PWY] 
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = PWY.DOCSERNO
	AND PP.DOCSERNO = PEC.PATHCLIENTDOCSERNO
	AND PP.ENDINGDATE IS NULL
	AND PP.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDER AS [P] 
	ON PP.REGION = P.PROVIDERCODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR] 
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HRR] 
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
WHERE (
		PROVIDERCODE IN (
			'^^PROGRAM|SELECT PROVIDERCODE, PROVIDERNAME FROM Q_PROVIDER WHERE ORGANIZATIONTYPE = 'PO' AND MASTERPROVIDER <> 'Yes' AND PROVIDERSTATUS = 'ACTIVE' AND DOCREVNO=' 0 ' ORDER BY PROVIDERNAME^^'
		)
		OR '^^PROGRAM^^' = ''
	)
GROUP BY P.PROVIDERNAME,
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	HR.FIRSTNAME,
	HR.LASTNAME,
	HRR.LASTNAME,
	HRR.FIRSTNAME,
	PP.STARTINGDATE,
	PC.STARTDATE,
	PC.ENDDATE
ORDER BY [PROGRAM_DESCRIPTION],
	[WORKER];