/*
Report Name: YERE Duplicate PWY Forms Per Enrollment
Category: Exception Reports  

See docs/exception/yere-duplicate-pwy-forms-per-enrollment.md for full documentation.
*/

SELECT [EENROLL].CLIENT_NUMBER,
	[EENROLL].PWY_START_DATE,
	[EENROLL].PWY_EVENT,
	[EENROLL].EVENT_START_DATE,
	[EENROLL].PEC_PATHCLIENT_DOCSERNO,
	COUNT([EENROLL].PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
FROM BEHAVHEALT_LIVE.DBO.Q_YERE_PATHCLIENT_ENROLLMENTS AS [EENROLL]
WHERE [EENROLL].PE_DATE_ACCOMPLISHED IS NOT NULL
GROUP BY [EENROLL].CLIENT_NUMBER,
	[EENROLL].PWY_START_DATE,
	[EENROLL].PWY_EVENT,
	[EENROLL].EVENT_START_DATE,
	[EENROLL].PEC_PATHCLIENT_DOCSERNO
HAVING COUNT([EENROLL].PWY_FORMS_DOCSERNO) > 1;