/*
Report Name: YERE Enrolled No Referral  
Category: Exception Reports  

See docs/exception-reports/yere-enrolled-no-referral.md for full documentation.
*/

SELECT YENROLL.CLIENT_NUMBER,
	YENROLL.CLIENT_LAST,
	YENROLL.CLIENT_FIRST,
	YENROLL.ENROLLMENT_STARTING_DATE,
	YENROLL.ENROLLMENT_ENDING_DATE
FROM Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
LEFT JOIN Q_YERE_REFERRAL AS [YREF]
	ON YENROLL.TIEDENROLLMENT = YREF.TIEDENROLLMENT
WHERE YENROLL.PWY_EVENT = 'YERE Referral'
	AND YENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND YENROLL.TIEDENROLLMENT IS NULL;