/*
Report Name: YERE Duplicate PWY Forms Per Enrollment
Category: Exception Reports  

See docs/exception-reports/yere-duplicate-pwy-forms-per-enrollment.md for full documentation.
*/

SELECT YENROLL.CLIENT_NUMBER,
	YENROLL.PWY_START_DATE,
	YENROLL.PWY_EVENT,
	YENROLL.EVENT_START_DATE,
	YENROLL.TIEDENROLLMENT,
	COUNT(YENROLL.PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
FROM BEHAVHEALT_LIVE.DBO.Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
WHERE YENROLL.TIEDENROLLMENT IS NOT NULL
GROUP BY YENROLL.CLIENT_NUMBER,
	YENROLL.PWY_START_DATE,
	YENROLL.PWY_EVENT,
	YENROLL.EVENT_START_DATE,
	YENROLL.TIEDENROLLMENT
HAVING COUNT(YENROLL.PWY_FORMS_DOCSERNO) > 1;