/*

*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_ALL_DELETED_PATHWAY_FORM_DOCSERNOS AS
SELECT EREPF.CLIENT_NUMBER,
	EREPF.PATHWAY_DATE,
	EREPF.DOCSERNO,
	EREPF.TIEDENROLLMENT,
	EREPF.FORM_TYPE
FROM DBO.Q_ERE_DELETED_PATHWAY_FORM_DOCSERNOS AS [EREPF]
UNION ALL
SELECT EPF.CLIENT_NUMBER,
	EPF.PATHWAY_DATE,
	EPF.DOCSERNO,
	EPF.TIEDENROLLMENT,
	EPF.FORM_TYPE
FROM DBO.Q_EPICC_DELETED_PATHWAY_FORM_DOCSERNOS AS [EPF]
UNION ALL
SELECT BPF.CLIENT_NUMBER,
	BPF.PATHWAY_DATE,
	BPF.DOCSERNO,
	BPF.TIEDENROLLMENT,
	BPF.FORM_TYPE
FROM DBO.Q_BCR_DELETED_PATHWAY_FORM_DOCSERNOS AS [BPF]
UNION ALL
SELECT YPF.CLIENT_NUMBER,
	YPF.PATHWAY_DATE,
	YPF.DOCSERNO,
	YPF.TIEDENROLLMENT,
	YPF.FORM_TYPE
FROM DBO.Q_YERE_DELETED_PATHWAY_FORM_DOCSERNOS AS [YPF]
UNION ALL
SELECT CPF.CLIENT_NUMBER,
	CPF.PATHWAY_DATE,
	CPF.DOCSERNO,
	CPF.TIEDENROLLMENT,
	CPF.FORM_TYPE
FROM DBO.Q_COMPLEX_CARE_DELETED_PATHWAY_FORM_DOCSERNOS AS [CPF]
