/*
View Name: Q_BCR_PHQ_DASS_REF_PLACED_W_DEMOGRAPHICS  
Category: View Definitions  

See docs/view-definitions/q-bcr-phq-dass-bh-ref-placed-w-demographics.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW .DBO.Q_BCR_PHQ_DASS_REF_PLACED_W_DEMOGRAPHICS AS
WITH [INITIAL_CONTACTS] AS (
	SELECT BENROLL.CLIENT_NUMBER,
		BENROLL.CLIENT_LAST,
		BENROLL.CLIENT_FIRST,
		C.BIRTH_DATE,
		C.GENDER_DESCRIPTION,
		C.RACE_DESCRIPTION,
		C.ETHNICITY_DESCRIPTION,
		C.ZIP_CODE,
		C.COUNTY_DESCRIPTION,
		BENROLL.ENROLLMENT_STARTING_DATE,
		BENROLL.ENROLLMENT_ENDING_DATE,
		BENROLL.TIEDENROLLMENT,
		BIC.PHQ9_SCORE,
		BIC.DASS_SCORE_IC
	FROM Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
	LEFT JOIN Q_CLIENT_BHN AS [C]
		ON C.CLIENT_NUMBER = BENROLL.CLIENT_NUMBER
	LEFT JOIN Q_BCR_IC AS [BIC]
		ON BIC.CLIENT_NUMBER = BENROLL.CLIENT_NUMBER
		AND BIC.DOCSERNO = BENROLL.PWY_FORMS_DOCSERNO
	WHERE BENROLL.PWY_EVENT = 'BCR Initial Contact'
		AND PHQ9_SCORE IS NOT NULL
		AND DASS_SCORE_IC IS NOT NULL
		),
[REFERRALS_PLACED] AS (
	SELECT BENROLL.CLIENT_NUMBER,
		BRP.BH_REF_PLACED,
		BRP.COUNSELING_REF_PLACED,
		BENROLL.TIEDENROLLMENT
	FROM Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
	LEFT JOIN Q_CLIENT_BHN AS [C]
		ON C.CLIENT_NUMBER = BENROLL.CLIENT_NUMBER
	LEFT JOIN Q_BCR_REF_PLACED AS [BRP]
		ON BRP.CLIENT_NUMBER = BENROLL.CLIENT_NUMBER
		AND BRP.DOCSERNO = BENROLL.PWY_FORMS_DOCSERNO
	WHERE BENROLL.PWY_EVENT = 'BCR Referrals Placed'
		AND BH_REF_PLACED = '1'
),
[CLIENT_COUNSELING] AS(
SELECT 
	BCC.CLIENT_NUMBER,
	COUNT(BCC.CLIENT_NUMBER) AS [COUNT_COUNSELING_SESSIONS]
FROM Q_BCR_CLIENT_COUNSELING_SESSIONS AS [BCC]
GROUP BY BCC.CLIENT_NUMBER
)
SELECT BIC.CLIENT_NUMBER,
	BIC.CLIENT_LAST,
	BIC.CLIENT_FIRST,
	BIC.ENROLLMENT_STARTING_DATE,
	BIC.ENROLLMENT_ENDING_DATE,
	BIC.BIRTH_DATE,
	BIC.GENDER_DESCRIPTION,
	BIC.RACE_DESCRIPTION,
	BIC.ETHNICITY_DESCRIPTION,
	BHOUSE.HOUSING_STATUS_STABLY_HOUSED,
	BHOUSE.HOUSING_STATUS_INSTITUTIONALLY_HOUSED,
	BHOUSE.HOUSING_STATUS_PRECARIOUSLY_HOUSED,
	BHOUSE.HOUSING_STATUS_UNHOUSED,
	BHOUSE.HOUSING_STATUS_UNKNOWN,
	BHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
	BPAY.PAYOR_SOURCE_PRIVATE_INSURANCE,
	BPAY.PAYOR_SOURCE_MEDICAID,
	BPAY.PAYOR_SOURCE_MEDICAID_IN_PROGRESS,
	BPAY.PAYOR_SOURCE_MANAGED_MEDICAID,
	BPAY.PAYOR_SOURCE_MEDICARE,
	BPAY.PAYOR_SOURCE_DUAL_ELIGIBLE,
	BPAY.PAYOR_SOURCE_UNINSURED,
	BPAY.PAYOR_SOURCE_UNKNOWN_REFUSED,
	BIC.ZIP_CODE,
	BIC.COUNTY_DESCRIPTION,
	BIC.PHQ9_SCORE,
	BIC.DASS_SCORE_IC,
	BRP.BH_REF_PLACED,
	BRP.COUNSELING_REF_PLACED,
	CC.COUNT_COUNSELING_SESSIONS
FROM INITIAL_CONTACTS AS [BIC]
LEFT JOIN REFERRALS_PLACED AS [BRP]
	ON BIC.TIEDENROLLMENT = BRP.TIEDENROLLMENT
LEFT JOIN CLIENT_COUNSELING AS [CC]
	ON CC.CLIENT_NUMBER = BIC.CLIENT_NUMBER
LEFT JOIN Q_BCR_ACTIVE_HOUSING_STATUS AS [BHOUSE]
	ON BHOUSE.CLIENT_NUMBER = BIC.CLIENT_NUMBER
LEFT JOIN Q_BCR_ACTIVE_PAYOR_SOURCE AS [BPAY]
	ON BPAY.CLIENT_NUMBER = BIC.CLIENT_NUMBER;