/*
View Name: Q_BCR_IC
Category: View Definitions  

See docs/view-definitions/q-bcr-ic.md for full documentation.
*/
USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_BCR_IC AS
SELECT BIC.ID,
	BIC.DOCSERNO,
	BIC.TIEDENROLLMENT,
	CAST(BIC.VISITDT AS DATE) AS [VISIT_DATE],
	BIC.VISITTM AS [VISIT_TIME],
	BIC.USERID,
	BIC.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'BCR Initial Contact' AS [EVENT_NAME],
	BIC.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(BIC.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	METHOD_OF_IC,
	ZIP_OF_INITIAL_CONTACT,
	PLANNED_EVENT,
	EVENT_TYPE,
	EVENT_TYPE_OTHER,
	CHURCH_HOME,
	BCR_CHURCHES,
	CHURCH.DESCRIPTION AS [BCR_CHURCHES_DESC],
	BIC.EMPLOYMENTSTATUS,
	EMPSTATUS.DESCRIPTION AS [EMPLOYMENTSTATUS_DESC],
	CLIENT_PCP_IC,
	AGREEABLE_PCP_REF,
	PRIOR_MH_BH_SERVICES,
	PSYCHIATRIST_IC,
	PREGNANT_IC, -- Deprecated as of '2025-11-19'
	PREG_CHILD_LAST_90_IC, -- Deprecated as of '2025-11-19'
	PHQ9_COMPLETED,
	PHQ9_SCORE,
	CAGE_AID_ADMINISTERED,
	CAGE_AID_SCORE_IC,
	DASS_ADMINISTERED,
	DASS_SCORE_IC,
	CRIM_JUSTICE_INVOLVEMENT,
	NATURE_CJ_INVOLVE_RECENT_ARREST,
	NATURE_CJ_INVOLVE_PAST_ARREST,
	NATURE_CJ_INVOLVE__CURRENT_PROBATION AS [NATURE_CJ_INVOLVE_CURRENT_PROBATION],
	NATURE_CJ_INVOLVE_ON_PAROLE,
	NATURE_CJ_INVOLVE_HISTORY_PROB_PAROLE,
	BIC.EDUCATIONLEVEL,
	EDLEVEL.DESCRIPTION AS [EDUCATIONLEVEL_DESC],
	BCR_PROG_PARTICIPATION,
	PART.DESCRIPTION AS [BCR_PROG_PARTICIPATION_DESC],
	REASON_IF_INELIGIBLE_IC,
	OTHER_REASON_INELIGIBLE_IC,
	RESIDE_STL_CITY,
	BCR_GRANT,
	BCRGRANT.DESCRIPTION AS [BCR_GRANT_DESC],
	PRESENTING_NOTES_IC
FROM BEHAVHEALT_LIVE.DBO.PWBCRINITIALCONTACT AS [BIC]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON BIC.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN BCR_PROG_PARTICIPATION AS [PART]
	ON BIC.BCR_PROG_PARTICIPATION = PART.CODE
LEFT JOIN BCR_CHURCHES AS [CHURCH]
	ON BIC.BCR_CHURCHES = CHURCH.CODE
LEFT JOIN EMPLOYMENTSTATUS AS [EMPSTATUS]
	ON BIC.EMPLOYMENTSTATUS = EMPSTATUS.CODE
LEFT JOIN EDUCATIONLEVEL AS [EDLEVEL]
	ON BIC.EDUCATIONLEVEL = EDLEVEL.CODE
LEFT JOIN BCR_GRANT AS [BCRGRANT]
	ON BIC.BCR_GRANT = BCRGRANT.CODE
WHERE BIC.DOCREVNO = ' 0 ';