/*
View Name: Q_BCR_REFERRAL_ENTERED_NO_IC  
Category: View Definitions  

See docs/view-definitions/q-bcr-referral-entered-no-ic.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_BCR_REFERRAL_ENTERED_NO_IC AS
WITH [BCR_REF] AS (
	SELECT BENROLL.CLIENT_NUMBER,
		BENROLL.CLIENT_LAST,
		BENROLL.CLIENT_FIRST,
		BENROLL.ENROLLMENT_STARTING_DATE,
		BENROLL.ENROLLMENT_ENDING_DATE,
		BENROLL.TIEDENROLLMENT,
		BREF.PATHWAY_DATE
	FROM Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
	LEFT JOIN Q_BCR_REFERRAL AS [BREF]
		ON BENROLL.TIEDENROLLMENT = BREF.TIEDENROLLMENT
	WHERE BENROLL.PWY_EVENT = 'BCR Referral'
		AND BENROLL.ENROLLMENT_STARTING_DATE >= '2025-07-01'
		AND BENROLL.PWY_FORMS_DOCSERNO IS NOT NULL
	),
[BCR_IC_MISSING] AS (
	SELECT BENROLL.CLIENT_NUMBER,
		BENROLL.CLIENT_LAST,
		BENROLL.CLIENT_FIRST,
		BENROLL.ENROLLMENT_STARTING_DATE,
		BENROLL.ENROLLMENT_ENDING_DATE,
		BENROLL.TIEDENROLLMENT,
		BENROLL.PWY_FORMS_DOCSERNO
	FROM Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
	WHERE BENROLL.PWY_EVENT = 'BCR Initial Contact'
		AND BENROLL.ENROLLMENT_STARTING_DATE >= '2025-07-01'
		AND BENROLL.PWY_FORMS_DOCSERNO IS  NOT NULL
)
SELECT BCR_REF.CLIENT_NUMBER,
	BCR_REF.CLIENT_LAST,
	BCR_REF.CLIENT_FIRST,
	BCR_REF.ENROLLMENT_STARTING_DATE,
	BCR_REF.PATHWAY_DATE AS [REF_PATHWAY_DATE],
	BCR_REF.TIEDENROLLMENT AS [REF_TIEDENROLLMENT],
	BCR_IC_MISSING.TIEDENROLLMENT AS [IC_TIEDENROLLMENT]
FROM BCR_REF
LEFT JOIN BCR_IC_MISSING
	ON BCR_REF.TIEDENROLLMENT = BCR_IC_MISSING.TIEDENROLLMENT
WHERE BCR_IC_MISSING.TIEDENROLLMENT IS NULL