/*
View Name: Q_BCR_REFERRAL  
Category: View Definitions  

See docs/view-definitions/q-bcr-referral.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_BCR_REFERRAL AS
SELECT BREF.ID,
	BREF.DOCSERNO,
	BREF.TIEDENROLLMENT,
	CAST(BREF.VISITDT AS DATE) AS [VISITDT],
	BREF.USERID,
	BREF.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'BCR Referral' AS [EVENT_NAME],
	BREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(BREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	METHOD_REFERRAL, -- Deprecated as of '2025-11-19'
	REF_SOURCE_TYPE,
	REF_SOURCE_NAME,
	OTHER_REFERRAL_SOURCE_TYPE,
	REF_THROUGH_EVENT, -- Deprecated as of '2025-11-19'
	BCR_REF_EVENT, -- Deprecated as of '2025-11-19'
	OTHER_EVENT_EXP, -- Deprecated as of '2025-11-19'
	HOW_HEAR_ABOUT_BCR,
	IF_OTHER_PLEASE_SPECIFY,
	PREV_MH_BH_SERVICES, -- Deprecated as of '2025-11-19'
	PREGNANT_AT_REF, -- Deprecated as of '2025-11-19'
	PREG_OR_CHILD_LAST_NINETY, -- Deprecated as of '2025-11-19'
	MARITAL_STATUS_REF, -- Deprecated as of '2025-11-19'
	HOUSING_STATUS_REFERRAL,
	RESIDE_IN_STL_CITY, -- Deprecated as of '2025-11-19'
	BCR_PROG_PARTICIPATION AS [BCR_PROGRAM_PARTICIPATION_CODE], -- Deprecated as of '2025-11-19'
	PART.DESCRIPTION AS [BCR_PROGRAM_PARTICIPATION_DESCRIPTION], -- Deprecated as of '2025-11-19'
	BCR_REASON_INELIGIBLE_REF, -- Deprecated as of '2025-11-19'
	OTHER_REASON_INELIGIBLE -- Deprecated as of '2025-11-19'
FROM BEHAVHEALT_LIVE.DBO.PWBCRREFERRAL AS [BREF]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON BREF.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN BCR_PROG_PARTICIPATION AS [PART] -- Deprecated as of '2025-11-19'
	ON BREF.BCR_PROG_PARTICIPATION = PART.CODE
WHERE BREF.DOCREVNO = ' 0 ';