/*
View Name: Q_BCR_CLIENT_COUNSELING_SESSIONS  
Category: View Definitions  

See docs/view-definitions/q-bcr-client-counseling-sessions.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_BCR_CLIENT_COUNSELING_SESSIONS AS
SELECT BCC.ID,
	BCC.DOCSERNO,
	BCC.TIEDENROLLMENT,
	CAST(BCC.VISITDT AS DATE) AS [VISITDT],
	BCC.VISITTM,
	BCC.USERID,
	C.CLIENT_NUMBER,
	CAST(BCC.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(BCC.SESSION_DATE AS DATE) AS [SESSION_DATE],
	BCC.SESSION_FORMAT,
	BCC.SESSION_GRANT,
	BCC.COUNSELING_AGENCY AS [COUNSELING_AGENCY_CODE],
	BCA.DESCRIPTION AS [COUNSELING_AGENCY_DESCRIPTION]
FROM PWBCRCLIENTCOUNSELINGSESSIONS AS [BCC]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = BCC.CLIENTNUMBER
LEFT JOIN BCR_GRANT AS [GRANT]
	ON BCC.SESSION_GRANT = [GRANT].CODE
LEFT JOIN BCR_COUNSELING_AGENCIES AS [BCA]
	ON BCC.COUNSELING_AGENCY = BCA.CODE
WHERE BCC.DOCREVNO = ' 0 ';