/*
View Name: Q_BCR_PRESENTING_CONCERNS  
Category: View Definitions  

See docs/view-definitions/q-bcr-presenting-concerns.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

 -- ALTER VIEW DBO.Q_BCR_PRESENTING_CONCERNS AS
SELECT BPC.ID,
	BPC.DOCSERNO,
	CAST(BPC.VISITDT AS DATE) AS [VISITDT],
	BPC.VISITTM,
	BPC.USERID,
	CASE
		WHEN BPC.PARENTDOCSERNO IS NULL OR BPC.PARENTDOCSERNO = ''
		THEN BIC.DOCSERNO
		ELSE BPC.PARENTDOCSERNO
	END AS [PARENT_DOCSERNO],
	C.CLIENT_NUMBER,
	CAST(BPC.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	BPC.BCR_PRESENTING_CONCERNS,
	BPC.BEHAVIORAL_HEALTH_NEED,
	BPC.HOUSING_NEED,
	BPC.MATERNAL_HEALTH_NEED,
	BPC.OTHER_NEED,
	BPC.PHYSICAL_HEALTH_NEED,
	BPC.SOCIAL_SERVICES_NEED,
	BPC.SPIRITUAL_CARE_NEED,
	BPC.OTHER_NEED_REF
FROM PWBCRPRESENTINGCONCERNS AS [BPC]
INNER JOIN Q_BCR_CLIENT AS [C]
	ON C.CLIENT_NUMBER = BPC.CLIENTNUMBER
LEFT JOIN Q_BCR_IC AS [BIC]
	ON BPC.CLIENTNUMBER = BIC.CLIENT_NUMBER
	AND BPC.PATHWAY_DATE = BIC.PATHWAY_DATE
	AND BPC.USERID LIKE 'import%'
WHERE BPC.DOCREVNO = ' 0 ';