/*
View Name: Q_BCR_EVENTS  
Category: View Definitions  

See docs/view-definitions/q-bcr-events.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_BCR_EVENTS AS
SELECT [EVENT].ID,
	[EVENT].DOCSERNO,
	CAST([EVENT].VISITDT AS DATE) AS [VISITDT],
	[EVENT].VISITTM,
	[EVENT].USERID,
	CAST([EVENT].PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	[EVENT].PARENTDOCSERNO AS [PARENT_DOCSERNO],
	[EVENT].EVENT_TYPE,
	[EVENT].EVENT_NAME,
	[EVENT].EVENT_TOPIC,
	[EVENT].IF_OTHER_EXPLAIN,
	[EVENT].EVENT_FORMAT,
	[EVENT].EVENT_LOCATION,
	[EVENT].TOTAL_NUM_ATTENDEES,
	[EVENT].NUM_ADULTS,
	[EVENT].NUM_YOUTH,
	[EVENT].NUM_PASTORS,
	[EVENT].NUM_REQUESTED_FU,
	[EVENT].NUM_COMPLETED_SCREENS,
	[EVENT].NUM_INC_KNOWLEDGE,
	[EVENT].NUM_NEW_ATTENDEES,
	[EVENT].EVENT_GRANT AS [EVENT_GRANT_CODE],
	[GRANT].DESCRIPTION AS [EVENT_GRANT_DESCRIPTION],
	[EVENT].ADDTL_NOTES_EVENT
FROM PWBCREVENT AS [EVENT]
LEFT JOIN BCR_GRANT AS [GRANT] 
	ON [EVENT].EVENT_GRANT = [GRANT].CODE
WHERE [EVENT].DOCREVNO = ' 0 '
	AND (
		LTRIM(
			RTRIM(
				[EVENT].CLIENTNUMBER
				)
			) = ''
		OR [EVENT].CLIENTNUMBER IS NULL
	);