/*
View Name: Q_BCR_REF_PLACED  
Category: View Definitions  

See docs/view-definitions/q-bcr-ref-placed.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_BCR_REF_PLACED AS
SELECT BRP.ID,
	BRP.DOCSERNO,
	BRP.DOCREVNO,
	CAST(BRP.VISITDT AS DATE) AS [VISITDT],
	BRP.VISITTM,
	BRP.USERID,
	BRP.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'BCR Referrals Placed' AS [EVENT_NAME],
	BRP.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_NAME,
	CAST(BRP.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	BRP.BCR_TYPE_REF_PLACED,
	BH_REF_PLACED,
	PHYSICAL_HEALTH_REF_PLACED,
	HOUSING_REF_PLACED,
	MAT_HEALTH_REF_PLACED,
	OTHER_REF_PLACED,
	SOC_SERVICES_REF_PLACED,
	SPIRITUAL_CARE_REF_PLACED,
	BRP.BCR_REF_PLACED_BH_SUBTYPE,
	CMHC_REF_PLACED,
	COUNSELING_REF_PLACED,
	GROUP_PEER_SUPPORT_REF_PLACED,
	INDIVIDUAL_PEER_SUPPORT_REF_PLACED,
	SU_REF_PLACED,
	CMHC_AGENCY,
	BH_CMHC_AGENCY.DESCRIPTION AS [CMHC_AGENCY_DESC],
	CAST(DATE_CMHC_REF_PLACED AS DATE) AS [DATE_CMHC_REF_PLACED],
	COUNSELING_AGENCY,
	BH_COUNSELING_AGENCY.DESCRIPTION AS [COUNSELING_AGENCY_DESC],
	CAST(DATE_COUNSELING_REF_PLACED AS DATE) AS [DATE_COUNSELING_REF_PLACED],
	GROUP_PEER_SUPPORT_AGENCY,
	BH_GROUP_PEER_SUPPORT_AGENCY.DESCRIPTION AS [GROUP_PEER_SUPPORT_AGENCY_DESC],
	CAST(DATE_GROUP_PEER_SUPPORT_REF_PLACED AS DATE) AS [DATE_GROUP_PEER_SUPPORT_REF_PLACED],
	INDIV_PEER_SUPPORT_AGENCY,
	BH_INDIV_PEER_SUPPORT_AGENCY.DESCRIPTION AS [INDIV_PEER_SUPPORT_AGENCY_DESC],
	CAST(DATE_INDIV_PEER_SUPPORT_REF AS DATE) AS [DATE_INDIV_PEER_SUPPORT_REF],
	SU_AGENCY,
	BH_SU_AGENCY.DESCRIPTION AS [SU_AGENCY_DESC],
	CAST(DATE_SU_REF AS DATE) AS [DATE_SU_REF],
	BCR_REF_PLACED_HOUSING_SUBTYPE,
	FURNITURE_REF_PLACED,
	HOME_REPAIR_REF_PLACED,
	HOMELESS_SERVICES_REF_PLACED,
	LANDLORD_MED_REF_PLACED,
	RENT_ASSIST_REF_PLACED,
	UTILITY_ASSIST_REF_PLACED,
	FURNITURE_AGENCY,
	H_FURNITURE_AGENCY.DESCRIPTION AS [FURNITURE_AGENCY_DESC],
	CAST(DATE_FURNITURE_REF AS DATE) AS [DATE_FURNITURE_REF],
	HOME_REPAIR_AGENCY,
	H_REPAIR_AGENCY.DESCRIPTION AS [HOME_REPAIR_AGENCY_DESC],
	CAST(DATE_HOME_REPAIRS_REF AS DATE) AS [DATE_HOME_REPAIRS_REF],
	HOMELESS_SERVICES_AGENCY,
	H_HOMELESS_SERVICES_AGENCY.DESCRIPTION AS [HOMELESS_SERVICES_AGENCY_DESC],
	CAST(DATE_HOMELESS_SERVICES_REF AS DATE) AS [DATE_HOMELESS_SERVICES_REF],
	LANDLORD_MED_AGENCY,
	H_LANDLORD_MED_AGENCY.DESCRIPTION AS [LANDLORD_MED_AGENCY_DESC],
	CAST(DATE_LANDLORD_MEDIATION_REF AS DATE) AS [DATE_LANDLORD_MEDIATION_REF],
	RENT_ASSIST_AGENCY,
	H_RENT_ASSIST_AGENCY.DESCRIPTION AS [RENT_ASSIST_AGENCY_DESC],
	CAST(DATE_RENT_ASSIST_REF AS DATE) AS [DATE_RENT_ASSIST_REF],
	UTILITY_ASSIST_AGENCY,
	H_UTILITY_ASSIST_AGENCY.DESCRIPTION AS [UTILITY_ASSIST_AGENCY_DESC],
	CAST(DATE_UTILITY_REF AS DATE) AS [DATE_UTILITY_REF],
	MAT_HEALTH_AGENCY,
	MATERNAL_HEALTH_AGENCY.DESCRIPTION AS [MAT_HEALTH_AGENCY_DESC],
	CAST(DATE_MAT_HEALTH_REF_PLACED AS DATE) AS [DATE_MAT_HEALTH_REF_PLACED],
	OTHER_AGENCY,
	CAST(DATE_OTHER_REF AS DATE) AS [DATE_OTHER_REF],
	BCR_REF_PLACED_PHYS_HEALTH_SUBTYPE,
	PRIMARY_CARE_REF_PLACED,
	DENTAL_REF_PLACED,
	PRIMARY_CARE_AGENCY,
	PHYS_PRIMARY_CARE_AGENCY.DESCRIPTION AS [PRIMARY_CARE_AGENCY_DESC],
	CAST(DATE_PRIMARY_CARE_REF_PLACED AS DATE) AS [DATE_PRIMARY_CARE_REF_PLACED],
	DENTAL_AGENCY,
	PHYS_DENTAL_AGENCY.DESCRIPTION AS [DENTAL_AGENCY_DESC],
	CAST(DATE_DENTAL_REF_PLACED AS DATE) AS [DATE_DENTAL_REF_PLACED],
	BCR_REF_PLACED_SOCIAL_SUBTYPE,
	CHILD_CARE_REF_PLACED,
	CLOTHING_REF_PLACED,
	DD_REF_PLACED,
	DV_REF_PLACED,
	EMPLOYMENT_REF_PLACED,
	FOOD_REF_PLACED,
	INSURANCE_REF_PLACED,
	LEGAL_REF_PLACED,
	LGBTQ_REF_PLACED,
	TRANSPORT_REF_PLACED,
	CHILD_CARE_AGENCY,
	SS_CHILD_CARE_AGENCY.DESCRIPTION AS [CHILD_CARE_AGENCY_DESC],
	CAST(DATE_CHILD_CARE_REF_PLACED AS DATE) AS [DATE_CHILD_CARE_REF_PLACED],
	CLOTHING_AGENCY,
	SS_CLOTHING_AGENCY.DESCRIPTION AS [CLOTHING_AGENCY_DESC],
	CAST(DATE_CLOTHING_REF_PLACED AS DATE) AS [DATE_CLOTHING_REF_PLACED],
	DD_AGENCY,
	SS_DD_AGENCY.DESCRIPTION AS [DD_AGENCY_DESC],
	CAST(DATE_DD_REF_PLACED AS DATE) AS [DATE_DD_REF_PLACED],
	DV_AGENCY,
	SS_DV_AGENCY.DESCRIPTION AS [DV_AGENCY_DESC],
	CAST(DATE_DV_REF_PLACED AS DATE) AS [DATE_DV_REF_PLACED],
	FOOD_AGENCY,
	SS_FOOD_AGENCY.DESCRIPTION AS [FOOD_AGENCY_DESC],
	CAST(DATE_FOOD_REF_PLACED AS DATE) AS [DATE_FOOD_REF_PLACED],
	EMPLOYMENT_AGENCY,
	SS_EMPLOYMENT_AGENCY.DESCRIPTION AS [EMPLOYMENT_AGENCY_DESC],
	CAST(DATE_EMPLOYMENT_REF_PLACED AS DATE) AS [DATE_EMPLOYMENT_REF_PLACED],
	INSURANCE_AGENCY,
	SS_INSURANCE_AGENCY.DESCRIPTION AS [INSURANCE_AGENCY_DESC],
	CAST(DATE_INSURANCE_REF_PLACED AS DATE) AS [DATE_INSURANCE_REF_PLACED],
	LEGAL_AGENCY,
	SS_LEGAL_AGENCY.DESCRIPTION AS [LEGAL_AGENCY_DESC],
	CAST(DATE_LEGAL_REF_PLACED AS DATE) AS [DATE_LEGAL_REF_PLACED],
	LGBTQ_AGENCY,
	SS_LGBTQ_AGENCY.DESCRIPTION AS [LGBTQ_AGENCY_DESC],
	CAST(DATE_LGBTQ_REF_PLACED AS DATE) AS [DATE_LGBTQ_REF_PLACED],
	TRANSPORT_AGENCY,
	SS_TRANSPORT_AGENCY.DESCRIPTION AS [TRANSPORT_AGENCY_DESC],
	CAST(DATE_TRANSPORT_REF_PLACED AS DATE) AS [DATE_TRANSPORT_REF_PLACED],
	SPIRITUAL_AGENCY,
	SPIRITUAL_CARE_AGENCY.DESCRIPTION AS [SPIRITUAL_AGENCY_DESC],
	CAST(DATE_SPIRITUAL_REF_PLACED AS DATE) AS [DATE_SPIRITUAL_REF_PLACED],
	WELLNESS_PLAN_RP,
	UNMET_NEEDS,
	UNMET_NEEDS_EXP,
	NOTES_RP
FROM BEHAVHEALT_LIVE.DBO.PWBCRREFERRALSPLACED AS [BRP]
LEFT JOIN Q_CLIENT_BHN AS [C]
	ON BRP.CLIENTNUMBER = C.CLIENT_NUMBER

/* Joining the same master table for each behavioral health subtype */
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [BH_CMHC_AGENCY]
	ON BRP.CMHC_AGENCY = BH_CMHC_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [BH_COUNSELING_AGENCY]
	ON BRP.COUNSELING_AGENCY = BH_COUNSELING_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [BH_GROUP_PEER_SUPPORT_AGENCY]
	ON BRP.GROUP_PEER_SUPPORT_AGENCY = BH_GROUP_PEER_SUPPORT_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [BH_INDIV_PEER_SUPPORT_AGENCY]
	ON BRP.INDIV_PEER_SUPPORT_AGENCY = BH_INDIV_PEER_SUPPORT_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [BH_SU_AGENCY]
	ON BRP.SU_AGENCY = BH_SU_AGENCY.CODE    

/* Joining the same master table for each housing subtype */
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [H_FURNITURE_AGENCY]
	ON BRP.FURNITURE_AGENCY = H_FURNITURE_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [H_REPAIR_AGENCY]
	ON BRP.HOME_REPAIR_AGENCY = H_REPAIR_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [H_HOMELESS_SERVICES_AGENCY]
	ON BRP.HOMELESS_SERVICES_AGENCY = H_HOMELESS_SERVICES_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [H_LANDLORD_MED_AGENCY]
	ON BRP.LANDLORD_MED_AGENCY = H_LANDLORD_MED_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [H_RENT_ASSIST_AGENCY]
	ON BRP.RENT_ASSIST_AGENCY = H_RENT_ASSIST_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [H_UTILITY_ASSIST_AGENCY]
	ON BRP.UTILITY_ASSIST_AGENCY = H_UTILITY_ASSIST_AGENCY.CODE

/* Joining the master table for the maternal health subtype */
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [MATERNAL_HEALTH_AGENCY]
	ON BRP.MAT_HEALTH_AGENCY = MATERNAL_HEALTH_AGENCY.CODE

/* Joining the same master table for each physical health subtype */
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [PHYS_PRIMARY_CARE_AGENCY]
	ON BRP.PRIMARY_CARE_AGENCY = PHYS_PRIMARY_CARE_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [PHYS_DENTAL_AGENCY]
	ON BRP.DENTAL_AGENCY = PHYS_DENTAL_AGENCY.CODE

/* Joining the same master table for each social service subtype */
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_CHILD_CARE_AGENCY]
	ON BRP.CHILD_CARE_AGENCY = SS_CHILD_CARE_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_CLOTHING_AGENCY]
	ON BRP.CLOTHING_AGENCY = SS_CLOTHING_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_DD_AGENCY]
	ON BRP.DD_AGENCY = SS_DD_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_DV_AGENCY]
	ON BRP.DV_AGENCY = SS_DV_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_FOOD_AGENCY]
	ON BRP.FOOD_AGENCY = SS_FOOD_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_EMPLOYMENT_AGENCY]
	ON BRP.EMPLOYMENT_AGENCY = SS_EMPLOYMENT_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_INSURANCE_AGENCY]
	ON BRP.INSURANCE_AGENCY = SS_INSURANCE_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_LEGAL_AGENCY]
	ON BRP.LEGAL_AGENCY = SS_LEGAL_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_LGBTQ_AGENCY]
	ON BRP.LGBTQ_AGENCY = SS_LGBTQ_AGENCY.CODE
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SS_TRANSPORT_AGENCY]
	ON BRP.TRANSPORT_AGENCY = SS_TRANSPORT_AGENCY.CODE

/* Joining the master table for the spiritual health subtype */
LEFT JOIN BCR_REF_PLACED_AGENCIES AS [SPIRITUAL_CARE_AGENCY]
	ON BRP.SPIRITUAL_AGENCY = SPIRITUAL_CARE_AGENCY.CODE

WHERE BRP.DOCREVNO = ' 0 ';