/*
View Name: Q_BCR_CLIENT_ACTIVE_90_DAYS_OR_LONGER  
Category: View Definitions  

See docs/view-definitions/q-bcr-client-active-90-days-or-longer.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_BCR_CLIENT_ACTIVE_90_DAYS_OR_LONGER AS
SELECT DISTINCT C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.ENROLLMENT_STARTING_DATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(DATEADD(DAY, 90, PP.ENROLLMENT_STARTING_DATE) AS DATE) AS [90_DAY_DATE]
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN (
	SELECT CLIENT_NUMBER,
		MIN(ENROLLMENT_STARTING_DATE) AS [ENROLLMENT_STARTING_DATE]
	FROM BEHAVHEALT_LIVE.DBO.Q_PROVIDERPLACEMENT_BHN
	WHERE ENROLLMENT_ENDING_DATE IS NULL
	GROUP BY CLIENT_NUMBER
) AS [PP] 
	ON C.CLIENT_NUMBER = PP.CLIENT_NUMBER
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYCLIENT AS [PC] 
	ON C.CLIENT_NUMBER = PC.CLIENTNUMBER
	AND PC.STARTDATE = PP.ENROLLMENT_STARTING_DATE
	AND PC.DOCREVNO = ' 0 '
	AND PC.PARENTDOCSERNO = '55320240917145557321'
WHERE DATEDIFF(DAY, PP.ENROLLMENT_STARTING_DATE, GETDATE()) >= 90;