/*
View Name: Q_BCR_ENROLLMENTS_AND_DISMISSALS  
Category: View Definitions  

See docs/view-definitions/q-bcr-enrollments-and-dismissals.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_BCR_ENROLLMENTS_AND_DISMISSALS AS
WITH [BCR_REF] AS (
	SELECT BENROLL.CLIENT_NUMBER,
		BENROLL.CLIENT_LAST,
		BENROLL.CLIENT_FIRST,
		BENROLL.ENROLLMENT_STARTING_DATE,
		BENROLL.ENROLLMENT_ENDING_DATE,
		BENROLL.DISMISSAL_REASON_DESCRIPTION,
		BENROLL.TIEDENROLLMENT,
		BREF.PATHWAY_DATE AS [REFERRAL_PATHWAY_DATE]
	FROM DBO.Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
	LEFT JOIN DBO.Q_BCR_REFERRAL AS [BREF]
		ON BENROLL.TIEDENROLLMENT = BREF.TIEDENROLLMENT
	WHERE BENROLL.PWY_EVENT = 'BCR Referral'
		AND BENROLL.ENROLLMENT_STARTING_DATE >= '2025-07-01'
		AND BENROLL.PWY_FORMS_DOCSERNO IS NOT NULL
	),
[BCR_IC] AS (
	SELECT BENROLL.CLIENT_NUMBER,
		BENROLL.ENROLLMENT_STARTING_DATE,
		BENROLL.TIEDENROLLMENT,
		BENROLL.PWY_FORMS_DOCSERNO,
		BIC.PATHWAY_DATE AS [IC_PATHWAY_DATE],
		BIC.BCR_GRANT AS [BCR_GRANT_CODE],
		BIC.BCR_GRANT_DESC AS [BCR_GRANT_DESCRIPTION]
	FROM DBO.Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
	LEFT JOIN DBO.Q_BCR_IC AS [BIC]
		ON BENROLL.TIEDENROLLMENT = BIC.TIEDENROLLMENT
		WHERE BENROLL.PWY_EVENT = 'BCR Initial Contact'
		AND BENROLL.ENROLLMENT_STARTING_DATE >= '2025-07-01'
		AND BENROLL.PWY_FORMS_DOCSERNO IS  NOT NULL
),
[BCR_REF_PLACED] AS (
	SELECT BENROLL.CLIENT_NUMBER,
		BENROLL.ENROLLMENT_STARTING_DATE,
		BENROLL.TIEDENROLLMENT,
		BENROLL.PWY_FORMS_DOCSERNO,
		BRP.PATHWAY_DATE AS [REF_PLACED_PATHWAY_DATE]
	FROM DBO.Q_BCR_PATHCLIENT_ENROLLMENTS AS [BENROLL]
	LEFT JOIN DBO.Q_BCR_REFERRAL_PLACED AS [BRP]
		ON BENROLL.TIEDENROLLMENT = BRP.TIEDENROLLMENT
	WHERE BENROLL.PWY_EVENT = 'BCR Referrals Placed'
		AND BENROLL.ENROLLMENT_STARTING_DATE >= '2025-07-01'
		AND BENROLL.PWY_FORMS_DOCSERNO IS NOT NULL
)
SELECT BCR_REF.CLIENT_NUMBER,
	BCR_REF.CLIENT_LAST,
	BCR_REF.CLIENT_FIRST,
	BCR_REF.ENROLLMENT_STARTING_DATE,
	BCR_REF.ENROLLMENT_ENDING_DATE,
	BCR_REF.DISMISSAL_REASON_DESCRIPTION,
	BCR_REF.TIEDENROLLMENT,
	BCR_REF.PATHWAY_DATE AS [REF_PATHWAY_DATE],
	BCR_IC.PATHWAY_DATE AS [IC_PATHWAY_DATE],
	BCR_REF_PLACED.PATHWAY_DATE AS [REF_PLACED_PATHWAY_DATE],
	BCR_IC.BCR_GRANT_CODE AS [BCR_GRANT_CODE],
	BCR_IC.BCR_GRANT_DESCRIPTION AS [BCR_GRANT_DESCRIPTION]
FROM BCR_REF
LEFT JOIN BCR_IC
	ON BCR_REF.TIEDENROLLMENT = BCR_IC.TIEDENROLLMENT
LEFT JOIN BCR_REF_PLACED
	ON BCR_REF.TIEDENROLLMENT = BCR_REF_PLACED.TIEDENROLLMENT
