/*
View Name: Q_BCR_PATHCLIENT_ENROLLMENTS  
Category: View Definitions  

See docs/view-definitions/q-bcr-pathclient-enrollments.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_BCR_PATHCLIENT_ENROLLMENTS AS
SELECT C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	PEC.USERID AS [PEC_USERID],
	PEC.LASTUPDATEBY AS [PEC_LAST_UPDATE_BY],
	PP.DOCSERNO AS [PP_DOCSERNO],
	COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) AS [PC_DOCSERNO],
	PEC.PATHCLIENTDOCSERNO AS [PEC_PATHCLIENT_DOCSERNO],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'BCR Referral' 
		THEN BREF.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'BCR Initial Contact' 
		THEN BIC.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'BCR Referrals Placed' 
		THEN BRP.TIEDENROLLMENT
	END AS [TIEDENROLLMENT],
	CASE 
		WHEN 
			CASE
				WHEN PE.SHORTDESCRIPTION = 'BCR Referral' 
				THEN BREF.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'BCR Initial Contact' 
				THEN BIC.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'BCR Referrals Placed' 
				THEN BRP.TIEDENROLLMENT
			END IS NULL 
		THEN NULL
		WHEN COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) = 
			CASE
				WHEN PE.SHORTDESCRIPTION = 'BCR Referral' 
				THEN BREF.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'BCR Initial Contact' 
				THEN BIC.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'BCR Referrals Placed' 
				THEN BRP.TIEDENROLLMENT
			END 
		THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS [TIEDENROLLMENT_MATCH],
	COALESCE(PC_DOCSERNO.JOIN_TYPE, PC_START.JOIN_TYPE) AS [ENROLL_PATH_JOIN_SOURCE],
	P.PROVIDERNAME AS [AGENCY_DESCRIPTION],
	CAST(COALESCE(PC_DOCSERNO.STARTDATE, PC_START.STARTDATE) AS DATE) AS [PWY_START_DATE],
	CAST(COALESCE(PC_DOCSERNO.ENDDATE, PC_START.ENDDATE) AS DATE) AS [PWY_END_DATE],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'BCR Referral' 
		THEN BREF.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'BCR Initial Contact' 
		THEN BIC.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'BCR Referrals Placed' 
		THEN BRP.DOCSERNO
	END AS [PWY_FORMS_DOCSERNO],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'BCR Referral' 
		THEN BREF.PATHWAY_DATE
		WHEN PE.SHORTDESCRIPTION = 'BCR Initial Contact' 
		THEN BIC.PATHWAY_DATE
		WHEN PE.SHORTDESCRIPTION = 'BCR Referrals Placed' 
		THEN BRP.PATHWAY_DATE
	END AS [PATHWAY_DATE],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'BCR Referral'
		THEN BREF.BCR_PROGRAM_PARTICIPATION_DESCRIPTION
		WHEN PE.SHORTDESCRIPTION = 'BCR Initial Contact' 
		THEN BIC.BCR_PROG_PARTICIPATION_DESC
	END AS [PROGRAM_PARTICIPATION],
	DATEADD(
		DAY,
		-PE.EARLYPERIOD,
		CAST(
			PEC.STARTDATE AS DATE
			)
	) AS [EARLIEST_START_DATE],
	CAST(PEC.STARTDATE AS DATE) AS [EVENT_START_DATE],
	CAST(PEC.ENDDATE AS DATE) AS [EVENT_END_DATE],
	DATEADD(
		DAY, PE.LATEPERIOD,
		CAST(
			PEC.ENDDATE AS DATE
			)
	) AS [LATEST_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [PE_DATE_ACCOMPLISHED],
	CASE
		WHEN PEC.DATEACCOMPLISHED IS NULL 
		THEN DATEDIFF(DAY, GETDATE(), PEC.ENDDATE)
	END AS [DAYS_UNTIL_FORM_DUE],
	PEC.CURRENTMESSAGE AS [CURRENT_MESSAGE],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST]
FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.CLOSINGREASONS AS [CR]
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN (
	SELECT 
		PC.*,
		'DOCSERNO Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_DOCSERNO]
	ON PP.CLIENTNUMBER = PC_DOCSERNO.CLIENTNUMBER
	AND PC_DOCSERNO.DOCSERNO = PP.DOCSERNO
LEFT JOIN (
	SELECT 
		PC.*,
		'Enrollment/Pathway Start Date Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_START]
	ON PP.CLIENTNUMBER = PC_START.CLIENTNUMBER
	AND PP.STARTINGDATE = PC_START.STARTDATE
	AND PP.PATHWAY = PC_START.PARENTDOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENTCLIENT AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.PATHCLIENTDOCSERNO = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENT AS [PE] 
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAY AS [PWY] 
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDER AS [P] 
	ON PP.PRIMARYPROVIDERCODE = P.PROVIDERCODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HRR]
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_BCR_REFERRAL AS [BREF] 
	ON BREF.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240917145557321
--	AND BREF.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND BREF.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND BREF.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_BCR_IC AS [BIC] 
	ON BIC.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240917145557321
--	AND BIC.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND BIC.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND BIC.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_BCR_REF_PLACED AS [BRP] 
	ON BRP.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240917145557321
--	AND BRP.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND BRP.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND BRP.EVENT_NAME = PE.SHORTDESCRIPTION
WHERE PP.PATHWAY = 55320240917145557321
	AND PP.DOCREVNO = ' 0 ';