/*
View Name: Q_BCR_REFERRAL  
Category: View Definitions  

See docs/view-definitions/q-bcr-referral.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_BCR_REFERRAL AS
SELECT BREF.ID,
	BREF.DOCSERNO,
	CAST(BREF.VISITDT AS DATE) AS [VISITDT],
	BREF.USERID,
	BREF.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'BCR Referral' AS [EVENT_NAME],
	BREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(BREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	METHOD_REFERRAL,
	REF_SOURCE_TYPE,
	REF_SOURCE_NAME,
	OTHER_REFERRAL_SOURCE_TYPE,
	REF_THROUGH_EVENT,
	BCR_REF_EVENT,
	OTHER_EVENT_EXP,
	HOW_HEAR_ABOUT_BCR,
	IF_OTHER_PLEASE_SPECIFY,
	PREV_MH_BH_SERVICES,
	PREGNANT_AT_REF,
	PREG_OR_CHILD_LAST_NINETY,
	MARITAL_STATUS_REF,
	HOUSING_STATUS_REFERRAL,
	RESIDE_IN_STL_CITY,
	BCR_PROG_PARTICIPATION AS [BCR_PROGRAM_PARTICIPATION_CODE],
	PART.DESCRIPTION AS [BCR_PROGRAM_PARTICIPATION_DESCRIPTION],
	BCR_REASON_INELIGIBLE_REF,
	OTHER_REASON_INELIGIBLE
FROM BEHAVHEALT_LIVE.DBO.PWBCRREFERRAL AS [BREF]
LEFT JOIN Q_CLIENT_BHN AS [C]
	ON BREF.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN BCR_PROG_PARTICIPATION AS [PART]
	ON BREF.BCR_PROG_PARTICIPATION = PART.CODE
WHERE BREF.DOCREVNO = ' 0 ';