/*
View Name: Q_BCR_PATHWAY_FORM_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-bcr-pathway-form-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_BCR_PATHWAY_FORM_DOCSERNOS AS
SELECT BREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(BREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	BREF.DOCSERNO,
	BREF.TIEDENROLLMENT,
	'BCR Referral' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWBCRREFERRAL AS [BREF]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = BREF.CLIENTNUMBER
WHERE BREF.DOCREVNO = ' 0 '
UNION ALL
SELECT BIC.CLIENTNUMBER,
	CAST(BIC.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	BIC.DOCSERNO,
	BIC.TIEDENROLLMENT,
	'BCR Initial Contact' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWBCRINITIALCONTACT AS [BIC]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = BIC.CLIENTNUMBER
WHERE BIC.DOCREVNO = ' 0 '
UNION ALL
SELECT BRP.CLIENTNUMBER,
	CAST(BRP.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	BRP.DOCSERNO,
	BRP.TIEDENROLLMENT,
	'BCR Referrals Placed' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWBCRREFERRALSPLACED AS [BRP]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = BRP.CLIENTNUMBER
WHERE BRP.DOCREVNO = ' 0 ';