/*
View Name: Q_BHN_ALL_DEPENDENCIES
Category: View Definitions

See docs/view-definitions/q-bhn-all-dependencies.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_BHN_ALL_DEPENDENCIES AS

-- 1. Saved Query Dependencies
SELECT
	SOURCE_TYPE = 'SAVEDQUERY',
	SOURCE_NAME = QUERYNAME,
	SOURCE_ID   = ID,
	REFERENCED_OBJECT,
	NORMALIZED_OBJECT,
	PROGRAM_SCOPE,
	PROGRAMS,
	LINEAGE_LEVEL = 1
FROM dbo.Q_BHN_SAVEDQUERY_DEPENDENCIES

UNION ALL

-- 2. SQL Object Dependencies (BHN Views and Tables)
SELECT
	SOURCE_TYPE = 'SQL_OBJECT',
	SOURCE_NAME = REFERENCING_NAME,
	SOURCE_ID   = NULL,
	REFERENCED_OBJECT = REFERENCED_NAME,
	NORMALIZED_OBJECT = NORMALIZED_REFERENCED_NAME,
	PROGRAM_SCOPE,
	PROGRAMS,
	LINEAGE_LEVEL = 1
FROM dbo.Q_BHN_VIEW_AND_TABLE_DEPENDENCIES;
GO
