/*
View Name: Q_BHN_REVERSE_DEPENDENCIES
Category: View Definitions

See docs/view-definitions/q-bhn-reverse-dependencies.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
 GO
 
 --ALTER VIEW dbo.Q_BHN_REVERSE_DEPENDENCIES AS 
SELECT DISTINCT NORMALIZED_OBJECT AS [BASE_OBJECT],
	ROOT_SOURCE_TYPE, 
	ROOT_SOURCE_NAME,
	MIN(LINEAGE_LEVEL) AS [MIN_LINEAGE_LEVEL]
FROM dbo.Q_BHN_FULL_DEPENDENCY_LINEAGE
GROUP BY
	NORMALIZED_OBJECT,
	ROOT_SOURCE_TYPE,
	ROOT_SOURCE_NAME;