/*
View Name: Q_BHNWIDE_PATHCLIENT_ENROLLMENTS
Category: View Definitions

See docs/view-definitions/q-bhnwide-pathclient-enrollments.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_BHNWIDE_PATHCLIENT_ENROLLMENTS AS
SELECT
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,

	-- Enrollment episode
	CAST(PP.ENROLLMENT_STARTING_DATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENROLLMENT_ENDING_DATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	PP.DOCSERNO AS [PP_DOCSERNO],

	-- Pathway client linkage (dual logic)
	COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) AS [PC_DOCSERNO],
	COALESCE(PC_DOCSERNO.JOIN_TYPE, PC_START.JOIN_TYPE) AS [ENROLL_PATH_JOIN_SOURCE],

	-- Pathway event client
	PEC.PATHCLIENTDOCSERNO AS [PEC_PATHCLIENT_DOCSERNO],
	PEC.USERID AS [PEC_USERID],

	-- Provider / worker context
	P.PROVIDERNAME AS [AGENCY_DESCRIPTION],
	HR.EMPLOYEENUMBER AS [PROGRAM_WORKER_EMPLOYEE_NUMBER],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST],

	-- Pathway metadata
	PWY.DOCSERNO AS [PATHWAY_DOCSERNO],
	PP.PATHWAY AS [PATHWAY_ID],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	PE.DOCSERNO AS [EVENT_DOCSERNO],

	-- Episode timing from PathwayClient
	CAST(COALESCE(PC_DOCSERNO.STARTDATE, PC_START.STARTDATE) AS DATE) AS [PWY_START_DATE],
	CAST(COALESCE(PC_DOCSERNO.ENDDATE, PC_START.ENDDATE) AS DATE) AS [PWY_END_DATE],

	-- Event timing from PathwayEventClient
	DATEADD(DAY, -PE.EARLYPERIOD, CAST(PEC.STARTDATE AS DATE)) AS [EARLIEST_START_DATE],
	CAST(PEC.STARTDATE AS DATE) AS [EVENT_START_DATE],
	CAST(PEC.ENDDATE   AS DATE) AS [EVENT_END_DATE],
	DATEADD(DAY, PE.LATEPERIOD, CAST(PEC.ENDDATE AS DATE)) AS [LATEST_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [PE_DATE_ACCOMPLISHED],

	-- Due date helper
	CASE
		WHEN PEC.DATEACCOMPLISHED IS NULL
		THEN DATEDIFF(DAY, GETDATE(), PEC.ENDDATE)
	END AS [DAYS_UNTIL_FORM_DUE],

	PEC.CURRENTMESSAGE AS [CURRENT_MESSAGE]

FROM BEHAVHEALT_LIVE.DBO.Q_PROVIDERPLACEMENT_BHN AS [PP]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = PP.CLIENT_NUMBER
LEFT JOIN CLOSINGREASONS AS [CR]
	ON PP.DISMISSAL_REASON_CODE = CR.CODE

-- DOCSERNO-based join (front-end records)
LEFT JOIN (
	SELECT
		PC.*,
		'DOCSERNO Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_DOCSERNO]
	ON PP.CLIENT_NUMBER = PC_DOCSERNO.CLIENTNUMBER
	AND PC_DOCSERNO.DOCSERNO = PP.DOCSERNO

-- STARTDATE-based join (imported records)
LEFT JOIN (
	SELECT
		PC.*,
		'Enrollment/Pathway Start Date Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_START]
	ON PP.CLIENT_NUMBER = PC_START.CLIENTNUMBER
	AND PP.ENROLLMENT_STARTING_DATE = PC_START.STARTDATE
	AND PP.PATHWAY = PC_START.PARENTDOCSERNO

-- Pathway event client
LEFT JOIN PATHWAYEVENTCLIENT AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.PATHCLIENTDOCSERNO = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PEC.DOCREVNO = ' 0 '

-- Pathway event definition
LEFT JOIN PATHWAYEVENT AS [PE]
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '

-- Pathway definition
LEFT JOIN PATHWAY AS [PWY]
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '

-- Provider / worker
LEFT JOIN Q_PROVIDER AS [P]
	ON PP.AGENCY_CODE = P.PROVIDERCODE
LEFT JOIN Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = PP.PROGRAM_WORKER;