/*
View Name: Q_BHN_VIEW_AND_TABLE_DEPENDENCIES
Category: View Definitions

See docs/view-definitions/q-bhn-view-and-table-dependencies.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_BHN_VIEW_AND_TABLE_DEPENDENCIES AS
WITH [DEPS] AS (
	SELECT
		REFERENCING_SCHEMA = OBJECT_SCHEMA_NAME(D.REFERENCING_ID),
		REFERENCING_NAME   = OBJECT_NAME(D.REFERENCING_ID),

		REFERENCED_SCHEMA = COALESCE(
			D.REFERENCED_SCHEMA_NAME,
			OBJECT_SCHEMA_NAME(D.REFERENCED_ID)
		),
		REFERENCED_NAME = COALESCE(
			D.REFERENCED_ENTITY_NAME,
			OBJECT_NAME(D.REFERENCED_ID)
		),

		-- Two-part names for PARSENAME
		REFERENCING = OBJECT_SCHEMA_NAME(D.REFERENCING_ID) + '.' + OBJECT_NAME(D.REFERENCING_ID),
		REFERENCED  = COALESCE(
			D.REFERENCED_SCHEMA_NAME + '.' + D.REFERENCED_ENTITY_NAME,
			OBJECT_SCHEMA_NAME(D.REFERENCED_ID) + '.' + OBJECT_NAME(D.REFERENCED_ID)
		)
	FROM sys.sql_expression_dependencies AS [D]
)

SELECT
	REFERENCING_SCHEMA,
	REFERENCING_NAME,
	REFERENCED_SCHEMA,
	REFERENCED_NAME,
	REFERENCING,
	REFERENCED,

	-- Normalized to object name only (matches Q_BHN_SAVEDQUERY_DEPENDENCIES)
	NORMALIZED_REFERENCING_NAME = PARSENAME(REFERENCING, 1),
	NORMALIZED_REFERENCED_NAME  = PARSENAME(REFERENCED, 1),
	CASE
		WHEN REFERENCING_NAME LIKE 'Q_EPICC_%' OR REFERENCING_NAME LIKE 'PWEPICC%' THEN 'single'
		WHEN REFERENCING_NAME LIKE 'Q_YERE_%'  OR REFERENCING_NAME LIKE 'PWYERE%'  THEN 'single'
		WHEN REFERENCING_NAME LIKE 'Q_COMPLEX_CARE_%' OR REFERENCING_NAME LIKE 'PWCOMPLEXCARE%' THEN 'single'
		WHEN REFERENCING_NAME LIKE 'Q_BCR_%' THEN 'single'
		WHEN REFERENCING_NAME LIKE 'Q_ERE_%' THEN 'single'
		WHEN REFERENCING_NAME LIKE 'Q_%' AND REFERENCING_NAME NOT LIKE 'Q_EPICC_%'
										AND REFERENCING_NAME NOT LIKE 'Q_YERE_%'
										AND REFERENCING_NAME NOT LIKE 'Q_COMPLEX_CARE_%'
										AND REFERENCING_NAME NOT LIKE 'Q_BCR_%'
										AND REFERENCING_NAME NOT LIKE 'Q_ERE_%'
			THEN 'all'
		ELSE 'none'
	END AS [PROGRAM_SCOPE],
	CASE
		WHEN REFERENCING_NAME LIKE 'Q_EPICC_%' OR REFERENCING_NAME LIKE 'PWEPICC%' THEN 'epicc'
		WHEN REFERENCING_NAME LIKE 'Q_YERE_%'  OR REFERENCING_NAME LIKE 'PWYERE%'  THEN 'yere'
		WHEN REFERENCING_NAME LIKE 'Q_COMPLEX_CARE_%' OR REFERENCING_NAME LIKE 'PWCOMPLEXCARE%' THEN 'complex-care'
		WHEN REFERENCING_NAME LIKE 'Q_BCR_%' THEN 'bcr'
		WHEN REFERENCING_NAME LIKE 'Q_ERE_%' THEN 'ere'
		WHEN REFERENCING_NAME LIKE 'Q_%' THEN ''
		ELSE 'none'
	END AS [PROGRAMS]


FROM DEPS
WHERE
	-- 1. Referencing object must be BHN
	(
			REFERENCING_NAME LIKE 'Q_EPICC_%'
		OR REFERENCING_NAME LIKE 'Q_YERE_%'
		OR REFERENCING_NAME LIKE 'Q_COMPLEX_CARE_%'
		OR REFERENCING_NAME LIKE 'Q_BCR_%'
		OR REFERENCING_NAME LIKE 'PWEPICC%'
		OR REFERENCING_NAME LIKE 'PWYERE%'
		OR REFERENCING_NAME LIKE 'PWCOMPLEXCARE%'
	)
	AND
	-- 2. Referenced object must be BHN or curated vendor
	(
			REFERENCED_NAME LIKE 'Q_EPICC_%'
		OR REFERENCED_NAME LIKE 'Q_YERE_%'
		OR REFERENCED_NAME LIKE 'Q_COMPLEX_CARE_%'
		OR REFERENCED_NAME LIKE 'Q_BCR_%'
		OR REFERENCED_NAME LIKE 'PWEPICC%'
		OR REFERENCED_NAME LIKE 'PWYERE%'
		OR REFERENCED_NAME LIKE 'PWCOMPLEXCARE%'
		OR REFERENCED_NAME IN (
			'CLIENT','CASENOTEDETAIL','CLIENTPASSPORT',
			'PROVIDERPLACEMENT','PROVIDER','PATHWAY',
			'PATHWAYEVENT','PATHWAYCLIENT','PATHWAYEVENTCLIENT'
		)
	);
GO