/*
View Name: Q_CLIENTS_WITH_MULTIPLE_ACTIVE_PATHWAYS  
Category: View Definitions  

See docs/view-definitions/q-clients-with-multiple-active-pathways.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .dbo.Q_CLIENTS_WITH_MULTIPLE_ACTIVE_PATHWAYS AS
WITH PathwayCounts AS (
	SELECT C.CLIENT_NAME,
		C.CLIENT_NUMBER,
		PC.USERID AS [WHODUNIT],
		PP.DOCSERNO AS [PP DOCSERNO],
		PP.REGION AS [PROGRAM_CODE],
		P.PROVIDERNAME AS [PROGRAM_DESCRIPTION],
		PP.PRIMARYPROVIDERCODE AS [AGENCY_CODE],
		PP.THEPROVIDERNAME AS [AGENCY_DESCRIPTION],
		PWY.[PATHWAYNAME],
		COUNT(C.CLIENT_NUMBER) OVER (PARTITION BY C.CLIENT_NUMBER) AS [COUNT_PATHWAY]
	FROM PATHWAY AS [PWY]
	INNER JOIN PATHWAYCLIENT AS [PC] 
		ON PC.PARENTDOCSERNO = PWY.DOCSERNO
		AND PC.DOCREVNO = ' 0 '
	INNER JOIN Q_PROVIDERPLACEMENT AS [PP] 
		ON PC.DOCSERNO = PP.DOCSERNO
	LEFT JOIN Q_PROVIDER AS [P] 
		ON PP.REGION = P.PROVIDERCODE
	INNER JOIN Q_CLIENT_BHN AS [C] 
		ON PC.CLIENTNUMBER = C.CLIENT_NUMBER
	INNER JOIN PATHWAY PWY2 
		ON PWY.ID = PWY2.ID
		AND PWY2.DOCREVNO = ' 0 '
	WHERE PWY.DOCREVNO = ' 0 '
		AND PC.ENDDATE IS NULL
		)
SELECT *
FROM PathwayCounts
WHERE [COUNT_PATHWAY] > 1;