/*
View Name: Q_CLIENTS_WITH_MULTIPLE_PATHWAYS_SHARING_SAME_START_DATE  
Category: View Definitions  

See docs/view-definitions/q-clients-with-multiple-pathways-sharing-same-start-date.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- CREATE VIEW DBO.Q_CLIENTS_WITH_MULTIPLE_PATHWAYS_SHARING_SAME_START_DATE AS
WITH [DuplicateStartDates] AS (
	SELECT 
		PC.CLIENTNUMBER,
		PC.STARTDATE,
		COUNT(*) AS [PathwayCount]
	FROM PATHWAYCLIENT AS [PC]
	INNER JOIN PATHWAY AS [PWY] 
		ON PC.PARENTDOCSERNO = PWY.DOCSERNO AND PWY.DOCREVNO = ' 0 '
	WHERE PC.DOCREVNO = ' 0 '
	GROUP BY PC.CLIENTNUMBER, PC.STARTDATE
	HAVING COUNT(*) > 1
)
SELECT 
	C.CLIENT_NAME,
	C.CLIENT_NUMBER,
	CAST(PC.STARTDATE AS DATE) AS [PWY_START_DATE],
	CAST(PC.ENDDATE AS DATE) AS [PWY_END_DATE],
	PC.USERID AS WHODUNIT,
	PP.DOCSERNO AS [PP_DOCSERNO],
	PP.REGION AS [PROGRAM_CODE],
	P.PROVIDERNAME AS [PROGRAM_DESCRIPTION],
	PP.PRIMARYPROVIDERCODE AS [AGENCY_CODE],
	PP.THEPROVIDERNAME AS [AGENCY_DESCRIPTION],
	PWY.PATHWAYNAME AS [PATHWAY_NAME]
FROM DuplicateStartDates AS [D]
JOIN PATHWAYCLIENT AS [PC] 
	ON D.CLIENTNUMBER = PC.CLIENTNUMBER 
	AND D.STARTDATE = PC.STARTDATE
	AND PC.DOCREVNO = ' 0 '
JOIN PATHWAY AS [PWY] 
	ON PC.PARENTDOCSERNO = PWY.DOCSERNO 
	AND PWY.DOCREVNO = ' 0 '
JOIN Q_PROVIDERPLACEMENT AS [PP] 
	ON PC.DOCSERNO = PP.DOCSERNO
LEFT JOIN Q_PROVIDER AS [P] 
	ON PP.REGION = P.PROVIDERCODE
JOIN Q_CLIENT_BHN AS [C] 
	ON PC.CLIENTNUMBER = C.CLIENT_NUMBER;