/*
View Name: Q_CLIENT_BHN  
Category: View Definitions  

See docs/view-definitions/q-client-bhn.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_CLIENT_BHN AS
SELECT C.ID,
	C.DOCSERNO,
	CAST(C.VISITDT AS DATE) AS [VISITDT],
	C.VISITTM,
	CAST(C.ENTRYDATE AS DATE) AS [ENTRY_DATE],
	C.USERID,
	C.CLIENTSTATUS AS [CLIENT_STATUS],
	C.CLIENTINDICATOR AS [CLIENT_INDICATOR],
	C.CLIENTNUMBER AS [CLIENT_NUMBER],
	CASE
		WHEN COALESCE([FAMILYSUFFIX].DESCRIPTION, '') = '' 
		THEN C.[LASTNAME] + ', ' + C.[FIRSTNAME] + ' ' + C.[MI]
		ELSE C.[LASTNAME] + ' ' + [FAMILYSUFFIX].DESCRIPTION + ', ' + C.[FIRSTNAME] + ' ' + C.[MI]
	END AS [CLIENT_NAME],
	C.LASTNAME AS [CLIENT_LAST],
	C.FIRSTNAME AS [CLIENT_FIRST],
	C.MI,
	C.SUFFIX,
	C.NICKNAME,
	CAST(C.BIRTHDATE AS DATE) AS [BIRTH_DATE],
	C.GENDER AS [GENDER_CODE],
	GENDER.DESCRIPTION AS [GENDER_DESCRIPTION],
	C.RACE AS [RACE_CODE],
	CASE
		WHEN C.[RACE] = '6' 
		THEN C.[RACEOTHER]
		ELSE 
			CASE
				WHEN C.[RACE] = '--' OR C.[RACE] = '' 
				THEN 'None Specified'
				ELSE dbo.RaceList(C.RACE)
			END
	END AS [RACE_DESCRIPTION],
	C.ETHNICITY AS [ETHNICITY_CODE],
	ETHNICITY.DESCRIPTION AS [ETHNICITY_DESCRIPTION],
	PASS.MRN_MERCY,
	PASS.MRN_BJC,
	PASS.MRN_SSM,
	PASS.SSN,
	PASS.SSN_LAST_FOUR,
	PASS.ETO_CASE_NUM,
	C.STREET,
	C.STREET2,
	C.CITY,
	C.STATE,
	C.ZIP AS [ZIP_CODE],
	C.COUNTY AS [COUNTY_CODE],
	COUNTY.DESCRIPTION AS [COUNTY_DESCRIPTION],
	LONGITUDE,
	LATITUDE,
	C.PRIMARYPHONE AS [PRIMARY_PHONE],
	C.CELLPHONE AS [CELL_PHONE],
	C.WORKPHONE AS [WORK_PHONE],
	C.CLIENTEMAIL AS [CLIENT_EMAIL],
	C.FACM
FROM BEHAVHEALT_LIVE.DBO.CLIENT AS [C]
LEFT JOIN BEHAVHEALT_LIVE.DBO.FAMILYSUFFIX 
	ON C.SUFFIX = FAMILYSUFFIX.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.GENDER 
	ON C.GENDER = GENDER.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.ETHNICITY 
	ON C.ETHNICITY = ETHNICITY.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.COUNTIES AS [COUNTY]
	ON C.COUNTY = COUNTY.CODE
LEFT JOIN (
	SELECT CLIENTNUMBER,
		MAX(
			CASE 
				WHEN IDNUMBERTYPE = 'mrn_mercy' 
				THEN IDNUMBER 
			END) AS [MRN_MERCY],
		MAX(
			CASE 
				WHEN IDNUMBERTYPE = 'mrn_bjc' 
				THEN IDNUMBER 
			END) AS [MRN_BJC],
		MAX(
			CASE 
				WHEN IDNUMBERTYPE = 'mrn_ssm' 
				THEN IDNUMBER 
			END) AS [MRN_SSM],
		MAX(
			CASE 
				WHEN IDNUMBERTYPE = 'SSN' 
				THEN IDNUMBER 
			END) AS [SSN],
		MAX(
			CASE 
				WHEN IDNUMBERTYPE = 'ssn_last_four' 
				THEN IDNUMBER 
			END) AS [SSN_LAST_FOUR],
		MAX(
			CASE 
				WHEN IDNUMBERTYPE = 'LegacyID' 
				THEN IDNUMBER 
			END) AS [ETO_CASE_NUM]
	FROM CLIENTPASSPORT
	WHERE DOCREVNO = ' 0 '
	GROUP BY CLIENTNUMBER
) AS [PASS]
	ON C.CLIENTNUMBER = PASS.CLIENTNUMBER
WHERE C.CLIENTINDICATOR = 'ON'
	AND C.DOCREVNO = ' 0 '
	AND C.LASTNAME NOT IN ('GVTTest', 'GVTest', 'GVTTEST');