/*

*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_COMPLEX_CARE_BEACN_HOUSING_STATUS_EXCEPTIONS AS 
WITH [BENCHMARKS] AS (
	SELECT 
		CBENCH.CLIENT_NUMBER,
		CBENCH.DOCSERNO,
		CBENCH.TIEDENROLLMENT,
		CENROLL.ENROLLMENT_STARTING_DATE AS [COHORT_REFERRAL_DATE],
		CENROLL.ENROLLMENT_ENDING_DATE AS [COHORT_DISCHARGE_DATE],
		CAST(CBENCH.ENROLLMENT_DATE AS DATE) AS [BASELINE_DATE]
	FROM BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCH]
	LEFT JOIN Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS [CENROLL]
		ON CBENCH.TIEDENROLLMENT = CENROLL.TIEDENROLLMENT
	WHERE CENROLL.PWY_EVENT = 'Complex Care Roster'
),
[EXPECTEDSCHEDULE] AS (
	-- Generates baseline (0) + 12 monthly checkpoints (1..12)
	SELECT 
		B.CLIENT_NUMBER,
		B.DOCSERNO,
		B.TIEDENROLLMENT,
		B.BASELINE_DATE,
		B.COHORT_REFERRAL_DATE,
		B.COHORT_DISCHARGE_DATE,
		X.n AS [EXPECTED_SEQ],
		CASE
			WHEN X.n = 0
			THEN B.BASELINE_DATE
			ELSE
				DATEADD(
					MONTH, 
					X.n, 
					DATEFROMPARTS(
						YEAR(
							B.BASELINE_DATE
							), 
						MONTH(
							B.BASELINE_DATE
							),
							1
						)
				) 
			END AS [EXPECTED_DATE],
		-- Adds earliest of COHORT_DISCHARGE_DATE or 12 months after baseline month
		CASE
			WHEN B.COHORT_DISCHARGE_DATE IS NOT NULL
			THEN B.COHORT_DISCHARGE_DATE
			ELSE DATEADD(
				MONTH,
				12,
				DATEFROMPARTS(
					YEAR(
						B.BASELINE_DATE
						),
					MONTH(
						B.BASELINE_DATE
						),
					1
				)
			)
		END AS [CUTOFF_DATE]
	FROM BENCHMARKS AS [B]
	CROSS APPLY (VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12)) AS X(n)
),
[EXPECTEDDATES] AS (
	SELECT
		ES.CLIENT_NUMBER,
		ES.TIEDENROLLMENT,
		ES.BASELINE_DATE,
		ES.COHORT_DISCHARGE_DATE,
		ES.EXPECTED_SEQ,
		ES.EXPECTED_DATE
	FROM EXPECTEDSCHEDULE AS [ES]
	WHERE ES.EXPECTED_DATE <= ES.CUTOFF_DATE
),
[ACTUALENTRIES] AS (
	SELECT 
		CHOUSE.CLIENT_NUMBER,
		CHOUSE.PARENT_DOCSERNO,
		CAST(CHOUSE.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE]
	FROM BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_ALL_HOUSING_STATUS AS [CHOUSE]
),
[COMPARISON] AS (
	SELECT 
		ES.CLIENT_NUMBER,
		ES.DOCSERNO,
		ES.TIEDENROLLMENT,
		ES.BASELINE_DATE,
		AE.HOUSING_START_DATE,
		ES.EXPECTED_SEQ,
		ES.EXPECTED_DATE,
		CASE 
			WHEN AE.HOUSING_START_DATE IS NOT NULL
				AND AE.HOUSING_START_DATE = ES.EXPECTED_DATE
			THEN 1 
			ELSE 0 
		END AS [HAS_EXPECTED_ENTRY],
		CASE
			WHEN ES.EXPECTED_SEQ = 0
			THEN 
				CASE
					WHEN ES.BASELINE_DATE = ES.EXPECTED_DATE
					THEN 0
					ELSE 1
				END
			ELSE NULL
		END AS [BASELINE_MISMATCH]
	FROM EXPECTEDSCHEDULE AS [ES]
	LEFT JOIN ACTUALENTRIES AS [AE]
		ON ES.CLIENT_NUMBER = AE.CLIENT_NUMBER
		AND ES.DOCSERNO = AE.PARENT_DOCSERNO
		AND ES.EXPECTED_DATE = AE.HOUSING_START_DATE
),
[BASELINECHECK] AS (
	SELECT 
		CBENCH.CLIENT_NUMBER,
		CBENCH.TIEDENROLLMENT,
		CASE 
			WHEN CBENCH.BASELINE_DATE IS NULL
			THEN NULL
			WHEN EXISTS (
				SELECT 1
				FROM ACTUALENTRIES AS [AE]
				WHERE AE.CLIENT_NUMBER = CBENCH.CLIENT_NUMBER
					AND AE.PARENT_DOCSERNO = CBENCH.DOCSERNO
					AND AE.HOUSING_START_DATE = CBENCH.BASELINE_DATE
			) THEN 1 ELSE 0
		END AS [HAS_BASELINE_ENTRY]
	FROM BENCHMARKS AS [CBENCH]
),
-- Counts multiple entries of HOUSING_START_DATE in the same month for a client
[MONTHLYCOUNTS] AS (
	SELECT 
		AE.CLIENT_NUMBER,
		AE.PARENT_DOCSERNO,
		YEAR(AE.HOUSING_START_DATE) AS [ENTRY_YEAR],
		MONTH(AE.HOUSING_START_DATE) AS [ENTRY_MONTH],
		COUNT(*) AS [ENTRY_COUNT]
	FROM ACTUALENTRIES AS [AE]
	GROUP BY 
		AE.CLIENT_NUMBER,
		AE.PARENT_DOCSERNO,
		YEAR(AE.HOUSING_START_DATE),
		MONTH(AE.HOUSING_START_DATE)
),
-- Flags rows with multiple entries
[MULTIPLEENTRIES] AS (
	SELECT 
		MC.CLIENT_NUMBER,
		MC.PARENT_DOCSERNO,
		MC.ENTRY_YEAR,
		MC.ENTRY_MONTH,
		CASE
			WHEN MC.ENTRY_COUNT > 1 
			THEN 1 
			ELSE 0 
		END AS [HAS_MULTIPLE_ENTRIES]
    FROM MONTHLYCOUNTS AS [MC]
)
SELECT 
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	COMP.BASELINE_DATE,
	COMP.EXPECTED_SEQ,
	COMP.EXPECTED_DATE,
	COMP.HOUSING_START_DATE AS [HOUSING_START_DATE_ENTERED],
	COMP.HAS_EXPECTED_ENTRY,
	ME.HAS_MULTIPLE_ENTRIES,
	COMP.BASELINE_MISMATCH,
	BC.HAS_BASELINE_ENTRY
FROM COMPARISON AS [COMP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON COMP.CLIENT_NUMBER = C.CLIENT_NUMBER
LEFT JOIN BASELINECHECK AS [BC]
	ON COMP.CLIENT_NUMBER = BC.CLIENT_NUMBER
	AND COMP.TIEDENROLLMENT = BC.TIEDENROLLMENT
LEFT JOIN MULTIPLEENTRIES AS [ME]
	ON COMP.CLIENT_NUMBER = ME.CLIENT_NUMBER
	AND COMP.DOCSERNO = ME.PARENT_DOCSERNO
	AND YEAR(COMP.EXPECTED_DATE) = ME.ENTRY_YEAR
	AND MONTH(COMP.EXPECTED_DATE) = ME.ENTRY_MONTH
WHERE (COMP.HAS_EXPECTED_ENTRY <> 1 
	OR ME.HAS_MULTIPLE_ENTRIES = 1)