/*
View Name: Q_COMPLEX_CARE_BEACN_QUALITY_OF_LIFE_ASSESSMENT 
Category: View Definitions  

See docs/view-definitions/q-complex-care-beacn-quality-of-life-assessment.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--CREATE VIEW DBO.Q_COMPLEX_CARE_BEACN_QUALITY_OF_LIFE_ASSESSMENT AS
SELECT ID,
	DOCSERNO,
	CAST(VISITDT AS DATE) AS [VISITDT],
	VISITTM,
	USERID,
	PARENTDOCSERNO,
	CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	GENERAL_HEALTH_QOL,
	PHYSICAL_HEALTH_QOL,
	MENTAL_HEALTH_QOL,
	POOR_HEALTH_INTERFERE_QOL,
	NOTES
FROM BEHAVHEALT_LIVE.DBO.PWBEACNQOLSUM AS [QOL]
WHERE QOL.DOCREVNO = ' 0 '