USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_COMPLEX_CARE_ALERTING_FOLLOW_UP AS
SELECT 
	CNOTE.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_NAME,
	CAST(CNOTE.VISITDT AS DATE) AS [VISIT_DATE],
	CNOTE.VISITTM AS [VISIT_TIME],
	CNOTE.USERID,
	CNOTE.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	CAST(CNOTE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(CNOTE.CLINICAL_COMMITTEE_MEETING_DATE AS DATE) AS [MEETING_DATE],
	CNOTE.NOTE_TYPE,
    CNOTE.PCC_NOTIFICATION,
	CNOTE.NUM_PCC_ALERTS,
	CNOTE.OUTREACH_RESPONSE,
	CNOTE.REASON_NO_OUTREACH AS [REASON_NO_OUTREACH_CODE],
	CNOOUTREASON.DESCRIPTION AS [REASON_NO_OUTREACH_DESCRIPTION],
	CNOTE.OTHER_REASON_NO_OUTREACH,
	CNOTE.TIEDENROLLMENT
FROM BEHAVHEALT_LIVE.DBO.PWCOMPLEXCARECLINICALNOTES AS [CNOTE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON CNOTE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.COMPLEX_CARE_REASON_NO_OUTREACH AS [CNOOUTREASON]
	ON CNOTE.REASON_NO_OUTREACH = CNOOUTREASON.CODE
WHERE DOCREVNO = ' 0 '
	AND CNOTE.NOTE_TYPE = 'Alerting Follow-up';