/*
View Name: Q_COMPLEX_CARE_PFP_DISCHARGE  
Category: View Definitions  

See docs/view-definitions/q-complex-care-pfp-discharge.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_COMPLEX_CARE_PFP_DISCHARGE AS
SELECT PFPDISCHARGE.ID, 
	PFPDISCHARGE.DOCSERNO, 
	CAST(PFPDISCHARGE.VISITDT AS DATE) AS [VISIT_DATE], 
	PFPDISCHARGE.VISITTM AS [VISIT_TIME], 
	PFPDISCHARGE.USERID, 
	PFPDISCHARGE.PARENTDOCSERNO AS [PARENT_DOCSERNO], 
	PFPDISCHARGE.CLIENTNUMBER AS [CLIENT_NUMBER], 
	CAST(PFPDISCHARGE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE], 
	CAST(PFPDISCHARGE.PFP_DISCHARGE_DATE AS DATE) AS [PFP_DISCHARGE_DATE], 
    PFPDISCHARGE.PFP_DISCHARGE_NOTES, 
	PFPDISCHARGE.TIEDENROLLMENT
FROM DBO.PWPFPDISCHARGE AS [PFPDISCHARGE]
WHERE PFPDISCHARGE.DOCREVNO = ' 0 ';