/*
View Name: Q_COMPLEX_CARE_BEACN_SHELTER_BED_TRACKING
Category: View Definitions  

See docs/view-definitions/q-complex-care-beacn-shelter-bed-tracking.md for full documentation.
*/

USE BEHAVHEALT_LIVE
GO

--CREATE VIEW DBO.Q_COMPLEX_CARE_BEACN_SHELTER_BED_TRACKING AS
SELECT ID,
	DOCSERNO,
	CAST(VISITDT AS DATE) AS [VISITDT],
	VISITTM,
	USERID,
	PARENTDOCSERNO,
	CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(DATE_OFFERED AS DATE) AS [DATE_OFFERED_SHELTER_BED],
	DECISION_SHELTER_BED,
	CAST(START_DATE_SHELTER_BED AS DATE) AS [START_DATE_SHELTER_BED],
	CAST(END_DATE_SHELTER_BED AS DATE) AS [END_DATE_SHELTER_BED],
	NOTES_SHELTER_BED
FROM BEHAVHEALT_LIVE.DBO.PWBEACNSHELTERBEDTRACKING AS [SHELTER]
WHERE SHELTER.DOCREVNO = ' 0 '