/*
View Name: Q_COMPLEX_CARE_BEACN_QUALITY_OF_LIFE_ASSESSMENT 
Category: View Definitions  

See docs/view-definitions/q-complex-care-beacn-quality-of-life-assessment.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--CREATE VIEW DBO.Q_COMPLEX_CARE_BEACN_QUALITY_OF_LIFE_ASSESSMENT AS
SELECT QOL.ID,
	QOL.DOCSERNO,
	CAST(QOL.VISITDT AS DATE) AS [VISITDT],
	QOL.VISITTM,
	QOL.USERID,
	QOL.PARENTDOCSERNO,
	C.CLIENT_NUMBER,
	CAST(QOL.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	QOL.GENERAL_HEALTH_QOL,
	QOL.PHYSICAL_HEALTH_QOL,
	QOL.MENTAL_HEALTH_QOL,
	QOL.POOR_HEALTH_INTERFERE_QOL,
	QOL.NOTES
FROM BEHAVHEALT_LIVE.DBO.PWBEACNQOLSUM AS [QOL]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON QOL.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE QOL.DOCREVNO = ' 0 '