/*
View Name: Q_COMPLEX_CARE_ROSTER  
Category: View Definitions  

See docs/view-definitions/q-complex-care-roster.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_COMPLEX_CARE_ROSTER AS
SELECT ROSTER.ID,
	ROSTER.DOCSERNO,
	CAST(ROSTER.VISITDT AS DATE) AS [VISITDT],
	ROSTER.VISITTM,
	ROSTER.USERID,
	'Complex Care Roster' AS [EVENT_NAME],
	ROSTER.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	C.CLIENT_NUMBER,
	CAST(ROSTER.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ROSTER.PROGRAM_ASSIGNED,
	ROSTER.CMHC_STATUS AS [CIMOR_STATUS_CODE],
	CIMOR_STATUS.DESCRIPTION AS [CMHC_CIMOR_STATUS.DESCRIPTION],
	ROSTER.CMHC_AGENCY AS [CMHC_AGENCY_CODE],
	CMHC.DESCRIPTION AS [CMHC_AGENCY_DESCRIPTION],
	ROSTER.OTHER_CMHC_AGENCY,
	ROSTER.ADA_SU_STATUS AS [ADA_CIMOR_STATUS_CODE],
	CIMOR_ADA.DESCRIPTION AS [ADA_CIMOR_STATUS_DESCRIPTION],
	ROSTER.ADA_SU_AGENCY AS [ADA_SU_AGENCY_CODE],
	ADA.DESCRIPTION AS [ADA_SU_AGENCY_DESCRIPTION],
	ROSTER.OTHER_ADA_SU_AGENCY
FROM PWCOMPLEXCAREROSTER AS [ROSTER]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = ROSTER.CLIENTNUMBER
LEFT JOIN CIMOR_STATUS
	ON ROSTER.CMHC_STATUS = CIMOR_STATUS.CODE
LEFT JOIN CMHC_AGENCY AS [CMHC]
	ON ROSTER.CMHC_AGENCY = CMHC.CODE
LEFT JOIN CIMOR_STATUS AS [CIMOR_ADA]
	ON ROSTER.ADA_SU_STATUS = CIMOR_ADA.CODE
LEFT JOIN ADA_SU_AGENCY AS [ADA]
	ON ROSTER.ADA_SU_AGENCY = ADA.CODE
WHERE ROSTER.DOCREVNO = ' 0 ';