/*
View Name: Q_COMPLEX_CARE_PATHWAY_FORM_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-complex-care-pathway-forms-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_COMPLEX_CARE_PATHWAY_FORM_DOCSERNOS AS
SELECT ROSTER.CLIENT_NUMBER AS [CLIENT_NUMBER],
	CAST(ROSTER.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ROSTER.DOCSERNO,
	ROSTER.TIEDENROLLMENT,
	'Complex Care Roster' AS [FORM_TYPE]
FROM DBO.Q_COMPLEX_CARE_ROSTER AS [ROSTER]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = ROSTER.CLIENT_NUMBER
UNION ALL
SELECT CBENCH.CLIENT_NUMBER AS [CLIENT_NUMBER],
	CAST(CBENCH.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CBENCH.DOCSERNO,
	CBENCH.TIEDENROLLMENT,
	'Clinical BEACN Metrics' AS [FORM_TYPE]
FROM DBO.Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCH]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = CBENCH.CLIENT_NUMBER
UNION ALL
SELECT PFPDISCHARGE.CLIENT_NUMBER AS [CLIENT_NUMBER],
	CAST(PFPDISCHARGE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	PFPDISCHARGE.DOCSERNO,
	PFPDISCHARGE.TIEDENROLLMENT,
	'PfP Discharge' AS [FORM_TYPE]
FROM DBO.Q_COMPLEX_CARE_PFP_DISCHARGE AS [PFPDISCHARGE]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = PFPDISCHARGE.CLIENT_NUMBER
UNION ALL
SELECT OUTNOTE.CLIENT_NUMBER AS [CLIENT_NUMBER],
	CAST(OUTNOTE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	OUTNOTE.DOCSERNO,
	OUTNOTE.TIEDENROLLMENT,
	'Complex Care Outreach Note' AS [FORM_TYPE]
FROM DBO.Q_COMPLEX_CARE_OUTREACH_NOTES AS [OUTNOTE]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = OUTNOTE.CLIENT_NUMBER;