/*
View Name: Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS  
Category: View Definitions  

See docs/view-definitions/q-complex-care-pathclient-enrollments.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS
SELECT C.CLIENT_NUMBER,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	PP.DOCSERNO AS [PP_DOCSERNO],
	PC.DOCSERNO AS [PC_DOCSERNO],
	PEC.PATHCLIENTDOCSERNO AS [PEC_PATHCLIENT_DOCSERNO],
	P.PROVIDERNAME AS [AGENCY_DESCRIPTION],
	CAST(PC.STARTDATE AS DATE) AS [PWY_START_DATE],
	CAST(PC.ENDDATE AS DATE) AS [PWY_END_DATE],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'Complex Care Roster' 
		THEN ROSTER.DOCSERNO
	END AS [PWY_FORMS_DOCSERNO],
	CAST(PEC.STARTDATE AS DATE) AS [EVENT_START_DATE],
	CAST(PEC.ENDDATE AS DATE) AS [EVENT_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [PE_DATE_ACCOMPLISHED],
	CASE
		WHEN PEC.DATEACCOMPLISHED IS NULL 
		THEN DATEDIFF(DAY, GETDATE(), PEC.ENDDATE)
	END AS [DAYS_UNTIL_FORM_DUE],
	PEC.CURRENTMESSAGE AS [CURRENT_MESSAGE],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST]
FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.CLOSINGREASONS AS [CR]
	ON PP.CLOSINGREASON = CR.CODE
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYCLIENT AS [PC]
	ON (
		PP.CLIENTNUMBER = PC.CLIENTNUMBER
		AND PC.DOCSERNO = PP.DOCSERNO
		AND PC.DOCREVNO = ' 0 '
		) OR (
			PP.CLIENTNUMBER = PC.CLIENTNUMBER
			AND PP.DOCSERNO <> PC.DOCSERNO
			AND PP.STARTINGDATE = PC.STARTDATE
			AND PP.PATHWAY = PC.PARENTDOCSERNO
			AND PC.DOCREVNO = ' 0 '
			)
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENTCLIENT AS [PEC]
	ON PC.DOCSERNO = PEC.PATHCLIENTDOCSERNO
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENT AS [PE]
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAY AS [PWY]
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDER AS [P]
	ON PP.PRIMARYPROVIDERCODE = P.PROVIDERCODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HRR]
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_ROSTER AS [ROSTER]
	ON ROSTER.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240920114308822
	AND ROSTER.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND ROSTER.EVENT_NAME = PE.SHORTDESCRIPTION
WHERE PP.PATHWAY = 55320240920114308822
	AND PP.DOCREVNO = ' 0 ';