/*
View Name: Q_COMPLEX_CARE_CLINICAL_NOTES
Category: View Definitions  

See docs/view-definitions/q-complex-care-clinical-notes.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_COMPLEX_CARE_CLINICAL_NOTES AS
SELECT 
	CNOTE.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(CNOTE.VISITDT AS DATE) AS [VISIT_DATE],
	CNOTE.VISITTM,
	CNOTE.USERID,
	CNOTE.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	CAST(CNOTE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(CNOTE.CLINICAL_COMMITTEE_MEETING_DATE AS DATE) AS [MEETING_DATE],
	CNOTE.DECISION,
	CNOTE.COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE AS [COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE_CODE],
	COMPRAT.DESCRIPTION AS [COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE_DESCRIPTION],
	CNOTE.COMPLEX_CARE_REASONS_INELIGIBLE AS [COMPLEX_CARE_REASONS_INELIGIBLE_CODE],
	COMPINELIGIBLE.DESCRIPTION AS [COMPLEX_CARE_REASONS_INELIGIBLE_DESCRIPTION],
	CNOTE.COMPLEX_CARE_OTHER_OUTCOMES AS [COMPLEX_CARE_OTHER_OUTCOMES_CODE],
	COMPOTHOUT.DESCRIPTION AS [COMPLEX_CARE_OTHER_OUTCOMES_DESCRIPTION],
	CNOTE.CLINICAL_NOTES,
	CNOTE.TIEDENROLLMENT
FROM BEHAVHEALT_LIVE.DBO.PWCOMPLEXCARECLINICALNOTES AS [CNOTE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON CNOTE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE AS [COMPRAT]
	ON CNOTE.COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE = COMPRAT.CODE
LEFT JOIN COMPLEX_CARE_REASONS_INELIGIBLE AS [COMPINELIGIBLE]
	ON CNOTE.COMPLEX_CARE_REASONS_INELIGIBLE = COMPINELIGIBLE.CODE
LEFT JOIN COMPLEX_CARE_OTHER_OUTCOMES AS [COMPOTHOUT]
	ON CNOTE.COMPLEX_CARE_OTHER_OUTCOMES = COMPOTHOUT.CODE
WHERE DOCREVNO = ' 0 '