USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_COMPLEX_CARE_OUTREACH_NOTES AS
SELECT CCOUTREACHNOTE.ID,
	CCOUTREACHNOTE.DOCSERNO,
	CAST(CCOUTREACHNOTE.VISITDT AS DATE) AS [VISIT_DATE],
	CCOUTREACHNOTE.VISITTM AS [VISIT_TIME],
	CCOUTREACHNOTE.USERID,
	CCOUTREACHNOTE.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	CCOUTREACHNOTE.CLIENTNUMBER AS [CLIENT_NUMBER],
	CCOUTREACHNOTE.TIEDENROLLMENT,
	CAST(CCOUTREACHNOTE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(ROSTER.ADDED_COHORT_DATE AS DATE) AS [ADDED_COHORT_DATE], 
	CCOUTREACHNOTE.ALERT_WEEK,
	CCOUTREACHNOTE.CLIENT_STATUS_ON,
	CCOUTREACHNOTE.CC_OUTREACH_ATTEMPT,
	CCOUTREACHNOTE.CC_OUTREACH_ALERT,
	CCOUTREACHNOTE.CC_OUTREACH_ALERT_TYPE,
	CCOUTREACHNOTE.NOTES_ON,
	CCOUTREACHNOTE.NUM_OUTREACH_ATTEMPTS_IN_PERSON,
	CCOUTREACHNOTE.NUM_OUTREACH_ATTEMPTS_PHONE_VIRTUAL,
	CCOUTREACHNOTE.NUM_OUTREACH_ATTEMPTS_AT_HOSPITAL,
	CCOUTREACHNOTE.NUM_OUTREACH_CONTACT_W_CLIENT,
	CCOUTREACHNOTE.CC_OUTREACH_OTHER_COLLATERAL_CONTACT,
	CCOUTREACHNOTE.CC_OUTREACH_COLLATERAL_CONTACT_HOSPITAL_STAFF,
	CCOUTREACHNOTE.CC_OUTREACH_COLLATERAL_CONTACT_AGENCY_STAFF,
	CCOUTREACHNOTE.CC_OUTREACH_COLLATERAL_CONTACT_CLIENT_FAMILY_FRIEND,
	CCOUTREACHNOTE.CC_OUTREACH_COLLATERAL_CONTACT_OTHER,
	CCOUTREACHNOTE.CC_OUTREACH_COLLATERAL_CONTACT AS [CC_OUTREACH_COLLATERAL_CONTACT_CODE],
	CCO.[DESCRIPTION] AS [CC_OUTREACH_COLLATERAL_CONTACT_DESCRIPTION]
FROM DBO.PWCOMPLEXCAREOUTREACHNOTE AS [CCOUTREACHNOTE]
LEFT JOIN DBO.COMPLEX_CARE_OUTREACH_COLLATERAL_CONTACT AS [CCO]
	ON CCO.CODE = CCOUTREACHNOTE.CC_OUTREACH_COLLATERAL_CONTACT
LEFT JOIN DBO.Q_COMPLEX_CARE_ROSTER AS [ROSTER]
	ON ROSTER.CLIENT_NUMBER = CCOUTREACHNOTE.CLIENTNUMBER
	AND ROSTER.TIEDENROLLMENT = CCOUTREACHNOTE.TIEDENROLLMENT
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = CCOUTREACHNOTE.CLIENTNUMBER
WHERE CCOUTREACHNOTE.DOCREVNO = ' 0 '
