/*
View Name: Q_COMPLEX_CARE_ACTIVE_PAYOR_SOURCE
Category: View Definitions  

See docs/view-definitions/q-complex-care-active-payor-source.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- CREATE VIEW dbo.Q_COMPLEX_CARE_ACTIVE_PAYOR_SOURCE AS
WITH [ALL_PAYOR] AS (
	SELECT 
		APS.DOCSERNO,
		APS.PARENT_DOCSERNO,
		APS.CLIENT_NUMBER,
		APS.VISITDT,
		APS.VISITTM,
		APS.USERID,
		APS.PAYOR_SOURCE_CODE,
		APS.PAYOR_SOURCE_DESCRIPTION,
		APS.MANAGED_MEDICAID_PROVIDER,
		APS.PRIVATE_INSURANCE_PROVIDER,
		APS.PAYOR_SOURCE_START_DATE,
		APS.PAYOR_SOURCE_END_DATE
	FROM BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_ALL_PAYOR_SOURCE AS [APS]
),
[BASELINE_PAYOR] AS (
	-- Earliest payor source per client (baseline at enrollment)
	SELECT CLIENT_NUMBER,
		 CAST(PAYOR_SOURCE_START_DATE AS DATE) AS [BASELINE_PAYOR_SOURCE_START_DATE],
		 CAST(PAYOR_SOURCE_END_DATE AS DATE) AS [BASELINE_PAYOR_SOURCE_END_DATE],
		 PAYOR_SOURCE_CODE AS [BASELINE_PAYOR_SOURCE_CODE],
		 PAYOR_SOURCE_DESCRIPTION AS [BASELINE_PAYOR_SOURCE_DESCRIPTION]
	FROM (
		SELECT *,
			ROW_NUMBER() OVER (
				PARTITION BY CLIENT_NUMBER
				ORDER BY PAYOR_SOURCE_START_DATE ASC, DOCSERNO ASC
			) AS [RN]
		FROM ALL_PAYOR
	) AS [X]
	WHERE RN = 1
),
[LATEST_ACTIVE] AS (
	-- Latest ACTIVE (end date IS NULL) payor source per client
	SELECT * FROM (
		SELECT CLIENT_NUMBER,
			DOCSERNO,
			PARENT_DOCSERNO,
			CAST(PAYOR_SOURCE_START_DATE AS DATE) AS [CURRENT_PAYOR_SOURCE_START_DATE],
			CAST(PAYOR_SOURCE_END_DATE AS DATE) AS [CURRENT_PAYOR_SOURCE_END_DATE],
			PAYOR_SOURCE_CODE AS [CURRENT_PAYOR_SOURCE_CODE],
			PAYOR_SOURCE_DESCRIPTION AS [CURRENT_PAYOR_SOURCE_DESCRIPTION],
			MANAGED_MEDICAID_PROVIDER,
			PRIVATE_INSURANCE_PROVIDER,
			CAST(VISITDT AS DATE) AS [VISITDT],
			VISITTM,
			USERID,
			ROW_NUMBER() OVER (
				PARTITION BY CLIENT_NUMBER
				ORDER BY PAYOR_SOURCE_START_DATE DESC, DOCSERNO DESC
			) AS [RN]
		FROM ALL_PAYOR
		WHERE PAYOR_SOURCE_END_DATE IS NULL
	) AS [X]
	WHERE RN = 1
)
SELECT 
	LA.CLIENT_NUMBER,
	LA.DOCSERNO,
	LA.PARENT_DOCSERNO,
	LA.VISITDT,
	LA.VISITTM,
	LA.USERID,

	-- Baseline (earliest)
	B.BASELINE_PAYOR_SOURCE_START_DATE,
	B.BASELINE_PAYOR_SOURCE_END_DATE,
	B.BASELINE_PAYOR_SOURCE_CODE,
	B.BASELINE_PAYOR_SOURCE_DESCRIPTION,
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '001' 
		THEN 1 
		ELSE 0 
  	END AS [BASELINE_PAYOR_SOURCE_DUAL_ELIGIBLE],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '005'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_MANAGED_MEDICAID],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '002'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_MEDICAID],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '003'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_MEDICAID_IN_PROGRESS],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '004'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_MEDICAID_CHP],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '006'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_MEDICARE],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '007'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_PRIVATE_INSURANCE],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '009'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_UNINSURED],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '010'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_UNKNOWN_REFUSED],
	CASE
		WHEN ISNULL(B.BASELINE_PAYOR_SOURCE_CODE,'') = '008'
		THEN 1
		ELSE 0
	END AS [BASELINE_PAYOR_SOURCE_VA_BENEFITS],

	-- Current (latest active)
	LA.CURRENT_PAYOR_SOURCE_START_DATE,
	LA.CURRENT_PAYOR_SOURCE_END_DATE,  -- will be NULL by design
	LA.CURRENT_PAYOR_SOURCE_CODE,
	LA.CURRENT_PAYOR_SOURCE_DESCRIPTION,
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '001'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_DUAL_ELIGIBLE],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '005'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_MANAGED_MEDICAID],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '002'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_MEDICAID],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '003'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_MEDICAID_IN_PROGRESS],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '004' 
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_MEDICAID_CHP],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '006'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_MEDICARE],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '007'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_PRIVATE_INSURANCE],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '009'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_UNINSURED],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '010'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_UNKNOWN_REFUSED],
	CASE
		WHEN ISNULL(LA.CURRENT_PAYOR_SOURCE_CODE,'') = '008'
		THEN 1
		ELSE 0
	END AS [CURRENT_PAYOR_SOURCE_VA_BENEFITS],

	-- Provider fields and description
	LA.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
	MMP.DESCRIPTION AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
	LA.PRIVATE_INSURANCE_PROVIDER
FROM LATEST_ACTIVE AS [LA]
LEFT JOIN BASELINE_PAYOR AS [B]
	ON B.CLIENT_NUMBER = LA.CLIENT_NUMBER
LEFT JOIN MANAGED_MEDICAID_PROVIDER AS [MMP]
	ON LA.MANAGED_MEDICAID_PROVIDER = MMP.CODE;
