/*
View Name: Q_COMPLEX_CARE_BEACN_SHELTER_BED_TRACKING
Category: View Definitions  

See docs/view-definitions/q-complex-care-beacn-shelter-bed-tracking.md for full documentation.
*/

USE BEHAVHEALT_LIVE
GO

--ALTER VIEW DBO.Q_COMPLEX_CARE_BEACN_SHELTER_BED_TRACKING AS
SELECT SHELTER.ID,
	SHELTER.DOCSERNO,
	CAST(SHELTER.VISITDT AS DATE) AS [VISIT_DATE],
	SHELTER.VISITTM AS [VISIT_TIME],
	SHELTER.USERID,
	SHELTER.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	C.CLIENT_NUMBER,
	CAST(SHELTER.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(SHELTER.DATE_OFFERED AS DATE) AS [DATE_OFFERED_SHELTER_BED],
	SHELTER.DECISION_SHELTER_BED,
	CAST(SHELTER.START_DATE_SHELTER_BED AS DATE) AS [START_DATE_SHELTER_BED],
	CAST(SHELTER.END_DATE_SHELTER_BED AS DATE) AS [END_DATE_SHELTER_BED],
	SHELTER.NOTES_SHELTER_BED
FROM BEHAVHEALT_LIVE.DBO.PWBEACNSHELTERBEDTRACKING AS [SHELTER]
INNER JOIN Q_COMPLEX_CARE_CLIENT AS [C]
	ON C.CLIENT_NUMBER = SHELTER.CLIENTNUMBER
WHERE SHELTER.DOCREVNO = ' 0 '