/*
View Name: Q_COMPLEX_CARE_PATHWAY_FORMS_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-complex-care-pathway-forms-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_COMPLEX_CARE_PATHWAY_FORM_DOCSERNOS AS
SELECT ROSTER.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ROSTER.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ROSTER.DOCSERNO,
	'Complex Care Roster' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWCOMPLEXCAREROSTER AS [ROSTER]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = ROSTER.CLIENTNUMBER
WHERE ROSTER.DOCREVNO = ' 0 ';