/*
View Name: Q_COMPLEX_CARE_BEACN_PAYOR_SUMMATION_EXCEPTIONS
Category: View Definitions  

See docs/view-definitions/q-complex-care-beacn-payor-summation-exceptions.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

WITH [ENROLLMENTS] AS (
	SELECT
		CENROLL.CLIENT_NUMBER,
		CENROLL.TIEDENROLLMENT,
		CENROLL.PWY_FORMS_DOCSERNO AS [BENCHMARK_DOCSERNO],
		CBENCH.ENROLLMENT_DATE AS [PFP_ENROLLMENT_DATE],
		CBENCH.PATHWAY_DATE AS [BENCHMARK_PATHWAY_DATE],
		CBENCH.VISIT_DATE AS [BENCHMARK_VISIT_DATE],
		CENROLL.ENROLLMENT_ENDING_DATE AS [PROGRAM_DISCHARGE_DATE]
	FROM dbo.Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS [CENROLL]
	INNER JOIN dbo.Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCH]
		ON CENROLL.CLIENT_NUMBER = CBENCH.CLIENT_NUMBER
		AND CENROLL.PWY_FORMS_DOCSERNO = CBENCH.DOCSERNO
	WHERE CENROLL.PWY_EVENT = 'Clinical BEACN Metrics'
		AND CBENCH.ENROLLMENT_DATE IS NOT NULL
		AND (
			CENROLL.ENROLLMENT_ENDING_DATE >= '2025-07-01'
			OR CENROLL.ENROLLMENT_ENDING_DATE IS NULL
			)
),
[BOUNDARIES] AS (
	SELECT
		E.*,
		DATEADD(MONTH, 20, E.PFP_ENROLLMENT_DATE) AS [MAX_20_MONTH_DATE],
		COALESCE(E.PROGRAM_DISCHARGE_DATE, DATEADD(MONTH, 20, E.PFP_ENROLLMENT_DATE)) AS [STOP_DATE],
		CAST(GETDATE() AS DATE) AS [TODAY]
	FROM ENROLLMENTS AS [E]
),
[EXPECTED_MONTHS] AS (
	SELECT
		B.CLIENT_NUMBER,
		B.TIEDENROLLMENT,
		B.BENCHMARK_DOCSERNO,
		B.PFP_ENROLLMENT_DATE,
		B.STOP_DATE,
		B.TODAY,
		0 AS MONTH_INDEX,
		CAST(B.PFP_ENROLLMENT_DATE AS DATE) AS [EXPECTED_DATE]
	FROM BOUNDARIES AS [B]

	UNION ALL

	SELECT
		EM.CLIENT_NUMBER,
		EM.TIEDENROLLMENT,
		EM.BENCHMARK_DOCSERNO,
		EM.PFP_ENROLLMENT_DATE,
		EM.STOP_DATE,
		EM.TODAY,
		EM.MONTH_INDEX + 1,
		DATEFROMPARTS(
			YEAR(DATEADD(MONTH, EM.MONTH_INDEX + 1, EM.PFP_ENROLLMENT_DATE)),
			MONTH(DATEADD(MONTH, EM.MONTH_INDEX + 1, EM.PFP_ENROLLMENT_DATE)),
			1
		) AS [EXPECTED_DATE]
	FROM EXPECTED_MONTHS AS [EM]
	WHERE 
		-- Compute the next expected month start
		DATEFROMPARTS(
			YEAR(DATEADD(MONTH, EM.MONTH_INDEX + 1, EM.PFP_ENROLLMENT_DATE)),
			MONTH(DATEADD(MONTH, EM.MONTH_INDEX + 1, EM.PFP_ENROLLMENT_DATE)),
			1
		) <= EM.STOP_DATE
		AND
		DATEFROMPARTS(
			YEAR(DATEADD(MONTH, EM.MONTH_INDEX + 1, EM.PFP_ENROLLMENT_DATE)),
			MONTH(DATEADD(MONTH, EM.MONTH_INDEX + 1, EM.PFP_ENROLLMENT_DATE)),
			1
		) <= EM.TODAY
),
[ACTUAL] AS (
	SELECT
		P.CLIENT_NUMBER,
		P.PARENT_DOCSERNO AS [BENCHMARK_DOCSERNO],
		P.PAYOR_SOURCE_START_DATE,
		P.PAYOR_SOURCE_CODE,
        P.PAYOR_SOURCE_DESCRIPTION
	FROM dbo.Q_COMPLEX_CARE_ALL_PAYOR_SOURCE AS [P]
),
[COMPARISON] AS (
	SELECT
		EM.CLIENT_NUMBER,
		EM.TIEDENROLLMENT,
		EM.BENCHMARK_DOCSERNO,
		EM.EXPECTED_DATE,
		EM.MONTH_INDEX,
		/* Exact-date match (aligned) */
		A_EXACT.PAYOR_SOURCE_START_DATE AS [ALIGNED_ENTRY_DATE],
		/* Month-level match (any entry in the same month) */
		A_MONTH.PAYOR_SOURCE_START_DATE AS [MONTH_MISALIGNED_ENTRY_DATE],
		/* Use month-level payor source code when exact-date is missing */
		COALESCE(A_EXACT.PAYOR_SOURCE_CODE, A_MONTH.PAYOR_SOURCE_CODE) AS [PAYOR_SOURCE_CODE],
        /* Use month-level payor source description when exact-date is missing */
		COALESCE(A_EXACT.PAYOR_SOURCE_DESCRIPTION, A_MONTH.PAYOR_SOURCE_DESCRIPTION) AS [PAYOR_SOURCE_DESCRIPTION],
		/* Missing entry: no entry in the entire month */
		CASE
			WHEN A_MONTH.PAYOR_SOURCE_START_DATE IS NULL
			THEN 1
			ELSE 0
		END AS [MISSING_ENTRY],
		/* Misaligned: entry exists but not on the expected date */
		CASE
			WHEN A_MONTH.PAYOR_SOURCE_START_DATE IS NOT NULL 
				 AND A_EXACT.PAYOR_SOURCE_START_DATE IS NULL 
			THEN 1
			ELSE 0 
		END AS [MISALIGNED_DATE],
		/* Baseline misalignment: entry exists in baseline month but wrong date */
		CASE
			WHEN EM.MONTH_INDEX = 0 
				AND A_EXACT.PAYOR_SOURCE_START_DATE IS NULL 
				AND A_MONTH.PAYOR_SOURCE_START_DATE IS NOT NULL
			THEN 1
			ELSE 0
		END AS [BASELINE_MISALIGNED],
		/* Early-entry detection: payor_source_start_date < enrollment_date */
		CASE
			WHEN EM.MONTH_INDEX = 0 
				AND EXISTS (
					SELECT 1
					FROM ACTUAL AS [A3]
					WHERE A3.CLIENT_NUMBER = EM.CLIENT_NUMBER
						AND A3.BENCHMARK_DOCSERNO = EM.BENCHMARK_DOCSERNO
						AND A3.PAYOR_SOURCE_START_DATE < EM.PFP_ENROLLMENT_DATE
					)
			THEN 1
			ELSE 0
		END AS [BASELINE_EARLY_ENTRY],
		EXC.Label AS [EXCEPTION_LABEL]
	FROM EXPECTED_MONTHS AS [EM]
	/* Exact-date match join */
	LEFT JOIN ACTUAL AS [A_EXACT]
		ON A_EXACT.CLIENT_NUMBER = EM.CLIENT_NUMBER
		AND A_EXACT.BENCHMARK_DOCSERNO = EM.BENCHMARK_DOCSERNO
		AND A_EXACT.PAYOR_SOURCE_START_DATE = EM.EXPECTED_DATE
	/* Month-level match join */
	LEFT JOIN ACTUAL AS [A_MONTH]
		ON A_MONTH.CLIENT_NUMBER = EM.CLIENT_NUMBER
		AND A_MONTH.BENCHMARK_DOCSERNO = EM.BENCHMARK_DOCSERNO
		AND MONTH(A_MONTH.PAYOR_SOURCE_START_DATE) = MONTH(EM.EXPECTED_DATE)
		AND YEAR(A_MONTH.PAYOR_SOURCE_START_DATE) = YEAR(EM.EXPECTED_DATE)
	/* Exception labels */
	CROSS APPLY (
		SELECT Label
		FROM (VALUES
			(CASE WHEN A_MONTH.PAYOR_SOURCE_START_DATE IS NULL THEN 'Missing' ELSE NULL END),
			(CASE WHEN A_MONTH.PAYOR_SOURCE_START_DATE IS NOT NULL AND A_EXACT.PAYOR_SOURCE_START_DATE IS NULL THEN 'Misaligned' ELSE NULL END),
			(CASE WHEN EM.MONTH_INDEX = 0 AND A_EXACT.PAYOR_SOURCE_START_DATE IS NULL AND A_MONTH.PAYOR_SOURCE_START_DATE IS NOT NULL THEN 'Baseline Misaligned' ELSE NULL END),
			(CASE WHEN EM.MONTH_INDEX = 0 AND EXISTS (
				SELECT 1
				FROM ACTUAL AS A3
				WHERE A3.CLIENT_NUMBER = EM.CLIENT_NUMBER
				  AND A3.BENCHMARK_DOCSERNO = EM.BENCHMARK_DOCSERNO
				  AND A3.PAYOR_SOURCE_START_DATE < EM.PFP_ENROLLMENT_DATE
			) THEN 'Baseline Early Entry' ELSE NULL END),
			(CASE WHEN EXISTS (
				SELECT 1
				FROM ACTUAL AS A4
				WHERE A4.CLIENT_NUMBER = EM.CLIENT_NUMBER
				  AND A4.BENCHMARK_DOCSERNO = EM.BENCHMARK_DOCSERNO
				  AND MONTH(A4.PAYOR_SOURCE_START_DATE) = MONTH(EM.EXPECTED_DATE)
				  AND YEAR(A4.PAYOR_SOURCE_START_DATE) = YEAR(EM.EXPECTED_DATE)
				GROUP BY A4.CLIENT_NUMBER, A4.BENCHMARK_DOCSERNO, MONTH(A4.PAYOR_SOURCE_START_DATE), YEAR(A4.PAYOR_SOURCE_START_DATE)
				HAVING COUNT(*) > 1
			) THEN 'Duplicate' ELSE NULL END)
		) AS V(Label)
		WHERE Label IS NOT NULL
	) AS EXC
)
SELECT COMP.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	COMP.TIEDENROLLMENT,
	COMP.BENCHMARK_DOCSERNO,
	COMP.EXPECTED_DATE,
	COMP.MONTH_INDEX,
	COMP.ALIGNED_ENTRY_DATE,
	COMP.PAYOR_SOURCE_CODE,
    COMP.PAYOR_SOURCE_DESCRIPTION,
	COMP.MONTH_MISALIGNED_ENTRY_DATE,
	COMP.MISSING_ENTRY,
	COMP.MISALIGNED_DATE,
	COMP.BASELINE_MISALIGNED,
	COMP.BASELINE_EARLY_ENTRY,
	STRING_AGG(COMP.EXCEPTION_LABEL, '; ') AS [EXCEPTION_CATEGORY]
FROM COMPARISON AS [COMP]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = COMP.CLIENT_NUMBER
GROUP BY
	COMP.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	COMP.TIEDENROLLMENT,
	COMP.BENCHMARK_DOCSERNO,
	COMP.EXPECTED_DATE,
	COMP.MONTH_INDEX,
	COMP.ALIGNED_ENTRY_DATE,
	COMP.PAYOR_SOURCE_CODE,
    COMP.PAYOR_SOURCE_DESCRIPTION,
	COMP.MONTH_MISALIGNED_ENTRY_DATE,
	COMP.MISSING_ENTRY,
	COMP.MISALIGNED_DATE,
	COMP.BASELINE_MISALIGNED,
	COMP.BASELINE_EARLY_ENTRY
--ORDER BY
--	COMP.CLIENT_NUMBER,
--	COMP.EXPECTED_DATE;