/*
View Name: Q_COMPLEX_CARE_CLINICAL_NOTES
Category: View Definitions  

See docs/view-definitions/q-complex-care-clinical-notes.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

CREATE VIEW DBO.Q_COMPLEX_CARE_CLINICAL_NOTES AS
SELECT 
	CNOTE.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(CNOTE.VISITDT AS DATE) AS [VISIT_DATE],
	CNOTE.VISITTM,
	CNOTE.USERID,
	CNOTE.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	CAST(CNOTE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(CNOTE.CLINICAL_COMMITTEE_MEETING_DATE AS DATE) AS [MEETING_DATE],
	CNOTE.DECISION,
	CNOTE.COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE,
	CNOTE.COMPLEX_CARE_REASONS_INELIGIBLE,
	CNOTE.COMPLEX_CARE_OTHER_OUTCOMES,
	CNOTE.CLINICAL_NOTES,
	CNOTE.TIEDENROLLMENT
FROM BEHAVHEALT_LIVE.DBO.PWCOMPLEXCARECLINICALNOTES AS [CNOTE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON CNOTE.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE DOCREVNO = ' 0 '