/*
View Name: Q_COMPLEX_CARE_DELETED_PATHWAY_FORMS_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-complex-care-deleted-pathway-forms-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_COMPLEX_CARE_DELETED_PATHWAY_FORM_DOCSERNOS AS
SELECT ROSTER.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ROSTER.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ROSTER.DOCSERNO,
	ROSTER.TIEDENROLLMENT,
	'Complex Care Roster' AS [FORM_TYPE]
FROM DBO.PWCOMPLEXCAREROSTER AS [ROSTER]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = ROSTER.CLIENTNUMBER
WHERE ROSTER.DOCREVNO = '888'
UNION ALL
SELECT CBENCH.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(CBENCH.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CBENCH.DOCSERNO,
	CBENCH.TIEDENROLLMENT,
	'Clinical BEACN Metrics' AS [FORM_TYPE]
FROM DBO.PWMERCYBEACNBENCHMARKS AS [CBENCH]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = CBENCH.CLIENTNUMBER
WHERE CBENCH.DOCREVNO = '888'
UNION ALL
SELECT PFPDISCHARGE.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(PFPDISCHARGE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	PFPDISCHARGE.DOCSERNO,
	PFPDISCHARGE.TIEDENROLLMENT,
	'PfP Discharge' AS [FORM_TYPE]
FROM DBO.PWPFPDISCHARGE AS [PFPDISCHARGE]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = PFPDISCHARGE.CLIENTNUMBER
WHERE PFPDISCHARGE.DOCREVNO = '888';