/*
View Name: Q_COMPLEX_CARE_ACTIVE_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-complex-care-active-housing-status.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_COMPLEX_CARE_ACTIVE_HOUSING_STATUS AS
WITH [LATESTHOUSINGSTART] AS (
	SELECT CLIENT_NUMBER, 
		MAX(HOUSING_START_DATE) AS [MAXSTARTDATE]
	FROM BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_ALL_HOUSING_STATUS
	GROUP BY CLIENT_NUMBER
),
[LATESTHOUSINGSTATUS] AS (
	SELECT CHOUSE.CLIENT_NUMBER,
		CHOUSE.DOCSERNO,
		CHOUSE.PARENT_DOCSERNO,
		CHOUSE.HOUSING_START_DATE,
		CHOUSE.CLIENT_HOUSING_STATUS,
		CHOUSE.HOUSING_STATUS_INCARCERATED,
		CHOUSE.UNHOUSED_SHELTER,
		CHOUSE.IF_UNHOUSED_EXP,
		CHOUSE.WORRIED_LOSING_HOUSING,
		CHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
		CHOUSE.VISIT_DATE,
		CHOUSE.VISITTM,
		CHOUSE.USERID,
		CHOUSE.DOCREVNO,
		CHOUSE.HOUSING_END_DATE
	FROM BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_ALL_HOUSING_STATUS AS [CHOUSE]
	INNER JOIN LATESTHOUSINGSTART AS [LHS]
		ON CHOUSE.CLIENT_NUMBER = LHS.CLIENT_NUMBER
		AND CHOUSE.HOUSING_START_DATE = LHS.MAXSTARTDATE
	WHERE CHOUSE.PARENT_DOCSERNO IN (
		SELECT CPF.DOCSERNO 
		FROM Q_COMPLEX_CARE_PATHWAY_FORM_DOCSERNOS AS [CPF]
	)
),
[BASELINEHOUSINGSTATUS] AS (
	SELECT CLIENT_NUMBER,
		HOUSING_START_DATE AS [BASELINE_HOUSING_START_DATE],
		HOUSING_END_DATE AS [BASELINE_HOUSING_END_DATE],
		CLIENT_HOUSING_STATUS AS [BASELINE_CLIENT_HOUSING_STATUS]
	FROM (
		SELECT CLIENT_NUMBER,
			HOUSING_START_DATE,
			HOUSING_END_DATE,
			CLIENT_HOUSING_STATUS,
			ROW_NUMBER() OVER (
				PARTITION BY CLIENT_NUMBER
				ORDER BY HOUSING_START_DATE ASC
			) AS [RN]
		FROM BEHAVHEALT_LIVE.DBO.Q_COMPLEX_CARE_ALL_HOUSING_STATUS
	) AS BASELINE_HOUSING_STATUS
	WHERE RN = 1
),
[FINALSELECTION] AS (
	SELECT CLIENT_NUMBER,
		MAX(PARENT_DOCSERNO) AS [MAXPARENTDOCSERNO],
		MAX(DOCSERNO) AS [MAXDOCSERNO]
	FROM LATESTHOUSINGSTATUS
	GROUP BY CLIENT_NUMBER
)
SELECT HS.CLIENT_NUMBER,
		HS.DOCSERNO,
		HS.PARENT_DOCSERNO,
		CAST(HS.VISIT_DATE AS DATE) AS [VISITDT],
		HS.VISITTM,
		HS.USERID,
		CAST(BASELINE.BASELINE_HOUSING_START_DATE AS DATE) AS [BASELINE_HOUSING_START_DATE],
		CAST(BASELINE.BASELINE_HOUSING_END_DATE AS DATE) AS [BASELINE_HOUSING_END_DATE],
		BASELINE.BASELINE_CLIENT_HOUSING_STATUS AS [BASELINE_CLIENT_HOUSING_STATUS],
		CASE 
			WHEN ISNULL(BASELINE.BASELINE_CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
			THEN 1 
			ELSE 0 
		END AS [BASELINE_HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
		CASE 
			WHEN ISNULL(BASELINE.BASELINE_CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
			THEN 1 
			ELSE 0 
		END AS [BASELINE_HOUSING_STATUS_PRECARIOUSLY_HOUSED],
		CASE 
			WHEN ISNULL(BASELINE.BASELINE_CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
			THEN 1 
			ELSE 0 
		END AS [BASELINE_HOUSING_STATUS_STABLY_HOUSED],
		CASE 
			WHEN ISNULL(BASELINE.BASELINE_CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
			THEN 1 
			ELSE 0 
		END AS [BASELINE_HOUSING_STATUS_UNHOUSED],
		CASE 
			WHEN ISNULL(BASELINE.BASELINE_CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
			THEN 1 
			ELSE 0 
		END AS [BASELINE_HOUSING_STATUS_UNKNOWN],
		CAST(HS.HOUSING_START_DATE AS DATE) AS [CURRENT_HOUSING_START_DATE],
		CAST(HS.HOUSING_END_DATE AS DATE) AS [CURRENT_HOUSING_END_DATE],
		HS.CLIENT_HOUSING_STATUS AS [CURRENT_CLIENT_HOUSING_STATUS],
		HS.HOUSING_STATUS_INCARCERATED AS [CURRENT_HOUSING_STATUS_INCARCERATED],
		HS.UNHOUSED_SHELTER AS [CURRENT_UNHOUSED_SHELTER],
		HS.IF_UNHOUSED_EXP AS [CURRENT_IF_UNHOUSED_EXP],
		HS.WORRIED_LOSING_HOUSING AS [CURRENT_WORRIED_LOSING_HOUSING],
		CASE 
			WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
			THEN 1 
			ELSE 0 
		END AS [CURRENT_HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
		CASE 
			WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
			THEN 1 
			ELSE 0 
		END AS [CURRENT_HOUSING_STATUS_PRECARIOUSLY_HOUSED],
		CASE 
			WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
			THEN 1 
			ELSE 0 
		END AS [CURRENT_HOUSING_STATUS_STABLY_HOUSED],
		CASE 
			WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
			THEN 1 
			ELSE 0 
		END AS [CURRENT_HOUSING_STATUS_UNHOUSED],
		CASE 
			WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
			THEN 1 
			ELSE 0 
		END AS [CURRENT_HOUSING_STATUS_UNKNOWN]
FROM LATESTHOUSINGSTATUS AS [HS]
INNER JOIN FINALSELECTION AS [FS]
	ON HS.CLIENT_NUMBER = FS.CLIENT_NUMBER
	AND HS.PARENT_DOCSERNO = FS.MAXPARENTDOCSERNO
	AND HS.DOCSERNO = FS.MAXDOCSERNO
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = HS.CLIENT_NUMBER
LEFT JOIN BASELINEHOUSINGSTATUS AS [BASELINE]
	ON BASELINE.CLIENT_NUMBER = HS.CLIENT_NUMBER
WHERE HS.DOCREVNO = ' 0 ';