/*
View Name: Q_COMPLEX_CARE_CLINICAL_NOTES_REPORT
Category: View Definitions  

See docs/view-definitions/q-complex-care-clinical-notes-report.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

CREATE VIEW DBO.Q_COMPLEX_CARE_CLINICAL_NOTES_REPORT AS
WITH [ROSTER_DATA] AS (
	SELECT CENROLL.CLIENT_NUMBER,
		CENROLL.TIEDENROLLMENT,
		ROSTER.ADDED_COHORT_DATE
	FROM Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS [CENROLL]
	LEFT JOIN Q_COMPLEX_CARE_ROSTER AS [ROSTER]
		ON CENROLL.CLIENT_NUMBER = ROSTER.CLIENT_NUMBER
		AND CENROLL.PWY_FORMS_DOCSERNO = ROSTER.DOCSERNO
	WHERE CENROLL.PWY_EVENT = 'Complex Care Roster'
),
[LATEST_HOUSING_STATUS] AS (
	SELECT CBENCH.CLIENT_NUMBER,
		CBENCH.TIEDENROLLMENT,
		CBENCH.DOCSERNO,
		CHOUSE.PARENT_DOCSERNO,
		CASE
			WHEN CHOUSE.CURRENT_HOUSING_STATUS_INSTITUTIONALLY_HOUSED = '1'
				OR CHOUSE.CURRENT_HOUSING_STATUS_PRECARIOUSLY_HOUSED = '1'
				OR CHOUSE.CURRENT_HOUSING_STATUS_STABLY_HOUSED = '1'
			THEN 'Housed'
			WHEN CHOUSE.CURRENT_HOUSING_STATUS_UNHOUSED = '1'
			THEN 'Unhoused'
			WHEN CHOUSE.CURRENT_HOUSING_STATUS_UNKNOWN = '1'
			THEN 'Unknown'
			WHEN CHOUSE.CURRENT_HOUSING_STATUS_INSTITUTIONALLY_HOUSED IS NULL
				AND CHOUSE.CURRENT_HOUSING_STATUS_PRECARIOUSLY_HOUSED IS NULL
				AND CHOUSE.CURRENT_HOUSING_STATUS_STABLY_HOUSED IS NULL
				AND CHOUSE.CURRENT_HOUSING_STATUS_UNHOUSED IS NULL
				AND CHOUSE.CURRENT_HOUSING_STATUS_UNKNOWN IS NULL
			THEN 'Unknown'
			ELSE 'Unhoused'
		END AS [CURRENT_HOUSING_STATUS]
	FROM Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCH]
	LEFT JOIN Q_COMPLEX_CARE_ACTIVE_HOUSING_STATUS AS [CHOUSE]
		ON CBENCH.CLIENT_NUMBER = CHOUSE.CLIENT_NUMBER
		AND CBENCH.DOCSERNO = CHOUSE.PARENT_DOCSERNO
),
[LATEST_PAYOR_SOURCE] AS (
	SELECT CBENCH.CLIENT_NUMBER,
		CBENCH.TIEDENROLLMENT,
		CBENCH.DOCSERNO,
		CPAY.PARENT_DOCSERNO,
		CASE
			WHEN CPAY.CURRENT_PAYOR_SOURCE_UNINSURED = '1'
			THEN 'Uninsured'
			WHEN CPAY.CURRENT_PAYOR_SOURCE_DUAL_ELIGIBLE = '1'
				OR CPAY.CURRENT_PAYOR_SOURCE_MANAGED_MEDICAID = '1'
				OR CPAY.CURRENT_PAYOR_SOURCE_MEDICAID = '1'
				OR CPAY.CURRENT_PAYOR_SOURCE_MEDICAID_IN_PROGRESS = '1'
				OR CPAY.CURRENT_PAYOR_SOURCE_MEDICAID_CHP = '1'
				OR CPAY.CURRENT_PAYOR_SOURCE_MEDICARE = '1'
				OR CPAY.CURRENT_PAYOR_SOURCE_PRIVATE_INSURANCE = '1'
				OR CPAY.CURRENT_PAYOR_SOURCE_VA_BENEFITS = '1'
			THEN 'Insured'
			WHEN CPAY.CURRENT_PAYOR_SOURCE_UNKNOWN_REFUSED = '1'
			THEN 'Unknown'
			WHEN CPAY.CURRENT_PAYOR_SOURCE_UNINSURED IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_DUAL_ELIGIBLE IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_MANAGED_MEDICAID IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_MEDICAID IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_MEDICAID_IN_PROGRESS IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_MEDICAID_CHP IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_MEDICARE IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_PRIVATE_INSURANCE IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_VA_BENEFITS IS NULL
				AND CPAY.CURRENT_PAYOR_SOURCE_UNKNOWN_REFUSED IS NULL
			THEN 'Unknown'
		END AS [CURRENT_PAYOR_SOURCE]
	FROM Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCH]
	LEFT JOIN Q_COMPLEX_CARE_ACTIVE_PAYOR_SOURCE AS [CPAY]
		ON CBENCH.CLIENT_NUMBER = CPAY.CLIENT_NUMBER
		AND CBENCH.DOCSERNO = CPAY.PARENT_DOCSERNO
),
[BENCHMARKS_DATA] AS (
	SELECT CENROLL.CLIENT_NUMBER,
		CENROLL.TIEDENROLLMENT,
		CBENCHMARKS.DOCSERNO,
		CBENCHMARKS.ENROLLMENT_DATE,
		CBENCHMARKS.COMPLETE_ADMISSION_SERVICE_DATE AS [ADMISSION_DATE],
		CBENCHMARKS.TREATMENT_TEAM_ASSIGNMENT_DATE
	FROM Q_COMPLEX_CARE_PATHCLIENT_ENROLLMENTS AS [CENROLL]
	LEFT JOIN Q_COMPLEX_CARE_MERCY_BEACN_BENCHMARKS AS [CBENCHMARKS]
		ON CENROLL.CLIENT_NUMBER = CBENCHMARKS.CLIENT_NUMBER
		AND CENROLL.PWY_FORMS_DOCSERNO = CBENCHMARKS.DOCSERNO
	WHERE CENROLL.PWY_EVENT = 'Clinical BEACN Metrics'
),
[CLINICAL_NOTES] AS (
	SELECT CNOTES.CLIENT_NUMBER,
		CNOTES.PARENT_DOCSERNO,
		CNOTES.PATHWAY_DATE,
		CNOTES.MEETING_DATE,
		CNOTES.DECISION,
		CNOTES.COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE,
		CNOTES.COMPLEX_CARE_REASONS_INELIGIBLE,
		CNOTES.COMPLEX_CARE_OTHER_OUTCOMES,
		CNOTES.CLINICAL_NOTES,
		CNOTES.TIEDENROLLMENT
	FROM Q_COMPLEX_CARE_CLINICAL_NOTES AS [CNOTES]
)
SELECT C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	C.BIRTH_DATE AS [DOB],
	C.MRN_MERCY,
	CNOTES.MEETING_DATE AS [DATE OF CLINICAL NOTE],
	CNOTES.DECISION AS [CLINICAL_COMMITTEE_DECISION],
	CNOTES.COMPLEX_CARE_CLINICAL_COMMITTEE_RATIONALE,
	CNOTES.COMPLEX_CARE_REASONS_INELIGIBLE,
	CNOTES.COMPLEX_CARE_OTHER_OUTCOMES,
	ROSTER_DATA.ADDED_COHORT_DATE,
	CBENCH.ENROLLMENT_DATE,
	CBENCH.ADMISSION_DATE,
	CBENCH.TREATMENT_TEAM_ASSIGNMENT_DATE,
	C.STREET AS [ADDRESS],
	C.ZIP_CODE,
	CHOUSE.CURRENT_HOUSING_STATUS,
	CPAY.[CURRENT_PAYOR_SOURCE],
	CNOTES.CLINICAL_NOTES AS [CLINICAL_COMMITTEE_NOTES]
FROM BENCHMARKS_DATA AS [CBENCH]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = CBENCH.CLIENT_NUMBER
LEFT JOIN ROSTER_DATA
	ON C.CLIENT_NUMBER = ROSTER_DATA.CLIENT_NUMBER
	AND CBENCH.TIEDENROLLMENT = ROSTER_DATA.TIEDENROLLMENT
LEFT JOIN LATEST_HOUSING_STATUS AS [CHOUSE]
	ON C.CLIENT_NUMBER = CHOUSE.CLIENT_NUMBER
	AND CBENCH.DOCSERNO = CHOUSE.PARENT_DOCSERNO
LEFT JOIN LATEST_PAYOR_SOURCE AS [CPAY]
	ON C.CLIENT_NUMBER = CPAY.CLIENT_NUMBER
	AND CBENCH.DOCSERNO = CPAY.PARENT_DOCSERNO
LEFT JOIN CLINICAL_NOTES AS [CNOTES]
	ON C.CLIENT_NUMBER = CNOTES.CLIENT_NUMBER
	AND CBENCH.DOCSERNO = CNOTES.PARENT_DOCSERNO