/*
View Name: Q_DUPLICATE_ENROLLMENTS_WITH_PROGRAM
Category: View Definitions

See docs/views/q-duplicate-enrollments-with-program.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

CREATE VIEW .DBO.Q_DUPLICATE_ENROLLMENTS_WITH_PROGRAM AS
WITH [DUPLICATE_ENROLLMENT_GROUPS] AS (
	SELECT 
		CLIENT_NUMBER,
		ENROLLMENT_STARTING_DATE
	FROM Q_PROVIDERPLACEMENT_BHN
	GROUP BY CLIENT_NUMBER, ENROLLMENT_STARTING_DATE
	HAVING COUNT(*) > 1
)

SELECT 
	PP.CLIENT_NUMBER,
	PP.ENROLLMENT_STARTING_DATE,
	PP.PROGRAM_DESCRIPTION,
	PP.DOCSERNO AS [ENROLLMENT_DOCSERNO],
	PP.USERID,
	'Duplicate Start Date' AS [ENROLLMENT_ISSUE]
FROM Q_PROVIDERPLACEMENT_BHN AS [PP]
INNER JOIN DUPLICATE_ENROLLMENT_GROUPS AS [DEG]
	ON PP.CLIENT_NUMBER = DEG.CLIENT_NUMBER
	AND PP.ENROLLMENT_STARTING_DATE = DEG.ENROLLMENT_STARTING_DATE;