/*
View Name: Q_EPICC_SUPPORT_SERVICES_TRACKER
Category: View Definitions  

See docs/view-definitions/q-epicc-support-services-tracker.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_EPICC_SUPPORT_SERVICES_TRACKER AS
SELECT EPICC_SS_TRACKER.ID,
	EPICC_SS_TRACKER.DOCSERNO,
	CAST(EPICC_SS_TRACKER.VISITDT AS DATE) AS [VISITDT],
	EPICC_SS_TRACKER.VISITTM,
	EPICC_SS_TRACKER.USERID,
	EPICC_SS_TRACKER.PARENTDOCSERNO,
	EPICC_SS_TRACKER.CLIENTNUMBER,
	CAST(EPICC_SS_TRACKER.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EPICC_SS_TRACKER.SS_BEHAVIORAL_HEALTH,
	EPICC_SS_TRACKER.SS_PHYSICAL_HEALTH,
	EPICC_SS_TRACKER.SS_SOCIAL_SERVICES,
	EPICC_SS_TRACKER.SS_MATERNAL_HEALTH,
	EPICC_SS_TRACKER.SS_HOUSING,
	EPICC_SS_TRACKER.SS_SUPPORTIVE_SERVICES,
	EPICC_SS_TRACKER.SS_TYPE_OTHER,
	EPICC_SS_TRACKER.BH_INDIVIDUAL_PEER_SUPPORT,
	EPICC_SS_TRACKER.BH_GROUP_PEER_SUPPORT,
	EPICC_SS_TRACKER.BH_SUBSTANCE_USE_SERVICES,
	EPICC_SS_TRACKER.BH_CMHC_SERVICES,
	EPICC_SS_TRACKER.BH_OTHER,
	EPICC_SS_TRACKER.PH_PRIMARY_CARE,
	EPICC_SS_TRACKER.PH_DENTAL_CARE,
	EPICC_SS_TRACKER.PH_OTHER,
	EPICC_SS_TRACKER.SS_FOOD,
	EPICC_SS_TRACKER.SS_CLOTHING,
	EPICC_SS_TRACKER.SS_HYGIENE,
	EPICC_SS_TRACKER.SS_UTILITY_ASSISTANCE,
	EPICC_SS_TRACKER.SS_CHILD_CARE,
	EPICC_SS_TRACKER.SS_DEVELOPMENTAL_DISABILITY,
	EPICC_SS_TRACKER.SS_DOMESTIC_VIOLENCE,
	EPICC_SS_TRACKER.SS_OTHER,
	EPICC_SS_TRACKER.MH_PREGNANCY_RESOURCES,
	EPICC_SS_TRACKER.MH_PRE_POST_NATAL_CARE,
	EPICC_SS_TRACKER.MH_OTHER,
	EPICC_SS_TRACKER.H_SHELTER_HOUSING,
	EPICC_SS_TRACKER.H_RECOVERY_HOUSING,
	EPICC_SS_TRACKER.H_RESPITE_HOUSING,
	EPICC_SS_TRACKER.H_TRANSITIONAL_HOUSING,
	EPICC_SS_TRACKER.H_HOMELESS_SERVICES,
	EPICC_SS_TRACKER.H_OTHER,
	EPICC_SS_TRACKER.SUPPORT_SERVICES_REFERRAL_TYPE,
	EPICC_SS_TRACKER.SUPPORT_SERVICE_OTHER_TYPE,
	EPICC_SS_TRACKER.SUPPORT_SERVICE_OTHER_AGENCY AS [SUPPORT_SERVICE_OTHER_AGENCY_CODE],
	SUPPORT_SERVICE_OTHER_ESSA.DESCRIPTION AS [SUPPORT_SERVICE_OTHER_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.SUPPORT_SERVICE_OTHER_AGENCY_OTHER,
	EPICC_SS_TRACKER.BEHAVIORAL_HEALTH_TYPE,
	EPICC_SS_TRACKER.BEHAVIORAL_HEALTH_TYPE_OTHER,
	EPICC_SS_TRACKER.CMHC_SERVICES_AGENCY AS [CMHC_SERVICES_AGENCY_CODE],
	CMHC_ESSA.DESCRIPTION AS [CMHC_SERVICES_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.CMHC_SERVICES_AGENCY_OTHER,
	EPICC_SS_TRACKER.GROUP_PEER_SUPPORT_AGENCY AS [GROUP_PEER_SUPPORT_AGENCY_CODE],
	GROUP_PEER_ESSA.DESCRIPTION AS [GROUP_PEER_SUPPORT_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.GROUP_PEER_SUPPORT_AGENCY_OTHER,
	EPICC_SS_TRACKER.INDIVIDUAL_PEER_SUPPORT_AGENCY AS [INDIVIDUAL_PEER_SUPPORT_AGENCY_CODE],
	IND_ESSA.DESCRIPTION AS [INDIVIDUAL_PEER_SUPPORT_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.INDIVIDUAL_PEER_SUPPORT_AGENCY_OTHER,
	EPICC_SS_TRACKER.SUBSTANCE_USE_SERVICES_AGENCY AS [SUBSTANCE_USE_SERVICES_AGENCY_CODE],
	SUBSTANCE_USE_ESSA.DESCRIPTION AS [SUBSTANCE_USE_SERVICES_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.SUBSTANCE_USE_SERVICES_AGENCY_OTHER,
	EPICC_SS_TRACKER.BEHAVIORAL_HEALTH_OTHER_AGENCY AS [BEHAVIORAL_HEALTH_OTHER_AGENCY_CODE],
	BEHAVIORAL_HEALTH_OTHER_ESSA.DESCRIPTION AS [BEHAVIORAL_HEALTH_OTHER_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.BEHAVIORAL_HEALTH_OTHER_AGENCY_OTHER,
	EPICC_SS_TRACKER.PHYSICAL_HEALTH_TYPE,
	EPICC_SS_TRACKER.PHYSICAL_HEALTH_TYPE_OTHER,
	EPICC_SS_TRACKER.PRIMARY_CARE,
	EPICC_SS_TRACKER.PRIMARY_CARE_OTHER,
	EPICC_SS_TRACKER.DENTAL_CARE,
	EPICC_SS_TRACKER.DENTAL_CARE_OTHER,
	EPICC_SS_TRACKER.PH_OTHER_AGENCY AS [PH_OTHER_AGENCY_CODE],
	PH_OTHER_ESSA.DESCRIPTION AS [PH_OTHER_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.PH_OTHER_AGENCY_OTHER,
	EPICC_SS_TRACKER.SOCIAL_SERVICES_TYPE,
	EPICC_SS_TRACKER.SOCIAL_SERVICES_TYPE_OTHER,
	EPICC_SS_TRACKER.FOOD_AGENCY AS [FOOD_AGENCY_CODE],
	FOOD_ESSA.DESCRIPTION AS [FOOD_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.FOOD_AGENCY_OTHER,
	EPICC_SS_TRACKER.CLOTHING_AGENCY AS [CLOTHING_AGENCY_CODE],
	CLOTHING_ESSA.DESCRIPTION AS [CLOTHING_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.CLOTHING_AGENCY_OTHER,
	EPICC_SS_TRACKER.HYGIENE_AGENCY AS [HYGIENE_AGENCY_CODE],
	HYGIENE_ESSA.DESCRIPTION AS [HYGIENE_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.HYGIENE_AGENCY_OTHER,
	EPICC_SS_TRACKER.UTILITY_ASSISTANCE_AGENCY AS [UTILITY_ASSISTANCE_AGENCY_CODE],
	UTILITY_ASSISTANCE_ESSA.DESCRIPTION AS [UTILITY_ASSISTANCE_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.UTILITY_ASSISTANCE_AGENCY_OTHER,
	EPICC_SS_TRACKER.CHILD_CARE_AGENCY AS [CHILD_CARE_AGENCY_CODE],
	CHILD_CARE_ESSA.DESCRIPTION AS [CHILD_CARE_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.CHILD_CARE_AGENCY_OTHER,
	EPICC_SS_TRACKER.DEVELOPMENTAL_DISABILITY_AGENCY AS [DEVELOPMENTAL_DISABILITY_AGENCY_CODE],
	DEVELOPMENTAL_DISABILITY_ESSA.DESCRIPTION AS [DEVELOPMENTAL_DISABILITY_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.DEVELOPMENTAL_DISABILITY_AGENCY_OTHER,
	EPICC_SS_TRACKER.DOMESTIC_VIOLENCE_AGENCY AS [DOMESTIC_VIOLENCE_AGENCY_CODE],
	DOMESTIC_VIOLENCE_ESSA.DESCRIPTION AS [DOMESTIC_VIOLENCE_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.DOMESTIC_VIOLENCE_AGENCY_OTHER,
	EPICC_SS_TRACKER.SS_OTHER_AGENCY AS [SS_OTHER_AGENCY_CODE],
	SS_OTHER_ESSA.DESCRIPTION AS [SS_OTHER_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.SS_OTHER_AGENCY_OTHER,
	EPICC_SS_TRACKER.MATERNAL_HEALTH_TYPE,
	EPICC_SS_TRACKER.MATERNAL_HEALTH_TYPE_OTHER,
	EPICC_SS_TRACKER.PREGNANCY_RESOURCES_AGENCY AS [PREGNANCY_RESOURCES_AGENCY_CODE],
	PREGNANCY_RESOURCES_ESSA.DESCRIPTION AS [PREGNANCY_RESOURCES_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.PREGNANCY_RESOURCES_AGENCY_OTHER,
	EPICC_SS_TRACKER.PRE_POST_NATAL_CARE_AGENCY AS [PRE_POST_NATAL_CARE_AGENCY_CODE],
	PRE_POST_NATAL_CARE_ESSA.DESCRIPTION AS [PRE_POST_NATAL_CARE_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.PRE_POST_NATAL_CARE_AGENCY_OTHER,
	EPICC_SS_TRACKER.MH_OTHER_AGENCY AS [MH_OTHER_AGENCY_CODE],
	MH_OTHER_ESSA.DESCRIPTION AS [MH_OTHER_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.MH_OTHER_AGENCY_OTHER,
	EPICC_SS_TRACKER.HOUSING_TYPE,
	EPICC_SS_TRACKER.HOUSING_TYPE_OTHER,
	EPICC_SS_TRACKER.SHELTER_HOUSING_AGENCY AS [SHELTER_HOUSING_AGENCY_CODE],
	SHELTER_HOUSING_ESSA.DESCRIPTION AS [SHELTER_HOUSING_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.SHELTER_HOUSING_AGENCY_OTHER,
	EPICC_SS_TRACKER.RECOVERY_HOUSING_AGENCY AS [RECOVERY_HOUSING_AGENCY_CODE],
	RECOV_ESSA.DESCRIPTION AS [RECOVERY_HOUSING_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.RECOVERY_HOUSING_AGENCY_OTHER,
	EPICC_SS_TRACKER.RESPITE_HOUSING_AGENCY AS [RESPITE_HOUSING_AGENCY_CODE],
	RESPITE_ESSA.DESCRIPTION AS [RESPITE_HOUSING_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.RESPITE_HOUSING_AGENCY_OTHER,
	EPICC_SS_TRACKER.TRANSITIONAL_HOUSING_AGENCY AS [TRANSITIONAL_HOUSING_AGENCY_CODE],
	TRANS_HOUSING_ESSA.DESCRIPTION AS [TRANSITIONAL_HOUSING_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.TRANSITIONAL_HOUSING_AGENCY_OTHER,
	EPICC_SS_TRACKER.HOMELESS_SERVICES_AGENCY AS [HOMELESS_SERVICES_AGENCY_CODE],
	HOMELESS_ESSA.DESCRIPTION AS [HOMELESS_SERVICES_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.HOMELESS_SERVICES_AGENCY_OTHER,
	EPICC_SS_TRACKER.HOUSING_OTHER_AGENCY AS [HOUSING_OTHER_AGENCY_CODE],
	HOUS_OTH_ESSA.DESCRIPTION AS [HOUSING_OTHER_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.HOUSING_OTHER_AGENCY_OTHER,
	EPICC_SS_TRACKER.SUPPORTIVE_SERVICES_TYPE,
	EPICC_SS_TRACKER.SUPPORTIVE_SERVICES_AGENCY AS [SUPPORTIVE_SERVICES_AGENCY_CODE],
	SSA_ESSA.DESCRIPTION AS [SUPPORTIVE_SERVICES_AGENCY_DESCRIPTION],
	EPICC_SS_TRACKER.SUPPORTIVE_SERVICES_AGENCY_OTHER,
	EPICC_SS_TRACKER.SST_NOTES
FROM BEHAVHEALT_LIVE.DBO.PWEPICCSUPPORTSERVICESTRACKER AS [EPICC_SS_TRACKER]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON EPICC_SS_TRACKER.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [SUPPORT_SERVICE_OTHER_ESSA]
	ON EPICC_SS_TRACKER.SUPPORT_SERVICE_OTHER_AGENCY = SUPPORT_SERVICE_OTHER_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [CMHC_ESSA]
	ON EPICC_SS_TRACKER.CMHC_SERVICES_AGENCY = CMHC_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [GROUP_PEER_ESSA]
	ON EPICC_SS_TRACKER.GROUP_PEER_SUPPORT_AGENCY = GROUP_PEER_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [IND_ESSA]
	ON EPICC_SS_TRACKER.INDIVIDUAL_PEER_SUPPORT_AGENCY = IND_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [SUBSTANCE_USE_ESSA]
	ON EPICC_SS_TRACKER.SUBSTANCE_USE_SERVICES_AGENCY = SUBSTANCE_USE_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [BEHAVIORAL_HEALTH_OTHER_ESSA]
	ON EPICC_SS_TRACKER.BEHAVIORAL_HEALTH_OTHER_AGENCY = BEHAVIORAL_HEALTH_OTHER_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [PH_OTHER_ESSA]
	ON EPICC_SS_TRACKER.PH_OTHER_AGENCY = PH_OTHER_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [FOOD_ESSA]
	ON EPICC_SS_TRACKER.FOOD_AGENCY = FOOD_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [CLOTHING_ESSA]
	ON EPICC_SS_TRACKER.CLOTHING_AGENCY = CLOTHING_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [HYGIENE_ESSA]
	ON EPICC_SS_TRACKER.HYGIENE_AGENCY = HYGIENE_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [UTILITY_ASSISTANCE_ESSA]
	ON EPICC_SS_TRACKER.UTILITY_ASSISTANCE_AGENCY = UTILITY_ASSISTANCE_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [CHILD_CARE_ESSA]
	ON EPICC_SS_TRACKER.CHILD_CARE_AGENCY = CHILD_CARE_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [DEVELOPMENTAL_DISABILITY_ESSA]
	ON EPICC_SS_TRACKER.DEVELOPMENTAL_DISABILITY_AGENCY = DEVELOPMENTAL_DISABILITY_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [DOMESTIC_VIOLENCE_ESSA]
	ON EPICC_SS_TRACKER.DOMESTIC_VIOLENCE_AGENCY = DOMESTIC_VIOLENCE_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [SS_OTHER_ESSA]
	ON EPICC_SS_TRACKER.SS_OTHER_AGENCY = SS_OTHER_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [PREGNANCY_RESOURCES_ESSA]
	ON EPICC_SS_TRACKER.PREGNANCY_RESOURCES_AGENCY = PREGNANCY_RESOURCES_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [PRE_POST_NATAL_CARE_ESSA]
	ON EPICC_SS_TRACKER.PRE_POST_NATAL_CARE_AGENCY = PRE_POST_NATAL_CARE_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [MH_OTHER_ESSA]
	ON EPICC_SS_TRACKER.MH_OTHER_AGENCY = MH_OTHER_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [SHELTER_HOUSING_ESSA]
	ON EPICC_SS_TRACKER.SHELTER_HOUSING_AGENCY = SHELTER_HOUSING_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [RECOV_ESSA]
	ON EPICC_SS_TRACKER.RECOVERY_HOUSING_AGENCY = RECOV_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [RESPITE_ESSA]
	ON EPICC_SS_TRACKER.RESPITE_HOUSING_AGENCY = RESPITE_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [TRANS_HOUSING_ESSA]
	ON EPICC_SS_TRACKER.TRANSITIONAL_HOUSING_AGENCY = TRANS_HOUSING_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [HOMELESS_ESSA]
	ON EPICC_SS_TRACKER.HOMELESS_SERVICES_AGENCY = HOMELESS_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [HOUS_OTH_ESSA]
	ON EPICC_SS_TRACKER.BEHAVIORAL_HEALTH_OTHER_AGENCY = HOUS_OTH_ESSA.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_SUPPORT_SERVICE_AGENCIES AS [SSA_ESSA]
	ON EPICC_SS_TRACKER.SUPPORTIVE_SERVICES_AGENCY = SSA_ESSA.CODE
WHERE EPICC_SS_TRACKER.DOCREVNO = ' 0 '