/*
View Name: Q_EPICC_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-epicc-all-payor-source.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .dbo.Q_EPICC_ALL_PAYOR_SOURCE AS
SELECT EPAY.ID,
	EPAY.DOCSERNO,
	EPAY.DOCREVNO,
	CAST(EPAY.VISITDT AS DATE) AS [VISITDT],
	EPAY.VISITTM,
	EPAY.USERID,
	COALESCE(EIC.PARENTDOCSERNO, EPAY.PARENTDOCSERNO) AS [PARENTDOCSERNO],
	EPF.FORM_TYPE,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(EPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EPAY.PAYOR_SOURCE,
	EPAY.MANAGED_MEDICAID_PROVIDER,
	EPAY.PRIVATE_INSURANCE_PROVIDER,
	CAST(EPAY.PAYOR_SOURCE_START_DATE AS DATE) AS PAYOR_SOURCE_START_DATE,
	CAST(EPAY.PAYOR_SOURCE_END_DATE AS DATE) AS PAYOR_SOURCE_END_DATE
FROM BEHAVHEALT_LIVE.DBO.PWPAYORSOURCE AS [EPAY]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON EPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN PWEPICCINITIALCONTACT AS [EIC]
	ON EPAY.CLIENTNUMBER = EIC.CLIENTNUMBER
	AND EPAY.PATHWAY_DATE = EIC.PATHWAY_DATE
	AND EPAY.USERID LIKE 'import%'
LEFT JOIN Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [EPF]
	ON COALESCE(EPAY.PARENTDOCSERNO, EIC.DOCSERNO) = EPF.DOCSERNO
WHERE EPAY.DOCREVNO = ' 0 '
	AND COALESCE(EPAY.PARENTDOCSERNO, EIC.DOCSERNO) IN (
			SELECT EPF.DOCSERNO 
			FROM Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [EPF]
	);