/*
View Name: Q_EPICC_TWO_WEEK  
Category: View Definitions  

See docs/view-definitions/q-epicc-two-week.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_TWO_WEEK AS
SELECT ETWOW.ID,
	ETWOW.DOCSERNO,
	ETWOW.TIEDENROLLMENT,
	CAST(ETWOW.VISITDT AS DATE) AS [VISIT_DATE],
	ETWOW.VISITTM AS [VISIT_TIME],
	ETWOW.USERID,
	ETWOW.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'EPICC 2 Week' AS [EVENT_NAME],
	ETWOW.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST (ETWOW.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	TREATMENT_PATH_TWO_WEEK,
	TREATMENT_PATH_TWO_WEEK_UNABLE_TO_CONTACT,
	RC_ONLY_CLIENT_ATTEND_FIRST_APPT_COACH_TWO_WEEK,
	CAST(RC_ONLY_LAST_DATE_COMMUNICATION_TWO_WEEK AS DATE) AS [RC_ONLY_LAST_DATE_COMMUNICATION_TWO_WEEK],
	INTAKE_CONDUCTED_APPT_DATE_TWO_WEEK,
	MAT_PRESCRIBED_PHYSICIAN_APPT_TWO_WEEK,
	MAT_PRESCRIBED_PHYSICIAN_TWO_WEEK_UNABLE_TO_CONTACT,
	WHAT_MAT_PHYSICIAN_APPT_TWO_WEEK AS [WHAT_MAT_PHYSICIAN_APPT_TWOW_CODE],
	MAT.DESCRIPTION AS [WHAT_MAT_PHYSICIAN_APPT_TWOW_DESCRIPTION],
	WHAT_MAT_PHYSICIAN_APPT_TWO_WEEK_UNABLE_TO_CONTACT AS [WHAT_MAT_PHYSICIAN_APPT_TWOW_UTC_CODE],
	MAT_UTC.DESCRIPTION AS [WHAT_MAT_PHYSICIAN_APPT_TWOW_UTC_DESCRIPTION],
	PROGRAM_PARTICIPATION_TWO_WEEK AS [PROGRAM_PARTICIPATION_TWOW_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_TWOW_DESCRIPTION],
	REASON_NOT_PARTICIPATING_TWO_WEEK,
	WHY_NOT_MEET_PROG_ELIGIBILITY_TWO_WEEK,
	REASON_NOT_ATTENDING_SUD_TX_TWO_WEEK,
	OTHER_REASON_NOT_ATTENDING_SUD_TX_TWO_WEEK,
	ATTENDING_SUD_TX_VERIFY_TWO_WEEK,
	TRANSFER_TYPE_TWO_WEEK,
	IF_TRANSFER_WHAT_REGION_TWO_WEEK,
	IF_TRANSFER_CONTACT_TRANSFER_REGION_SUCCESS_TWO_WEEK,
	CLIENT_STATUS_TWO_WEEK,
	CAST(DATE_TRANSFERRED_REENGAGEMENT_SPECIALIST_TWO_WEEK AS DATE) AS [DATE_TRANSFERRED_REENGAGEMENT_SPECIALIST_TWO_WEEK],
	PREG_POST_PART_TWO_WEEK
FROM DBO.PWEPICC2WEEKFOLLOWUP AS [ETWOW]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON ETWOW.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON ETWOW.PROGRAM_PARTICIPATION_TWO_WEEK = EPP.CODE
LEFT JOIN DBO.EPICC_TYPES_MAT AS [MAT]
	ON ETWOW.WHAT_MAT_PHYSICIAN_APPT_TWO_WEEK = MAT.CODE
LEFT JOIN DBO.EPICC_TYPES_MAT AS [MAT_UTC]
	ON ETWOW.WHAT_MAT_PHYSICIAN_APPT_TWO_WEEK_UNABLE_TO_CONTACT = MAT_UTC.CODE
WHERE ETWOW.DOCREVNO = ' 0 ';