/*
View Name: Q_EPICC_REENGAGEMENT  
Category: View Definitions  

See docs/view-definitions/q-epicc-reengagement.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_EPICC_REENGAGEMENT AS
SELECT REENGAGE.ID,
	REENGAGE.DOCSERNO,
	REENGAGE.TIEDENROLLMENT,
	CAST(REENGAGE.VISITDT AS DATE) AS [VISITDT],
	REENGAGE.VISITTM,
	REENGAGE.USERID,
	REENGAGE.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(REENGAGE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	REENGAGE.REENGAGEMENT_SPECIALIST AS [REENGAGEMENT_SPECIALIST_EMPLOYEE_NUMBER],
	HR.FIRSTNAME + '-' + HR.LASTNAME AS [REENGAGEMENT_SPECIALIST_DESCRIPTION],
	REENGAGE.FOLLOW_UP_FORM_REENGAGEMENT,
	REENGAGE.DID_CLIENT_REENGAGE,
	REENGAGE.EFFORTS_TO_ENGAGE_AGENCY_VISIT,
	REENGAGE.EFFORTS_TO_ENGAGE_COMMUNITY_VISIT,
	REENGAGE.EFFORTS_TO_ENGAGE_LETTER,
	REENGAGE.EFFORTS_TO_ENGAGE_PHONE,
	REENGAGE.EFFORTS_TO_ENGAGE_OTHER,
	REENGAGE.NOTES_REENGAGEMENT,
	REENGAGE.STATUS_REENGAGEMENT
FROM BEHAVHEALT_LIVE.DBO.PWEPICCREENGAGEMENTFORM AS [REENGAGE]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = REENGAGE.CLIENTNUMBER
LEFT JOIN Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER= REENGAGE.REENGAGEMENT_SPECIALIST
WHERE REENGAGE.DOCREVNO = ' 0 ';