/*
View Name: Q_EPICC_PATHWAY_FORMS_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-epicc-pathway-forms-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_PATHWAY_FORM_DOCSERNOS AS
SELECT EREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREF.DOCSERNO,
	NULL AS [TREATMENT_PATH],
	'EPICC Referral' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWEPICCREFERRAL AS [EREF]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = EREF.CLIENTNUMBER
WHERE EREF.DOCREVNO = ' 0 '
UNION ALL
SELECT EIC.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EIC.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EIC.DOCSERNO,
	EIC.TREATMENT_PATH_IC AS [TREATMENT_PATH],
	'EPICC Initial Contact' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWEPICCINITIALCONTACT AS [EIC]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = EIC.CLIENTNUMBER
WHERE EIC.DOCREVNO = ' 0 '
UNION ALL
SELECT ETWOW.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ETWOW.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ETWOW.DOCSERNO,
	ETWOW.TREATMENT_PATH_TWO_WEEK AS [TREATMENT_PATH],
	'EPICC 2-Week Follow-Up' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWEPICC2WEEKFOLLOWUP AS [ETWOW]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = ETWOW.CLIENTNUMBER
WHERE ETWOW.DOCREVNO = ' 0 '
UNION ALL
SELECT ETHIRTYD.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ETHIRTYD.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ETHIRTYD.DOCSERNO,
	ETHIRTYD.TREATMENT_PATH_THIRTY_DAY AS [TREATMENT_PATH],
	'EPICC 30-Day Follow-Up' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWEPICC30DAYFOLLOWUP AS [ETHIRTYD]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = ETHIRTYD.CLIENTNUMBER
WHERE ETHIRTYD.DOCREVNO = ' 0 '
UNION ALL
SELECT ETHREEM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ETHREEM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ETHREEM.DOCSERNO,
	ETHREEM.TREATMENT_PATH_THREE_MONTH AS [TREATMENT_PATH],
	'EPICC 3-Month Follow-Up' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWEPICC3MONTHFOLLOWUP AS [ETHREEM]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = ETHREEM.CLIENTNUMBER
WHERE ETHREEM.DOCREVNO = ' 0 '
UNION ALL
SELECT ESIXM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ESIXM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ESIXM.DOCSERNO,
	ESIXM.TREATMENT_PATH_SIX_MONTH AS [TREATMENT_PATH],
	'EPICC 6-Month Follow-Up' AS [FORM_TYPE]
FROM BEHAVHEALT_LIVE.DBO.PWEPICC6MONTHFOLLOWUP AS [ESIXM]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = ESIXM.CLIENTNUMBER
WHERE ESIXM.DOCREVNO = ' 0 ';