/*
View Name: Q_EPICC_LATEST_SU_TX_AGENCY  
Category: View Definitions  

See docs/view-definitions/q-epicc-latest-su-tx-agency.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_LATEST_SU_TX_AGENCY AS
WITH [FORM_MATCH] AS (
	SELECT 
		SUTX.ID,
		COALESCE(
			EIC.DOCSERNO,
			ETWOW.DOCSERNO,
			ETHIRTYD.DOCSERNO,
			ETHREEM.DOCSERNO,
			ESIXM.DOCSERNO
		) AS [INFERRED_DOCSERNO]
	FROM PWSUBROADTREATMENTAGENCY AS [SUTX]
	LEFT JOIN Q_EPICC_IC AS [EIC]
		ON SUTX.CLIENTNUMBER = EIC.CLIENT_NUMBER
		AND SUTX.START_DATE = EIC.PATHWAY_DATE
	LEFT JOIN Q_EPICC_TWO_WEEK AS [ETWOW]
		ON SUTX.CLIENTNUMBER = ETWOW.CLIENT_NUMBER
		AND SUTX.START_DATE = ETWOW.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THIRTY_DAY AS [ETHIRTYD]
		ON SUTX.CLIENTNUMBER = ETHIRTYD.CLIENT_NUMBER
		AND SUTX.START_DATE = ETHIRTYD.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THREE_MONTH AS [ETHREEM]
		ON SUTX.CLIENTNUMBER = ETHREEM.CLIENT_NUMBER
		AND SUTX.START_DATE = ETHREEM.PATHWAY_DATE
	LEFT JOIN Q_EPICC_SIX_MONTH AS [ESIXM]
		ON SUTX.CLIENTNUMBER = ESIXM.CLIENT_NUMBER
		AND SUTX.START_DATE = ESIXM.PATHWAY_DATE
),
[INFERRED_SUTX] AS (
	SELECT 
		SUTX.*,
		CASE 
			WHEN (SUTX.PARENTDOCSERNO IS NULL OR LTRIM(RTRIM(SUTX.PARENTDOCSERNO)) = '')
				 AND SUTX.USERID LIKE 'import%' 
				 AND FM.INFERRED_DOCSERNO IS NOT NULL
			THEN FM.INFERRED_DOCSERNO
			ELSE SUTX.PARENTDOCSERNO
		END AS [RESOLVED_PARENTDOCSERNO]
	FROM PWSUBROADTREATMENTAGENCY AS [SUTX]
	LEFT JOIN FORM_MATCH AS [FM]
		ON SUTX.ID = FM.ID
),
[LATEST_VISIT_DATE] AS (
	SELECT CLIENTNUMBER,
		MAX(VISITDT) AS [MAXVISITDATE]
	FROM INFERRED_SUTX
	WHERE DOCREVNO = ' 0 '
	GROUP BY CLIENTNUMBER
),
[LATEST_SUTX_RECORD] AS (
	SELECT 
		S.CLIENTNUMBER,
		S.DOCSERNO,
		S.RESOLVED_PARENTDOCSERNO AS [PARENTDOCSERNO],
		S.VISITDT,
		S.EPICC_SU_TX_AGENCY,
		SAGENCY.DESCRIPTION AS [EPICC_SU_TX_AGENCY_DESCRIPTION],
		S.SU_TX_INTAKE,
		S.INTAKE_NOT_COMPLETED,
		S.SU_TX_INTAKE_DATE,
		S.USERID,
		S.DOCREVNO
	FROM INFERRED_SUTX AS [S]
	INNER JOIN LATEST_VISIT_DATE AS [LVD]
		ON S.CLIENTNUMBER = LVD.CLIENTNUMBER
		AND S.VISITDT = LVD.MAXVISITDATE
	LEFT JOIN EPICC_SU_TX_AGENCY AS [SAGENCY]
		ON S.EPICC_SU_TX_AGENCY = SAGENCY.CODE
	WHERE S.DOCREVNO = ' 0 '
),
[FINAL_SELECTION] AS (
	SELECT CLIENTNUMBER,
		MAX(PARENTDOCSERNO) AS [MAXPARENTDOCSERNO],
		MAX(DOCSERNO) AS [MAXDOCSERNO]
	FROM LATEST_SUTX_RECORD
	GROUP BY CLIENTNUMBER
)
SELECT 
	S.CLIENTNUMBER AS [CLIENT_NUMBER],
	S.DOCSERNO,
	S.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	CAST(S.VISITDT AS DATE) AS [VISITDT],
	S.EPICC_SU_TX_AGENCY AS [EPICC_SU_TX_AGENCY_CODE],
	S.EPICC_SU_TX_AGENCY_DESCRIPTION,
	S.SU_TX_INTAKE,
	S.INTAKE_NOT_COMPLETED,
	S.SU_TX_INTAKE_DATE,
	S.USERID
FROM LATEST_SUTX_RECORD AS [S]
INNER JOIN FINAL_SELECTION AS [FS]
	ON S.CLIENTNUMBER = FS.CLIENTNUMBER
	AND S.PARENTDOCSERNO = FS.MAXPARENTDOCSERNO
	AND S.DOCSERNO = FS.MAXDOCSERNO
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = S.CLIENTNUMBER
WHERE S.DOCREVNO = ' 0 ';