/*
View Name: Q_EPICC_REFERRAL  
Category: View Definitions  

See docs/view-definitions/q-epicc-referral.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_EPICC_REFERRAL AS
SELECT EREF.ID,
	EREF.DOCSERNO,
	EREF.TIEDENROLLMENT,
	CAST(EREF.VISITDT AS DATE) AS [VISIT_DATE],
	EREF.VISITTM as [VISIT_TIME],
	EREF.USERID,
	'EPICC Referral' AS [EVENT_NAME],
	EREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(EREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREF.TIME_CALL_RECEIVED,
	EREF.REFERRER_NAME,
	EREF.REFERRER_PHONE,
	EREF.EPICC_REFERRING_AGENCY AS [EPICC_REFERRING_AGENCY_CODE],
	PRS.DESCRIPTION AS [EPICC_REFERRING_AGENCY_DESCRIPTION],
	EREF.COMMUNITY_REFERRAL_SOURCE AS [COMMUNITY_REFERRAL_SOURCE_CODE],
	CRS.DESCRIPTION AS [COMMUNITY_REFERRAL_SOURCE_DESCRIPTION],
	EREF.SPECIFY_OTHER_REFERRING_AGENCY,
	EREF.SHELTER,
	EREF.FAMILY_OR_FRIEND,
	EREF.HOUSING_STATUS_REFERRAL,
	EREF.CLIENT_ON_OUTREACH_LIST,
	EREF.EMS_FIRE_DISTRICT_PLACE_REFERRAL_IN_TRANSIT,
	EREF.EMS_FIRE_DISTRICT AS [EMS_FIRE_DISTRICT_CODE],
	EMS.DESCRIPTION AS [EMS_FIRE_DISTRICT_DESCRIPTION],
	EREF.CLIENT_AGE_14_17,
	EREF.PARENT_CAREGIVER_PRESENT_REF_OR_NOTIFIED,
	EREF.EMS_INVOLVED_REF,
	EREF.EMERGENCY_RESPONSE_CALL,
	EREF.SUBOXONE_EMS,
	EREF.WHY_NOT_SUBOXONE_EMS,
	EREF.WHO_ADMINISTERED_SUBOXONE,
	EREF.MILLIGRAMS_SUBOXONE,
	EREF.EMS_TRANSPORT_TO_HOSPITAL AS [EMS_TRANSPORT_TO_HOSPITAL_CODE],
	EMSPRS.DESCRIPTION AS [EMS_TRANSPORT_TO_HOSPITAL_DESCRIPTION],
	EREF.OTHER_EMS_FIRE_DISTRICT,
	EREF.LEO_INVOLVED_REFERRAL,
	EREF.IN_POLICE_CUSTODY,
	EREF.EPICC_PROGRAM_PARTICIPATION_REFERRAL AS [EPICC_PROGRAM_PARTICIPATION_REFERRAL_CODE],
	EPP.DESCRIPTION AS [EPICC_PROGRAM_PARTICIPATION_REFERRAL_DESCRIPTION],
	EREF.INELIGIBLE_REFERRAL,
	EREF.INELIGIBLE_REASON,
	EREF.CLIENT_ENROLLED_SU_BEFORE,
	EREF.DM3700_STATUS,
	EREF.LIST_ALL_ADA,
	EREF.PRESENTING_NOTES
FROM DBO.PWEPICCREFERRAL AS [EREF]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON EREF.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PROGRAM_REFERRAL_SOURCES AS [PRS]
	ON EREF.EPICC_REFERRING_AGENCY = PRS.CODE
LEFT JOIN DBO.COMMUNITY_REFERRAL_SOURCE AS [CRS]
	ON EREF.COMMUNITY_REFERRAL_SOURCE = CRS.CODE
LEFT JOIN DBO.EPICC_EMS_FIRE_DISTRICT AS [EMS]
	ON EREF.EMS_FIRE_DISTRICT = EMS.CODE
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON EREF.EPICC_PROGRAM_PARTICIPATION_REFERRAL = EPP.CODE
LEFT JOIN DBO.PROGRAM_REFERRAL_SOURCES AS [EMSPRS]
	ON EREF.EMS_TRANSPORT_TO_HOSPITAL = EMSPRS.CODE
WHERE EREF.DOCREVNO = ' 0 ';