/*
View Name: Q_EPICC_DUPLICATE_PWY_FORMS_W_CHILD_SUM_JOINS  
Category: View Definitions  

See docs/view-definitions/q-epicc-duplicate-pwy-forms-w-child-sum-joins.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_EPICC_DUPLICATE_PWY_FORMS_W_CHILD_SUM_JOINS AS
WITH [BASE] AS (
    SELECT
        P.CLIENT_NUMBER,
		P.PATHWAY_DATE AS [PWY_START_DATE],
        P.FORM_TYPE AS [PWY_EVENT],
        P.PATHWAY_DATE AS [EVENT_START_DATE],
        P.DOCSERNO AS [PWY_FORMS_DOCSERNO],
        P.TIEDENROLLMENT,
        COUNT(P.DOCSERNO) OVER (
            PARTITION BY
                P.CLIENT_NUMBER,
                P.FORM_TYPE,
                P.TIEDENROLLMENT
        ) AS [DUPE_COUNT]
    FROM DBO.Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [P]
),
[DUPES] AS (
    SELECT *
    FROM BASE
    WHERE DUPE_COUNT > 1
)
SELECT
    D.CLIENT_NUMBER,
	D.TIEDENROLLMENT,
    D.DUPE_COUNT,
    D.PWY_START_DATE,
    D.EVENT_START_DATE,
    D.PWY_EVENT AS [PARENT_PWY_EVENT],
    D.PWY_START_DATE AS [PARENT_VISIT_DATE],
    NULL AS [PARENT_VISIT_TIME],
    D.PWY_FORMS_DOCSERNO AS [PARENT_DOCSERNO],

    SUTX.PARENT_DOCSERNO AS [SUTX_CHILD_DOCSERNO],
    SUTX.PARENT_PWY_EVENT AS [SUTX_PARENT_EVENT],

    EHOUSE.PARENT_DOCSERNO AS [HOUSE_CHILD_DOCSERNO],
    EHOUSE.FORM_TYPE AS [HOUSE_PARENT_EVENT],

    EPAY.PARENT_DOCSERNO AS [PAY_CHILD_DOCSERNO],
    EPAY.FORM_TYPE AS [PAY_PARENT_EVENT]

FROM DUPES AS [D]
LEFT JOIN DBO.Q_EPICC_ALL_SU_TX_AGENCY AS [SUTX]
    ON D.PWY_FORMS_DOCSERNO = SUTX.PARENT_DOCSERNO
LEFT JOIN DBO.Q_EPICC_ALL_HOUSING_STATUS AS [EHOUSE]
    ON D.PWY_FORMS_DOCSERNO = EHOUSE.PARENT_DOCSERNO
LEFT JOIN DBO.Q_EPICC_ALL_PAYOR_SOURCE AS [EPAY]
    ON D.PWY_FORMS_DOCSERNO = EPAY.PARENT_DOCSERNO;