/*
View Name: Q_EPICC_THREE_MONTH  
Category: View Definitions  

See docs/view-definitions/q-epicc-three-month.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_THREE_MONTH AS
SELECT ETHREEM.ID,
	ETHREEM.DOCSERNO,
	ETHREEM.TIEDENROLLMENT,
	CAST(ETHREEM.VISITDT AS DATE) AS [VISIT_DATE],
	ETHREEM.VISITTM AS [VISIT_TIME],
	ETHREEM.USERID,
	ETHREEM.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'EPICC 3 Month' AS [EVENT_NAME],
	ETHREEM.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	TREATMENT_PATH_THREE_MONTH,
	TREATMENT_PATH_THREE_MONTH_UNABLE_TO_CONTACT,
	RC_ONLY_CLIENT_ATTEND_FIRST_APPT_COACH_THREE_MONTH,
	CAST(RC_ONLY_LAST_DATE_COMMUNICATION_THREE_MONTH AS DATE) AS [RC_ONLY_LAST_DATE_COMMUNICATION_THREE_MONTH],
	CLIENT_ATTEND_INTAKE_APPT_THREE_MONTH,
	CAST(INTAKE_APPT_DATE_THREE_MONTH AS DATE) AS [INTAKE_APPT_DATE_THREE_MONTH],
	INTAKE_CONDUCTED_APPT_DATE_THREE_MONTH,
	MAT_PRESCRIBED_PHYSICIAN_APPT_THREE_MONTH,
	MAT_PRESCRIBED_PHYSICIAN_APPT_THREE_MONTH_UNABLE_TO_CONTACT,
	WHAT_MAT_PHYSICIAN_APPT_THREE_MONTH AS [WHAT_MAT_PHYSICIAN_APPT_THREEM_CODE],
	MAT.DESCRIPTION AS [WHAT_MAT_PHYSICIAN_APPT_THREEM_DESCRIPTION],
	WHAT_MAT_PHYSICIAN_APPT_THREE_MONTH_UNABLE_TO_CONTACT AS [WHAT_MAT_PHYSICIAN_APPT_THREEM_UTC_CODE],
	MAT_UTC.DESCRIPTION AS [WHAT_MAT_PHYSICIAN_APPT_THREEM_UTC_DESCRIPTION],
	PROGRAM_PARTICIPATION_THREE_MONTH AS [PROGRAM_PARTICIPATION_THREEM_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_THREEM_DESCRIPTION],
	REASON_NOT_PARTICIPATING_THREE_MONTH,
	WHY_NOT_MEET_PROG_ELIGIBILITY_THREE_MONTH,
	REASON_NOT_ATTENDING_SUD_TX_THREE_MONTH,
	OTHER_REASON_NOT_ATTENDING_SUD_TX_THREE_MONTH,
	ATTENDING_SUD_TX_VERIFY_THREE_MONTH,
	TRANSFER_TYPE_THREE_MONTH,
	IF_TRANSFER_WHAT_REGION_THREE_MONTH,
	IF_TRANSFER_CONTACT_TRANSFER_REGION_SUCCESS_THREE_MONTH,
	CLIENT_STATUS_THREE_MONTH,
	CAST(DATE_TRANSFERRED_REENGAGEMENT_SPECIALIST_THREE_MONTH AS DATE) AS [DATE_TRANSFERRED_REENGAGEMENT_SPECIALIST_THREE_MONTH],
	PREG_POST_PART_THREE_MONTH
FROM BEHAVHEALT_LIVE.DBO.PWEPICC3MONTHFOLLOWUP AS [ETHREEM]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON ETHREEM.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN EPICC_TYPES_MAT AS [MAT]
	ON WHAT_MAT_PHYSICIAN_APPT_THREE_MONTH = MAT.CODE -- Modified this to three month on 6/16/2025
LEFT JOIN EPICC_TYPES_MAT AS [MAT_UTC]
	ON WHAT_MAT_PHYSICIAN_APPT_THREE_MONTH_UNABLE_TO_CONTACT = MAT_UTC.CODE
LEFT JOIN EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON PROGRAM_PARTICIPATION_THREE_MONTH = EPP.CODE
WHERE ETHREEM.DOCREVNO = ' 0 ';