/*

*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_EPICC_EVENTS AS
SELECT EEVENTS.ID,
	EEVENTS.DOCSERNO,
	EEVENTS.DOCREVNO,
	CAST(EEVENTS.VISITDT AS DATE) AS [VISITDT],
	EEVENTS.VISITTM,
	EEVENTS.USERID,
	EEVENTS.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	C.CLIENT_NUMBER,
	CAST(EEVENTS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EEVENTS.EPICC_EVENT_TYPE,
	EEVENTS.STAFF_DELEVERING_EPICC_EVENT AS [STAFF_DELIVERING_EPICC_EVENT_CODE],
	HR.LASTNAME AS [STAFF_LAST],
	HR.FIRSTNAME AS [STAFF_FIRST],
	EEVENTS.INSERVICE_TYPE,
	EEVENTS.OUTREACHING_TYPE,
	EEVENTS.INSERVICE_HOSP_LOCATION AS [INSERVICE_HOSP_LOCATION_CODE],
	INSERV_REFSOURCE.DESCRIPTION AS [INSERVICE_HOSP_LOCATION_DESCRIPTION],
	EEVENTS.OUTREACH_BUSINESS,
	EEVENTS.INSERVICE_EMS_FIRE_LOCATION AS [INSERVICE_EMS_FIRE_LOCATION_CODE],
	INSERV_EMSFIRE.DESCRIPTION AS [INSERVICE_EMS_FIRE_LOCATION_DESCRIPTION],
	EEVENTS.OUTREACH_EMS_FIRE_LOCATION AS [OUTREACH_EMS_FIRE_LOCATION_CODE],
	OUTREACH_EMSFIRE.DESCRIPTION AS [OUTREACH_EMS_FIRE_LOCATION_DESCRIPTION],
	EEVENTS.OUTREACH_CLINIC,
	EEVENTS.OUTREACH_HOSP_LOCATION AS [OUTREACH_HOSP_LOCATION_CODE],
	OUTREACH_REFSOURCE.DESCRIPTION AS [OUTREACH_HOSP_LOCATION_DESCRIPTION],
	EEVENTS.INSERVICE_COMMUNITY,
	EEVENTS.OUTREACH_GVMT_CENTER,
	EEVENTS.INSERVICE_LAW_ENFORCEMENT,
	EEVENTS.OUTREACH_LAW_ENFORCEMENT,
	EEVENTS.OUTREACH_LIBRARY,
	EEVENTS.OUTREACH_SHELTER,
	EEVENTS.OUTREACH_UNIVERSITY,
	EEVENTS.OUTREACH_OTHER_ORG,
	EEVENTS.STREET,
	EEVENTS.CITY,
	EEVENTS.[STATE],
	EEVENTS.COUNTY,
	EEVENTS.ZIP,
	EEVENTS.LATITUDE,
	EEVENTS.LONGITUDE,
	EEVENTS.TIME_OF_INSERVICE,
	EEVENTS.OUTREACH_METHOD,
	EEVENTS.OUTREACH_PURPOSE,
	EEVENTS.NEW_INSERVICE,
	EEVENTS.EPICC_EVENTS_PROGRAMS_DISCUSSED,
	EEVENTS.EPICC_EVENTS_OTHER_PROGRAMS,
	EEVENTS.EPICC_EVENTS_MATERIALS_DISTRIBUTED,
	EEVENTS.EEVENTS_EMS_PACKET,
	EEVENTS.EEVENTS_BADGE_BUDDIES,
	EEVENTS.EEVENTS_PENS,
	EEVENTS.EEVENTS_MAGNETS,
	EEVENTS.EEVENTS_BROCHURES,
	EEVENTS.EEVENTS_FLYERS,
	EEVENTS.EEVENTS_BUSINESS_CARDS,
	EEVENTS.EEVENTS_OTHER,
	EEVENTS.EPICC_EVENTS_MATERIALS_DISTRIBUTED_OTHER,
	EEVENTS.EPICC_EVENTS_NUMBER_OF_ATTENDEES,
	EEVENTS.EPICC_EVENTS_PRIMARY_CONTACT_NAME,
	EEVENTS.EPICC_EVENTS_CONTACT_PHONE,
	EEVENTS.EPICC_EVENTS_PRIMARY_CONTACT_EMAIL,
	EEVENTS.EPICC_EVENTS_SECOND_CONTACT_NAME,
	EEVENTS.EPICC_EVENTS_SECOND_CONTACT_PHONE,
	EEVENTS.EPICC_EVENTS_SECOND_CONTACT_EMAIL,
	EEVENTS.EPICC_EVENT_NOTES
FROM BEHAVHEALT_LIVE.DBO.PWEPICCEVENTS AS [EEVENTS]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON EEVENTS.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR]
	ON EEVENTS.STAFF_DELEVERING_EPICC_EVENT = HR.EMPLOYEENUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.PROGRAM_REFERRAL_SOURCES AS [INSERV_REFSOURCE]
	ON EEVENTS.INSERVICE_HOSP_LOCATION = INSERV_REFSOURCE.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.PROGRAM_REFERRAL_SOURCES AS [OUTREACH_REFSOURCE]
	ON EEVENTS.OUTREACH_HOSP_LOCATION = OUTREACH_REFSOURCE.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_EMS_FIRE_DISTRICT AS [INSERV_EMSFIRE]
	ON EEVENTS.INSERVICE_EMS_FIRE_LOCATION = INSERV_EMSFIRE.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_EMS_FIRE_DISTRICT AS [OUTREACH_EMSFIRE]
	ON EEVENTS.OUTREACH_HOSP_LOCATION = OUTREACH_EMSFIRE.CODE
WHERE EEVENTS.DOCREVNO = ' 0 '