/*
View Name: Q_EPICC_PATHWAY_FORMS_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-epicc-pathway-forms-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_PATHWAY_FORM_DOCSERNOS AS
SELECT EREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREF.DOCSERNO,
	EREF.TIEDENROLLMENT,
	EREF.EPICC_PROGRAM_PARTICIPATION_REFERRAL AS [PROGRAM_PARTICIPATION_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_DESCRIPTION],
	'N/A' AS [TREATMENT_PATH],
	'EPICC Referral' AS [FORM_TYPE]
FROM DBO.PWEPICCREFERRAL AS [EREF]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = EREF.CLIENTNUMBER
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON EREF.EPICC_PROGRAM_PARTICIPATION_REFERRAL = EPP.CODE
WHERE EREF.DOCREVNO = ' 0 '
UNION ALL
SELECT EIC.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EIC.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EIC.DOCSERNO,
	EIC.TIEDENROLLMENT,
	EIC.PROGRAM_PARTICIPATION_IC AS [PROGRAM_PARTICIPATION_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_DESCRIPTION],
	CASE
		WHEN EIC.PROGRAM_PARTICIPATION_IC = '019'
		THEN EIC.TREATMENT_PATH_IC
		ELSE 'N/A'
	END AS [TREATMENT_PATH],
	'EPICC Initial Contact' AS [FORM_TYPE]
FROM DBO.PWEPICCINITIALCONTACT AS [EIC]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = EIC.CLIENTNUMBER
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON EIC.PROGRAM_PARTICIPATION_IC = EPP.CODE
WHERE EIC.DOCREVNO = ' 0 '
UNION ALL
SELECT ETWOW.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ETWOW.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ETWOW.DOCSERNO,
	ETWOW.TIEDENROLLMENT,
	ETWOW.PROGRAM_PARTICIPATION_TWO_WEEK AS [PROGRAM_PARTICIPATION_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_DESCRIPTION],
	CASE
		WHEN ETWOW.PROGRAM_PARTICIPATION_TWO_WEEK = '023'
		THEN ETWOW.TREATMENT_PATH_TWO_WEEK
		ELSE 'N/A'
	END AS [TREATMENT_PATH],	
	'EPICC 2-Week Follow-Up' AS [FORM_TYPE]
FROM DBO.PWEPICC2WEEKFOLLOWUP AS [ETWOW]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = ETWOW.CLIENTNUMBER
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON ETWOW.PROGRAM_PARTICIPATION_TWO_WEEK = EPP.CODE
WHERE ETWOW.DOCREVNO = ' 0 '
UNION ALL
SELECT ETHIRTYD.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ETHIRTYD.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ETHIRTYD.DOCSERNO,
	ETHIRTYD.TIEDENROLLMENT,
	ETHIRTYD.PROGRAM_PARTICIPATION_THIRTY_DAY AS [PROGRAM_PARTICIPATION_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_DESCRIPTION],
	CASE
		WHEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTY_DAY = '023'
		THEN ETHIRTYD.TREATMENT_PATH_THIRTY_DAY
		ELSE 'N/A'
	END AS [TREATMENT_PATH],
	'EPICC 30-Day Follow-Up' AS [FORM_TYPE]
FROM DBO.PWEPICC30DAYFOLLOWUP AS [ETHIRTYD]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = ETHIRTYD.CLIENTNUMBER
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON ETHIRTYD.PROGRAM_PARTICIPATION_THIRTY_DAY = EPP.CODE
WHERE ETHIRTYD.DOCREVNO = ' 0 '
UNION ALL
SELECT ETHREEM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ETHREEM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ETHREEM.DOCSERNO,
	ETHREEM.TIEDENROLLMENT,
	ETHREEM.PROGRAM_PARTICIPATION_THREE_MONTH AS [PROGRAM_PARTICIPATION_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_DESCRIPTION],
	CASE
		WHEN ETHREEM.PROGRAM_PARTICIPATION_THREE_MONTH = '023'
		THEN ETHREEM.TREATMENT_PATH_THREE_MONTH
		ELSE 'N/A'
	END AS [TREATMENT_PATH],
	'EPICC 3-Month Follow-Up' AS [FORM_TYPE]
FROM DBO.PWEPICC3MONTHFOLLOWUP AS [ETHREEM]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = ETHREEM.CLIENTNUMBER
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON ETHREEM.PROGRAM_PARTICIPATION_THREE_MONTH = EPP.CODE
WHERE ETHREEM.DOCREVNO = ' 0 '
UNION ALL
SELECT ESIXM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ESIXM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ESIXM.DOCSERNO,
	ESIXM.TIEDENROLLMENT,
	ESIXM.PROGRAM_PARTICIPATION_SIX_MONTH AS [PROGRAM_PARTICIPATION_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_DESCRIPTION],
	CASE
		WHEN ESIXM.PROGRAM_PARTICIPATION_SIX_MONTH = '020'
		THEN ESIXM.TREATMENT_PATH_SIX_MONTH
		ELSE 'N/A'
	END AS [TREATMENT_PATH],
	'EPICC 6-Month Follow-Up' AS [FORM_TYPE]
FROM DBO.PWEPICC6MONTHFOLLOWUP AS [ESIXM]
INNER JOIN DBO.Q_CLIENT_BHN_FILTER AS [C]
	ON C.CLIENT_NUMBER = ESIXM.CLIENTNUMBER
LEFT JOIN DBO.EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON ESIXM.PROGRAM_PARTICIPATION_SIX_MONTH = EPP.CODE
WHERE ESIXM.DOCREVNO = ' 0 ';