/*
View Name: Q_EPICC_THIRTY_DAY  
Category: View Definitions  

See docs/view-definitions/q-epicc-thirty-day.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_THIRTY_DAY AS
SELECT ETHIRTYD.ID,
	ETHIRTYD.DOCSERNO,
	CAST(ETHIRTYD.VISITDT AS DATE) AS [VISITDT],
	ETHIRTYD.VISITTM,
	ETHIRTYD.USERID,
	ETHIRTYD.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'EPICC 30 Day' AS [EVENT_NAME],
	ETHIRTYD.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	TREATMENT_PATH_THIRTY_DAY,
	RC_ONLY_CLIENT_ATTEND_FIRST_APPT_COACH_THIRTY_DAY,
	CAST(RC_ONLY_LAST_DATE_COMMUNICATION_THIRTY_DAY AS DATE) AS [RC_ONLY_LAST_DATE_COMMUNICATION_THIRTY_DAY],
	CLIENT_ATTEND_INTAKE_APPT_THIRTY_DAY,
	CAST(INTAKE_APPT_DATE_THIRTY_DAY AS DATE) AS [INTAKE_APPT_DATE_THIRTY_DAY],
	INTAKE_CONDUCTED_APPT_DATE_THIRTY_DAY,
	MAT_PRESCRIBED_PHYSICIAN_THIRTY_DAY,
	WHAT_MAT_PHYSICIAN_APPT_THIRTY_DAY AS [WHAT_MAT_PHYSICIAN_APPT_THIRTYD_CODE],
	MAT.DESCRIPTION AS [WHAT_MAT_PHYSICIAN_APPT_THIRTYD_DESCRIPTION],
	PROGRAM_PARTICIPATION_THIRTY_DAY AS [PROGRAM_PARTICIPATION_THIRTYD_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION],
	IF_TRANSFER_WHAT_REGION_THIRTY_DAY,
	IF_TRANSFER_CONTACT_TRANSFER_REGION_SUCCESS_THIRTY_DAY,
	CLIENT_STATUS_THIRTY_DAY,
	CAST(DATE_TRANSFERRED_REENGAGEMENT_SPECIALIST_THIRTY_DAY AS DATE) AS [DATE_TRANSFERRED_REENGAGEMENT_SPECIALIST_THIRTY_DAY],
	PREG_POST_PART_THIRTY_DAY
FROM BEHAVHEALT_LIVE.DBO.PWEPICC30DAYFOLLOWUP AS [ETHIRTYD]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON ETHIRTYD.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN EPICC_TYPES_MAT AS [MAT]
	ON WHAT_MAT_PHYSICIAN_APPT_THIRTY_DAY = MAT.CODE 
LEFT JOIN EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON PROGRAM_PARTICIPATION_THIRTY_DAY = [EPP].CODE
WHERE ETHIRTYD.DOCREVNO = ' 0 ';