/*
View Name: EPICC Referral Form Referring Agency Mismatch With IC Type (PRO or CORE)  
Category: View Definitions  

See docs/view-definitions/q-epicc-referral-referring-agency-ic-pro-or-core-mismatch.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_EPICC_REFERRAL_REFERRING_AGENCY_IC_PRO_OR_CORE_MISMATCH AS
WITH [EPICC_REF] AS (
	SELECT C.CLIENT_NUMBER,
		C.CLIENT_LAST,
		C.CLIENT_FIRST,
		EENROLL.TIEDENROLLMENT,
		EREF.PATHWAY_DATE,
		EENROLL.ENROLLMENT_STARTING_DATE,
		EENROLL.ENROLLMENT_ENDING_DATE,
		EREF.EPICC_REFERRING_AGENCY_DESCRIPTION
	FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL]
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
		ON EENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_REFERRAL AS [EREF]
		ON EENROLL.CLIENT_NUMBER = EREF.CLIENT_NUMBER
		AND EENROLL.PWY_FORMS_DOCSERNO = EREF.DOCSERNO
	WHERE EENROLL.PWY_EVENT = 'EPICC Referral'
),
[EPICC_IC] AS (
	SELECT C.CLIENT_NUMBER,
		EENROLL.TIEDENROLLMENT,
		EIC.PATHWAY_DATE,
		EENROLL.PRO_OR_CORE
	FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL]
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
		ON EENROLL.CLIENT_NUMBER = C.CLIENT_NUMBER
	LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_IC AS [EIC]
		ON EENROLL.CLIENT_NUMBER = EIC.CLIENT_NUMBER
		AND EENROLL.PWY_FORMS_DOCSERNO = EIC.DOCSERNO
	WHERE EENROLL.PWY_EVENT = 'EPICC Initial Contact'
)
SELECT EREF.CLIENT_NUMBER,
	EREF.CLIENT_LAST,
	EREF.CLIENT_FIRST,
	EREF.PATHWAY_DATE AS [REFERRAL_PATHWAY_DATE],
	EIC.PATHWAY_DATE AS [IC_PATHWAY_DATE],
	EREF.ENROLLMENT_STARTING_DATE,
	EREF.ENROLLMENT_ENDING_DATE,
	EREF.EPICC_REFERRING_AGENCY_DESCRIPTION,
	EIC.PRO_OR_CORE
FROM [EPICC_REF] AS [EREF]
LEFT JOIN [EPICC_IC] AS [EIC]
	ON EREF.CLIENT_NUMBER = EIC.CLIENT_NUMBER
	AND EREF.TIEDENROLLMENT = EIC.TIEDENROLLMENT
WHERE EIC.TIEDENROLLMENT IS NOT NULL
	AND EREF.EPICC_REFERRING_AGENCY_DESCRIPTION = 'Community'
	AND EIC.PRO_OR_CORE = 'PRO'