/*
View Name: Q_EPICC_ALL_SU_TX_AGENCY  
Category: View Definitions  

See docs/view-definitions/q-epicc-all-su-tx-agency.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_EPICC_ALL_SU_TX_AGENCY AS
WITH CTE_FORM_MATCH AS (
	SELECT 
		SUTX.ID,
		COALESCE(
			EIC.DOCSERNO,
			ETWOW.DOCSERNO,
			ETHIRTYD.DOCSERNO,
			ETHREEM.DOCSERNO,
			ESIXM.DOCSERNO
		) AS Matched_DOCSERNO
	FROM PWSUBROADTREATMENTAGENCY AS [SUTX]
	LEFT JOIN Q_EPICC_IC AS [EIC]
		ON SUTX.CLIENTNUMBER = EIC.CLIENT_NUMBER
		AND SUTX.START_DATE = EIC.PATHWAY_DATE
	LEFT JOIN Q_EPICC_TWO_WEEK AS [ETWOW]
		ON SUTX.CLIENTNUMBER = ETWOW.CLIENT_NUMBER
		AND SUTX.START_DATE = ETWOW.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THIRTY_DAY AS [ETHIRTYD]
		ON SUTX.CLIENTNUMBER = ETHIRTYD.CLIENT_NUMBER
		AND SUTX.START_DATE = ETHIRTYD.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THREE_MONTH AS [ETHREEM]
		ON SUTX.CLIENTNUMBER = ETHREEM.CLIENT_NUMBER
		AND SUTX.START_DATE = ETHREEM.PATHWAY_DATE
	LEFT JOIN Q_EPICC_SIX_MONTH AS [ESIXM]
		ON SUTX.CLIENTNUMBER = ESIXM.CLIENT_NUMBER
		AND SUTX.START_DATE = ESIXM.PATHWAY_DATE
)
SELECT 
	SUTX.ID,
	SUTX.DOCSERNO,
	CAST(SUTX.VISITDT AS DATE) AS [VISITDT],
	SUTX.USERID,
	CASE 
		WHEN (SUTX.PARENTDOCSERNO IS NULL OR LTRIM(RTRIM(SUTX.PARENTDOCSERNO)) = '')
		     AND SUTX.USERID LIKE 'import%' 
		     AND FM.Matched_DOCSERNO IS NOT NULL 
		THEN FM.Matched_DOCSERNO
		ELSE SUTX.PARENTDOCSERNO
	END AS [PARENT_DOCSERNO],
	C.CLIENT_NUMBER,
	CAST(SUTX.START_DATE AS DATE) AS [START_DATE],
	CAST(SUTX.END_DATE AS DATE) AS [END_DATE],
	CAST(SUTX.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	SUTX.ADA_SU_AGENCY,
	SUTX.EPICC_SU_TX_AGENCY AS [EPICC_SU_TX_AGENCY_CODE],
	SUTXAGENCY.DESCRIPTION AS [EPICC_SU_TX_AGENCY_DESCRIPTION],
	SUTX.IF_OTHER_SPECIFY,
	SUTX.PFH_TX_FACILITY AS [PFH_TX_FACILITY_CODE],
	PFHSUTXAGENCY.DESCRIPTION AS [PFH_TX_FACILITY_DESCRIPTION],
	CAST(SUTX.SU_TX_INTAKE_DATE AS DATE) AS [SU_TX_INTAKE_DATE],
	SUTX.SU_TX_INTAKE,
	SUTX.WAS_INTAKE_COMPLETED,
	SUTX.INTAKE_NOT_COMPLETED,
	SUTX.INTAKE_NOT_COMPLETED_OTHER,
	SUTX.COACH_ATTEND_INTAKE,
	SUTX.CES_ATTEND_INTAKE,
	SUTX.COACH_NOT_ATTEND_INTAKE,
	SUTX.CES_NOT_ATTEND_INTAKE
FROM PWSUBROADTREATMENTAGENCY AS [SUTX]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = SUTX.CLIENTNUMBER
LEFT JOIN EPICC_SU_TX_AGENCY AS [SUTXAGENCY]
	ON SUTX.EPICC_SU_TX_AGENCY = SUTXAGENCY.CODE
LEFT JOIN EPICC_SU_TX_AGENCY AS [PFHSUTXAGENCY]
	ON SUTX.PFH_TX_FACILITY = PFHSUTXAGENCY.CODE
LEFT JOIN CTE_FORM_MATCH AS FM
	ON SUTX.ID = FM.ID
WHERE SUTX.DOCREVNO = ' 0 ';