/*
View Name: Q_EPICC_SIX_MONTH  
Category: View Definitions  

See docs/view-definitions/q-epicc-six-month.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_SIX_MONTH AS
SELECT ESIXM.ID,
	ESIXM.DOCSERNO,
	CAST(ESIXM.VISITDT AS DATE) AS [VISITDT],
	ESIXM.VISITTM,
	ESIXM.USERID,
	ESIXM.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'EPICC 6 Month' AS [EVENT_NAME],
	ESIXM.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	TREATMENT_PATH_SIX_MONTH,
	RC_ONLY_CLIENT_ATTEND_FIRST_APPT_COACH_SIX_MONTH,
	CAST(RC_ONLY_LAST_DATE_COMMUNICATION_SIX_MONTH AS DATE) AS [RC_ONLY_LAST_DATE_COMMUNICATION_SIX_MONTH],
	CLIENT_ATTEND_INTAKE_APPT_SIX_MONTH,
	CAST(INTAKE_APPT_DATE_SIX_MONTH AS DATE) AS [INTAKE_APPT_DATE_SIX_MONTH],
	INTAKE_CONDUCTED_APPT_DATE_SIX_MONTH,
	MAT_PRESCRIBED_PHYSICIAN_APPT_SIX_MONTH,
	WHAT_MAT_PHYSICIAN_APPT_SIX_MONTH AS [WHAT_MAT_PHYSICIAN_APPT_SIXM_CODE],
	MAT.DESCRIPTION AS [WHAT_MAT_PHYSICIAN_APPT_SIXM_DESCRIPTION],
	IF_TRANSFER_WHAT_REGION_SIX_MONTH,
	IF_TRANSFER_CONTACT_TRANSFER_REGION_SUCCESS_SIX_MONTH,
	PREG_POST_PART_SIX_MONTH,
	PROGRAM_PARTICIPATION_SIX_MONTH AS [PROGRAM_PARTICIPATION_SIXM_CODE],
	EPP.DESCRIPTION AS [PROGRAM_PARTICIPATION_SIXM_DESCRIPTION]
FROM BEHAVHEALT_LIVE.DBO.PWEPICC6MONTHFOLLOWUP AS [ESIXM]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON ESIXM.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN EPICC_TYPES_MAT AS [MAT]
	ON WHAT_MAT_PHYSICIAN_APPT_SIX_MONTH = MAT.CODE
LEFT JOIN EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON PROGRAM_PARTICIPATION_SIX_MONTH = EPP.CODE
WHERE ESIXM.DOCREVNO = ' 0 ';