/*
View Name: Q_EPICC_ACTIVE_PAYOR_SOURCE
Category: View Definitions

See docs/view-definitions/q-epicc-active-payor-source.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_EPICC_ACTIVE_PAYOR_SOURCE AS
WITH ACTIVE_PAYOR_SOURCE AS (
	SELECT 
		EPAY.CLIENTNUMBER,
		EPAY.PARENTDOCSERNO,
		EPAY.PAYOR_SOURCE,
		EPAY.MANAGED_MEDICAID_PROVIDER,
		EPAY.PRIVATE_INSURANCE_PROVIDER,
		EPAY.VISITDT,
		EPAY.VISITTM
	FROM PWPAYORSOURCE AS [EPAY]
	WHERE EPAY.DOCREVNO = ' 0 '
		AND EPAY.PAYOR_SOURCE_END_DATE IS NULL
),
AGGREGATED_PAYOR_SOURCE AS (
	SELECT 
		AGPS.CLIENTNUMBER,
		MAX(AGPS.PARENTDOCSERNO) AS [PARENTDOCSERNO], -- Will not guarantee uniqueness, but aggregation is needed because grouping is applied, and there could be multiple PARENTDOCSERNOs associated with active payor sources.
		MAX(AGPS.MANAGED_MEDICAID_PROVIDER) AS [MANAGED_MEDICAID_PROVIDER],
		MAX(AGPS.PRIVATE_INSURANCE_PROVIDER) AS [PRIVATE_INSURANCE_PROVIDER],
		AGPS.PAYOR_SOURCE,
		1 AS [PAYOR_SOURCE_FLAG] -- Adds a constant column for pivoting
	FROM ACTIVE_PAYOR_SOURCE AS [AGPS]
	WHERE AGPS.PARENTDOCSERNO IN (SELECT EPF.DOCSERNO FROM Q_EPICC_PATHWAY_FORM_DOCSERNOS AS [EPF]) -- Filter by Q_EPICC_PATHWAY_FORMS view to ensure only relevant EPICC records are included.
	GROUP BY AGPS.CLIENTNUMBER, AGPS.PAYOR_SOURCE -- Group by CLIENTNUMBER and PAYOR_SOURCE to aggregate.
),
PIVOTED_PAYOR_SOURCES AS (
	SELECT 
		CLIENTNUMBER,
		MAX(PARENTDOCSERNO) AS [PARENTDOCSERNO], -- Still won't guarantee uniqueness, but needed for pivoting.
		ISNULL(MAX([001]), 0) AS [PAYOR_SOURCE_DUAL_ELIGIBLE],
		ISNULL(MAX([005]), 0) AS [PAYOR_SOURCE_MANAGED_MEDICAID],
		ISNULL(MAX([002]), 0) AS [PAYOR_SOURCE_MEDICAID],
		ISNULL(MAX([003]), 0) AS [PAYOR_SOURCE_MEDICAID_IN_PROGRESS],
		ISNULL(MAX([004]), 0) AS [PAYOR_SOURCE_MEDICAID_CHP],
		ISNULL(MAX([006]), 0) AS [PAYOR_SOURCE_MEDICARE],
		ISNULL(MAX([007]), 0) AS [PAYOR_SOURCE_PRIVATE_INSURANCE],
		ISNULL(MAX([009]), 0) AS [PAYOR_SOURCE_UNINSURED],
		ISNULL(MAX([010]), 0) AS [PAYOR_SOURCE_UNKNOWN_REFUSED],
		ISNULL(MAX([008]), 0) AS [PAYOR_SOURCE_VA_BENEFITS],
		MAX(MANAGED_MEDICAID_PROVIDER) AS [MANAGED_MEDICAID_PROVIDER],
		MAX(PRIVATE_INSURANCE_PROVIDER) AS [PRIVATE_INSURANCE_PROVIDER]
	FROM AGGREGATED_PAYOR_SOURCE
	PIVOT (
		MAX(PAYOR_SOURCE_FLAG) FOR PAYOR_SOURCE IN (
			[001], -- Dual Eligible (Medicare & Medicaid)
			[005], -- Managed Medicaid
			[002], -- Medicaid
			[003], -- Medicaid Application In Progress
			[004], -- Medicaid CHP
			[006], -- Medicare
			[007], -- Private Insurance
			[009], -- Uninsured
			[010], -- Unknown/Refused
			[008]  -- VA Benefits
		)
	) AS [PIVOTTABLE]
	GROUP BY CLIENTNUMBER -- Group by CLIENTNUMBER to ensure unique rows per client.
),
LATEST_PARENTDOCSERNO AS (
	SELECT 
		PPS.CLIENTNUMBER,
		MAX(APS.PARENTDOCSERNO) AS [LATEST_PARENTDOCSERNO] -- Retain the latest PARENTDOCSERNO. This should finally ensure uniqueness.
	FROM PIVOTED_PAYOR_SOURCES AS [PPS]
	JOIN ACTIVE_PAYOR_SOURCE AS [APS]
		ON PPS.CLIENTNUMBER = APS.CLIENTNUMBER
	GROUP BY PPS.CLIENTNUMBER
),
FINAL_OUTPUT AS (
	SELECT 
		PPS.CLIENTNUMBER AS [CLIENT_NUMBER],
		LPS.LATEST_PARENTDOCSERNO AS [PARENT_DOCSERNO],
		PPS.PAYOR_SOURCE_DUAL_ELIGIBLE,
		PPS.PAYOR_SOURCE_MANAGED_MEDICAID,
		PPS.PAYOR_SOURCE_MEDICAID,
		PPS.PAYOR_SOURCE_MEDICAID_IN_PROGRESS,
		PPS.PAYOR_SOURCE_MEDICAID_CHP,
		PPS.PAYOR_SOURCE_MEDICARE,
		PPS.PAYOR_SOURCE_PRIVATE_INSURANCE,
		PPS.PAYOR_SOURCE_UNINSURED,
		PPS.PAYOR_SOURCE_UNKNOWN_REFUSED,
		PPS.PAYOR_SOURCE_VA_BENEFITS,
		PPS.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
		MMP.DESCRIPTION AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
		PPS.PRIVATE_INSURANCE_PROVIDER
	FROM PIVOTED_PAYOR_SOURCES AS [PPS]
	JOIN LATEST_PARENTDOCSERNO AS [LPS]
		ON PPS.CLIENTNUMBER = LPS.CLIENTNUMBER
	LEFT JOIN MANAGED_MEDICAID_PROVIDER AS [MMP]
		ON PPS.MANAGED_MEDICAID_PROVIDER = MMP.CODE -- Join to get the description
)
SELECT * FROM FINAL_OUTPUT;