/*
View Name: Q_EPICC_ALL_SU_TX_AGENCY  
Category: View Definitions  

See docs/view-definitions/q-epicc-all-su-tx-agency.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_EPICC_ALL_SU_TX_AGENCY AS
WITH [CTE_FORM_MATCH] AS (
	SELECT 
		SUTX.ID,
		COALESCE(
			EIC_DATE.DOCSERNO,
			EIC_DOC.DOCSERNO,
			ETWOW_DATE.DOCSERNO,
			ETWOW_DOC.DOCSERNO,
			ETHIRTYD_DATE.DOCSERNO,
			ETHIRTYD_DOC.DOCSERNO,
			ETHREEM_DATE.DOCSERNO,
			ETHREEM_DOC.DOCSERNO,
			ESIXM_DATE.DOCSERNO,
			ESIXM_DOC.DOCSERNO
		) AS [MATCHED_DOCSERNO],
		-- Imported summation records lack PATHWAY_DATE, so *_DATE joins will never match.
		-- This CASE for parent Pathway Form reflects only *_DOC matches, which are valid for front-end-entered records.
		CASE
			WHEN EIC_DOC.DOCSERNO IS NOT NULL THEN 'Initial Contact'
			WHEN ETWOW_DOC.DOCSERNO IS NOT NULL THEN 'Two-Week'
			WHEN ETHIRTYD_DOC.DOCSERNO IS NOT NULL THEN 'Thirty-Day'
			WHEN ETHREEM_DOC.DOCSERNO IS NOT NULL THEN 'Three-Month'
			WHEN ESIXM_DOC.DOCSERNO IS NOT NULL THEN 'Six-Month'
			ELSE NULL
		END AS [PARENT_PWY_EVENT]
	FROM PWSUBROADTREATMENTAGENCY AS [SUTX]
	-- Match by START_DATE = PATHWAY_DATE when PARENTDOCSERNO is NULL
	LEFT JOIN Q_EPICC_IC AS [EIC_DATE]
		ON SUTX.CLIENTNUMBER = EIC_DATE.CLIENT_NUMBER
		AND SUTX.PARENTDOCSERNO IS NULL
		AND SUTX.START_DATE = EIC_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_TWO_WEEK AS [ETWOW_DATE]
		ON SUTX.CLIENTNUMBER = ETWOW_DATE.CLIENT_NUMBER
		AND SUTX.PARENTDOCSERNO IS NULL
		AND SUTX.START_DATE = ETWOW_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THIRTY_DAY AS [ETHIRTYD_DATE]
		ON SUTX.CLIENTNUMBER = ETHIRTYD_DATE.CLIENT_NUMBER
		AND SUTX.PARENTDOCSERNO IS NULL
		AND SUTX.START_DATE = ETHIRTYD_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THREE_MONTH AS [ETHREEM_DATE]
		ON SUTX.CLIENTNUMBER = ETHREEM_DATE.CLIENT_NUMBER
		AND SUTX.PARENTDOCSERNO IS NULL
		AND SUTX.START_DATE = ETHREEM_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_SIX_MONTH AS [ESIXM_DATE]
		ON SUTX.CLIENTNUMBER = ESIXM_DATE.CLIENT_NUMBER
		AND SUTX.PARENTDOCSERNO IS NULL
		AND SUTX.START_DATE = ESIXM_DATE.PATHWAY_DATE
	-- Match by PARENTDOCSERNO = DOCSERNO when PARENTDOCSERNO is NOT NULL
	-- Joining on CLIENT_NUMBER is not necessary here since PARENTDOCSERNO is unique
	LEFT JOIN Q_EPICC_IC AS [EIC_DOC]
		ON SUTX.PARENTDOCSERNO IS NOT NULL
		AND SUTX.PARENTDOCSERNO = EIC_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_TWO_WEEK AS [ETWOW_DOC]
		ON SUTX.PARENTDOCSERNO IS NOT NULL
		AND SUTX.PARENTDOCSERNO = ETWOW_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_THIRTY_DAY AS [ETHIRTYD_DOC]
		ON SUTX.PARENTDOCSERNO IS NOT NULL
		AND SUTX.PARENTDOCSERNO = ETHIRTYD_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_THREE_MONTH AS [ETHREEM_DOC]
		ON SUTX.PARENTDOCSERNO IS NOT NULL
		AND SUTX.PARENTDOCSERNO = ETHREEM_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_SIX_MONTH AS [ESIXM_DOC]
		ON SUTX.PARENTDOCSERNO IS NOT NULL
		AND SUTX.PARENTDOCSERNO = ESIXM_DOC.DOCSERNO
)
SELECT 
	SUTX.ID,
	SUTX.DOCSERNO,
	CAST(SUTX.VISITDT AS DATE) AS [VISITDT],
	SUTX.USERID,
	CASE 
		WHEN (SUTX.PARENTDOCSERNO IS NULL OR LTRIM(RTRIM(SUTX.PARENTDOCSERNO)) = '')
		     AND SUTX.USERID LIKE 'import%' 
		     AND FM.MATCHED_DOCSERNO IS NOT NULL 
		THEN FM.MATCHED_DOCSERNO
		ELSE SUTX.PARENTDOCSERNO
	END AS [PARENT_DOCSERNO],
	FM.PARENT_PWY_EVENT,
	C.CLIENT_NUMBER,
	CAST(SUTX.START_DATE AS DATE) AS [START_DATE],
	CAST(SUTX.END_DATE AS DATE) AS [END_DATE],
	CAST(SUTX.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	SUTX.ADA_SU_AGENCY,
	SUTX.EPICC_SU_TX_AGENCY AS [EPICC_SU_TX_AGENCY_CODE],
	SUTXAGENCY.DESCRIPTION AS [EPICC_SU_TX_AGENCY_DESCRIPTION],
	SUTX.IF_OTHER_SPECIFY,
	SUTX.PFH_TX_FACILITY AS [PFH_TX_FACILITY_CODE],
	PFHSUTXAGENCY.DESCRIPTION AS [PFH_TX_FACILITY_DESCRIPTION],
	CAST(SUTX.SU_TX_INTAKE_DATE AS DATE) AS [SU_TX_INTAKE_DATE],
	SUTX.SU_TX_INTAKE,
	SUTX.WAS_INTAKE_COMPLETED,
	SUTX.INTAKE_NOT_COMPLETED,
	SUTX.INTAKE_NOT_COMPLETED_OTHER,
	SUTX.COACH_ATTEND_INTAKE,
	SUTX.CES_ATTEND_INTAKE,
	SUTX.COACH_NOT_ATTEND_INTAKE,
	SUTX.CES_NOT_ATTEND_INTAKE
FROM PWSUBROADTREATMENTAGENCY AS [SUTX]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = SUTX.CLIENTNUMBER
LEFT JOIN EPICC_SU_TX_AGENCY AS [SUTXAGENCY]
	ON SUTX.EPICC_SU_TX_AGENCY = SUTXAGENCY.CODE
LEFT JOIN EPICC_SU_TX_AGENCY AS [PFHSUTXAGENCY]
	ON SUTX.PFH_TX_FACILITY = PFHSUTXAGENCY.CODE
LEFT JOIN CTE_FORM_MATCH AS [FM]
	ON SUTX.ID = FM.ID
WHERE SUTX.DOCREVNO = ' 0 ';