/*
View Name: Q_EPICC_CORE_COMMUNITY_OUTREACH_EVENTS
Category: View Definitions  

See docs/view-definitions/q-epicc-core-community-outreach-events.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- CREATE Q_EPICC_CORE_OUTREACH_EVENTS ASSELECT EOUTREACH.ID,
	EOUTREACH.DOCSERNO,
	EOUTREACH.DOCREVNO,
	CAST(EOUTREACH.VISITDT AS DATE) AS [VISIT_DATE],
	EOUTREACH.VISITTM,
	EOUTREACH.USERID,
	EOUTREACH.CLIENTNUMBER AS [CLIENT_NUMBER],
	EOUTREACH.COMMUNITY_OUTREACH_EVENT_TYPE,
	EOUTREACH.COMMUNITY_OUTREACH_EVENT_TYPE_OTHER,
	EOUTREACH.COMMUNITY_OUTREACH_MATERIALS_DISTRIBUTED,
	EOUTREACH.COE_ED_MATERIALS,
	EOUTREACH.COE_FOOD_WATER,
	EOUTREACH.COE_HYGEINE_PRODUCTS,
	EOUTREACH.COE_NALOXONE,
	EOUTREACH.COE_TOILETRIES,
	EOUTREACH.COE_OTHER,
	EOUTREACH.COMMUNITY_OUTREACH_MATERIALS_DISTRIBUTED_OTHER,
	EOUTREACH.COMMUNITY_OUTREACH_LOCATION,
	EOUTREACH.STREET,
	EOUTREACH.CITY,
	EOUTREACH.ZIP,
	EOUTREACH.LATITUDE,
	EOUTREACH.LONGITUDE,
	EOUTREACH.STATE,
	EOUTREACH.COUNTY,
	CAST(EOUTREACH.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EOUTREACH.NOTES_COE
FROM BEHAVHEALT_LIVE.DBO.PWEPICCCOMMUNITYOUTREACHEVENT AS [EOUTREACH]
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = EOUTREACH.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.EPICC_MATERIALS_DISTRIBUTED AS [EMD]
	ON EMD.CODE = EOUTREACH.COMMUNITY_OUTREACH_MATERIALS_DISTRIBUTED
LEFT JOIN BEHAVHEALT_LIVE.DBO.COUNTY AS [COUNTY]
	ON COUNTY.CODE = EOUTREACH.COUNTY
WHERE EOUTREACH.DOCREVNO = ' 0 ';