/*
View Name: Q_EPICC_DUPLICATE_PWY_FORMS_W_CHILD_SUM_JOINS  
Category: View Definitions  

See docs/view-definitions/q-epicc-duplicate-pwy-forms-w-child-sum-joins.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW .DBO.Q_EPICC_DUPLICATE_PWY_FORMS_W_CHILD_SUM_JOINS AS
WITH [DUPES] AS (
	SELECT 
		EENROLL.CLIENT_NUMBER,
		EENROLL.PWY_START_DATE,
		EENROLL.PWY_EVENT,
		EENROLL.EVENT_START_DATE,
		EENROLL.TIEDENROLLMENT,
		COUNT(EENROLL.PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
	FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL]
	WHERE EENROLL.TIEDENROLLMENT IS NOT NULL
		AND EENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	GROUP BY EENROLL.CLIENT_NUMBER,
		EENROLL.PWY_START_DATE,
		EENROLL.PWY_EVENT,
		EENROLL.EVENT_START_DATE,
		EENROLL.TIEDENROLLMENT
	HAVING COUNT(EENROLL.PWY_FORMS_DOCSERNO) > 1
),
[DUPES_DETAIL] AS (
	SELECT 
		EENROLL.CLIENT_NUMBER,
		EENROLL.PWY_FORMS_VISIT_DATE,
		EENROLL.PWY_FORMS_VISIT_TIME,
		EENROLL.PWY_START_DATE,
		EENROLL.PWY_EVENT,
		EENROLL.EVENT_START_DATE,
		EENROLL.PWY_FORMS_DOCSERNO,
		EENROLL.TIEDENROLLMENT
	FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_PATHCLIENT_ENROLLMENTS AS [EENROLL]
	INNER JOIN DUPES
		ON EENROLL.CLIENT_NUMBER = DUPES.CLIENT_NUMBER
		AND EENROLL.PWY_START_DATE = DUPES.PWY_START_DATE
		AND EENROLL.PWY_EVENT = DUPES.PWY_EVENT
		AND EENROLL.EVENT_START_DATE = DUPES.EVENT_START_DATE
		AND EENROLL.TIEDENROLLMENT = EENROLL.TIEDENROLLMENT
),
[SUTX_CHILD] AS (
	SELECT 
		SUTX.CLIENT_NUMBER,
		SUTX.PARENT_DOCSERNO,
		SUTX.PARENT_PWY_EVENT
	FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_ALL_SU_TX_AGENCY AS [SUTX]
),
[HOUSE_CHILD] AS(
	SELECT 
		HOUSE_CHILD.CLIENT_NUMBER,
		HOUSE_CHILD.PARENT_DOCSERNO,
		HOUSE_CHILD.FORM_TYPE AS [PARENT_PWY_EVENT]
	FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_ALL_HOUSING_STATUS AS [HOUSE_CHILD]
),
[PAY_CHILD] AS(
	SELECT 
		PAY_CHILD.CLIENT_NUMBER,
		PAY_CHILD.PARENTDOCSERNO,
		PAY_CHILD.FORM_TYPE AS [PARENT_PWY_EVENT]
	FROM BEHAVHEALT_LIVE.DBO.Q_EPICC_ALL_PAYOR_SOURCE AS [PAY_CHILD]
)
SELECT DUPES_DETAIL.CLIENT_NUMBER,
	DUPES_DETAIL.PWY_START_DATE,
	DUPES_DETAIL.EVENT_START_DATE,
	DUPES_DETAIL.PWY_EVENT AS [PARENT_PWY_EVENT],
	DUPES_DETAIL.PWY_FORMS_VISIT_DATE AS [PARENT_VISIT_DATE],
	DUPES_DETAIL.PWY_FORMS_VISIT_TIME AS [PARENT_VISIT_TIME],
	DUPES_DETAIL.PWY_FORMS_DOCSERNO AS [PARENT_DOCSERNO],
	SUTX_CHILD.PARENT_DOCSERNO AS [SUTX_CHILD_DOCSERNO],
	SUTX_CHILD.PARENT_PWY_EVENT AS [SUTX_PARENT_EVENT],
	HOUSE_CHILD.PARENT_DOCSERNO AS [HOUSE_CHILD_DOCSERNO],
	HOUSE_CHILD.PARENT_PWY_EVENT AS [HOUSE_PARENT_EVENT],
	PAY_CHILD.PARENTDOCSERNO AS [PAY_CHILD_DOCSERNO],
	PAY_CHILD.PARENT_PWY_EVENT AS [PAY_PARENT_EVENT],
	DUPES_DETAIL.TIEDENROLLMENT
FROM DUPES_DETAIL AS [DUPES_DETAIL]
LEFT JOIN SUTX_CHILD AS [SUTX_CHILD]
	ON DUPES_DETAIL.PWY_FORMS_DOCSERNO = SUTX_CHILD.PARENT_DOCSERNO
LEFT JOIN HOUSE_CHILD AS [HOUSE_CHILD]
	ON DUPES_DETAIL.PWY_FORMS_DOCSERNO = HOUSE_CHILD.PARENT_DOCSERNO
LEFT JOIN PAY_CHILD AS [PAY_CHILD]
	ON DUPES_DETAIL.PWY_FORMS_DOCSERNO = PAY_CHILD.PARENTDOCSERNO
INNER JOIN DUPES AS [DUPES]
	ON DUPES_DETAIL.CLIENT_NUMBER = DUPES.CLIENT_NUMBER
	AND DUPES_DETAIL.PWY_START_DATE = DUPES.PWY_START_DATE
	AND DUPES_DETAIL.PWY_EVENT = DUPES.PWY_EVENT
	AND DUPES_DETAIL.EVENT_START_DATE = DUPES.EVENT_START_DATE
	AND DUPES_DETAIL.TIEDENROLLMENT = DUPES.TIEDENROLLMENT;