/*
View Name: Q_EPICC_CASE_NOTES
Category: View Definitions  

See docs/view-definitions/q-epicc-case-notes.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--CREATE VIEW DBO.Q_EPICC_CASE_NOTES AS
SELECT CN.ID,
	CN.DOCSERNO,
	CAST(CN.VISITDT AS DATE) AS [VISITDT],
	CN.VISITTM,
	CN.USERID,
	C.CLIENT_NUMBER,
	CAST(CN.CONTACTDATE AS DATE) AS [CONTACT_DATE],
	CN.APPTMISSED as [APPT_MISSED],
	CN.MISSEDREASON AS [APPT_MISSED_REASON],
	CN.MISSEDDETAILS AS [APPT_MISSED_DETAILS],
	CN.[SERVER] AS [PROGRAM_WORKER_NUMBER],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST_NAME],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST_NAME],
	CN.CONTACTTYPE AS [CONTACT_TYPE_CODE],
	CT.DESCRIPTION AS [CONTACT_TYPE_DESCRIPTION],
	CN.CONTACTWITH AS [CONTACT_WITH],
	CN.CONTACTINITIATEDBY AS [CONTACT_INITIATED_BY],
	ENROLL.PROGRAM_CODE,
	ENROLL.PROGRAM_DESCRIPTION,
	CN.PROVIDERSERVICE AS [AGENCY_CODE],
	P.PROVIDER_NAME AS [AGENCY_NAME],
	CN.SERVICESITE AS [LOCATION_CODE],
	SP.DESCRIPTION AS [LOCATION_DESCRIPTION],
	CN.OTHER_LOCATION,
	CN.OTHER_ORGANIZATION
FROM CASENOTEDETAIL AS [CN]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = CN.CLIENTNUMBER
LEFT JOIN Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = CN.[SERVER]
LEFT JOIN CONTACTTYPE AS [CT]
	ON CT.CODE = CN.CONTACTTYPE
LEFT JOIN Q_PROVIDER_BHN AS [P]
	ON P.PROVIDER_CODE = CN.PROVIDERSERVICE
LEFT JOIN SERVICESITE AS [SP]
	ON SP.CODE = CN.SERVICESITE
LEFT JOIN (
	SELECT 
		PP.CLIENT_NUMBER,
		PP.AGENCY_CODE,
		PP.ENROLLMENT_STARTING_DATE,
		PP.ENROLLMENT_ENDING_DATE,
		PP.PROGRAM_CODE,
		PP.PROGRAM_DESCRIPTION
	FROM Q_PROVIDERPLACEMENT_BHN AS [PP]
) AS [ENROLL]
	ON ENROLL.CLIENT_NUMBER = CN.CLIENTNUMBER
	AND ENROLL.AGENCY_CODE = CN.PROVIDERSERVICE
	AND CN.CONTACTDATE BETWEEN ENROLL.ENROLLMENT_STARTING_DATE AND ISNULL(ENROLL.ENROLLMENT_ENDING_DATE, '2099-12-31')
	AND (
		ENROLL.ENROLLMENT_ENDING_DATE IS NULL
		OR ENROLL.ENROLLMENT_STARTING_DATE <> ENROLL.ENROLLMENT_ENDING_DATE
		)
WHERE CN.DOCREVNO = ' 0 '
	AND ENROLL.PROGRAM_CODE = '100006';