/*
View Name: Q_EPICC_PATHCLIENT_ENROLLMENTS  
Category: View Definitions  

See docs/view-definitions/q-epicc-pathclient-enrollments.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_EPICC_PATHCLIENT_ENROLLMENTS AS
SELECT
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	PEC.USERID AS [PEC_USERID],
	PEC.LASTUPDATEBY AS [PEC_LAST_UPDATE_BY],
	PP.DOCSERNO AS [PP_DOCSERNO],
	COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) AS [PC_DOCSERNO],
	PEC.PATHCLIENTDOCSERNO AS [PEC_PATHCLIENT_DOCSERNO],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
		THEN EREF.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
		THEN ETWOW.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
		THEN ETHIRTYD.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
		THEN ETHREEM.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
		THEN ESIXM.TIEDENROLLMENT
	END AS [TIEDENROLLMENT],
	CASE 
		WHEN 
			CASE
				WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
				THEN EREF.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
				THEN EIC.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
				THEN ETWOW.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
				THEN ETHIRTYD.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
				THEN ETHREEM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
				THEN ESIXM.TIEDENROLLMENT
			END IS NULL 
		THEN NULL
		WHEN COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) = 
			CASE
			WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
			THEN EREF.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
			THEN EIC.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
			THEN ETWOW.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
			THEN ETHIRTYD.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
			THEN ETHREEM.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
			THEN ESIXM.TIEDENROLLMENT
			END 
		THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS [TIEDENROLLMENT_MATCH],
	COALESCE(PC_DOCSERNO.JOIN_TYPE, PC_START.JOIN_TYPE) AS [ENROLL_PATH_JOIN_SOURCE],
	PP.PRIMARYPROVIDERCODE AS [AGENCY_CODE],
	P.PROVIDERNAME AS [AGENCY_DESCRIPTION],
	PROGHISTORY.PRIMARYPROVIDERCODE AS [AGENCY_CODE_NON_CFL],
	P2.PROVIDERNAME AS [AGENCY_DESCRIPTION_NON_CFL],
	CASE
		WHEN PP.PRIMARYPROVIDERCODE <> PROGHISTORY.PRIMARYPROVIDERCODE
		THEN 1
		ELSE 0
	END AS [AGENCY_TRANSFORMATION_FLAG],
	CAST(COALESCE(PC_DOCSERNO.STARTDATE, PC_START.STARTDATE) AS DATE) AS [PWY_START_DATE],
	CAST(COALESCE(PC_DOCSERNO.ENDDATE, PC_START.ENDDATE) AS DATE) AS [PWY_END_DATE],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
		THEN EREF.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
		THEN ETWOW.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
		THEN ETHIRTYD.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
		THEN ETHREEM.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
		THEN ESIXM.DOCSERNO
	END AS [PWY_FORMS_DOCSERNO],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
		THEN EREF.PATHWAY_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.PATHWAY_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
		THEN ETWOW.PATHWAY_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
		THEN ETHIRTYD.PATHWAY_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
		THEN ETHREEM.PATHWAY_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
		THEN ESIXM.PATHWAY_DATE
	END AS [PATHWAY_DATE],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
		THEN EREF.VISIT_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.VISIT_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
		THEN ETWOW.VISIT_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
		THEN ETHIRTYD.VISIT_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
		THEN ETHREEM.VISIT_DATE
		WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
		THEN ESIXM.VISIT_DATE
	END AS [PWY_FORMS_VISIT_DATE],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Referral' 
		THEN EREF.VISIT_TIME
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.VISIT_TIME
		WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
		THEN ETWOW.VISIT_TIME
		WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
		THEN ETHIRTYD.VISIT_TIME
		WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
		THEN ETHREEM.VISIT_TIME
		WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
		THEN ESIXM.VISIT_TIME
	END AS [PWY_FORMS_VISIT_TIME],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.EPICC_PRO_OR_CORE_IC
	END AS [PRO_OR_CORE],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.TREATMENT_PATH_IC
		WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
		THEN ETWOW.TREATMENT_PATH_TWO_WEEK
		WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
		THEN ETHIRTYD.TREATMENT_PATH_THIRTY_DAY
		WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
		THEN ETHREEM.TREATMENT_PATH_THREE_MONTH
		WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
		THEN ESIXM.TREATMENT_PATH_SIX_MONTH
	END AS [TREATMENT_PATH],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'EPICC Referral'
		THEN EREF.EPICC_PROGRAM_PARTICIPATION_REFERRAL_DESCRIPTION
		WHEN PE.SHORTDESCRIPTION = 'EPICC Initial Contact' 
		THEN EIC.EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION
		WHEN PE.SHORTDESCRIPTION = 'EPICC 2 Week' 
		THEN ETWOW.PROGRAM_PARTICIPATION_TWOW_DESCRIPTION
		WHEN PE.SHORTDESCRIPTION = 'EPICC 30 Day' 
		THEN ETHIRTYD.PROGRAM_PARTICIPATION_THIRTYD_DESCRIPTION
		WHEN PE.SHORTDESCRIPTION = 'EPICC 3 Month' 
		THEN ETHREEM.PROGRAM_PARTICIPATION_THREEM_DESCRIPTION
		WHEN PE.SHORTDESCRIPTION = 'EPICC 6 Month' 
		THEN ESIXM.PROGRAM_PARTICIPATION_SIXM_DESCRIPTION
	END AS [PROGRAM_PARTICIPATION],
	DATEADD(
		DAY,
		-PE.EARLYPERIOD,
		CAST(
			PEC.STARTDATE AS DATE
			)
	) AS [EARLIEST_START_DATE],
	CAST(PEC.STARTDATE AS DATE) AS [EVENT_START_DATE],
	CAST(PEC.ENDDATE AS DATE) AS [EVENT_END_DATE],
	DATEADD(
		DAY, PE.LATEPERIOD,
		CAST(
			PEC.ENDDATE AS DATE
			)
	) AS [LATEST_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [PE_DATE_ACCOMPLISHED],
	CASE
		WHEN PEC.DATEACCOMPLISHED IS NULL 
		THEN DATEDIFF(DAY, GETDATE(), PEC.ENDDATE)
	END AS [DAYS_UNTIL_FORM_DUE],
	PEC.CURRENTMESSAGE AS [CURRENT_MESSAGE],
	HR.EMPLOYEENUMBER AS [PROGRAM_WORKER_EMPLOYEE_NUMBER],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST]
FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.CLOSINGREASONS AS [CR]
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN (
	SELECT 
		PC.*,
		'DOCSERNO Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_DOCSERNO]
	ON PP.CLIENTNUMBER = PC_DOCSERNO.CLIENTNUMBER
	AND PC_DOCSERNO.DOCSERNO = PP.DOCSERNO
LEFT JOIN (
	SELECT 
		PC.*,
		'Enrollment/Pathway Start Date Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_START]
	ON PP.CLIENTNUMBER = PC_START.CLIENTNUMBER
	AND PP.STARTINGDATE = PC_START.STARTDATE
	AND PP.PATHWAY = PC_START.PARENTDOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENTCLIENT AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.PATHCLIENTDOCSERNO = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAYEVENT AS [PE]
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN BEHAVHEALT_LIVE.DBO.PATHWAY AS [PWY]
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDER AS [P]
	ON PP.PRIMARYPROVIDERCODE = P.PROVIDERCODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_HRFORM AS [HRR]
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_REFERRAL AS [EREF]
	ON EREF.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND EREF.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND EREF.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_IC AS [EIC]
	ON EIC.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND EIC.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND EIC.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_TWO_WEEK AS [ETWOW]
	ON ETWOW.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ETWOW.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND ETWOW.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_THIRTY_DAY AS [ETHIRTYD]
	ON ETHIRTYD.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ETHIRTYD.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND ETHIRTYD.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_THREE_MONTH AS [ETHREEM]
	ON ETHREEM.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ETHREEM.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND ETHREEM.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_EPICC_SIX_MONTH AS [ESIXM] 
	ON ESIXM.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807113504583
	AND ESIXM.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND ESIXM.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN (
	SELECT 
		PRIMARYPROVIDERCODE,
		PARENTDOCSERNO,
		DOCREVNO,
		STARTINGDATE,
		ROW_NUMBER() OVER (
			PARTITION BY PARENTDOCSERNO
			ORDER BY STARTINGDATE DESC, VISITDT DESC, VISITTM DESC
		) AS [RN]
	FROM PRIMARYPROVIDERCODEHISTORY
	WHERE PRIMARYPROVIDERCODE <> '100030'
) AS [PROGHISTORY]
	ON PP.DOCSERNO = PROGHISTORY.PARENTDOCSERNO
	AND PROGHISTORY.RN = 1
LEFT JOIN Q_PROVIDER AS [P2]
    ON PROGHISTORY.PRIMARYPROVIDERCODE = P2.PROVIDERCODE
WHERE PP.PATHWAY = 55320240807113504583
	AND PEC.CLIENTNUMBER IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';