/*
View Name: Q_EPICC_IC  
Category: View Definitions  

See docs/view-definitions/q-epicc-ic.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_EPICC_IC AS
SELECT EIC.ID,
	EIC.DOCSERNO,
	EIC.TIEDENROLLMENT,
	CAST(EIC.VISITDT AS DATE) AS [VISIT_DATE],
	EIC.VISITTM AS [VISIT_TIME],
	EIC.USERID,
	EIC.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'EPICC Initial Contact' AS [EVENT_NAME],
	EIC.CLIENTNUMBER AS [CLIENT_NUMBER],
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	TIME_REFERRAL_PLACED,
	TIME_RECOVERY_COACH_ARRIVAL,
	TIME_RECOVERY_COACH_RESPONSE,
	EPICC_PRO_OR_CORE_IC,
	HEARD_ABOUT_FROM_FRIEND_FAMILY,
	HEARD_ABOUT_FROM_COMMUNITY_CENTER,
	HEARD_ABOUT_FROM_OUTREACH_WORKER,
	HEARD_ABOUT_FROM_HOSPITAL_STAFF,
	HEARD_ABOUT_FROM_FLYER,
	HEARD_ABOUT_FROM_CHURCH,
	HEARD_ABOUT_FROM_OTHER,
	PROGRAM_PARTICIPATION_IC AS [EPICC_PROGRAM_PARTICIPATION_IC_CODE],
	EPP.DESCRIPTION AS [EPICC_PROGRAM_PARTICIPATION_IC_DESCRIPTION],
	TREATMENT_PATH_IC,
	TREATMENT_PATH_IC_UNKNOWN,
	WHO_INITIATED_REFERRAL,
	COMMUNITY_REFERRAL_SOURCE_IC AS [COMMUNITY_REFERRAL_SOURCE_IC_CODE],
	CRS.DESCRIPTION AS [COMMUNITY_REFERRAL_SOURCE_IC_DESCRIPTION],
	TYPE_CONTACT_IC,
	REASON_IC_NOT_SUCCESS,
	CONSENT_CRC_REFERRAL_IC,
	REASON_CONSENT_REFUSED_CRC_IC,
	EPICC_OPIOIDS_OF_USE,
	OPIOID_OF_USE_FENTANYL,
	OPIOID_OF_USE_HEROIN,
	OPIOID_OF_USE_PRESCRIPTION_OPIATES,
	OPIOID_OF_USE_SUBOXONE_MAT,
	OPIOID_OF_USE_OTHER,
	OPIOID_OF_USE_NA,
	OTHER_OPIOID_IC,
	OVERDOSE_EVENT_REFERRAL,
	OVERDOSE_EVENT_REFERRAL_UNKNOWN,
	OVERDOSE_LOCATION,
	SPECIFY_OTHER_LOCATION,
	FIRST_OVERDOSE,
	MOST_RECENT_PAST_OVERDOSE_DATE,
	MOST_RECENT_PAST_OVERDOSE_DATE_UNKNOWN,
	NUM_PAST_OVERDOSES,
	SU_TREATMENT_PAST_TWELVE_MOS,
	SU_TREATMENT_PAST_TWELVE_MOS_UNKNOWN,
	CURRENT_SU_TREATMENT,
	CURRENT_SU_TREATMENT_UNKNOWN,
	OPIOID_PRESCRIPTION_LONG_TERM_PAIN_MGMT,
	OPIOID_PRESCRIPTION_LONG_TERM_PAIN_MGMT_UNKNOWN,
	EVER_PRESCRIPTION_MAT_NOT_REFERRAL,
	EVER_PRESCRIPTION_MAT_NOT_REFERRAL_UNKNOWN,
	CURRENT_SCRIPT_MAT_NOT_REFERRAL,
	CURRENT_SCRIPT_MAT_NOT_REFERRAL_UNKNOWN,
	CURRENT_SCRIPT_MAT_TYPE AS [CURRENT_SCRIPT_MAT_TYPE_CODE],
	CURRENT_MAT.DESCRIPTION AS [CURRENT_SCRIPT_MAT_TYPE_DESCRIPTION],
	MAT_INITIATED_HOSPITAL,
	WHAT_MAT_INITIATED_HOSPITAL AS [WHAT_MAT_INITIATED_HOSPITAL_CODE],
	HOSPITAL_MAT.DESCRIPTION AS [WHAT_MAT_INITIATED_HOSPITAL_DESCRIPTION],
	MAT_SCRIPT_DISCHARGE,
	MAT_SCRIPT_DISCHARGE_UNKNOWN,
	WHAT_MAT_SCRIPT_DISCHARGE AS [WHAT_MAT_SCRIPT_DISCHARGE_CODE],
	DISCHARGE_MAT.DESCRIPTION AS [WHAT_MAT_SCRIPT_DISCHARGE_DESCRIPTION],
	OVERDOSE_ED_PROVIDED,
	REASON_OE_NOT_PROVIDED,
	NARCAN_DISTRIBUTED,
	REASON_NARCAN_NOT_DISTRIBUTED,
	NO_NARCAN_EXP,
	IF_OTHER_SPECIFY,
	PREG_POST_PART_IC,
	PREG_POST_PART_IC_UNKNOWN,
	VETERAN_STATUS,
	TRANSFER_TYPE_IC,
	IF_TRANSFER_WHAT_REGION_IC,
	IF_TRANSFER_CONTACT_TRANSFER_REGION_SUCCESS_IC,
	WHY_NOT_MEET_PROG_ELIGIBILITY_IC,
	STATUS_UNABLE_CONTACT_TRANSFER,
	REASON_NOT_PARTICIPATING_IC,
	NON_OPIOID_SUBSTANCE_ALCOHOL,
	NON_OPIOID_SUBSTANCE_CANNABIS,
	NON_OPIOID_SUBSTANCE_HALLUCINOGEN,
	NON_OPIOID_SUBSTANCE_INHALANT,
	NON_OPIOID_SUBSTANCE_PCP,
	NON_OPIOID_SUBSTANCE_STIMULANT,
	NON_OPIOID_SUBSTANCE_DEPRESSANT,
	NON_OPIOID_SUBSTANCE_OTHER,
	PRESENTING_NOTES_IC
FROM BEHAVHEALT_LIVE.DBO.PWEPICCINITIALCONTACT AS [EIC]
LEFT JOIN EPICC_PROGRAM_PARTICIPATION AS [EPP]
	ON EIC.PROGRAM_PARTICIPATION_IC = EPP.CODE
INNER JOIN Q_CLIENT_BHN AS [C]
	ON EIC.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN COMMUNITY_REFERRAL_SOURCE AS [CRS]
	ON EIC.COMMUNITY_REFERRAL_SOURCE_IC = CRS.CODE
LEFT JOIN EPICC_TYPES_MAT AS [CURRENT_MAT]
	ON EIC.CURRENT_SCRIPT_MAT_TYPE = CURRENT_MAT.CODE
LEFT JOIN EPICC_TYPES_MAT AS [HOSPITAL_MAT]
	ON EIC.WHAT_MAT_INITIATED_HOSPITAL = HOSPITAL_MAT.CODE
LEFT JOIN EPICC_TYPES_MAT AS [DISCHARGE_MAT]
	ON EIC.WHAT_MAT_SCRIPT_DISCHARGE = DISCHARGE_MAT.CODE
WHERE EIC.DOCREVNO = ' 0 ';