/*
View Name: Q_EPICC_ALL_SU_TX_AGENCY  
Category: View Definitions  

See docs/view-definitions/q-epicc-all-su-tx-agency.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_EPICC_ALL_SU_TX_AGENCY AS
WITH [SUTX_BASE] AS (
	SELECT 
		SUTX.ID,
		SUTX.CLIENTNUMBER,
		SUTX.DOCSERNO,
		-- Normalize PARENTDOCSERNO once
		NULLIF(LTRIM(RTRIM(SUTX.PARENTDOCSERNO)), '') AS [PARENTDOCSERNO_CLEAN],
		CASE
			WHEN LTRIM(RTRIM(SUTX.PARENTDOCSERNO)) = '' 
			THEN 1
			ELSE 0 
		END AS [PARENTDOCSERNO_ISNULL],
		SUTX.USERID,
		CAST(SUTX.VISITDT AS DATE) AS [VISITDT],
		CAST(SUTX.START_DATE AS DATE) AS [START_DATE],
		CAST(SUTX.END_DATE AS DATE) AS [END_DATE],
		CAST(SUTX.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
		CAST(SUTX.PATHWAY_DATE_JOINKEY AS DATE) AS [PATHWAY_DATE_JOINKEY], -- normalize once
		SUTX.EPICC_SU_TX_AGENCY,
		SUTX.IF_OTHER_SPECIFY,
		SUTX.PFH_TX_FACILITY,
		CAST(SUTX.SU_TX_INTAKE_DATE AS DATE) AS [SU_TX_INTAKE_DATE],
		SUTX.SU_TX_INTAKE,
		SUTX.WAS_INTAKE_COMPLETED,
		SUTX.INTAKE_NOT_COMPLETED,
		SUTX.INTAKE_NOT_COMPLETED_OTHER,
		SUTX.COACH_ATTEND_INTAKE,
		SUTX.CES_ATTEND_INTAKE,
		SUTX.COACH_NOT_ATTEND_INTAKE,
		SUTX.CES_NOT_ATTEND_INTAKE
	FROM dbo.PWSUBROADTREATMENTAGENCY AS [SUTX]
	WHERE SUTX.DOCREVNO = ' 0 '
),
[CTE_FORM_MATCH] AS (
	SELECT 
		SUTX_BASE.ID,
		COALESCE(
			EIC_DATE.DOCSERNO,
			EIC_DOC.DOCSERNO,
			ETWOW_DATE.DOCSERNO,
			ETWOW_DOC.DOCSERNO,
			ETHIRTYD_DATE.DOCSERNO,
			ETHIRTYD_DOC.DOCSERNO,
			ETHREEM_DATE.DOCSERNO,
			ETHREEM_DOC.DOCSERNO,
			ESIXM_DATE.DOCSERNO,
			ESIXM_DOC.DOCSERNO
		) AS [MATCHED_DOCSERNO],
		-- Imported summation records lack PATHWAY_DATE, so *_DATE joins will never match.
		-- This CASE for parent Pathway Form reflects only *_DOC matches, which are valid for front-end-entered records.
		CASE
			WHEN EIC_DOC.DOCSERNO IS NOT NULL OR EIC_DATE.DOCSERNO IS NOT NULL
			THEN 'EPICC Initial Contact'
			WHEN ETWOW_DOC.DOCSERNO IS NOT NULL OR ETWOW_DATE.DOCSERNO IS NOT NULL
			THEN 'EPICC 2 Week'
			WHEN ETHIRTYD_DOC.DOCSERNO IS NOT NULL OR ETHIRTYD_DATE.DOCSERNO IS NOT NULL
			THEN 'EPICC 30 Day'
			WHEN ETHREEM_DOC.DOCSERNO IS NOT NULL OR ETHREEM_DATE.DOCSERNO IS NOT NULL
			THEN 'EPICC 3 Month'
			WHEN ESIXM_DOC.DOCSERNO IS NOT NULL OR ESIXM_DATE.DOCSERNO IS NOT NULL
			THEN 'EPICC 6 Month'
			ELSE NULL
		END AS [PARENT_PWY_EVENT]
	FROM SUTX_BASE
	-- Match by START_DATE = PATHWAY_DATE when PARENTDOCSERNO is NULL
	LEFT JOIN Q_EPICC_IC AS [EIC_DATE]
		ON SUTX_BASE.CLIENTNUMBER = EIC_DATE.CLIENT_NUMBER
		AND SUTX_BASE.PARENTDOCSERNO_ISNULL = 1
		AND SUTX_BASE.PATHWAY_DATE_JOINKEY = EIC_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_TWO_WEEK AS [ETWOW_DATE]
		ON SUTX_BASE.CLIENTNUMBER = ETWOW_DATE.CLIENT_NUMBER
		AND SUTX_BASE.PARENTDOCSERNO_ISNULL = 1
		AND SUTX_BASE.PATHWAY_DATE_JOINKEY = ETWOW_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THIRTY_DAY AS [ETHIRTYD_DATE]
		ON SUTX_BASE.CLIENTNUMBER = ETHIRTYD_DATE.CLIENT_NUMBER
		AND SUTX_BASE.PARENTDOCSERNO_ISNULL = 1
		AND SUTX_BASE.PATHWAY_DATE_JOINKEY = ETHIRTYD_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_THREE_MONTH AS [ETHREEM_DATE]
		ON SUTX_BASE.CLIENTNUMBER = ETHREEM_DATE.CLIENT_NUMBER
		AND SUTX_BASE.PARENTDOCSERNO_ISNULL = 1
		AND SUTX_BASE.PATHWAY_DATE_JOINKEY = ETHREEM_DATE.PATHWAY_DATE
	LEFT JOIN Q_EPICC_SIX_MONTH AS [ESIXM_DATE]
		ON SUTX_BASE.CLIENTNUMBER = ESIXM_DATE.CLIENT_NUMBER
		AND SUTX_BASE.PARENTDOCSERNO_ISNULL = 1
		AND SUTX_BASE.PATHWAY_DATE_JOINKEY = ESIXM_DATE.PATHWAY_DATE
	-- Match by PARENTDOCSERNO = DOCSERNO when PARENTDOCSERNO is NOT NULL
	-- Joining on CLIENT_NUMBER is not necessary here since PARENTDOCSERNO is unique
	LEFT JOIN Q_EPICC_IC AS [EIC_DOC]
		ON SUTX_BASE.PARENTDOCSERNO_CLEAN = EIC_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_TWO_WEEK AS [ETWOW_DOC]
		ON SUTX_BASE.PARENTDOCSERNO_CLEAN = ETWOW_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_THIRTY_DAY AS [ETHIRTYD_DOC]
		ON SUTX_BASE.PARENTDOCSERNO_CLEAN = ETHIRTYD_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_THREE_MONTH AS [ETHREEM_DOC]
		ON SUTX_BASE.PARENTDOCSERNO_CLEAN = ETHREEM_DOC.DOCSERNO
	LEFT JOIN Q_EPICC_SIX_MONTH AS [ESIXM_DOC]
		ON SUTX_BASE.PARENTDOCSERNO_CLEAN = ESIXM_DOC.DOCSERNO
)
SELECT 
	SUTX_BASE.ID,
	SUTX_BASE.DOCSERNO,
	CAST(SUTX_BASE.VISITDT AS DATE) AS [VISITDT],
	SUTX_BASE.USERID,
	FM.MATCHED_DOCSERNO AS [PARENT_DOCSERNO],
	FM.PARENT_PWY_EVENT,
	C.CLIENT_NUMBER,
	CAST(SUTX_BASE.START_DATE AS DATE) AS [START_DATE],
	CAST(SUTX_BASE.END_DATE AS DATE) AS [END_DATE],
	SUTX_BASE.PATHWAY_DATE_JOINKEY AS [PATHWAY_DATE],
	SUTX_BASE.EPICC_SU_TX_AGENCY AS [EPICC_SU_TX_AGENCY_CODE],
	SUTXAGENCY.DESCRIPTION AS [EPICC_SU_TX_AGENCY_DESCRIPTION],
	SUTX_BASE.IF_OTHER_SPECIFY,
	SUTX_BASE.PFH_TX_FACILITY AS [PFH_TX_FACILITY_CODE],
	PFHSUTXAGENCY.DESCRIPTION AS [PFH_TX_FACILITY_DESCRIPTION],
	CAST(SUTX_BASE.SU_TX_INTAKE_DATE AS DATE) AS [SU_TX_INTAKE_DATE],
	SUTX_BASE.SU_TX_INTAKE,
	SUTX_BASE.WAS_INTAKE_COMPLETED,
	SUTX_BASE.INTAKE_NOT_COMPLETED,
	SUTX_BASE.INTAKE_NOT_COMPLETED_OTHER,
	SUTX_BASE.COACH_ATTEND_INTAKE,
	SUTX_BASE.CES_ATTEND_INTAKE,
	SUTX_BASE.COACH_NOT_ATTEND_INTAKE,
	SUTX_BASE.CES_NOT_ATTEND_INTAKE
FROM SUTX_BASE
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = SUTX_BASE.CLIENTNUMBER
LEFT JOIN EPICC_SU_TX_AGENCY AS [SUTXAGENCY]
	ON SUTX_BASE.EPICC_SU_TX_AGENCY = SUTXAGENCY.CODE
LEFT JOIN EPICC_SU_TX_AGENCY AS [PFHSUTXAGENCY]
	ON SUTX_BASE.PFH_TX_FACILITY = PFHSUTXAGENCY.CODE
LEFT JOIN CTE_FORM_MATCH AS [FM]
	ON SUTX_BASE.ID = FM.ID;