/*
View Name: Q_ERE_BHS_DATE_VALIDATION_EXCEPTIONS
Category: View Definitions  

See docs/view-definitions/q-ere-bhs-date-validation-exceptions.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_ERE_BHS_DATE_VALIDATION_EXCEPTIONS AS
WITH [REFERRAL] AS (
	SELECT EREENROLL.CLIENT_NUMBER,
		EREENROLL.TIEDENROLLMENT,
		EREENROLL.ENROLLMENT_STARTING_DATE,
		EREENROLL.ENROLLMENT_ENDING_DATE,
		EREENROLL.PWY_FORMS_DOCSERNO,
		EREENROLL.PATHWAY_DATE
	FROM Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
		LEFT JOIN Q_ERE_REFERRAL AS [EREREF] ON EREREF.DOCSERNO = EREENROLL.PWY_FORMS_DOCSERNO
	WHERE EREENROLL.PWY_EVENT = 'ERE Referral'
		AND PWY_FORMS_DOCSERNO IS NOT NULL
),
[BHS] AS (
	SELECT EREENROLL.CLIENT_NUMBER,
		EREENROLL.TIEDENROLLMENT,
		EREENROLL.PWY_FORMS_DOCSERNO,
		EREENROLL.PATHWAY_DATE,
		EREBHS.ADMITTED_TO_SERVICES,
		EREBHS.BH_ADMISSION_DATE,
		EREBHS.SU_ADMISSION_DATE
	FROM Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
		LEFT JOIN Q_ERE_BHS AS [EREBHS] ON EREBHS.DOCSERNO = EREENROLL.PWY_FORMS_DOCSERNO
	WHERE EREENROLL.PWY_EVENT = 'ERE Behavioral Health Service'
		AND PWY_FORMS_DOCSERNO IS NOT NULL
		AND EREBHS.ADMITTED_TO_SERVICES = 'Yes'
		AND NOT (
			EREBHS.BH_ADMISSION_DATE IS NULL
			AND EREBHS.SU_ADMISSION_DATE IS NULL
		)
)
SELECT REF.CLIENT_NUMBER,
	REF.ENROLLMENT_STARTING_DATE,
	REF.ENROLLMENT_ENDING_DATE,
	REF.PATHWAY_DATE AS [REF_PATHWAY_DATE],
	BHS.PATHWAY_DATE AS [BHS_PATHWAY_DATE],
	BHS.BH_ADMISSION_DATE,
	BHS.SU_ADMISSION_DATE,
	/* ------------ 1. REFERRAL BEFORE ENROLLMENT? ------------ */
	CASE
		WHEN REF.PATHWAY_DATE < REF.ENROLLMENT_STARTING_DATE THEN 'REF BEFORE ENROLLMENT'
		ELSE NULL
	END AS [REF_DATE_ISSUE],
	/* ------------ 2. ADMISSION DATE OUTSIDE ENROLLMENT WINDOW? ------------ */
	CASE
		WHEN BHS.BH_ADMISSION_DATE IS NOT NULL
		AND (
			BHS.BH_ADMISSION_DATE < REF.ENROLLMENT_STARTING_DATE
			OR (
				REF.ENROLLMENT_ENDING_DATE IS NOT NULL
				AND BHS.BH_ADMISSION_DATE > REF.ENROLLMENT_ENDING_DATE
			)
		) THEN 'BH ADMISSION OUTSIDE ENROLLMENT'
		ELSE NULL
	END AS [BH_ADMISSION_ISSUE],
	CASE
		WHEN BHS.SU_ADMISSION_DATE IS NOT NULL
		AND (
			BHS.SU_ADMISSION_DATE < REF.ENROLLMENT_STARTING_DATE
			OR (
				REF.ENROLLMENT_ENDING_DATE IS NOT NULL
				AND BHS.SU_ADMISSION_DATE > REF.ENROLLMENT_ENDING_DATE
			)
		) THEN 'SU ADMISSION OUTSIDE ENROLLMENT'
		ELSE NULL
	END AS [SU_ADMISSION_ISSUE]
FROM REFERRAL AS [REF]
	LEFT JOIN BHS AS [BHS] ON BHS.TIEDENROLLMENT = REF.TIEDENROLLMENT
WHERE
	/* Only show rows with issues */
	(
		REF.PATHWAY_DATE < REF.ENROLLMENT_STARTING_DATE
		OR (
			BHS.BH_ADMISSION_DATE IS NOT NULL
			AND (
				BHS.BH_ADMISSION_DATE < REF.ENROLLMENT_STARTING_DATE
				OR (
					REF.ENROLLMENT_ENDING_DATE IS NOT NULL
					AND BHS.BH_ADMISSION_DATE > REF.ENROLLMENT_ENDING_DATE
				)
			)
		)
		OR (
			BHS.SU_ADMISSION_DATE IS NOT NULL
			AND (
				BHS.SU_ADMISSION_DATE < REF.ENROLLMENT_STARTING_DATE
				OR (
					REF.ENROLLMENT_ENDING_DATE IS NOT NULL
					AND BHS.SU_ADMISSION_DATE > REF.ENROLLMENT_ENDING_DATE
				)
			)
		)
	);