/*
View Name: Q_ERE_PATHCLIENT_ENROLLMENTS  
Category: View Definitions  

See docs/view-definitions/q-ere-pathclient-enrollments.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_ERE_PATHCLIENT_ENROLLMENTS AS
SELECT C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	DATEDIFF(YEAR, C.BIRTH_DATE, PP.STARTINGDATE)
	- CASE 
		WHEN DATEADD(
				YEAR, 
				DATEDIFF(YEAR, C.BIRTH_DATE, PP.STARTINGDATE), 
				C.BIRTH_DATE
			) > PP.STARTINGDATE 
		THEN 1 
		ELSE 0 
	END AS [AGE_AT_ENROLLMENT],
	PEC.USERID AS [PEC_USERID],
	PEC.LASTUPDATEBY AS [PEC_LAST_UPDATE_BY],
	PP.DOCSERNO AS [PP_DOCSERNO],
	COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) AS [PC_DOCSERNO],
	PEC.PATHCLIENTDOCSERNO AS [PEC_PATHCLIENT_DOCSERNO],
		CASE
		WHEN PE.SHORTDESCRIPTION = 'ERE Referral' 
		THEN EREREF.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'ERE Hospital Visit Note'
		THEN EREHOSP.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'ERE IHNA' 
		THEN IHNA.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'ERE 3 Month' 
		THEN ERETHREEM.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'ERE 6 Month' 
		THEN ERESIXM.TIEDENROLLMENT
		WHEN PE.SHORTDESCRIPTION = 'ERE Behavioral Health Service' 
		THEN EREBHS.TIEDENROLLMENT
	END AS [TIEDENROLLMENT],
	CASE 
		WHEN 
			CASE
				WHEN PE.SHORTDESCRIPTION = 'ERE Referral' 
				THEN EREREF.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE Hospital Visit Note' 
				THEN EREHOSP.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE IHNA' 
				THEN IHNA.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE 3 Month' 
				THEN ERETHREEM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE 6 Month' 
				THEN ERESIXM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE Behavioral Health Service' 
				THEN EREBHS.TIEDENROLLMENT
			END IS NULL 
		THEN NULL
		WHEN COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) = 
			CASE
				WHEN PE.SHORTDESCRIPTION = 'ERE Referral' 
				THEN EREREF.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE Hospital Visit Note' 
				THEN EREHOSP.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE IHNA' 
				THEN IHNA.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE 3 Month' 
				THEN ERETHREEM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE 6 Month' 
				THEN ERESIXM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'ERE Behavioral Health Service' 
				THEN EREBHS.TIEDENROLLMENT
			END 
		THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS [TIEDENROLLMENT_MATCH],
	COALESCE(PC_DOCSERNO.JOIN_TYPE, PC_START.JOIN_TYPE) AS [ENROLL_PATH_JOIN_SOURCE],
	PP.PRIMARYPROVIDERCODE AS [AGENCY_CODE],
	P.PROVIDERNAME AS [AGENCY_DESCRIPTION],
	CAST(COALESCE(PC_DOCSERNO.STARTDATE, PC_START.ENDDATE) AS DATE) AS [PWY_START_DATE],
	CAST(COALESCE(PC_DOCSERNO.ENDDATE, PC_START.ENDDATE) AS DATE) AS [PWY_END_DATE],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'ERE Referral' 
		THEN EREREF.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'ERE Hospital Visit Note'
		THEN EREHOSP.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'ERE IHNA' 
		THEN IHNA.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'ERE 3 Month' 
		THEN ERETHREEM.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'ERE 6 Month' 
		THEN ERESIXM.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'ERE Behavioral Health Service' 
		THEN EREBHS.DOCSERNO
	END AS [PWY_FORMS_DOCSERNO],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'ERE Referral' 
		THEN EREREF.VISITDT
		WHEN PE.SHORTDESCRIPTION = 'ERE Hospital Visit Note'
		THEN EREHOSP.VISITDT
		WHEN PE.SHORTDESCRIPTION = 'ERE IHNA' 
		THEN IHNA.VISITDT
		WHEN PE.SHORTDESCRIPTION = 'ERE 3 Month' 
		THEN ERETHREEM.VISITDT
		WHEN PE.SHORTDESCRIPTION = 'ERE 6 Month' 
		THEN ERESIXM.VISITDT
		WHEN PE.SHORTDESCRIPTION = 'ERE Behavioral Health Service' 
		THEN EREBHS.VISITDT
	END AS [PWY_FORMS_VISIT_DATE],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'ERE Referral' 
		THEN EREREF.VISITTM
		WHEN PE.SHORTDESCRIPTION = 'ERE Hospital Visit Note'
		THEN EREHOSP.VISITTM
		WHEN PE.SHORTDESCRIPTION = 'ERE IHNA' 
		THEN IHNA.VISITTM
		WHEN PE.SHORTDESCRIPTION = 'ERE 3 Month' 
		THEN ERETHREEM.VISITTM
		WHEN PE.SHORTDESCRIPTION = 'ERE 6 Month' 
		THEN ERESIXM.VISITTM
		WHEN PE.SHORTDESCRIPTION = 'ERE Behavioral Health Service' 
		THEN EREBHS.VISITTM
	END AS [PWY_FORMS_VISIT_TIME],
	CAST(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'ERE Referral' 
			THEN EREREF.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'ERE Hospital Visit Note'
			THEN EREHOSP.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'ERE IHNA' 
			THEN IHNA.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'ERE 3 Month' 
			THEN ERETHREEM.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'ERE 6 Month' 
			THEN ERESIXM.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'ERE Behavioral Health Service' 
			THEN EREBHS.PATHWAY_DATE
		END AS DATE
	) AS [PATHWAY_DATE],
	DATEADD(
		DAY,
		-PE.EARLYPERIOD,
		CAST(
			PEC.STARTDATE AS DATE
			)
	) AS [EARLIEST_START_DATE],
	CAST(PEC.STARTDATE AS DATE) AS [EVENT_START_DATE],
	CAST(PEC.ENDDATE AS DATE) AS [EVENT_END_DATE],
	DATEADD(
		DAY, PE.LATEPERIOD,
		CAST(
			PEC.ENDDATE AS DATE
			)
	) AS [LATEST_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [PE_DATE_ACCOMPLISHED],
	CASE
		WHEN PEC.DATEACCOMPLISHED IS NULL 
		THEN DATEDIFF(DAY, GETDATE(), PEC.ENDDATE)
	END AS [DAYS_UNTIL_FORM_DUE],
	PEC.CURRENTMESSAGE AS [CURRENT_MESSAGE],
	HR.EMPLOYEENUMBER AS [PROGRAM_WORKER_EMPLOYEE_NUMBER],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST]
FROM DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN DBO.CLOSINGREASONS AS [CR] 
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN (
	SELECT 
		PC.*,
		'DOCSERNO Join' AS [JOIN_TYPE]
	FROM DBO.PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_DOCSERNO]
	ON PP.CLIENTNUMBER = PC_DOCSERNO.CLIENTNUMBER
	AND PC_DOCSERNO.DOCSERNO = PP.DOCSERNO
LEFT JOIN (
	SELECT 
		PC.*,
		'Enrollment/Pathway Start Date Join' AS [JOIN_TYPE]
	FROM DBO.PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_START]
	ON PP.CLIENTNUMBER = PC_START.CLIENTNUMBER
	AND PP.STARTINGDATE = PC_START.STARTDATE
	AND PP.PATHWAY = PC_START.PARENTDOCSERNO
LEFT JOIN DBO.PATHWAYEVENTCLIENT AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.PATHCLIENTDOCSERNO = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN DBO.PATHWAYEVENT AS [PE] 
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN DBO.PATHWAY AS [PWY] 
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
LEFT JOIN DBO.Q_PROVIDER AS [P] 
	ON PP.PRIMARYPROVIDERCODE = P.PROVIDERCODE
LEFT JOIN DBO.Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN DBO.Q_HRFORM AS [HRR]
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
LEFT JOIN DBO.Q_ERE_REFERRAL AS [EREREF] 
	ON EREREF.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320250326123001961
	AND EREREF.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND EREREF.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN DBO.Q_ERE_IHNA AS [IHNA] 
	ON IHNA.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320250326123001961
	AND IHNA.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND IHNA.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN DBO.Q_ERE_THREE_MONTH AS [ERETHREEM] 
	ON ERETHREEM.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320250326123001961
	AND ERETHREEM.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND ERETHREEM.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN DBO.Q_ERE_SIX_MONTH AS [ERESIXM] 
	ON ERESIXM.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND ERESIXM.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PP.PATHWAY = 55320250326123001961
	AND ERESIXM.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN DBO.Q_ERE_BHS AS [EREBHS] 
	ON EREBHS.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND EREBHS.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND EREBHS.EVENT_NAME = PE.SHORTDESCRIPTION
	AND PP.PATHWAY = 55320250326123001961
LEFT JOIN DBO.Q_ERE_HOSPITAL_VISIT_NOTE AS [EREHOSP]
	ON EREHOSP.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND EREHOSP.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND EREHOSP.EVENT_NAME = PE.SHORTDESCRIPTION
	AND PP.PATHWAY = 55320250326123001961
WHERE PP.PATHWAY = 55320250326123001961
	AND PEC.CLIENTNUMBER IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';