/*
View Name: Q_ERE_DELETED_PATHWAY_FORM_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-ere-deleted-pathway-form-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_ERE_DELETED_PATHWAY_FORM_DOCSERNOS AS
SELECT EREREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREREF.DOCSERNO,
	EREREF.TIEDENROLLMENT,
	'ERE Referral' AS [FORM_TYPE]
FROM DBO.PWEREREFERRAL AS [EREREF]
INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = EREREF.CLIENTNUMBER
WHERE EREREF.DOCREVNO = '888'
UNION ALL
SELECT EREIHNA.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREIHNA.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREIHNA.DOCSERNO,
	EREIHNA.TIEDENROLLMENT,
	'ERE IHNA' AS [FORM_TYPE]
FROM DBO.PWEREIHNA AS [EREIHNA]
INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = EREIHNA.CLIENTNUMBER
WHERE EREIHNA.DOCREVNO = '888'
UNION ALL
SELECT ERETHREEM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ERETHREEM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ERETHREEM.DOCSERNO,
	ERETHREEM.TIEDENROLLMENT,
	'ERE 3-Month Follow-Up' AS [FORM_TYPE]
FROM DBO.PWERETHREEMONTHFOLLOWUP AS [ERETHREEM]
INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = ERETHREEM.CLIENTNUMBER
WHERE ERETHREEM.DOCREVNO = '888'
UNION ALL
SELECT ERESIXM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ERESIXM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ERESIXM.DOCSERNO,
	ERESIXM.TIEDENROLLMENT,
	'ERE 6-Month Follow-Up' AS [FORM_TYPE]
FROM DBO.PWERESIXMONTHFOLLOWUP AS [ERESIXM]
INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = ERESIXM.CLIENTNUMBER
WHERE ERESIXM.DOCREVNO = '888'
UNION ALL
SELECT EREBHS.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREBHS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREBHS.DOCSERNO,
	EREBHS.TIEDENROLLMENT,
	'ERE BHS' AS [FORM_TYPE]
FROM DBO.PWEREBEHAVIORALHEALTHSERVICE AS [EREBHS]
INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = EREBHS.CLIENTNUMBER
WHERE EREBHS.DOCREVNO = '888';