/*
View Name: Q_ERE_ACTIVE_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-ere-active-housing-status.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_ERE_ACTIVE_HOUSING_STATUS AS
WITH [LATESTHOUSINGSTART] AS (
	SELECT CLIENT_NUMBER, 
		   MAX(HOUSING_START_DATE) AS [MAXSTARTDATE]
	FROM BEHAVHEALT_LIVE.DBO.Q_ERE_ALL_HOUSING_STATUS
	GROUP BY CLIENT_NUMBER
),
[LATESTHOUSINGSTATUS] AS (
	SELECT EREHOUSE.CLIENT_NUMBER,
		EREHOUSE.DOCSERNO,
		EREHOUSE.PARENT_DOCSERNO,
		EREHOUSE.HOUSING_START_DATE,
		EREHOUSE.CLIENT_HOUSING_STATUS,
		EREHOUSE.IF_UNHOUSED_EXP,
		EREHOUSE.WORRIED_LOSING_HOUSING,
		EREHOUSE.HOMELESS_HOUSING_INSECURE_ETO,
		EREHOUSE.VISITDT,
		EREHOUSE.VISITTM,
		EREHOUSE.USERID,
		EREHOUSE.HOUSING_END_DATE
	FROM BEHAVHEALT_LIVE.DBO.Q_ERE_ALL_HOUSING_STATUS AS [EREHOUSE]
	INNER JOIN LATESTHOUSINGSTART AS [LHS]
		ON EREHOUSE.CLIENT_NUMBER = LHS.CLIENT_NUMBER
	   AND EREHOUSE.HOUSING_START_DATE = LHS.MAXSTARTDATE
	WHERE EREHOUSE.PARENT_DOCSERNO IN (
			SELECT EREPF.DOCSERNO 
			FROM Q_ERE_PATHWAY_FORM_DOCSERNOS AS [EREPF]
	  )
),
[FINALSELECTION] AS (
	SELECT CLIENT_NUMBER,
		MAX(PARENT_DOCSERNO) AS [MAXPARENTDOCSERNO],
		MAX(DOCSERNO) AS [MAXDOCSERNO]
	FROM LATESTHOUSINGSTATUS
	GROUP BY CLIENT_NUMBER
)
SELECT C.CLIENT_NUMBER,
		HS.DOCSERNO,
		HS.PARENT_DOCSERNO,
		CAST(HS.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE],
		CAST(HS.HOUSING_END_DATE AS DATE) AS [HOUSING_END_DATE],
		HS.IF_UNHOUSED_EXP,
		HS.WORRIED_LOSING_HOUSING,
		HS.HOMELESS_HOUSING_INSECURE_ETO,
		CAST(HS.VISITDT AS DATE) AS [VISITDT],
		HS.VISITTM,
		HS.USERID,
		CASE WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
			THEN 1 ELSE 0 END AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	   CASE WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
			THEN 1 ELSE 0 END AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
		CASE WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
			THEN 1 ELSE 0 END AS [HOUSING_STATUS_STABLY_HOUSED],
		CASE WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
			THEN 1 ELSE 0 END AS [HOUSING_STATUS_UNHOUSED],
		CASE WHEN ISNULL(HS.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
			THEN 1 ELSE 0 END AS [HOUSING_STATUS_UNKNOWN]
FROM LATESTHOUSINGSTATUS AS [HS]
INNER JOIN FINALSELECTION AS [FS]
	ON HS.CLIENT_NUMBER = FS.CLIENT_NUMBER
	AND HS.PARENT_DOCSERNO = FS.MAXPARENTDOCSERNO
	AND HS.DOCSERNO = FS.MAXDOCSERNO
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = HS.CLIENT_NUMBER;