/*
View Name: Q_ERE_FAMCARE_UPDATES_TO_ENTER_INTO_CAREMANAGER  
Category: View Definitions  

See docs/view-definitions/q-ere-famcare-updates-to-enter-into-caremanager.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

CREATE VIEW dbo.Q_ERE_FAMCARE_UPDATES_TO_ENTER_INTO_CAREMANAGER AS
SELECT EENROLL.CLIENT_NUMBER,
	EENROLL.CLIENT_LAST,
	EENROLL.CLIENT_FIRST,
	C.BIRTH_DATE,
	EENROLL.ENROLLMENT_STARTING_DATE,
	EENROLL.ENROLLMENT_ENDING_DATE,
	EENROLL.DISMISSAL_REASON_DESCRIPTION,
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'ERE Referral'
			THEN EENROLL.PWY_FORMS_VISIT_DATE 
		END) AS [ERE_REF_VISITDT],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'ERE IHNA'
			THEN EENROLL.PWY_FORMS_VISIT_DATE
		END) AS [ERE_IHNA_VISITDT],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'ERE 3 Month'
			THEN EENROLL.PWY_FORMS_VISIT_DATE
		END) AS [ERE_THREE_MO_VISITDT],
	MAX(
		CASE
			WHEN EENROLL.PWY_EVENT = 'ERE 6 Month'
			THEN EENROLL.PWY_FORMS_VISIT_DATE
		END) AS [ERE_SIX_MO_VISITDT]
FROM Q_ERE_PATHCLIENT_ENROLLMENTS AS [EENROLL]
LEFT JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = EENROLL.CLIENT_NUMBER
WHERE EENROLL.PWY_FORMS_VISIT_DATE IS NOT NULL
	AND (
		EENROLL.DISMISSAL_REASON_DESCRIPTION NOT IN ('Reconnect', 'Re-Referred')
		OR EENROLL.ENROLLMENT_ENDING_DATE IS NULL
		)
GROUP BY EENROLL.CLIENT_NUMBER,
	EENROLL.CLIENT_LAST,
	EENROLL.CLIENT_FIRST,
	C.BIRTH_DATE,
	EENROLL.ENROLLMENT_STARTING_DATE,
	EENROLL.ENROLLMENT_ENDING_DATE,
	EENROLL.DISMISSAL_REASON_DESCRIPTION;