/*
View Name: Q_ERE_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-ere-all-payor-source.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .dbo.Q_ERE_ALL_PAYOR_SOURCE AS
SELECT EREPAY.ID,
	EREPAY.DOCSERNO,
	EREPAY.DOCREVNO,
	CAST(EREPAY.VISITDT AS DATE) AS [VISITDT],
	EREPAY.VISITTM,
	EREPAY.USERID,
	COALESCE(EREIHNA.PARENTDOCSERNO, EREPAY.PARENTDOCSERNO) AS [PARENTDOCSERNO],
	EREPF.FORM_TYPE,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(EREPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREPAY.PAYOR_SOURCE,
	EREPAY.MANAGED_MEDICAID_PROVIDER,
	EREPAY.PRIVATE_INSURANCE_PROVIDER,
	CAST(EREPAY.PAYOR_SOURCE_START_DATE AS DATE) AS PAYOR_SOURCE_START_DATE,
	CAST(EREPAY.PAYOR_SOURCE_END_DATE AS DATE) AS PAYOR_SOURCE_END_DATE
FROM BEHAVHEALT_LIVE.DBO.PWPAYORSOURCE AS [EREPAY]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON EREPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN PWEREIHNA AS [EREIHNA]
	ON EREPAY.CLIENTNUMBER = EREIHNA.CLIENTNUMBER
	AND EREPAY.PATHWAY_DATE = EREIHNA.PATHWAY_DATE
	AND EREPAY.USERID LIKE 'import%'
LEFT JOIN Q_ERE_PATHWAY_FORM_DOCSERNOS AS [EREPF]
	ON COALESCE(EREPAY.PARENTDOCSERNO, EREIHNA.DOCSERNO) = EREPF.DOCSERNO
WHERE EREPAY.DOCREVNO = ' 0 '
	AND COALESCE(EREPAY.PARENTDOCSERNO, EREIHNA.DOCSERNO) IN (
			SELECT EREPF.DOCSERNO 
			FROM Q_ERE_PATHWAY_FORM_DOCSERNOS AS [EREPF]
	);