/*
View Name: Q_ERE_SIX_MONTH  
Category: View Definitions  

See docs/view-definitions/q-ere-six-month.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .DBO.Q_ERE_SIX_MONTH AS
SELECT ERESIXM.ID,
	ERESIXM.DOCSERNO,
	ERESIXM.TIEDENROLLMENT,
	CAST(ERESIXM.VISITDT AS DATE) AS [VISITDT],
	ERESIXM.VISITTM,
	ERESIXM.USERID,
	'ERE 6 Month' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(ERESIXM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ERESIXM.STILL_ENGAGED_ERE_SERVICES_SIX_MONTH,
	ERESIXM.INELIGIBLE_REASON_SIX_MONTH,
	ERESIXM.CONTACT_RESULT_PPC_SIX_MONTH,
	ERESIXM.EMPLOYMENT_STATUS_SIX_MONTH AS [EMPLOYMENT_STATUS_SIX_MONTH_CODE],
	EMPSTATUS.DESCRIPTION AS [EMPLOYMENT_STATUS_SIX_MONTH_DESCRIPTION],
	ERESIXM.NUM_ER_VISITS_PAST_THREE_MONTHS_SIX_MONTH,
	ERESIXM.NUM_HOSP_PAST_THREE_MONTHS_SIX_MONTH,
	ERESIXM.NUM_LEO_CONTACTS_PAST_THREE_MONTHS_SIX_MONTH
FROM BEHAVHEALT_LIVE.DBO.PWERESIXMONTHFOLLOWUP AS [ERESIXM]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON ERESIXM.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.EMPLOYMENTSTATUS AS [EMPSTATUS]
	ON ERESIXM.EMPLOYMENT_STATUS_SIX_MONTH = EMPSTATUS.CODE
WHERE ERESIXM.DOCREVNO = ' 0 ';