/*
View Name: Q_ERE_REFERRAL  
Category: View Definitions  

See docs/view-definitions/q-ere-referral.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_ERE_REFERRAL AS
SELECT EREREF.ID,
EREREF.DOCSERNO,
EREREF.TIEDENROLLMENT,
CAST(EREREF.VISITDT AS DATE) AS [VISITDT],
EREREF.VISITTM,
EREREF.USERID,
'ERE Referral' AS [EVENT_NAME],
C.CLIENT_NUMBER,
C.CLIENT_LAST,
C.CLIENT_FIRST,
CAST(EREREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
EREREF.PATIENT_LOCATION_REFERRAL,
EREREF.FIRST_IP_HOSP,
EREREF.ANSWERFIRST_CASE_NUM,
EREREF.CALLER_NAME,
EREREF.TIME_OF_CALL_REF,
REREF.REFERRING_AGENCY AS [REFERRING_AGENCY_CODE],
PRS.DESCRIPTION AS [REFERRING_AGENCY_DESCRIPTION],
EREREF.REFERRAL_METHOD,
EREREF.SOBERING_CENTER_REFERRAL,
EREREF.EPICC_REFERRAL,
EREREF.EMPLOYMENT_STATUS_REFERRAL AS [EMPLOYMENT_STATUS_REFERRAL_CODE],
EES.DESCRIPTION AS [EMPLOYMENT_STATUS_REFERRAL_DESCRIPTION],
EREREF.MILITARY_STATUS,
EREREF.REFERRAL_REASON,
EREREF.CLIENT_ELIGIBLE,
EREREF.INELIGIBLE_REASON_REFERRAL AS [INELIGIBLE_REASON_REFERRAL_CODE],
EIS.DESCRIPTION AS [INELIGIBLE_REASON_REFERRAL_DESCRIPTION],
EREREF.OTHER_INELIGIBLE_REASON,
EREREF.CLIENT_ENGAGE
FROM DBO.PWEREREFERRAL AS [EREREF]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON EREREF.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PROGRAM_REFERRAL_SOURCES AS [PRS]
	ON EREREF.REFERRING_AGENCY = PRS.CODE
LEFT JOIN DBO.ERE_EMPLOY_STATUS AS [EES]
	ON EREREF.EMPLOYMENT_STATUS_REFERRAL = EES.CODE
LEFT JOIN DBO.ERE_INELIGIBLE_STATUS AS [EIS]
	ON EREREF.INELIGIBLE_REASON_REFERRAL = EIS.CODE
WHERE EREREF.DOCREVNO = ' 0 ';