/*
View Name: Q_ERE_NEEDS_REPORT
Category: View Definitions

See docs/view-definitions/q-ere-needs-report.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_ERE_NEEDS_REPORT AS
WITH [IHNAAGG] AS (
	SELECT
		IHNA.CLIENT_NUMBER,
		IHNA.TIEDENROLLMENT,

		/* Mental Health History Count */
		(
			SUM(CASE WHEN IHNA.MH_HX_ADD_ADHD = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_ALZHEIMERS = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_ANTISOCIAL_PERSONALITY_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_AUTISM_SPECTRUM_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_BIPOLAR_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_BORDERLINE_PERSONALITY_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_DD_INTELLECTUAL_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_DELUSIONAL = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_DEMENTIA = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_DEPRESSION = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_EATING_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_OCD = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_PANIC_ANXIETY = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_PTSD = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_SCHIZOPHRENIA = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_SLEEP_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_OTHER_PSYCHIOTIC_DISORDER = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.MH_HX_OTHER = '1' THEN 1 ELSE 0 END)
		) AS [MH_HISTORY_COUNT],

		/* Substance Use History Count */
		(
			SUM(CASE WHEN IHNA.SU_HX_ALCOHOL = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_COCAINE = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_HALLUCINOGENS = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_HEROIN = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_INHALANTS = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_MARIJUANA = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_METHAMPHETAMINE = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_PRESCRIPTION_OPIOIDS = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_PRESCRIPTION_SEDATIVES = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_PRESCRIPTION_STIMULANTS = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_SYNTHETIC_DRUGS = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_FENTANYL = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.SU_HX_OTHER = '1' THEN 1 ELSE 0 END)
		) AS [SU_HISTORY_COUNT],

		/* Physical Health History Count */
		(
			SUM(CASE WHEN IHNA.PHY_HX_BMI = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_CHRONIC_PAIN = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_CONGESTIVE_HEART_FAILURE = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_COPD_ASTHMA = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_DENTAL_CARE = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_DIABETES = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_HEPATITIS_C = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_HYPERTENTION = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_TOBACCO_USE = '1' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN IHNA.PHY_HX_OTHER = '1' THEN 1 ELSE 0 END)
		) AS [PHYSICAL_HISTORY_COUNT]
	FROM DBO.Q_ERE_IHNA AS [IHNA]
	GROUP BY
		IHNA.CLIENT_NUMBER,
		IHNA.TIEDENROLLMENT
),
[NEEDSAGG] AS (
	SELECT
		E.CLIENT_NUMBER,
		E.TIEDENROLLMENT,
		-- Needs identified (exclude NEED_NONE)
		(
			SUM(CASE WHEN N.NEED_BASIC_NEEDS_ASSISTANCE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_BIRTH_CERTIFICATE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_CHILD_CARE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_COMMUNITY_BASED_ASSISTANCE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_CRISIS_SERVICES = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_DENTAL_CARE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_DEVELOPMENTAL_DISABILITIES_SERVICES = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_EMPLOYMENT_SERVICES = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_FOOD_ASSISTANCE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_HOUSING = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_ID = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_LEGAL_ASSISTANCE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_MENTAL_HEALTH_SERVICES = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_PAYER_ASSISTANCE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_PHYICAL_HEALTH_SERVICES = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_PSYCHIATRY = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_SOCIAL_SECURITY_CARD = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_SUBSTANCE_USE_SERVICES = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_TRANSPORTATION_ASSISTANCE = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.NEED_MEDICATION_ASSISTANCE = 1 THEN 1 ELSE 0 END)
		) AS [NEEDS_IDENTIFIED],
		-- Needs connected (REFERRED_ENGAGED = 1)
		(
			SUM(CASE WHEN N.BASIC_NEEDS_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.BIRTH_CERTIFICATE_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.CHILD_CARE_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.COMMUNITY_BASED_ASSIST_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.CRISIS_SERVICES_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.DENTAL_CARE_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.DD_SERVICES_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.EMPLOYMENT_SERVICES_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.FOOD_ASSIST_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.HOUSING_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.ID_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.LEGAL_ASSIT_REFERRED_ENAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.MH_STATUS_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.PAYOR_SOURCE_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.PHYS_HEALTH_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.PSYCHIATRY_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.SS_CARD_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.SU_SERVICES_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.TRANSPORTATION_ASSIST_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN N.MEDICATION_ASSIST_REFERRED_ENGAGED = 'ON' THEN 1 ELSE 0 END)
		) AS [NEEDS_CONNECTED]
	FROM DBO.Q_ERE_CLIENT_NEEDS AS [N]
	INNER JOIN DBO.Q_ERE_PATHCLIENT_ENROLLMENTS AS [E]
		ON N.PARENT_DOCSERNO = E.PWY_FORMS_DOCSERNO
	GROUP BY
		E.CLIENT_NUMBER,
		E.TIEDENROLLMENT
)
SELECT DISTINCT
	EREENROLL.CLIENT_NUMBER,
	EREENROLL.CLIENT_LAST,
	EREENROLL.CLIENT_FIRST,
	EREENROLL.ENROLLMENT_STARTING_DATE,
	EREENROLL.ENROLLMENT_ENDING_DATE,
	EREENROLL.DISMISSAL_REASON_DESCRIPTION,
	EREENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER,
	EREENROLL.PROGRAM_WORKER_LAST,
	EREENROLL.PROGRAM_WORKER_FIRST,
	EREENROLL.AGENCY_DESCRIPTION,
	ISNULL(IH.MH_HISTORY_COUNT, 0) AS [MH_HISTORY_COUNT],
	ISNULL(IH.SU_HISTORY_COUNT, 0) AS [SU_HISTORY_COUNT],
	ISNULL(IH.PHYSICAL_HISTORY_COUNT, 0)  AS [PHYSICAL_HISTORY_COUNT],
	ISNULL(ND.NEEDS_IDENTIFIED, 0) AS [NEEDS_IDENTIFIED],
	ISNULL(ND.NEEDS_CONNECTED, 0) AS [NEEDS_CONNECTED]
FROM DBO.Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
LEFT JOIN IHNAAGG AS [IH]
	ON EREENROLL.CLIENT_NUMBER   = IH.CLIENT_NUMBER
	AND EREENROLL.TIEDENROLLMENT  = IH.TIEDENROLLMENT
LEFT JOIN NEEDSAGG AS [ND]
	ON EREENROLL.CLIENT_NUMBER   = ND.CLIENT_NUMBER
	AND EREENROLL.TIEDENROLLMENT  = ND.TIEDENROLLMENT
WHERE EREENROLL.PWY_EVENT = 'ERE IHNA'
	AND EREENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND EREENROLL.PWY_FORMS_DOCSERNO IS NOT NULL;