/*
View Name: Q_ERE_LINCS_NAV_REREFERRAL
Category: View Definitions

See docs/view-definitions/q-ere-lincs-nav-rereferrals.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_ERE_LINCS_NAV_REREFERRAL AS
WITH [ERE_NAV_EVENTS] AS (
	SELECT
		A.CLIENT_NUMBER,
		A.CLIENT_LAST,
		A.CLIENT_FIRST,
		A.PROGRAM_WORKER_EMPLOYEE_NUMBER,
		A.PROGRAM_WORKER_LAST,
		A.PROGRAM_WORKER_FIRST,
		A.ENROLLMENT_STARTING_DATE,
		A.ENROLLMENT_ENDING_DATE,
		A.PP_DOCSERNO,
		A.PC_DOCSERNO,
		A.PEC_PATHCLIENT_DOCSERNO,
		A.PATHWAY_ID,
		A.PWY_EVENT,
		A.PE_DATE_ACCOMPLISHED AS REFERRAL_EVENT_DATE
	FROM Q_BHNWIDE_PATHCLIENT_ENROLLMENTS AS [A]
	WHERE
		A.PATHWAY_ID IN (55320250326123001961, 55320240905123251861)
		AND A.PWY_EVENT IN ('ERE Referral', 'LINCS NAV Referral')
),

[ERE_REF_WITH_FORM] AS (
	SELECT
		E.*,
		R.REFERRING_AGENCY_CODE,
		R.REFERRING_AGENCY_DESCRIPTION,
		R.REFERRAL_REASON,
		R.PATIENT_LOCATION_REFERRAL,
		R.DOCSERNO AS [REFERRAL_FORM_DOCSERNO],
		R.PATHWAY_DATE
	FROM ERE_NAV_EVENTS AS [E]
	LEFT JOIN Q_ERE_REFERRAL AS [R]
		ON R.CLIENT_NUMBER = E.CLIENT_NUMBER
		AND R.TIEDENROLLMENT  = E.PC_DOCSERNO
		AND R.EVENT_NAME = E.PWY_EVENT
),

[NAV_REF_FORM] AS (
	SELECT
		E.*,
		R.REFERRING_AGENCY_CODE,
		R.REFERRING_AGENCY_DESCRIPTION,
		R.REFERRAL_REASON,
		R.PATIENT_LOCATION_REFERRAL,
		R.DOCSERNO AS [REFERRAL_FORM_DOCSERNO],
		R.PATHWAY_DATE
	FROM [ERE_NAV_EVENTS] AS [E]
	LEFT JOIN Q_LINCS_NAV_REFERRAL AS [R]
		ON R.CLIENT_NUMBER = E.CLIENT_NUMBER
		AND R.PATHWAY_DATE = E.REFERRAL_EVENT_DATE
	WHERE
		E.PATHWAY_ID = 55320240905123251861   -- LINCS NAV
		AND E.PWY_EVENT = 'LINCS NAV Referral'
),

[ALL_ERE_LINCS_NAV_REFS] AS (
	SELECT ERE.*
	FROM ERE_REF_WITH_FORM AS [ERE]
	UNION
	SELECT NAV.*
	FROM NAV_REF_FORM AS [NAV]
),

[BHN_REF] AS (
	SELECT
		CLIENT_NUMBER,
		COUNT(*) AS [TOTAL_BHN_REFERRALS],
		MAX(ENROLLMENT_STARTING_DATE) AS [LAST_BHN_REFERRAL_DATE]
	FROM Q_PROVIDERPLACEMENT_BHN
	GROUP BY CLIENT_NUMBER
),

[FINAL_WITH_RN] AS (
	SELECT
		F.CLIENT_NUMBER,
		F.CLIENT_LAST,
		F.CLIENT_FIRST,

		-- Identify which program supplies the latest referral
		CASE 
			WHEN F.PATHWAY_ID = 55320250326123001961 THEN 'ERE'
			WHEN F.PATHWAY_ID = 55320240905123251861 THEN 'LINCS NAV'
			ELSE 'Unknown'
		END AS LATEST_REFERRAL_PROGRAM,

		F.ENROLLMENT_STARTING_DATE AS [LATEST_ENROLLMENT_STARTING_DATE],
		F.ENROLLMENT_ENDING_DATE AS [LATEST_ENROLLMENT_ENDING_DATE],
		F.REFERRING_AGENCY_DESCRIPTION AS [LATEST_REFERRING_AGENCY],
		F.PATIENT_LOCATION_REFERRAL AS [LATEST_PATIENT_LOCATION],
		F.REFERRAL_REASON AS [LATEST_REFERRAL_REASON],

		-- Unified housing status (ERE latest + NAV fallback if ERE is absent)
		CASE
			WHEN EREHOUSE.HOUSING_STATUS_INSTITUTIONALLY_HOUSED = 1 THEN 'Institutionally Housed'
			WHEN EREHOUSE.HOUSING_STATUS_PRECARIOUSLY_HOUSED = 1 THEN 'Precariously Housed'
			WHEN EREHOUSE.HOUSING_STATUS_STABLY_HOUSED = 1 THEN 'Stably Housed'
			WHEN EREHOUSE.HOUSING_STATUS_UNHOUSED = 1 THEN 'Unhoused'
			WHEN EREHOUSE.HOUSING_STATUS_UNKNOWN = 1 THEN 'Unknown'
			WHEN NAVREF.HOUSING_STATUS_REFERRAL IS NOT NULL THEN NAVREF.HOUSING_STATUS_REFERRAL
			ELSE 'Unknown'
		END AS [LATEST_HOUSING_STATUS],
		F.PROGRAM_WORKER_LAST,
		F.PROGRAM_WORKER_FIRST,
		F.REFERRAL_FORM_DOCSERNO AS [LATEST_REFERRAL_FORM_DOCSERNO],

		-- Client-level ERE referral metrics
		COUNT(*) OVER (PARTITION BY F.CLIENT_NUMBER) AS [TOTAL_ERE_PLUS_NAV_REFERRALS],
		MAX(F.ENROLLMENT_STARTING_DATE) OVER (PARTITION BY F.CLIENT_NUMBER) AS [LAST_ERE_OR_NAV_REFERRAL_DATE],

		-- Agency-wide referral metrics
		AR.TOTAL_BHN_REFERRALS,
		AR.LAST_BHN_REFERRAL_DATE,

		-- Window function to pick the latest referral per client
		ROW_NUMBER() OVER (
			PARTITION BY F.CLIENT_NUMBER
			ORDER BY F.ENROLLMENT_STARTING_DATE DESC
		) AS [RN]

	FROM ALL_ERE_LINCS_NAV_REFS AS [F]
	LEFT JOIN Q_ERE_ACTIVE_HOUSING_STATUS AS [EREHOUSE]
		ON EREHOUSE.CLIENT_NUMBER = F.CLIENT_NUMBER
	LEFT JOIN Q_LINCS_NAV_REFERRAL AS [NAVREF]
		ON NAVREF.CLIENT_NUMBER = F.CLIENT_NUMBER
		AND NAVREF.DOCSERNO = F.REFERRAL_FORM_DOCSERNO
	LEFT JOIN BHN_REF AS [AR]
		ON AR.CLIENT_NUMBER = F.CLIENT_NUMBER
)

SELECT RN.CLIENT_NUMBER,
	RN.CLIENT_LAST,
	RN.CLIENT_FIRST,
	RN.LATEST_REFERRAL_PROGRAM,
	RN.LATEST_REFERRING_AGENCY,
	RN.LATEST_REFERRAL_REASON,
	RN.LATEST_REFERRAL_FORM_DOCSERNO,
	RN.TOTAL_ERE_PLUS_NAV_REFERRALS,
	RN.LAST_ERE_OR_NAV_REFERRAL_DATE,
	RN.TOTAL_BHN_REFERRALS,
	RN.LAST_BHN_REFERRAL_DATE
FROM FINAL_WITH_RN AS [RN]
WHERE RN.RN = 1;