/*
View Name: Q_ERE_PATHWAY_FORM_DOCSERNOS  
Category: View Definitions  

See docs/view-definitions/q-ere-pathway-form-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_ERE_PATHWAY_FORM_DOCSERNOS AS
SELECT EREREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREREF.DOCSERNO,
	'ERE Referral' AS [FORM_TYPE]
FROM PWEREREFERRAL AS [EREREF]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = EREREF.CLIENTNUMBER
WHERE EREREF.DOCREVNO = ' 0 '
UNION ALL
SELECT EREIHNA.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREIHNA.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREIHNA.DOCSERNO,
	'ERE IHNA' AS [FORM_TYPE]
FROM PWEREIHNA AS [EREIHNA]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = EREIHNA.CLIENTNUMBER
WHERE EREIHNA.DOCREVNO = ' 0 '
UNION ALL
SELECT ERETHREEM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ERETHREEM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ERETHREEM.DOCSERNO,
	'ERE 3-Month Follow-Up' AS [FORM_TYPE]
FROM PWERETHREEMONTHFOLLOWUP AS [ERETHREEM]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = ERETHREEM.CLIENTNUMBER
WHERE ERETHREEM.DOCREVNO = ' 0 '
UNION ALL
SELECT ERESIXM.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(ERESIXM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	ERESIXM.DOCSERNO,
	'ERE 6-Month Follow-Up' AS [FORM_TYPE]
FROM PWERESIXMONTHFOLLOWUP AS [ERESIXM]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = ERESIXM.CLIENTNUMBER
WHERE ERESIXM.DOCREVNO = ' 0 '
UNION ALL
SELECT EREBHS.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(EREBHS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREBHS.DOCSERNO,
	'ERE BHS' AS [FORM_TYPE]
FROM PWEREBEHAVIORALHEALTHSERVICE AS [EREBHS]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = EREBHS.CLIENTNUMBER
WHERE EREBHS.DOCREVNO = ' 0 ';