/*
View Name: Q_ERE_HOSPITAL_VISIT_NOTE  
Category: View Definitions  

See docs/view-definitions/q-ere-hospital-visit-note.md for full documentation.
*/
USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_ERE_HOSPITAL_VISIT_NOTE AS
SELECT EREHOSP.ID,
	EREHOSP.DOCSERNO,
	EREHOSP.TIEDENROLLMENT,
	CAST(EREHOSP.VISITDT AS DATE) AS [VISITDT],
	EREHOSP.VISITTM,
	EREHOSP.USERID,
	'ERE Hospital Visit Note' AS [EVENT_NAME],
	EREHOSP.PARENTDOCSERNO,
	C.CLIENT_NUMBER,
	CAST(EREHOSP.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREHOSP.ERE_VISIT_HOSP,
	EREHOSP.VISIT_HOSP_OUTCOME,
	EREHOSP.VISIT_HOSP_OUTCOME_OTHER,
	EREHOSP.VISIT_HOSP_NO_OUTCOME,
	EREHOSP.VISIT_HOSP_NO_OUTCOME_OTHER,
	EREHOSP.ERE_NOTES_HVN
FROM BEHAVHEALT_LIVE.DBO.PWEREHOSPITALVISITNOTE AS [EREHOSP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = EREHOSP.CLIENTNUMBER
WHERE EREHOSP.DOCREVNO = ' 0 ';