/*
View Name: Q_ERE_DUPLICATE_PWY_FORMS_W_CHILD_SUM_JOINS  
Category: View Definitions  

See docs/view-definitions/q-ere-duplicate-pwy-forms-w-child-sum-joins.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW .DBO.Q_ERE_DUPLICATE_PWY_FORMS_W_CHILD_SUM_JOINS AS
WITH [DUPES] AS (
	SELECT 
		EREENROLL.CLIENT_NUMBER,
		EREENROLL.PWY_START_DATE,
		EREENROLL.PWY_EVENT,
		EREENROLL.EVENT_START_DATE,
		EREENROLL.TIEDENROLLMENT,
		COUNT(EREENROLL.PWY_FORMS_DOCSERNO) AS [COUNT PWY FORM]
	FROM BEHAVHEALT_LIVE.DBO.Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
	WHERE EREENROLL.TIEDENROLLMENT IS NOT NULL
		AND EREENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	GROUP BY EREENROLL.CLIENT_NUMBER,
		EREENROLL.PWY_START_DATE,
		EREENROLL.PWY_EVENT,
		EREENROLL.EVENT_START_DATE,
		EREENROLL.TIEDENROLLMENT
	HAVING COUNT(EREENROLL.PWY_FORMS_DOCSERNO) > 1
),
[DUPES_DETAIL] AS (
	SELECT 
		EREENROLL.CLIENT_NUMBER,
		EREENROLL.PWY_FORMS_VISIT_DATE,
		EREENROLL.PWY_FORMS_VISIT_TIME,
		EREENROLL.PWY_START_DATE,
		EREENROLL.PWY_EVENT,
		EREENROLL.EVENT_START_DATE,
		EREENROLL.PWY_FORMS_DOCSERNO,
		EREENROLL.TIEDENROLLMENT
	FROM BEHAVHEALT_LIVE.DBO.Q_ERE_PATHCLIENT_ENROLLMENTS AS [EREENROLL]
	INNER JOIN DUPES
		ON EREENROLL.CLIENT_NUMBER = DUPES.CLIENT_NUMBER
		AND EREENROLL.PWY_START_DATE = DUPES.PWY_START_DATE
		AND EREENROLL.PWY_EVENT = DUPES.PWY_EVENT
		AND EREENROLL.EVENT_START_DATE = DUPES.EVENT_START_DATE
		AND EREENROLL.TIEDENROLLMENT = DUPES.TIEDENROLLMENT
),
[HOUSE_CHILD] AS(
	SELECT 
		HOUSE_CHILD.CLIENT_NUMBER,
		HOUSE_CHILD.PARENT_DOCSERNO,
		HOUSE_CHILD.FORM_TYPE AS [PARENT_PWY_EVENT]
	FROM BEHAVHEALT_LIVE.DBO.Q_ERE_ALL_HOUSING_STATUS AS [HOUSE_CHILD]
),
[PAY_CHILD] AS(
	SELECT 
		PAY_CHILD.CLIENT_NUMBER,
		PAY_CHILD.PARENT_DOCSERNO,
		PAY_CHILD.FORM_TYPE AS [PARENT_PWY_EVENT]
	FROM BEHAVHEALT_LIVE.DBO.Q_ERE_ALL_PAYOR_SOURCE AS [PAY_CHILD]
),
[NEEDS_CHILD] AS(
	SELECT 
		NEEDS_CHILD.CLIENT_NUMBER,
		NEEDS_CHILD.PARENT_DOCSERNO,
		NEEDS_CHILD.FORM_TYPE AS [PARENT_PWY_EVENT]
	FROM BEHAVHEALT_LIVE.DBO.Q_ERE_CLIENT_NEEDS AS [NEEDS_CHILD]
)
SELECT DUPES_DETAIL.CLIENT_NUMBER,
	DUPES.[COUNT PWY FORM] AS [DUPE_COUNT],
	DUPES_DETAIL.PWY_START_DATE,
	DUPES_DETAIL.EVENT_START_DATE,
	DUPES_DETAIL.PWY_EVENT AS [PARENT_PWY_EVENT],
	DUPES_DETAIL.PWY_FORMS_VISIT_DATE AS [PARENT_VISIT_DATE],
	DUPES_DETAIL.PWY_FORMS_VISIT_TIME AS [PARENT_VISIT_TIME],
	DUPES_DETAIL.PWY_FORMS_DOCSERNO AS [PARENT_DOCSERNO],
	HOUSE_CHILD.PARENT_DOCSERNO AS [HOUSE_CHILD_DOCSERNO],
	HOUSE_CHILD.PARENT_PWY_EVENT AS [HOUSE_PARENT_EVENT],
	PAY_CHILD.PARENT_DOCSERNO AS [PAY_CHILD_DOCSERNO],
	PAY_CHILD.PARENT_PWY_EVENT AS [PAY_PARENT_EVENT],
	DUPES_DETAIL.TIEDENROLLMENT
FROM DUPES_DETAIL AS [DUPES_DETAIL]
LEFT JOIN HOUSE_CHILD AS [HOUSE_CHILD]
	ON DUPES_DETAIL.PWY_FORMS_DOCSERNO = HOUSE_CHILD.PARENT_DOCSERNO
LEFT JOIN PAY_CHILD AS [PAY_CHILD]
	ON DUPES_DETAIL.PWY_FORMS_DOCSERNO = PAY_CHILD.PARENT_DOCSERNO
LEFT JOIN NEEDS_CHILD AS [NEEDS_CHILD]
	ON DUPES_DETAIL.PWY_FORMS_DOCSERNO = NEEDS_CHILD.PARENT_DOCSERNO
INNER JOIN DUPES AS [DUPES]
	ON DUPES_DETAIL.CLIENT_NUMBER = DUPES.CLIENT_NUMBER
   AND DUPES_DETAIL.PWY_START_DATE = DUPES.PWY_START_DATE
   AND DUPES_DETAIL.PWY_EVENT = DUPES.PWY_EVENT
   AND DUPES_DETAIL.EVENT_START_DATE = DUPES.EVENT_START_DATE
   AND DUPES_DETAIL.TIEDENROLLMENT = DUPES.TIEDENROLLMENT;