/*
View Name: Q_ERE_BHS  
Category: View Definitions  

See docs/view-definitions/q-ere-bhs.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .DBO.Q_ERE_BHS AS
SELECT EREBHS.ID,
	EREBHS.DOCSERNO,
	CAST(EREBHS.VISITDT AS DATE) AS [VISITDT],
	EREBHS.VISITTM,
	EREBHS.USERID,
	'ERE Behavioral Health Service' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(EREBHS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	EREBHS.ADMITTED_TO_SERVICES,
	EREBHS.BH_ADMISSION,
	EREBHS.BH_ADMISSION_AGENCY AS [BH_ADMISSION_AGENCY_CODE],
	CMHC.DESCRIPTION AS [BH_ADMISSION_AGENCY_DESCRIPTION],
	CAST(EREBHS.BH_ADMISSION_DATE AS DATE) AS [BH_ADMISSION_DATE],
	EREBHS.SU_ADMISSION,
	EREBHS.SU_ADMISSION_AGENCY AS [SU_ADMISSION_AGENCY_CODE],
	ADA_SU.DESCRIPTION AS [SU_ADMISSION_AGENCY_DESCRIPTION],
	CAST(EREBHS.SU_ADMISSION_DATE AS DATE) AS [SU_ADMISSION_DATE]
FROM BEHAVHEALT_LIVE.DBO.PWEREBEHAVIORALHEALTHSERVICE AS [EREBHS]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
	ON EREBHS.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.CMHC_AGENCY AS [CMHC]
	ON EREBHS.BH_ADMISSION_AGENCY = CMHC.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.ADA_SU_AGENCY AS [ADA_SU]
	ON EREBHS.SU_ADMISSION_AGENCY = ADA_SU.CODE
WHERE EREBHS.DOCREVNO = ' 0 ';