/*
View Name: Q_LINCS_NAV_BHS  
Category: View Definitions  

See docs/view-definitions/q-lincs-nav-bhs.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_LINCS_NAV_BHS AS
SELECT NAVBHS.ID,
	NAVBHS.DOCSERNO,
	CAST(NAVBHS.VISITDT AS DATE) AS [VISIT_DATE],
	NAVBHS.VISITTM AS [VISIT_TIME],
	NAVBHS.USERID,
	'LINCS NAV Behavioral Health Service' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
    CAST(NAVBHS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	CAST(NAVBHS.DATE_HOSPITAL_DISCHARGE AS DATE) AS [DATE_HOSPITAL_DISCHARGE],
	NAVBHS.BEHAVIORAL_HEALTH_SERVICE_PATH,
	NAVBHS.RECONNECT_TO_CMHC,
	NAVBHS.MH_RECONNECT_AGENCY AS [MH_RECONNECT_AGENCY_CODE],
    CMHC_RECONNECT.DESCRIPTION AS [MH_RECONNECT_AGENCY_DESCRIPTION],
	NAVBHS.RECONNECTED_TO_DM3700,
	NAVBHS.DM_TRANSFER AS [DM_TRANSFER_CODE],
    DM_TRANSFER.DESCRIPTION AS [DM_TRANSFER_DESCRIPTION],
	NAVBHS.ATTEND_BH_INTAKE,
	NAVBHS.MH_INTAKE,
	NAVBHS.MH_INTAKE_AGENCY AS [MH_INTAKE_AGENCY_CODE],
    CMHC_INTAKE.DESCRIPTION AS [MH_INTAKE_AGENCY_DESCRIPTION],
	NAVBHS.MH_INTAKE_OTHER_AGENCY,
	CAST(NAVBHS.MH_INTAKE_DATE AS DATE) AS [MH_INTAKE_DATE],
	NAVBHS.SU_INTAKE,
	NAVBHS.SU_INTAKE_AGENCY AS [SU_INTAKE_AGENCY_CODE],
    ADA_INTAKE.DESCRIPTION AS [SU_INTAKE_AGENCY_DESCRIPTION],
	NAVBHS.SU_INTAKE_OTHER_AGENCY,
	CAST(NAVBHS.SU_INTAKE_DATE AS DATE) AS [SU_INTAKE_DATE],
	NAVBHS.ADMITTED_TO_SERVICES,
	NAVBHS.MH_ADMISSION,
	NAVBHS.MH_ADMISSION_AGENCY AS [MH_ADMISSION_AGENCY_CODE],
    CMHC_ADMISSION.DESCRIPTION AS [MH_ADMISSION_AGENCY_DESCRIPTION],
	NAVBHS.MH_ADMISSION_OTHER_AGENCY,
	CAST(NAVBHS.MH_ADMISSION_DATE AS DATE) AS [MH_ADMISSION_DATE],
	NAVBHS.SU_ADMISSION,
	NAVBHS.SU_ADMISSION_AGENCY AS [SU_ADMISSION_AGENCY_CODE],
    ADA_ADMISSION.DESCRIPTION AS [SU_ADMISSION_AGENCY_DESCRIPTION],
	NAVBHS.SU_ADMISSION_OTHER_AGENCY,
	CAST(NAVBHS.SU_ADMISSION_DATE AS DATE) AS [SU_ADMISSION_DATE],
	NAVBHS.REASON_NOT_ADMITTED,
	NAVBHS.NOT_ADMITTED_CAPACITY_LIM,
	NAVBHS.NOT_ADMITTED_INELIGIBLE,
	NAVBHS.NOT_ADMITTED_OTHER_REASON
FROM PWLINCSNAVBEHAVIORALHEALTHSERVICE AS [NAVBHS]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = NAVBHS.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.CMHC_AGENCY AS [CMHC_RECONNECT]
	ON NAVBHS.MH_RECONNECT_AGENCY = CMHC_RECONNECT.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.CMHC_AGENCY AS [CMHC_INTAKE]
	ON NAVBHS.MH_INTAKE_AGENCY = CMHC_INTAKE.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.CMHC_AGENCY AS [CMHC_ADMISSION]
    ON NAVBHS.MH_ADMISSION_AGENCY = CMHC_ADMISSION.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.ADA_SU_AGENCY AS [ADA_INTAKE]
	ON NAVBHS.SU_INTAKE_AGENCY = ADA_INTAKE.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.ADA_SU_AGENCY AS [ADA_ADMISSION]
    ON NAVBHS.SU_ADMISSION_AGENCY = ADA_ADMISSION.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.CMHC_AGENCY AS [DM_TRANSFER]
    ON NAVBHS.DM_TRANSFER = DM_TRANSFER.CODE
WHERE DOCREVNO = ' 0 '