/*
View Name: Q_LINCS_NAV_PATHCLIENT_ENROLLMENTS  
Category: View Definitions  

See docs/view-definitions/q-lincs-nav-pathclient-enrollments.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

 --ALTER VIEW dbo.Q_LINCS_NAV_PATHCLIENT_ENROLLMENTS AS
SELECT C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	PEC.USERID AS [PEC_USERID],
	PP.DOCSERNO AS [PP_DOCSERNO],
	COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) AS [PC_DOCSERNO],
	PEC.PATHCLIENTDOCSERNO AS [PEC_PATHCLIENT_DOCSERNO],
	--CASE
	--	WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Referral' 
	--	THEN NAVREF.TIEDENROLLMENT
	--	WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Behavioral Health Service' 
	--	THEN NAVBHS.TIEDENROLLMENT
	--END AS [TIEDENROLLMENT],
	--CASE 
	--	WHEN 
	--		CASE
	--			WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Referral' 
	--			THEN NAVREF.TIEDENROLLMENT
	--			WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Behavioral Health Service' 
	--			THEN NAVBHS.TIEDENROLLMENT
	--		END IS NULL 
	--	THEN NULL
	--	WHEN COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) = 
	--		CASE
	--			WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Referral' 
	--			THEN NAVREF.TIEDENROLLMENT
	--			WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Behavioral Health Service' 
	--			THEN NAVBHS.TIEDENROLLMENT
	--		END 
	--	THEN CAST(1 AS BIT)
	--	ELSE CAST(0 AS BIT)
	--END AS [TIEDENROLLMENT_MATCH],
	COALESCE(PC_DOCSERNO.JOIN_TYPE, PC_START.JOIN_TYPE) AS [ENROLL_PATH_JOIN_SOURCE],
	P.PROVIDERNAME AS [AGENCY_DESCRIPTION],
	CAST(COALESCE(PC_DOCSERNO.STARTDATE, PC_START.ENDDATE) AS DATE) AS [PWY_START_DATE],
	CAST(COALESCE(PC_DOCSERNO.ENDDATE, PC_START.ENDDATE) AS DATE) AS [PWY_END_DATE],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Referral' 
		THEN NAVREF.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Behavioral Health Service' 
		THEN NAVBHS.DOCSERNO
	END AS [PWY_FORMS_DOCSERNO],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Referral' 
		THEN NAVREF.VISIT_DATE
		WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Behavioral Health Service' 
		THEN NAVBHS.VISIT_DATE
	END AS [PWY_FORMS_VISIT_DATE],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Referral' 
		THEN NAVREF.VISIT_TIME
		WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Behavioral Health Service' 
		THEN NAVBHS.VISIT_TIME
	END AS [PWY_FORMS_VISIT_TIME],
	CAST(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Referral' 
			THEN NAVREF.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'LINCS NAV Behavioral Health Service' 
			THEN NAVBHS.PATHWAY_DATE
		END AS DATE
	) AS [PATHWAY_DATE],
	DATEADD(
		DAY,
		-PE.EARLYPERIOD,
		CAST(
			PEC.STARTDATE AS DATE
			)
	) AS [EARLIEST_START_DATE],
	CAST(PEC.STARTDATE AS DATE) AS [EVENT_START_DATE],
	CAST(PEC.ENDDATE AS DATE) AS [EVENT_END_DATE],
	DATEADD(
		DAY, PE.LATEPERIOD,
		CAST(
			PEC.ENDDATE AS DATE
			)
	) AS [LATEST_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [PE_DATE_ACCOMPLISHED],
	CASE
		WHEN PEC.DATEACCOMPLISHED IS NULL 
		THEN DATEDIFF(DAY, GETDATE(), PEC.ENDDATE)
	END AS [DAYS_UNTIL_FORM_DUE],
	PEC.CURRENTMESSAGE AS [CURRENT_MESSAGE],
	HR.EMPLOYEENUMBER AS [PROGRAM_WORKER_EMPLOYEE_NUMBER],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST]
FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN Q_LINCS_NAV_CLIENT AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN CLOSINGREASONS AS [CR] 
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN (
	SELECT 
		PC.*,
		'DOCSERNO Join' AS JOIN_TYPE
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS PC_DOCSERNO
	ON PP.CLIENTNUMBER = PC_DOCSERNO.CLIENTNUMBER
	AND PC_DOCSERNO.DOCSERNO = PP.DOCSERNO
LEFT JOIN (
	SELECT 
		PC.*,
		'Enrollment/Pathway Start Date Join' AS JOIN_TYPE
	FROM PATHWAYCLIENT AS PC
	WHERE PC.DOCREVNO = ' 0 '
) AS PC_START
	ON PP.CLIENTNUMBER = PC_START.CLIENTNUMBER
	AND PP.STARTINGDATE = PC_START.STARTDATE
	AND PP.PATHWAY = PC_START.PARENTDOCSERNO
LEFT JOIN PATHWAYEVENTCLIENT AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.PATHCLIENTDOCSERNO = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN PATHWAYEVENT AS [PE] 
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN PATHWAY AS [PWY] 
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
LEFT JOIN Q_PROVIDER AS [P] 
	ON PP.PRIMARYPROVIDERCODE = P.PROVIDERCODE
LEFT JOIN Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN Q_HRFORM AS [HRR]
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
LEFT JOIN Q_LINCS_NAV_REFERRAL AS [NAVREF] 
	ON NAVREF.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240905123251861
	AND NAVREF.PATHWAY_DATE = PEC.DATEACCOMPLISHED
--	AND NAVREF.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND NAVREF.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_LINCS_NAV_BHS AS [NAVBHS] 
	ON NAVBHS.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND NAVBHS.PATHWAY_DATE = PEC.DATEACCOMPLISHED
--	AND NAVBHS.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND NAVBHS.EVENT_NAME = PE.SHORTDESCRIPTION
	AND PP.PATHWAY = 55320240905123251861
WHERE PP.PATHWAY = 55320240905123251861
	AND PEC.CLIENTNUMBER IS NOT NULL
	AND PP.DOCREVNO = ' 0 '
	AND PP.STARTINGDATE >= '2024-07-01';