/*
View Name: Q_LINCS_NAV_REFERRAL
Category: View Definitions  

See docs/view-definitions/q-lincs-nav-referral.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_LINCS_NAV_REFERRAL AS
SELECT NAVREF.ID,
	NAVREF.DOCSERNO,
	CAST(NAVREF.VISITDT AS DATE) AS [VISIT_DATE],
	NAVREF.VISITTM AS [VISIT_TIME],
	NAVREF.USERID,
	'LINCS NAV Referral' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(NAVREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	NAVREF.PATIENT_LOCATION_REFERRAL,
	NAVREF.ANSWERFIRST_CASE_NUM,
	NAVREF.CONTACT_METHOD_AT_REFERRAL,
	NAVREF.CALLER_NAME,
	NAVREF.CALLERS_DIRECT_NUM,
	NAVREF.REFERRING_AGENCY AS [REFERRING_AGENCY_CODE],
	PRS.DESCRIPTION AS [REFERRING_AGENCY_DESCRIPTION],
	NAVREF.REFERRAL_METHOD,
	NAVREF.HOUSING_STATUS_REFERRAL,
	NAVREF.CMHC_STATUS AS [CMHC_STATUS_CODE],
	CIMOR_STATUS.DESCRIPTION AS [CMHC_STATUS_DESCRIPTION],
	NAVREF.CIMOR_CMHC_AGENCY AS [CIMOR_CMHC_AGENCY_CODE],
	CMHC.DESCRIPTION AS [CIMOR_CMHC_AGENCY_DESCRIPTION],
	NAVREF.OTHER_CMHC_AGENCY,
	NAVREF.ADA_SU_STATUS AS [ADA_SU_STATUS_CODE],
	CIMOR_ADA.DESCRIPTION AS [ADA_SU_STATUS_DESCRIPTION],
	NAVREF.CIMOR_ADA_SU_AGENCY AS [CIMOR_ADA_SU_AGENCY_CODE],
	NAVREF.OTHER_ADA_SU_AGENCY,
	NAVREF.DD_STATUS,
	NAVREF.DM3700_STATUS,
	NAVREF.EMPLOYMENT_STATUS_REFERRAL,
	NAVREF.MILITARY_STATUS,
	NAVREF.REFERRAL_REASON,
	NAVREF.PRESENTING_SU_CONCERN,
	NAVREF.OTHER_REFERRAL_REASON,
	NAVREF.NUM_HOSP_PAST_THREE_MONTHS_REF,
	NAVREF.NUM_PRIOR_INPATIENT_HOSP_REF,
	NAVREF.NUM_ER_VISITS_PAST_THREE_MONTHS_REF,
	NAVREF.HISTORY_SERIOUS_MENTAL_ILLNESS,
	NAVREF.LEO_INVOLVEMENT_THIS_VISIT,
	NAVREF.CLIENT_DEAF_OR_HARD_OF_HEARING,
	NAVREF.OUTREACH_ADDITIONAL_INFO,
	NAVREF.CLIENT_PARTICIPATION,
	NAVREF.PROGRAM_PARTICIPATION,
	NAVREF.INELIGIBLE_REASON,
	NAVREF.INELIGIBLE_OTHER_REASON,
	NAVREF.PRESENTING_NOTES_REFERRAL,
	NAVREF.ImportID
FROM PWLINCSNAVREFERRALFORM AS [NAVREF]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = NAVREF.CLIENTNUMBER
LEFT JOIN PROGRAM_REFERRAL_SOURCES AS [PRS]
	ON NAVREF.REFERRING_AGENCY = PRS.CODE
LEFT JOIN CIMOR_STATUS
	ON NAVREF.CMHC_STATUS = CIMOR_STATUS.CODE
LEFT JOIN CMHC_AGENCY AS [CMHC]
	ON NAVREF.CIMOR_CMHC_AGENCY = CMHC.CODE
LEFT JOIN CIMOR_STATUS AS [CIMOR_ADA]
	ON NAVREF.ADA_SU_STATUS = CIMOR_ADA.CODE
LEFT JOIN ADA_SU_AGENCY AS [ADA]
	ON NAVREF.CIMOR_ADA_SU_AGENCY = ADA.CODE
WHERE DOCREVNO = ' 0 ';