/*
View Name: Q_PLACEMENT_PROGRAM_WORKER_HISTORY
Category: View Definitions  

See docs/view-definitions/q-placement-program-worker-history.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_PLACEMENT_PROGRAM_WORKER_HISTORY AS
SELECT WORKER_HISTORY.ID,
	WORKER_HISTORY.DOCSERNO,
	CAST(WORKER_HISTORY.VISITDT AS DATE) AS [VISITDT],
	WORKER_HISTORY.VISITTM,
	WORKER_HISTORY.USERID,
	PP.DOCSERNO AS [PP_DOCSERNO],
	WORKER_HISTORY.PARENTDOCSERNO,
	PP.ENROLLMENT_STARTING_DATE,
	PP.ENROLLMENT_ENDING_DATE,
	WORKER_HISTORY.CLIENTNUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	WORKER_HISTORY.PROGRAM_WORKER AS [PROGRAM_WORKER_CODE],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST],
	CAST(WORKER_HISTORY.BEGIN_DATE AS DATE) AS [BEGIN_DATE],
	CAST(WORKER_HISTORY.END_DATE AS DATE) AS [END_DATE],
	WORKER_HISTORY.CHANGE_REASON AS [CHANGE_REASON_CODE],
	CHANGE.DESCRIPTION AS [CHANGE_REASON_DESCRIPTION]
 FROM BEHAVHEALT_LIVE.DBO.PLACEMENTPROGRAMWORKERHISTORY AS [WORKER_HISTORY]
 INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = WORKER_HISTORY.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_PROVIDERPLACEMENT_BHN AS [PP]
	ON PP.CLIENT_NUMBER = WORKER_HISTORY.CLIENTNUMBER
	AND PP.DOCSERNO = WORKER_HISTORY.PARENTDOCSERNO
LEFT JOIN BEHAVHEALT_LIVE.DBO.CHANGEREASON_BASE AS [CHANGE]
	ON WORKER_HISTORY.CHANGE_REASON = CHANGE.CODE
LEFT JOIN Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = WORKER_HISTORY.PROGRAM_WORKER
WHERE WORKER_HISTORY.DOCREVNO = ' 0 '