/*
View Name: Q_PROVIDER_BHN  
Category: View Definitions  

See docs/view-definitions/q-provider-bhn.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_PROVIDER_BHN AS
SELECT ID,
	DOCSERNO,
	CAST(VISITDT AS DATE) AS [VISITDT],
	VISITTM,
	PROVIDERSTATUS AS [PROVIDER_STATUS],
	PARENTORGANIZATION AS [PARENT_ORGANIZATION_CODE],
	PARENTORGANIZATIONNAME AS [PARENT_ORGANIZATION_NAME],
	PROVIDERCODE AS [PROVIDER_CODE],
	PROVIDERNAME AS [PROVIDER_NAME],
	SITEPROVIDER AS [SITE_PROVIDER],
	MASTERPROVIDER AS [MASTER_PROVIDER],
	ORGANIZATIONTYPE AS [ORGANIZATION_TYPE]
FROM BEHAVHEALT_LIVE.DBO.Q_PROVIDER;