/*
View Name: Q_PROGRAM_AGENCY_BRIDGE  
Category: View Definitions  

See docs/view-definitions/q-program-agency-bridge.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .DBO.Q_PROGRAM_AGENCY_BRIDGE AS
SELECT PROGRAM.PROVIDER_CODE AS [PARENT_ORGANIZATION_CODE],
	PROGRAM.PROVIDER_NAME AS [PARENT_ORGANIZATION_NAME],
	AGENCY.PROVIDER_CODE AS [AGENCY_CODE],
	AGENCY.PROVIDER_NAME AS [AGENCY_NAME],
	AGENCY.PROVIDER_STATUS
FROM Q_PROVIDER_BHN AS [AGENCY]
INNER JOIN PROVIDERHEIRARCHY AS [PH]
	ON PH.PROVIDERCODE = AGENCY.PROVIDER_CODE
	AND PH.ALLOWABLEPROVIDER <> AGENCY.PROVIDER_CODE -- Exclude self-matches
INNER JOIN Q_PROVIDER_BHN AS [PROGRAM]
	ON PH.ALLOWABLEPROVIDER = PROGRAM.PROVIDER_CODE
	AND PROGRAM.PROVIDER_CODE <> '100001' -- Exclude master provider as parent
WHERE AGENCY.ORGANIZATION_TYPE = 'SP'; -- Include only agencies