/*
View Name: Q_PROVIDERPLACEMENT_BHN
Category: View Definitions

See docs/views/q-providerplacement-bhn.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_PROVIDERPLACEMENT_BHN AS
SELECT PP.ID,
	PP.DOCSERNO,
	CAST(PP.VISITDT AS DATE) AS "VISITDT",
	PP.VISITTM,
	PP.USERID,
	PP.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	PP.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(PP.DATEENTERED AS DATE) AS [DATE_ENTERED],
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ORIGINALADMISSIONDATE AS DATE) AS [ORIGINAL_ADMISSION_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	PP.CLOSINGREASON AS [DISMISSAL_REASON_CODE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	PP.SERVICECODE AS [SERVICE_CODE],
	MS.DESCRIPTION AS [SERVICE_DESCRIPTION],
	PP.REGION AS [PROGRAM_CODE],
	P.PROVIDERNAME AS [PROGRAM_DESCRIPTION],
	PP.PRIMARYPROVIDERCODE AS [AGENCY_CODE],
	PP.THEPROVIDERNAME AS [AGENCY_DESCRIPTION],	
	PP.PATHWAY,
	CAST(PP.PATHWAYDATE AS DATE) AS [PATHWAY_DATE],
	PP.PROGRAMWORKER AS [PROGRAM_WORKER]
FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
INNER JOIN Q_PROVIDER AS [P] 
	ON PP.REGION = P.PROVIDERCODE
LEFT JOIN CLOSINGREASONS AS [CR] 
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN MASTERSERVICE AS [MS] 
	ON PP.SERVICECODE = MS.CODE
WHERE PP.DOCREVNO = ' 0 ';