/*
View Name: Q_YERE_ALL_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-yere-all-payor-source.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .dbo.Q_YERE_ALL_PAYOR_SOURCE AS
SELECT YPAY.ID,
	YPAY.DOCSERNO,
	YPAY.DOCREVNO,
	CAST(YPAY.VISITDT AS DATE) AS [VISITDT],
	YPAY.VISITTM,
	YPAY.USERID,
	COALESCE(YIA.PARENTDOCSERNO, YPAY.PARENTDOCSERNO) AS [PARENTDOCSERNO],
	YPF.FORM_TYPE,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(YPAY.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YPAY.PAYOR_SOURCE,
	YPAY.MANAGED_MEDICAID_PROVIDER,
	YPAY.PRIVATE_INSURANCE_PROVIDER,
    YPAY.SHOW_ME_HEALTHY_KIDS,
	CAST(YPAY.PAYOR_SOURCE_START_DATE AS DATE) AS PAYOR_SOURCE_START_DATE,
	CAST(YPAY.PAYOR_SOURCE_END_DATE AS DATE) AS PAYOR_SOURCE_END_DATE
FROM BEHAVHEALT_LIVE.DBO.PWPAYORSOURCE AS [YPAY]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON YPAY.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN PWYEREINITIALCONTACT AS [YIA]
	ON YPAY.CLIENTNUMBER = YIA.CLIENTNUMBER
	AND YPAY.PATHWAY_DATE = YIA.PATHWAY_DATE
	AND YPAY.USERID LIKE 'import%'
LEFT JOIN Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	ON COALESCE(YPAY.PARENTDOCSERNO, YIA.DOCSERNO) = YPF.DOCSERNO
WHERE YPAY.DOCREVNO = ' 0 '
	AND COALESCE(YPAY.PARENTDOCSERNO, YIA.DOCSERNO) IN (
			SELECT YPF.DOCSERNO 
			FROM Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	);