/*
View Name: Q_YERE_THIRTY_DAY
Category: View Definitions  

See docs/view-definitions/q-yere-thirty-day.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_YERE_THIRTY_DAY AS
SELECT YTHIRTYD.ID,
	YTHIRTYD.DOCSERNO,
	YTHIRTYD.TIEDENROLLMENT,
	CAST(YTHIRTYD.VISITDT AS DATE) AS [VISITDT],
	YTHIRTYD.VISITTM,
	YTHIRTYD.USERID,
	YTHIRTYD.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'YERE 30 Day' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(YTHIRTYD.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YTHIRTYD.STILL_ACTIVELY_ENGAGED_YERE_THIRTY_DAY,
	YTHIRTYD.METHOD_CONTACT_THIRTY_DAY,
	YTHIRTYD.OTHER_CONTACT_METHOD_THIRTY_DAY,
	YTHIRTYD.RESIDENCY_CHANGE_SINCE_REFERRAL_THIRTY_DAY,
	YTHIRTYD.RESIDENCY_CHANGE_TYPE_THIRTY_DAY,
	YTHIRTYD.SPECIFY_OTHER_RESIDENCY_CHANGE_TYPE_THIRTY_DAY,
	YTHIRTYD.RESIDENCY_CHANGE_ADDRESS_EXISTING_BARRIER_SERVICE_PLAN_GOAL_THIRTY_DAY,
	YTHIRTYD.SCHOOL_CHANGE_THIRTY_DAY,
	YTHIRTYD.ATTEND_BH_INTAKE_BETWEEN_IA_THIRTY_DAY,
	YTHIRTYD.LEGAL_GUARDIAN_MEET_YERE_FAMILY_SUPPORT_SPECIALIST_THIRTY_DAY,
	YTHIRTYD.CASE_STAFFED_YERE_COLLAB_STAFFING_THIRTY_DAY,
	YTHIRTYD.ACTIVELY_ENGAGED_BHS_PAST_THIRTY_DAYS_THIRTY_DAY,
	YTHIRTYD.NOTES_THIRTY_DAY
FROM DBO.PWYERE30DAYFOLLOWUPTP AS [YTHIRTYD]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON YTHIRTYD.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE YTHIRTYD.DOCREVNO = ' 0 ';