/*
View Name: Q_YERE_ACTIVE_PAYOR_SOURCE  
Category: View Definitions  

See docs/view-definitions/q-yere-active-payor-source.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- CREATE VIEW dbo.Q_YERE_ACTIVE_PAYOR_SOURCE AS
WITH ACTIVE_PAYOR_SOURCE AS (
	SELECT 
		YPAY.CLIENTNUMBER,
		COALESCE(YIA.DOCSERNO, YPAY.PARENTDOCSERNO) AS [PARENTDOCSERNO],
		YPAY.PAYOR_SOURCE,
		YPAY.MANAGED_MEDICAID_PROVIDER,
		YPAY.PRIVATE_INSURANCE_PROVIDER,
		YPAY.SHOW_ME_HEALTHY_KIDS,
		YPAY.VISITDT,
		YPAY.VISITTM
	FROM BEHAVHEALT_LIVE.DBO.PWPAYORSOURCE AS [YPAY]
	LEFT JOIN PWYEREINITIALCONTACT AS [YIA]
		ON YPAY.CLIENTNUMBER = YIA.CLIENTNUMBER
		AND YPAY.PATHWAY_DATE = YIA.PATHWAY_DATE
		AND YPAY.USERID LIKE 'import%'
	WHERE YPAY.DOCREVNO = ' 0 '
		AND YPAY.PAYOR_SOURCE_END_DATE IS NULL
),
AGGREGATED_PAYOR_SOURCE AS (
AGGREGATED_PAYOR_SOURCE AS (
	SELECT 
		AGPS.CLIENTNUMBER,
		MAX(AGPS.PARENTDOCSERNO) AS [PARENTDOCSERNO], -- Will not guarantee uniqueness, but aggregation is needed because grouping is applied, and there could be multiple PARENTDOCSERNOs associated with active payor sources.
		MAX(AGPS.MANAGED_MEDICAID_PROVIDER) AS [MANAGED_MEDICAID_PROVIDER],
		MAX(AGPS.PRIVATE_INSURANCE_PROVIDER) AS [PRIVATE_INSURANCE_PROVIDER],
		MAX(AGPS.SHOW_ME_HEALTHY_KIDS) AS [SHOW_ME_HEALTHY_KIDS],
		AGPS.PAYOR_SOURCE,
		1 AS [PAYOR_SOURCE_FLAG] -- Adds a constant column for pivoting
	FROM ACTIVE_PAYOR_SOURCE AS [AGPS]
	WHERE AGPS.PARENTDOCSERNO IN (SELECT YPF.DOCSERNO FROM Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]) -- Filter by Q_YERE_PATHWAY_FORMS view to ensure only relevant YERE records are included.
	GROUP BY AGPS.CLIENTNUMBER, AGPS.PAYOR_SOURCE -- Group by CLIENTNUMBER and PAYOR_SOURCE to aggregate.
),
PIVOTED_PAYOR_SOURCES AS (
	SELECT 
		CLIENTNUMBER,
		MAX(PARENTDOCSERNO) AS [PARENTDOCSERNO], -- Still won't guarantee uniqueness, but needed for pivoting.
		ISNULL(MAX([001]), 0) AS [PAYOR_SOURCE_DUAL_ELIGIBLE],
		ISNULL(MAX([005]), 0) AS [PAYOR_SOURCE_MANAGED_MEDICAID],
		ISNULL(MAX([002]), 0) AS [PAYOR_SOURCE_MEDICAID],
		ISNULL(MAX([003]), 0) AS [PAYOR_SOURCE_MEDICAID_IN_PROGRESS],
		ISNULL(MAX([004]), 0) AS [PAYOR_SOURCE_MEDICAID_CHP],
		ISNULL(MAX([006]), 0) AS [PAYOR_SOURCE_MEDICARE],
		ISNULL(MAX([007]), 0) AS [PAYOR_SOURCE_PRIVATE_INSURANCE],
		ISNULL(MAX([009]), 0) AS [PAYOR_SOURCE_UNINSURED],
		ISNULL(MAX([010]), 0) AS [PAYOR_SOURCE_UNKNOWN_REFUSED],
		ISNULL(MAX([008]), 0) AS [PAYOR_SOURCE_VA_BENEFITS],
		MAX(MANAGED_MEDICAID_PROVIDER) AS [MANAGED_MEDICAID_PROVIDER],
		MAX(PRIVATE_INSURANCE_PROVIDER) AS [PRIVATE_INSURANCE_PROVIDER],
		MAX(SHOW_ME_HEALTHY_KIDS) AS [SHOWME_HEALTHY_KIDS]
	FROM AGGREGATED_PAYOR_SOURCE
	PIVOT (
		MAX(PAYOR_SOURCE_FLAG) FOR PAYOR_SOURCE IN (
			[001], -- Dual Eligible (Medicare & Medicaid)
			[005], -- Managed Medicaid
			[002], -- Medicaid
			[003], -- Medicaid Application In Progress
			[004], -- Medicaid CHP
			[006], -- Medicare
			[007], -- Private Insurance
			[009], -- Uninsured
			[010], -- Unknown/Refused
			[008]  -- VA Benefits
		)
	) AS [PIVOTTABLE]
	GROUP BY CLIENTNUMBER -- Group by CLIENTNUMBER to ensure unique rows per client.
),
LATEST_PARENTDOCSERNO AS (
	SELECT 
		PPS.CLIENTNUMBER,
		MAX(APS.PARENTDOCSERNO) AS [LATEST_PARENTDOCSERNO] -- Retain the latest PARENTDOCSERNO. This should finally ensure uniqueness.
	FROM PIVOTED_PAYOR_SOURCES AS [PPS]
	JOIN ACTIVE_PAYOR_SOURCE AS [APS]
		ON PPS.CLIENTNUMBER = APS.CLIENTNUMBER
	GROUP BY PPS.CLIENTNUMBER
),
FINAL_OUTPUT AS (
	SELECT 
		PPS.CLIENTNUMBER AS [CLIENT_NUMBER],
		LPS.LATEST_PARENTDOCSERNO AS [PARENT_DOCSERNO],
		PPS.PAYOR_SOURCE_DUAL_ELIGIBLE,
		PPS.PAYOR_SOURCE_MANAGED_MEDICAID,
		PPS.PAYOR_SOURCE_MEDICAID,
		PPS.PAYOR_SOURCE_MEDICAID_IN_PROGRESS,
		PPS.PAYOR_SOURCE_MEDICAID_CHP,
		PPS.PAYOR_SOURCE_MEDICARE,
		PPS.PAYOR_SOURCE_PRIVATE_INSURANCE,
		PPS.PAYOR_SOURCE_UNINSURED,
		PPS.PAYOR_SOURCE_UNKNOWN_REFUSED,
		PPS.PAYOR_SOURCE_VA_BENEFITS,
		PPS.MANAGED_MEDICAID_PROVIDER AS [MANAGED_MEDICAID_PROVIDER_CODE],
		MMP.DESCRIPTION AS [MANAGED_MEDICAID_PROVIDER_DESCRIPTION],
		PPS.PRIVATE_INSURANCE_PROVIDER,
		PPS.SHOWME_HEALTHY_KIDS
	FROM PIVOTED_PAYOR_SOURCES AS [PPS]
	JOIN LATEST_PARENTDOCSERNO AS [LPS]
		ON PPS.CLIENTNUMBER = LPS.CLIENTNUMBER
	LEFT JOIN MANAGED_MEDICAID_PROVIDER AS [MMP]
		ON PPS.MANAGED_MEDICAID_PROVIDER = MMP.CODE -- Join to get the description
)
SELECT * FROM FINAL_OUTPUT;