USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_YERE_CAREGIVER_NEEDS AS
SELECT YCARENEEDS.ID,
	YCARENEEDS.DOCSERNO,
	CAST(YCARENEEDS.VISITDT AS DATE) AS [VISITDT],
	YCARENEEDS.VISITTM AS [VISITTM],
	YCARENEEDS.USERID,
	YCARENEEDS.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(YCARENEEDS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YCARENEEDS.CAREGIVER_NEEDS,
	YCARENEEDS.BASIC_NEEDS_ASSISTANCE_CAREGIVER_NEED,
	YCARENEEDS.CRISIS_SERVICES_CAREGIVER_NEED,
	YCARENEEDS.EDUCATIONAL_SERVICES_CAREGIVER_NEED,
	YCARENEEDS.EMPLOYMENT_SERVICES_CAREGIVER_NEED,
	YCARENEEDS.FAMILY_THERAPY_CAREGIVER_NEED,
	YCARENEEDS.HOUSING_CAREGIVER_NEED,
	YCARENEEDS.LEGAL_SERVICES_CAREGIVER_NEED,
	YCARENEEDS.MH_SERVICES_CASE_MGMT_CAREGIVER_NEED,
	YCARENEEDS.MH_SERVICES_ADULT_PSYCHIATRY_CAREGIVER_NEED,
	YCARENEEDS.MH_SERVICES_THERAPY_CAREGIVER_NEED,
	YCARENEEDS.PARENTING_RESOURCES_CAREGIVER_NEED,
	YCARENEEDS.SU_SERVICES_CAREGIVER_NEED,
	YCARENEEDS.SUPPORT_GROUPS_CAREGIVER_NEED,
	YCARENEEDS.NONE_CAREGIVER_NEED,
	YCARENEEDS.CAREGIVER_NEED_BASIC_STATUS,
	YCARENEEDS.CAREGIVER_NEED_CRISIS_SERVICES_STATUS,
	YCARENEEDS.CAREGIVER_NEED_EDU_STATUS,
	YCARENEEDS.CAREGIVER_NEED_EMPLOY_STATUS,
	YCARENEEDS.CAREGIVER_NEED_FAMILY_THERAPY_STATUS,
	YCARENEEDS.CAREGIVER_NEED_HOUSING_STATUS,
	YCARENEEDS.CAREGIVER_NEED_LEGAL_STATUS,
	YCARENEEDS.CAREGIVER_NEED_MH_CASE_MGMT_STATUS,
	YCARENEEDS.CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS,
	YCARENEEDS.CARGIVER_NEED_MG_THERAPY_STATUS,
	YCARENEEDS.CAREGIVER_NEED_PARENTING_STATUS,
	YCARENEEDS.CAREGIVER_NEED_SU_STATUS,
	YCARENEEDS.CAREGIVER_NEED_SUPPORT_GROUP_STATUS
FROM DBO.PWYERECAREGIVERPROGRAMNEEDS AS [YCARENEEDS]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON YCARENEEDS.CLIENTNUMBER = C.CLIENT_NUMBER
WHERE DOCREVNO = ' 0 '