/*
View Name: Q_YERE_BHS  
Category: View Definitions  

See docs/view-definitions/q-yere-bhs.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW .DBO.Q_YERE_BHS AS
SELECT YBHS.ID,
	YBHS.DOCSERNO,
	YBHS.TIEDENROLLMENT,
	CAST(YBHS.VISITDT AS DATE) AS [VISITDT],
	YBHS.VISITTM,
	YBHS.USERID,
	YBHS.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'YERE Behavioral Health Services' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(YBHS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YBHS.OPEN_CMHC_AND_RECONNECTED,
	YBHS.BHS_SERVICE_PATH,
	YBHS.ATTEND_BH_INTAKE,
	YBHS.NUM_DAYS_BH_INTAKE_SINCE_IA,
	YBHS.MH_INTAKE,
	YBHS.MH_INTAKE_AGENCY,
	CMHC.DESCRIPTION AS [MH_INTAKE_AGENCY_DESCRIPTION],
	YBHS.OTHER_MH_INTAKE_AGENCY,
	YBHS.TYPE_MH_INTAKE_THERAPY,
	YBHS.TYPE_MH_INTAKE_CASE_MGMT,
	YBHS.TYPE_MH_INTAKE_PSYCHIATRY,
	YBHS.SU_INTAKE,
	YBHS.SU_INTAKE_AGENCY,
	ADA.DESCRIPTION AS [SU_INTAKE_AGENCY_DESCRIPTION],
	YBHS.OTHER_SU_INTAKE_AGENCY,
	YBHS.ADMITTED_TO_SERVICES,
	YBHS.REASON_NOT_ADMITTED,
	YBHS.REASON_NOT_ADMITTED_CAPACITY,
	YBHS.REASON_NOT_ADMITTED_INELIGIBILITY,
	YBHS.REASON_NOT_ADMITTED_OTHER,
	CAST(YBHS.DATE_ADMITTED_SERVICES AS DATE) AS [DATE_ADMITTED_SERVICES],
	YBHS.ADMITTING_PROGRAM_DMH_OR_NONDMH,
	YBHS.NUM_DAYS_FIRST_BH_SERVICE_SINCE_DATE_ADMISSION
FROM BEHAVHEALT_LIVE.DBO.PWYEREBEHAVIORALHEALTHSERVICESTP AS [YBHS]
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = YBHS.CLIENTNUMBER
LEFT JOIN BEHAVHEALT_LIVE.DBO.CMHC_AGENCY AS [CMHC]
	ON YBHS.MH_INTAKE_AGENCY = CMHC.CODE
LEFT JOIN BEHAVHEALT_LIVE.DBO.ADA_SU_AGENCY AS [ADA]
	ON YBHS.SU_INTAKE_AGENCY = ADA.CODE
WHERE YBHS.DOCREVNO = ' 0 ';