/*
View Name: Q_YERE_NEEDS_REPORT
Category: View Definitions

See docs/view-definitions/q-yere-needs-report.md for full documentation.
*/

--ALTER VIEW DBO.Q_YERE_NEEDS_REPORT AS
WITH [CAREGIVERAGG] AS (
	SELECT 
		CN.PARENT_DOCSERNO,
		(
			SUM(CASE WHEN CN.BASIC_NEEDS_ASSISTANCE_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CRISIS_SERVICES_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.EDUCATIONAL_SERVICES_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.EMPLOYMENT_SERVICES_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.FAMILY_THERAPY_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.HOUSING_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.LEGAL_SERVICES_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.MH_SERVICES_CASE_MGMT_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.MH_SERVICES_ADULT_PSYCHIATRY_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.MH_SERVICES_THERAPY_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.PARENTING_RESOURCES_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.SU_SERVICES_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.SUPPORT_GROUPS_CAREGIVER_NEED = 1 THEN 1 ELSE 0 END)
		) AS [CAREGIVER_NEEDS_IDENTIFIED],
		(
			SUM(CASE WHEN CN.CAREGIVER_NEED_BASIC_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_CRISIS_SERVICES_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_EDU_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_EMPLOY_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_FAMILY_THERAPY_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_HOUSING_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_LEGAL_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_MH_CASE_MGMT_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CARGIVER_NEED_MG_THERAPY_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_PARENTING_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_SU_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN CN.CAREGIVER_NEED_SUPPORT_GROUP_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END)
		) AS [CAREGIVER_NEEDS_CONNECTED]
	FROM DBO.Q_YERE_CAREGIVER_NEEDS AS [CN]
	GROUP BY CN.PARENT_DOCSERNO
),
[YOUTHAGG] AS (
	SELECT 
		YN.PARENT_DOCSERNO,
		(
			SUM(CASE WHEN YN.BASIC_NEEDS_ASSISTANCE_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.CRISIS_SERVICES_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.DENTAL_CARE_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.DEVELOPMENTAL_DISABILITY_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.EDUCATIONAL_SERVICES_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.EMPLOYMENT_SERVICES_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.HOUSING_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.LEGAL_SERVICES_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.MEDICATION_ASSISTANCE_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.PHYSICAL_HEALTH_SERVICES_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.SPECIALIZED_TREATMENT_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.SUPPORT_GROUPS_YOUTH_NEED = 1 THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.TRANSPORTATION_ASSISTANCE_YOUTH_NEED = 1 THEN 1 ELSE 0 END)
		) AS [YOUTH_NEEDS_IDENTIFIED],
		(
			SUM(CASE WHEN YN.YOUTH_NEED_BASIC_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_CRISIS_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_DENTAL_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_DDS_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_EDU_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_EMPLOY_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_HOUSING_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_LEGAL_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_MEDICATION_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_PHYS_HEALTH_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_SPECIALIZED_TX_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_SUPPORT_GROUPS_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END) +
			SUM(CASE WHEN YN.YOUTH_NEED_TRANSPORTATION_STATUS = 'Referral/Assistance Provided; Connected' THEN 1 ELSE 0 END)
		) AS [YOUTH_NEEDS_CONNECTED]
	FROM DBO.Q_YERE_CLIENT_NEEDS AS [YN]
	GROUP BY YN.PARENT_DOCSERNO
)
SELECT 
	YENROLL.CLIENT_NUMBER,
	YENROLL.CLIENT_LAST,
	YENROLL.CLIENT_FIRST,
	YENROLL.ENROLLMENT_STARTING_DATE,
	YENROLL.ENROLLMENT_ENDING_DATE,
	YENROLL.DISMISSAL_REASON_DESCRIPTION,
	YENROLL.PROGRAM_WORKER_EMPLOYEE_NUMBER,
	YENROLL.PROGRAM_WORKER_LAST,
	YENROLL.PROGRAM_WORKER_FIRST,
	YENROLL.AGENCY_DESCRIPTION,
	ISNULL(CA.CAREGIVER_NEEDS_IDENTIFIED,0) AS [CAREGIVER_NEEDS_IDENTIFIED],
	ISNULL(CA.CAREGIVER_NEEDS_CONNECTED,0) AS [CAREGIVER_NEEDS_CONNECTED],
	ISNULL(YA.YOUTH_NEEDS_IDENTIFIED,0) AS [YOUTH_NEEDS_IDENTIFIED],
	ISNULL(YA.YOUTH_NEEDS_CONNECTED,0) AS [YOUTH_NEEDS_CONNECTED]
FROM DBO.Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
LEFT JOIN CAREGIVERAGG AS [CA]
	ON YENROLL.PWY_FORMS_DOCSERNO = CA.PARENT_DOCSERNO
LEFT JOIN YOUTHAGG AS [YA]
	ON YENROLL.PWY_FORMS_DOCSERNO = YA.PARENT_DOCSERNO
WHERE YENROLL.PWY_EVENT = 'YERE Initial Assessment'
	AND YENROLL.ENROLLMENT_STARTING_DATE >= '2024-07-01'
	AND YENROLL.PWY_FORMS_DOCSERNO IS NOT NULL