/*
View Name: Q_YERE_ALL_HOUSING_STATUS  
Category: View Definitions  

See docs/view-definitions/q-yere-all-housing-status.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_YERE_ALL_HOUSING_STATUS AS
SELECT HOUSE.ID,
	HOUSE.DOCSERNO,
	CAST(HOUSE.VISITDT AS DATE) AS [VISITDT],
	HOUSE.VISITTM,
	HOUSE.USERID,
	COALESCE(HOUSE.PARENTDOCSERNO, YIA.DOCSERNO) AS [PARENT_DOCSERNO],
	YPF.FORM_TYPE,
	C.CLIENT_NUMBER,
	C.CLIENT_FIRST,
	C.CLIENT_LAST,
	CAST(HOUSE.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	HOUSE.CLIENT_HOUSING_STATUS,
	HOUSE.IF_UNHOUSED_EXP,
	HOUSE.WORRIED_LOSING_HOUSING,
	CAST(HOUSE.HOUSING_START_DATE AS DATE) AS [HOUSING_START_DATE],
	CAST(HOUSE.HOUSING_END_DATE AS DATE) AS [HOUSING_END_DATE],
	HOUSE.HOMELESS_HOUSING_INSECURE_ETO,
	CASE
		WHEN ISNULL(HOUSE.CLIENT_HOUSING_STATUS, '0') = 'Institutionally Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_INSTITUTIONALLY_HOUSED],
	CASE
		WHEN ISNULL(HOUSE.CLIENT_HOUSING_STATUS, '0') = 'Precariously Housed'  
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_PRECARIOUSLY_HOUSED],
	CASE
		WHEN ISNULL(HOUSE.CLIENT_HOUSING_STATUS, '0') = 'Stably Housed' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_STABLY_HOUSED],
	CASE
		WHEN ISNULL(HOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unhoused' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNHOUSED],
	CASE
		WHEN ISNULL(HOUSE.CLIENT_HOUSING_STATUS, '0') = 'Unknown' 
		THEN 1 
		ELSE 0 
	END AS [HOUSING_STATUS_UNKNOWN]
FROM BEHAVHEALT_LIVE.DBO.PWHOUSINGSTATUS AS [YHOUSE]
INNER JOIN Q_CLIENT_BHN AS [C]
	ON YHOUSE.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN Q_YERE_IA AS [YIA]
	ON YHOUSE.CLIENTNUMBER = YIA.CLIENT_NUMBER
	AND YHOUSE.PATHWAY_DATE = YIA.PATHWAY_DATE
	AND YHOUSE.USERID LIKE 'import%'
LEFT JOIN Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	ON COALESCE(YHOUSE.PARENTDOCSERNO, YIA.DOCSERNO) = YPF.DOCSERNO
WHERE YHOUSE.DOCREVNO = ' 0 '
	AND COALESCE(YHOUSE.PARENTDOCSERNO, YIA.DOCSERNO) IN (
			SELECT YPF.DOCSERNO 
			FROM Q_YERE_PATHWAY_FORM_DOCSERNOS AS [YPF]
	);