/*
View Name: Q_YERE_HOSPITAL_VISIT  
Category: View Definitions  

See docs/view-definitions/q-yere-hospital-visit.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_YERE_HOSPITAL_VISIT AS
SELECT HOSP.ID,
	HOSP.DOCSERNO,
	CAST(HOSP.VISITDT AS DATE) AS [VISITDT],
	HOSP.VISITTM,
	HOSP.USERID,
	HOSP.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'YERE Hospital Visit Note' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(HOSP.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	HOSP.CLIENT_STATUS_HVN,
	HOSP.YERE_VISIT_HOSP,
	HOSP.HOSP_FTF,
	HOSP.HOSP_FTF_YOUTH,
	HOSP.HOSP_FTF_REFERRING_STAFF,
	HOSP.HOSP_FTF_CAREGIVER,
	HOSP.HOSP_FTF_OTHER,
	HOSP.OTHER_FTF,
	HOSP.NO_HOSP_VISIT_REASON,
	HOSP.OTHER_REASON_NOT_FTF,
	HOSP.NOTES_HVN
FROM BEHAVHEALT_LIVE.DBO.PWYEREHOSPITALVISITNOTE AS [HOSP]
INNER JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = HOSP.CLIENTNUMBER
WHERE HOSP.DOCREVNO = ' 0 ';