/*
View Name: Q_YERE_CLIENT_NEEDS  
Category: View Definitions  

See docs/view-definitions/q-yere-client-needs.md for full documentation.
*/
USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW DBO.Q_YERE_CLIENT_NEEDS AS
SELECT YERECLIENTNEEDS.ID,
	YERECLIENTNEEDS.DOCSERNO,
	CAST(YERECLIENTNEEDS.VISITDT AS DATE) AS [VISIT_DATE],
	YERECLIENTNEEDS.VISITTM AS [VISIT_TIME],
	YERECLIENTNEEDS.USERID,
	YERECLIENTNEEDS.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	YERECLIENTNEEDS.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(YERECLIENTNEEDS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YERECLIENTNEEDS.YOUTH_NEED_BASIC_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_CRISIS_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_DENTAL_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_DDS_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_EDU_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_EMPLOY_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_HOUSING_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_LEGAL_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_MEDICATION_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_PHYS_HEALTH_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_SPECIALIZED_TX_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_SUPPORT_GROUPS_STATUS,
	YERECLIENTNEEDS.YOUTH_NEED_TRANSPORTATION_STATUS,
	YERECLIENTNEEDS.YOUTH_NEEDS,
	YERECLIENTNEEDS.BASIC_NEEDS_ASSISTANCE_YOUTH_NEED,
	YERECLIENTNEEDS.CRISIS_SERVICES_YOUTH_NEED,
	YERECLIENTNEEDS.DENTAL_CARE_YOUTH_NEED,
	YERECLIENTNEEDS.DEVELOPMENTAL_DISABILITY_YOUTH_NEED,
	YERECLIENTNEEDS.EDUCATIONAL_SERVICES_YOUTH_NEED,
	YERECLIENTNEEDS.EMPLOYMENT_SERVICES_YOUTH_NEED,
	YERECLIENTNEEDS.HOUSING_YOUTH_NEED,
	YERECLIENTNEEDS.LEGAL_SERVICES_YOUTH_NEED,
	YERECLIENTNEEDS.MEDICATION_ASSISTANCE_YOUTH_NEED,
	YERECLIENTNEEDS.PHYSICAL_HEALTH_SERVICES_YOUTH_NEED,
	YERECLIENTNEEDS.SPECIALIZED_TREATMENT_YOUTH_NEED,
	YERECLIENTNEEDS.SUPPORT_GROUPS_YOUTH_NEED,
	YERECLIENTNEEDS.TRANSPORTATION_ASSISTANCE_YOUTH_NEED,
	YERECLIENTNEEDS.NONE_YOUTH_NEED
FROM BEHAVHEALT_LIVE.dbo.PWYERECLIENTNONBEHAVIORALNEEDSSUM AS [YERECLIENTNEEDS]
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = YERECLIENTNEEDS.CLIENTNUMBER
WHERE YERECLIENTNEEDS.DOCREVNO = ' 0 ';