/*
View Name: Q_YERE_CLIENT_FAMILY_NEEDS  
Category: View Definitions  

See docs/view-definitions/q-yere-client-family-needs.md for full documentation.
*/
USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW DBO.Q_YERE_CLIENT_FAMILY_NEEDS AS
SELECT YCFN.ID,
	YCFN.DOCSERNO,
	CAST(YCFN.VISITDT AS DATE) AS [VISIT_DATE],
	YCFN.VISITTM AS [VISIT_TIME],
	YCFN.USERID,
	YCFN.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	YENROLL.TIEDENROLLMENT,
	C.CLIENT_NUMBER,
	YCFN.BASIC_NEEDS_ASSISTANCE_YOUTH_FAMILY_NEED,
	YCFN.CRISIS_SERVICES_YOUTH_FAMILY_NEED,
	YCFN.DENTAL_CARE_YOUTH_FAMILY_NEED,
	YCFN.DEVELOPMENTAL_DISABILITY_YOUTH_FAMILY_NEED,
	YCFN.EDUCATIONAL_SERVICES_YOUTH_FAMILY_NEED,
	YCFN.EMPLOYMENT_SERVICES_YOUTH_FAMILY_NEED,
	YCFN.FAMILY_MENTAL_HEALTH_YOUTH_FAMILY_NEED,
	YCFN.FAMILY_THERAPY_YOUTH_FAMILY_NEED,
	YCFN.HOUSING_YOUTH_FAMILY_NEED,
	YCFN.LEGAL_SERVICES_YOUTH_FAMILY_NEED,
	YCFN.MEDICATION_ASSISTANCE_YOUTH_FAMILY_NEED,
	YCFN.PARENT_RESOURCE_YOUTH_FAMILY_NEED,
	YCFN.PHYSICAL_HEALTH_SERVICES_YOUTH_FAMILY_NEED,
	YCFN.SPECIALIZED_TREATMENT_YOUTH_FAMILY_NEED,
	YCFN.SU_SERVICE_YOUTH_FAMILY_NEED,
	YCFN.SUPPORT_GROUPS_YOUTH_FAMILY_NEED,
	CAST(YCFN.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YCFN.YOUTH_FAMILY_NEEDS,
	YCFN.YOUTH_FAMILY_NEED_BASIC_STATUS,
	YCFN.YOUTH_FAMILY_NEED_CRISIS_STATUS,
	YCFN.YOUTH_FAMILY_NEED_DENTAL_STATUS,
	YCFN.YOUTH_FAMILY_NEED_DDS_STATUS,
	YCFN.YOUTH_FAMILY_NEED_EDU_STATUS,
	YCFN.YOUTH_FAMILY_NEED_EMPLOY_STATUS,
	YCFN.YOUTH_FAMILY_NEED_FAMILY_MENTAL_HEALTH_STATUS,
	YCFN.YOUTH_FAMILY_NEED_FAMILY_THERAPY_STATUS,
	YCFN.YOUTH_FAMILY_NEED_HOUSING_STATUS,
	YCFN.YOUTH_FAMILY_NEED_LEGAL_STATUS,
	YCFN.YOUTH_FAMILY_NEED_MEDICATION_STATUS,
	YCFN.YOUTH_FAMILY_NEED_PARENT_RESOURCE_STATUS,
	YCFN.YOUTH_FAMILY_NEED_PHYS_HEALTH_STATUS,
	YCFN.YOUTH_FAMILY_NEED_SPECIALIZED_TX_STATUS,
	YCFN.YOUTH_FAMILY_NEED_SU_SERVICE_STATUS,
	YCFN.YOUTH_FAMILY_NEED_SUPPORT_GROUPS_STATUS
FROM DBO.PWYERECLIENTFAMILYNEEDS AS [YCFN]
INNER JOIN DBO.Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = YCFN.CLIENTNUMBER
LEFT JOIN DBO.Q_YERE_PATHCLIENT_ENROLLMENTS AS [YENROLL]
	ON YENROLL.PWY_FORMS_DOCSERNO = YCFN.PARENTDOCSERNO
WHERE YCFN.DOCREVNO = ' 0 ';