/*
View Name: Q_YERE_NEEDS_UNIFIED
Category: View Definitions  

See docs/view-definitions/q-yere-needs-unified.md for full documentation.
*/

-- CREATE VIEW dbo.Q_YERE_NEEDS_UNIFIED AS
WITH [ALL_NEEDS] AS (
    /* Youth needs */
    SELECT 
        CN.ID AS [SOURCE_ID],
        'youth' AS [SOURCE_FORM],
        CN.CLIENT_NUMBER,
        CN.VISIT_DATE,
        CN.PATHWAY_DATE,
        CN.TIEDENROLLMENT,
        CN.ENROLLMENT_STARTING_DATE,
        CN.ENROLLMENT_ENDING_DATE,
        CN.DOCSERNO,
        CN.PARENT_DOCSERNO,

        CN.BASIC_NEEDS_ASSISTANCE_YOUTH_NEED,
        CN.YOUTH_NEED_BASIC_STATUS,
        CN.CRISIS_SERVICES_YOUTH_NEED,
        CN.YOUTH_NEED_CRISIS_STATUS,
        CN.DENTAL_CARE_YOUTH_NEED,
        CN.YOUTH_NEED_DENTAL_STATUS,
        CN.DEVELOPMENTAL_DISABILITY_YOUTH_NEED,
        CN.YOUTH_NEED_DDS_STATUS,
        CN.EDUCATIONAL_SERVICES_YOUTH_NEED,
        CN.YOUTH_NEED_EDU_STATUS,
        CN.EMPLOYMENT_SERVICES_YOUTH_NEED,
        CN.YOUTH_NEED_EMPLOY_STATUS,
        CN.HOUSING_YOUTH_NEED,
        CN.YOUTH_NEED_HOUSING_STATUS,
        CN.LEGAL_SERVICES_YOUTH_NEED,
        CN.YOUTH_NEED_LEGAL_STATUS,
        CN.MEDICATION_ASSISTANCE_YOUTH_NEED,
        CN.YOUTH_NEED_MEDICATION_STATUS,
        CN.PHYSICAL_HEALTH_SERVICES_YOUTH_NEED,
        CN.YOUTH_NEED_PHYS_HEALTH_STATUS,
        CN.SPECIALIZED_TREATMENT_YOUTH_NEED,
        CN.YOUTH_NEED_SPECIALIZED_TX_STATUS,
        CN.SUPPORT_GROUPS_YOUTH_NEED,
        CN.YOUTH_NEED_SUPPORT_GROUPS_STATUS,
        CN.TRANSPORTATION_ASSISTANCE_YOUTH_NEED,
        CN.YOUTH_NEED_TRANSPORTATION_STATUS,

        /* caregiver-only / client-family-only sources as NULL for youth rows */
        CAST(NULL AS int) AS [BASIC_NEEDS_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_BASIC_STATUS],
        CAST(NULL AS int) AS [CRISIS_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_CRISIS_SERVICES_STATUS],
        CAST(NULL AS int) AS [EDUCATIONAL_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_EDU_STATUS],
        CAST(NULL AS int) AS [EMPLOYMENT_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_EMPLOY_STATUS],
        CAST(NULL AS int) AS [FAMILY_THERAPY_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_FAMILY_THERAPY_STATUS],
        CAST(NULL AS int) AS [HOUSING_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_HOUSING_STATUS],
        CAST(NULL AS int) AS [LEGAL_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_LEGAL_STATUS],
        CAST(NULL AS int) AS [MEDICATION_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MEDICATION_STATUS],
        CAST(NULL AS int) AS [MH_SERVICES_CASE_MGMT_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MH_CASE_MGMT_STATUS],
        CAST(NULL AS int) AS [MH_SERVICES_ADULT_PSYCHIATRY_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS],
        CAST(NULL AS int) AS [MH_SERVICES_THERAPY_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MH_THERAPY_STATUS],
        CAST(NULL AS int) AS [PARENTING_RESOURCES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_PARENTING_STATUS],
        CAST(NULL AS int) AS [SU_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_SU_STATUS],
        CAST(NULL AS int) AS [SUPPORT_GROUPS_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_SUPPORT_GROUP_STATUS],
        CAST(NULL AS int) AS [TRANSPORTATION_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_TRANSPORTATION_STATUS],

        CAST(NULL AS int) AS [BASIC_NEEDS_ASSISTANCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_BASIC_STATUS],
        CAST(NULL AS int) AS [CRISIS_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_CRISIS_STATUS],
        CAST(NULL AS int) AS [DENTAL_CARE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_DENTAL_STATUS],
        CAST(NULL AS int) AS [DEVELOPMENTAL_DISABILITY_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_DDS_STATUS],
        CAST(NULL AS int) AS [EDUCATIONAL_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_EDU_STATUS],
        CAST(NULL AS int) AS [EMPLOYMENT_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_EMPLOY_STATUS],
        CAST(NULL AS int) AS [FAMILY_MENTAL_HEALTH_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_FAMILY_MENTAL_HEALTH_STATUS],
        CAST(NULL AS int) AS [FAMILY_THERAPY_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_FAMILY_THERAPY_STATUS],
        CAST(NULL AS int) AS [HOUSING_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_HOUSING_STATUS],
        CAST(NULL AS int) AS [LEGAL_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_LEGAL_STATUS],
        CAST(NULL AS int) AS [MEDICATION_ASSISTANCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_MEDICATION_STATUS],
        CAST(NULL AS int) AS [PARENT_RESOURCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_PARENT_RESOURCE_STATUS],
        CAST(NULL AS int) AS [PHYSICAL_HEALTH_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_PHYS_HEALTH_STATUS],
        CAST(NULL AS int) AS [SPECIALIZED_TREATMENT_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_SPECIALIZED_TX_STATUS],
        CAST(NULL AS int) AS [SU_SERVICE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_SU_SERVICE_STATUS],
        CAST(NULL AS int) AS [SUPPORT_GROUPS_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_SUPPORT_GROUPS_STATUS],
        CAST(NULL AS int) AS [TRANSPORTATION_ASSISTANCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_TRANSPORTATION_STATUS]

    FROM DBO.Q_YERE_CLIENT_NEEDS AS [CN]

    UNION ALL

    /* Caregiver needs */
    SELECT
        CG.ID AS [SOURCE_ID],
        'caregiver' AS [SOURCE_FORM],
        CG.CLIENT_NUMBER,
        CG.VISIT_DATE,
        CG.PATHWAY_DATE,
        CG.TIEDENROLLMENT,
        CG.ENROLLMENT_STARTING_DATE,
        CG.ENROLLMENT_ENDING_DATE,
        CG.DOCSERNO,
        CG.PARENT_DOCSERNO,

        CAST(NULL AS int) AS [BASIC_NEEDS_ASSISTANCE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_BASIC_STATUS],
        CAST(NULL AS int) AS [CRISIS_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_CRISIS_STATUS],
        CAST(NULL AS int) AS [DENTAL_CARE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_DENTAL_STATUS],
        CAST(NULL AS int) AS [DEVELOPMENTAL_DISABILITY_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_DDS_STATUS],
        CAST(NULL AS int) AS [EDUCATIONAL_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_EDU_STATUS],
        CAST(NULL AS int) AS [EMPLOYMENT_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_EMPLOY_STATUS],
        CAST(NULL AS int) AS [HOUSING_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_HOUSING_STATUS],
        CAST(NULL AS int) AS [LEGAL_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_LEGAL_STATUS],
        CAST(NULL AS int) AS [MEDICATION_ASSISTANCE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_MEDICATION_STATUS],
        CAST(NULL AS int) AS [PHYSICAL_HEALTH_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_PHYS_HEALTH_STATUS],
        CAST(NULL AS int) AS [SPECIALIZED_TREATMENT_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_SPECIALIZED_TX_STATUS],
        CAST(NULL AS int) AS [SUPPORT_GROUPS_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_SUPPORT_GROUPS_STATUS],
        CAST(NULL AS int) AS [TRANSPORTATION_ASSISTANCE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_TRANSPORTATION_STATUS],

        CG.BASIC_NEEDS_ASSISTANCE_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_BASIC_STATUS,
        CG.CRISIS_SERVICES_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_CRISIS_SERVICES_STATUS,
        CG.EDUCATIONAL_SERVICES_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_EDU_STATUS,
        CG.EMPLOYMENT_SERVICES_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_EMPLOY_STATUS,
        CG.FAMILY_THERAPY_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_FAMILY_THERAPY_STATUS,
        CG.HOUSING_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_HOUSING_STATUS,
        CG.LEGAL_SERVICES_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_LEGAL_STATUS,
        CAST(NULL AS int) AS [MEDICATION_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MEDICATION_STATUS],
        CG.MH_SERVICES_CASE_MGMT_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_MH_CASE_MGMT_STATUS,
        CG.MH_SERVICES_ADULT_PSYCHIATRY_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS,
        CG.MH_SERVICES_THERAPY_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_MH_THERAPY_STATUS,
        CG.PARENTING_RESOURCES_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_PARENTING_STATUS,
        CG.SU_SERVICES_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_SU_STATUS,
        CG.SUPPORT_GROUPS_CAREGIVER_NEED,
        CG.CAREGIVER_NEED_SUPPORT_GROUP_STATUS,
        CAST(NULL AS int) AS [TRANSPORTATION_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_TRANSPORTATION_STATUS],

        CAST(NULL AS int) AS [BASIC_NEEDS_ASSISTANCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_BASIC_STATUS],
        CAST(NULL AS int) AS [CRISIS_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_CRISIS_STATUS],
        CAST(NULL AS int) AS [DENTAL_CARE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_DENTAL_STATUS],
        CAST(NULL AS int) AS [DEVELOPMENTAL_DISABILITY_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_DDS_STATUS],
        CAST(NULL AS int) AS [EDUCATIONAL_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_EDU_STATUS],
        CAST(NULL AS int) AS [EMPLOYMENT_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_EMPLOY_STATUS],
        CAST(NULL AS int) AS [FAMILY_MENTAL_HEALTH_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_FAMILY_MENTAL_HEALTH_STATUS],
        CAST(NULL AS int) AS [FAMILY_THERAPY_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_FAMILY_THERAPY_STATUS],
        CAST(NULL AS int) AS [HOUSING_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_HOUSING_STATUS],
        CAST(NULL AS int) AS [LEGAL_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_LEGAL_STATUS],
        CAST(NULL AS int) AS [MEDICATION_ASSISTANCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_MEDICATION_STATUS],
        CAST(NULL AS int) AS [PARENT_RESOURCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_PARENT_RESOURCE_STATUS],
        CAST(NULL AS int) AS [PHYSICAL_HEALTH_SERVICES_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_PHYS_HEALTH_STATUS],
        CAST(NULL AS int) AS [SPECIALIZED_TREATMENT_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_SPECIALIZED_TX_STATUS],
        CAST(NULL AS int) AS [SU_SERVICE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_SU_SERVICE_STATUS],
        CAST(NULL AS int) AS [SUPPORT_GROUPS_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_SUPPORT_GROUPS_STATUS],
        CAST(NULL AS int) AS [TRANSPORTATION_ASSISTANCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_TRANSPORTATION_STATUS]

    FROM DBO.Q_YERE_CAREGIVER_NEEDS AS [CG]

    UNION ALL

    /* Client & family needs */
    SELECT
        CF.ID AS [SOURCE_ID],
        'client_family' AS [SOURCE_FORM],
        CF.CLIENT_NUMBER,
        CF.VISIT_DATE,
        CF.PATHWAY_DATE,
        CF.TIEDENROLLMENT,
        CF.ENROLLMENT_STARTING_DATE,
        CF.ENROLLMENT_ENDING_DATE,
        CF.DOCSERNO,
        CF.PARENT_DOCSERNO,

        CAST(NULL AS int) AS [BASIC_NEEDS_ASSISTANCE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_BASIC_STATUS],
        CAST(NULL AS int) AS [CRISIS_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_CRISIS_STATUS],
        CAST(NULL AS int) AS [DENTAL_CARE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_DENTAL_STATUS],
        CAST(NULL AS int) AS [DEVELOPMENTAL_DISABILITY_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_DDS_STATUS],
        CAST(NULL AS int) AS [EDUCATIONAL_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_EDU_STATUS],
        CAST(NULL AS int) AS [EMPLOYMENT_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_EMPLOY_STATUS],
        CAST(NULL AS int) AS [HOUSING_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_HOUSING_STATUS],
        CAST(NULL AS int) AS [LEGAL_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_LEGAL_STATUS],
        CAST(NULL AS int) AS [MEDICATION_ASSISTANCE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_MEDICATION_STATUS],
        CAST(NULL AS int) AS [PHYSICAL_HEALTH_SERVICES_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_PHYS_HEALTH_STATUS],
        CAST(NULL AS int) AS [SPECIALIZED_TREATMENT_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_SPECIALIZED_TX_STATUS],
        CAST(NULL AS int) AS [SUPPORT_GROUPS_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_SUPPORT_GROUPS_STATUS],
        CAST(NULL AS int) AS [TRANSPORTATION_ASSISTANCE_YOUTH_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_NEED_TRANSPORTATION_STATUS],

        CAST(NULL AS int) AS [BASIC_NEEDS_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_BASIC_STATUS],
        CAST(NULL AS int) AS [CRISIS_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_CRISIS_SERVICES_STATUS],
        CAST(NULL AS int) AS [EDUCATIONAL_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_EDU_STATUS],
        CAST(NULL AS int) AS [EMPLOYMENT_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_EMPLOY_STATUS],
        CAST(NULL AS int) AS [FAMILY_THERAPY_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_FAMILY_THERAPY_STATUS],
        CAST(NULL AS int) AS [HOUSING_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_HOUSING_STATUS],
        CAST(NULL AS int) AS [LEGAL_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_LEGAL_STATUS],
        CAST(NULL AS int) AS [MEDICATION_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MEDICATION_STATUS],
        CAST(NULL AS int) AS [MH_SERVICES_CASE_MGMT_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MH_CASE_MGMT_STATUS],
        CAST(NULL AS int) AS [MH_SERVICES_ADULT_PSYCHIATRY_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS],
        CAST(NULL AS int) AS [MH_SERVICES_THERAPY_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_MH_THERAPY_STATUS],
        CAST(NULL AS int) AS [PARENTING_RESOURCES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_PARENTING_STATUS],
        CAST(NULL AS int) AS [SU_SERVICES_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_SU_STATUS],
        CAST(NULL AS int) AS [SUPPORT_GROUPS_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_SUPPORT_GROUP_STATUS],
        CAST(NULL AS int) AS [TRANSPORTATION_ASSISTANCE_CAREGIVER_NEED],
        CAST(NULL AS varchar(255)) AS [CAREGIVER_NEED_TRANSPORTATION_STATUS],

        CF.BASIC_NEEDS_ASSISTANCE_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_BASIC_STATUS,
        CF.CRISIS_SERVICES_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_CRISIS_STATUS,
        CF.DENTAL_CARE_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_DENTAL_STATUS,
        CF.DEVELOPMENTAL_DISABILITY_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_DDS_STATUS,
        CF.EDUCATIONAL_SERVICES_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_EDU_STATUS,
        CF.EMPLOYMENT_SERVICES_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_EMPLOY_STATUS,
        CF.FAMILY_MENTAL_HEALTH_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_FAMILY_MENTAL_HEALTH_STATUS,
        CF.FAMILY_THERAPY_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_FAMILY_THERAPY_STATUS,
        CF.HOUSING_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_HOUSING_STATUS,
        CF.LEGAL_SERVICES_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_LEGAL_STATUS,
        CF.MEDICATION_ASSISTANCE_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_MEDICATION_STATUS,
        CF.PARENT_RESOURCE_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_PARENT_RESOURCE_STATUS,
        CF.PHYSICAL_HEALTH_SERVICES_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_PHYS_HEALTH_STATUS,
        CF.SPECIALIZED_TREATMENT_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_SPECIALIZED_TX_STATUS,
        CF.SU_SERVICE_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_SU_SERVICE_STATUS,
        CF.SUPPORT_GROUPS_YOUTH_FAMILY_NEED,
        CF.YOUTH_FAMILY_NEED_SUPPORT_GROUPS_STATUS,
        CAST(NULL AS INT) AS [TRANSPORTATION_ASSISTANCE_YOUTH_FAMILY_NEED],
        CAST(NULL AS varchar(255)) AS [YOUTH_FAMILY_NEED_TRANSPORTATION_STATUS]

    FROM DBO.Q_YERE_CLIENT_FAMILY_NEEDS AS [CF]
)

SELECT
    CLIENT_NUMBER,
    MAX(VISIT_DATE) AS [VISIT_DATE],
    MAX(PATHWAY_DATE) AS [PATHWAY_DATE],
    MAX(TIEDENROLLMENT) AS [TIEDENROLLMENT],
    ENROLLMENT_STARTING_DATE,
    MAX(ENROLLMENT_ENDING_DATE) AS [ENROLLMENT_ENDING_DATE],
    MAX(DOCSERNO) AS [DOCSERNO],
    MAX(PARENT_DOCSERNO) AS [PARENT_DOCSERNO],
    MAX(
        CASE
            WHEN SOURCE_FORM = 'youth'
                THEN 1
            ELSE 0
        END) AS [SOURCE_YOUTH],
    MAX(
        CASE
            WHEN SOURCE_FORM = 'caregiver'
                THEN 1
            ELSE 0
        END) AS [SOURCE_CAREGIVER],
    MAX(
        CASE
            WHEN SOURCE_FORM = 'client_family'
                THEN 1
            ELSE 0
        END) AS [SOURCE_CLIENT_FAMILY],

    /* Flags */

    MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN BASIC_NEEDS_ASSISTANCE_YOUTH_FAMILY_NEED
        ELSE COALESCE(BASIC_NEEDS_ASSISTANCE_YOUTH_NEED, BASIC_NEEDS_ASSISTANCE_CAREGIVER_NEED)
    END) AS [BASIC_NEEDS_ASSISTANCE_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN CRISIS_SERVICES_YOUTH_FAMILY_NEED
        ELSE COALESCE(CRISIS_SERVICES_YOUTH_NEED, CRISIS_SERVICES_CAREGIVER_NEED)
    END) AS [CRISIS_SERVICES_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN DENTAL_CARE_YOUTH_FAMILY_NEED
        ELSE DENTAL_CARE_YOUTH_NEED
    END) AS [DENTAL_CARE_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN DEVELOPMENTAL_DISABILITY_YOUTH_FAMILY_NEED
        ELSE DEVELOPMENTAL_DISABILITY_YOUTH_NEED
    END) AS [DEVELOPMENTAL_DISABILITY_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN EDUCATIONAL_SERVICES_YOUTH_FAMILY_NEED
        ELSE COALESCE(EDUCATIONAL_SERVICES_YOUTH_NEED, EDUCATIONAL_SERVICES_CAREGIVER_NEED)
    END) AS [EDUCATIONAL_SERVICES_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN EMPLOYMENT_SERVICES_YOUTH_FAMILY_NEED
        ELSE COALESCE(EMPLOYMENT_SERVICES_YOUTH_NEED, EMPLOYMENT_SERVICES_CAREGIVER_NEED)
    END) AS [EMPLOYMENT_SERVICES_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN FAMILY_MENTAL_HEALTH_YOUTH_FAMILY_NEED
        ELSE COALESCE(MH_SERVICES_CASE_MGMT_CAREGIVER_NEED, MH_SERVICES_ADULT_PSYCHIATRY_CAREGIVER_NEED)
    END) AS [FAMILY_MENTAL_HEALTH_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN FAMILY_THERAPY_YOUTH_FAMILY_NEED
        ELSE COALESCE(FAMILY_THERAPY_CAREGIVER_NEED, MH_SERVICES_THERAPY_CAREGIVER_NEED)
    END) AS [FAMILY_THERAPY_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN HOUSING_YOUTH_FAMILY_NEED
        ELSE COALESCE(HOUSING_YOUTH_NEED, HOUSING_CAREGIVER_NEED)
    END) AS [HOUSING_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN LEGAL_SERVICES_YOUTH_FAMILY_NEED
        ELSE COALESCE(LEGAL_SERVICES_YOUTH_NEED, LEGAL_SERVICES_CAREGIVER_NEED)
    END) AS [LEGAL_SERVICES_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN MEDICATION_ASSISTANCE_YOUTH_FAMILY_NEED
        ELSE COALESCE(MEDICATION_ASSISTANCE_YOUTH_NEED, MEDICATION_ASSISTANCE_CAREGIVER_NEED)
    END) AS [MEDICATION_ASSISTANCE_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN PARENT_RESOURCE_YOUTH_FAMILY_NEED
        ELSE PARENTING_RESOURCES_CAREGIVER_NEED
    END) AS [PARENT_RESOURCE_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN PHYSICAL_HEALTH_SERVICES_YOUTH_FAMILY_NEED
        ELSE PHYSICAL_HEALTH_SERVICES_YOUTH_NEED
    END) AS [PHYSICAL_HEALTH_SERVICES_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN SPECIALIZED_TREATMENT_YOUTH_FAMILY_NEED
        ELSE SPECIALIZED_TREATMENT_YOUTH_NEED
    END) AS [SPECIALIZED_TREATMENT_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN SU_SERVICE_YOUTH_FAMILY_NEED
        ELSE SU_SERVICES_CAREGIVER_NEED
    END) AS [SU_SERVICE_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN SUPPORT_GROUPS_YOUTH_FAMILY_NEED
        ELSE COALESCE(SUPPORT_GROUPS_YOUTH_NEED, SUPPORT_GROUPS_CAREGIVER_NEED)
    END) AS [SUPPORT_GROUPS_YOUTH_FAMILY_NEED],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN TRANSPORTATION_ASSISTANCE_YOUTH_FAMILY_NEED
        ELSE COALESCE(TRANSPORTATION_ASSISTANCE_YOUTH_NEED, TRANSPORTATION_ASSISTANCE_CAREGIVER_NEED)
    END) AS [TRANSPORTATION_ASSISTANCE_YOUTH_FAMILY_NEED],

/* Statuses */

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_BASIC_STATUS
        WHEN YOUTH_NEED_BASIC_STATUS IS NULL AND CAREGIVER_NEED_BASIC_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_BASIC_STATUS IS NULL
            THEN CAREGIVER_NEED_BASIC_STATUS
        WHEN CAREGIVER_NEED_BASIC_STATUS IS NULL
            THEN YOUTH_NEED_BASIC_STATUS
        WHEN YOUTH_NEED_BASIC_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_BASIC_STATUS
        WHEN CAREGIVER_NEED_BASIC_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_BASIC_STATUS
        ELSE YOUTH_NEED_BASIC_STATUS
    END) AS [YOUTH_FAMILY_NEED_BASIC_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_CRISIS_STATUS
        WHEN YOUTH_NEED_CRISIS_STATUS IS NULL AND CAREGIVER_NEED_CRISIS_SERVICES_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_CRISIS_STATUS IS NULL
            THEN CAREGIVER_NEED_CRISIS_SERVICES_STATUS
        WHEN CAREGIVER_NEED_CRISIS_SERVICES_STATUS IS NULL
            THEN YOUTH_NEED_CRISIS_STATUS
        WHEN YOUTH_NEED_CRISIS_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_CRISIS_STATUS
        WHEN CAREGIVER_NEED_CRISIS_SERVICES_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_CRISIS_SERVICES_STATUS
        ELSE YOUTH_NEED_CRISIS_STATUS
    END) AS [YOUTH_FAMILY_NEED_CRISIS_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_DENTAL_STATUS
        ELSE YOUTH_NEED_DENTAL_STATUS
    END) AS [YOUTH_FAMILY_NEED_DENTAL_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_DDS_STATUS
        ELSE YOUTH_NEED_DDS_STATUS
    END) AS [YOUTH_FAMILY_NEED_DDS_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_EDU_STATUS
        WHEN YOUTH_NEED_EDU_STATUS IS NULL AND CAREGIVER_NEED_EDU_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_EDU_STATUS IS NULL
            THEN CAREGIVER_NEED_EDU_STATUS
        WHEN CAREGIVER_NEED_EDU_STATUS IS NULL
            THEN YOUTH_NEED_EDU_STATUS
        WHEN YOUTH_NEED_EDU_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_EDU_STATUS
        WHEN CAREGIVER_NEED_EDU_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_EDU_STATUS
        ELSE YOUTH_NEED_EDU_STATUS
    END) AS [YOUTH_FAMILY_NEED_EDU_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_EMPLOY_STATUS
        WHEN YOUTH_NEED_EMPLOY_STATUS IS NULL AND CAREGIVER_NEED_EMPLOY_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_EMPLOY_STATUS IS NULL
            THEN CAREGIVER_NEED_EMPLOY_STATUS
        WHEN CAREGIVER_NEED_EMPLOY_STATUS IS NULL
            THEN YOUTH_NEED_EMPLOY_STATUS
        WHEN YOUTH_NEED_EMPLOY_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_EMPLOY_STATUS
        WHEN CAREGIVER_NEED_EMPLOY_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_EMPLOY_STATUS
        ELSE YOUTH_NEED_EMPLOY_STATUS
    END) AS [YOUTH_FAMILY_NEED_EMPLOY_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_FAMILY_MENTAL_HEALTH_STATUS
        WHEN CAREGIVER_NEED_MH_CASE_MGMT_STATUS IS NULL AND CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS IS NULL
            THEN NULL
        WHEN CAREGIVER_NEED_MH_CASE_MGMT_STATUS IS NULL
            THEN CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS
        WHEN CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS IS NULL
            THEN CAREGIVER_NEED_MH_CASE_MGMT_STATUS
        WHEN CAREGIVER_NEED_MH_CASE_MGMT_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_MH_CASE_MGMT_STATUS
        WHEN CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_MH_ADULT_PSYCH_STATUS
        ELSE CAREGIVER_NEED_MH_CASE_MGMT_STATUS
    END) AS [YOUTH_FAMILY_NEED_FAMILY_MENTAL_HEALTH_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_FAMILY_THERAPY_STATUS
        WHEN CAREGIVER_NEED_FAMILY_THERAPY_STATUS IS NULL AND CAREGIVER_NEED_MH_THERAPY_STATUS IS NULL
            THEN NULL
        WHEN CAREGIVER_NEED_FAMILY_THERAPY_STATUS IS NULL
            THEN CAREGIVER_NEED_MH_THERAPY_STATUS
        WHEN CAREGIVER_NEED_MH_THERAPY_STATUS IS NULL
            THEN CAREGIVER_NEED_FAMILY_THERAPY_STATUS
        WHEN CAREGIVER_NEED_FAMILY_THERAPY_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_FAMILY_THERAPY_STATUS
        WHEN CAREGIVER_NEED_MH_THERAPY_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_MH_THERAPY_STATUS
        ELSE CAREGIVER_NEED_FAMILY_THERAPY_STATUS
    END) AS [YOUTH_FAMILY_NEED_FAMILY_THERAPY_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_HOUSING_STATUS
        WHEN YOUTH_NEED_HOUSING_STATUS IS NULL AND CAREGIVER_NEED_HOUSING_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_HOUSING_STATUS IS NULL
            THEN CAREGIVER_NEED_HOUSING_STATUS
        WHEN CAREGIVER_NEED_HOUSING_STATUS IS NULL
            THEN YOUTH_NEED_HOUSING_STATUS
        WHEN YOUTH_NEED_HOUSING_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_HOUSING_STATUS
        WHEN CAREGIVER_NEED_HOUSING_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_HOUSING_STATUS
        ELSE YOUTH_NEED_HOUSING_STATUS
    END) AS [YOUTH_FAMILY_NEED_HOUSING_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_LEGAL_STATUS
        WHEN YOUTH_NEED_LEGAL_STATUS IS NULL AND CAREGIVER_NEED_LEGAL_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_LEGAL_STATUS IS NULL
            THEN CAREGIVER_NEED_LEGAL_STATUS
        WHEN CAREGIVER_NEED_LEGAL_STATUS IS NULL
            THEN YOUTH_NEED_LEGAL_STATUS
        WHEN YOUTH_NEED_LEGAL_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_LEGAL_STATUS
        WHEN CAREGIVER_NEED_LEGAL_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_LEGAL_STATUS
        ELSE YOUTH_NEED_LEGAL_STATUS
    END) AS [YOUTH_FAMILY_NEED_LEGAL_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_MEDICATION_STATUS
        WHEN YOUTH_NEED_MEDICATION_STATUS IS NULL AND CAREGIVER_NEED_MEDICATION_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_MEDICATION_STATUS IS NULL
            THEN CAREGIVER_NEED_MEDICATION_STATUS
        WHEN CAREGIVER_NEED_MEDICATION_STATUS IS NULL
            THEN YOUTH_NEED_MEDICATION_STATUS
        WHEN YOUTH_NEED_MEDICATION_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_MEDICATION_STATUS
        WHEN CAREGIVER_NEED_MEDICATION_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_MEDICATION_STATUS
        ELSE YOUTH_NEED_MEDICATION_STATUS
    END) AS [YOUTH_FAMILY_NEED_MEDICATION_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_PARENT_RESOURCE_STATUS
        ELSE CAREGIVER_NEED_PARENTING_STATUS
    END) AS [YOUTH_FAMILY_NEED_PARENT_RESOURCE_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_PHYS_HEALTH_STATUS
        ELSE YOUTH_NEED_PHYS_HEALTH_STATUS
    END) AS [YOUTH_FAMILY_NEED_PHYS_HEALTH_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_SPECIALIZED_TX_STATUS
        ELSE YOUTH_NEED_SPECIALIZED_TX_STATUS
    END) AS [YOUTH_FAMILY_NEED_SPECIALIZED_TX_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_SU_SERVICE_STATUS
        ELSE CAREGIVER_NEED_SU_STATUS
    END) AS [YOUTH_FAMILY_NEED_SU_SERVICE_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_SUPPORT_GROUPS_STATUS
        WHEN YOUTH_NEED_SUPPORT_GROUPS_STATUS IS NULL AND CAREGIVER_NEED_SUPPORT_GROUP_STATUS IS NULL
            THEN NULL
        WHEN YOUTH_NEED_SUPPORT_GROUPS_STATUS IS NULL
            THEN CAREGIVER_NEED_SUPPORT_GROUP_STATUS
        WHEN CAREGIVER_NEED_SUPPORT_GROUP_STATUS IS NULL
            THEN YOUTH_NEED_SUPPORT_GROUPS_STATUS
        WHEN YOUTH_NEED_SUPPORT_GROUPS_STATUS LIKE '%Connected%'
            THEN YOUTH_NEED_SUPPORT_GROUPS_STATUS
        WHEN CAREGIVER_NEED_SUPPORT_GROUP_STATUS LIKE '%Connected%'
            THEN CAREGIVER_NEED_SUPPORT_GROUP_STATUS
        ELSE YOUTH_NEED_SUPPORT_GROUPS_STATUS
    END) AS [YOUTH_FAMILY_NEED_SUPPORT_GROUPS_STATUS],

MAX(CASE
        WHEN SOURCE_FORM = 'client_family'
            THEN YOUTH_FAMILY_NEED_TRANSPORTATION_STATUS
        ELSE YOUTH_NEED_TRANSPORTATION_STATUS
    END) AS [YOUTH_FAMILY_NEED_TRANSPORTATION_STATUS]


FROM ALL_NEEDS
GROUP BY CLIENT_NUMBER, ENROLLMENT_STARTING_DATE;
