/*
View Name: Q_YERE_REFERRAL
Category: View Definitions  

See docs/view-definitions/q-yere-referral.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_YERE_REFERRAL AS
SELECT YREF.ID,
	YREF.DOCSERNO,
	YREF.TIEDENROLLMENT,
	CAST(YREF.VISITDT AS DATE) AS [VISITDT],
	YREF.VISITTM,
	YREF.USERID,
	YREF.PARENTDOCSERNO AS [PARENT_DOCSERNO],
	'YERE Referral' AS [EVENT_NAME],
	C.CLIENT_NUMBER,
	CAST(YREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YREF.ANSWERFIRST_CASE_NUM,
	YREF.TIME_OF_CALL_REF,
	YREF.CALLERS_FIRST_LAST_NAME,
	YREF.CALLERS_DIRECT_PHONE_NUMBER,
	YREF.TRANSFER_FROM_EPICC,
	YREF.YERE_REFERRING_HOSPITAL,
	PRS.DESCRIPTION AS [YERE_REFERRING_HOSPITAL_DESCRIPTION],
	YREF.OTHER_REFERRAL_SOURCE,
	YREF.REFERRED_FROM,
	CAST(YREF.DATE_HOSPITAL_ADMISSION_REFERRAL AS DATE) AS [DATE_HOSPITAL_ADMISSION_REFERRAL],
	YREF.HOUSING_STATUS_REFERRAL,
	YREF.PRIMARY_REASON_REFERRAL,
	YREF.WAS_SUICIDE_ATTEMPT,
	YREF.OTHER_REASON_FOR_REFERRAL,
	YREF.CMHC_STATUS,
	CIMOR_STATUS.DESCRIPTION AS [CMHC_STATUS_DESCRIPTION],
	YREF.CMHC_AGENCY_FOUND,
	CMHC.DESCRIPTION AS [CMHC_AGENCY_FOUND_DESCRIPTION],
	YREF.OTHER_CMHC_FOUND,
	YREF.ADA_SU_STATUS,
	CIMOR_ADA.DESCRIPTION AS [ADA_SU_STATUS_DESCRIPTION],
	YREF.ADA_SU_AGENCY_FOUND,
	ADA.DESCRIPTION AS [ADA_SU_AGENCY_FOUND_DESCRIPTION],
	YREF.OTHER_ADA_AGENCY_FOUND,
	YREF.DD_STATUS,
	YREF.PROGRAM_PARTICIPATION_REFERRAL,
	YREF.INELIGIBLE_REASON_REFERRAL,
	YREF.ImportID
FROM DBO.PWYEREREFERRAL AS [YREF]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON YREF.CLIENTNUMBER = C.CLIENT_NUMBER
LEFT JOIN DBO.PROGRAM_REFERRAL_SOURCES AS [PRS]
	ON YREF.YERE_REFERRING_HOSPITAL = PRS.CODE
LEFT JOIN DBO.CIMOR_STATUS
	ON YREF.CMHC_STATUS = CIMOR_STATUS.CODE
LEFT JOIN DBO.CMHC_AGENCY AS [CMHC]
	ON YREF.CMHC_AGENCY_FOUND = CMHC.CODE
LEFT JOIN DBO.CIMOR_STATUS AS [CIMOR_ADA]
	ON YREF.ADA_SU_STATUS = CIMOR_ADA.CODE
LEFT JOIN DBO.ADA_SU_AGENCY AS [ADA]
	ON YREF.ADA_SU_AGENCY_FOUND = ADA.CODE
WHERE YREF.DOCREVNO = ' 0 ';