/*
View Name: Q_YERE_CLIENT  
Category: View Definitions  

See docs/view-definitions/q-yere-client.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_YERE_CLIENT AS
SELECT DISTINCT C.ID,
	C.DOCSERNO,
	C.VISITDT,
	C.VISITTM,
	C.ENTRY_DATE,
	C.USERID,
	C.CLIENT_STATUS,
	C.CLIENT_INDICATOR,
	C.CLIENT_NUMBER,
	C.CLIENT_NAME,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	C.MI,
	C.SUFFIX,
	C.NICKNAME,
	C.BIRTH_DATE,
	C.GENDER_CODE,
	C.GENDER_DESCRIPTION,
	C.RACE_CODE,
	C.RACE_DESCRIPTION,
	C.ETHNICITY_CODE,
	C.ETHNICITY_DESCRIPTION,
	C.MRN_MERCY,
	C.MRN_BJC,
	C.MRN_SSM,
	C.SSN,
	C.SSN_LAST_FOUR,
	C.STREET,
	C.STREET2,
	C.CITY,
	C.[STATE],
	C.ZIP_CODE,
	C.COUNTY_CODE,
	C.COUNTY_DESCRIPTION,
	C.PRIMARY_PHONE,
	C.CELL_PHONE,
	C.WORK_PHONE,
	C.CLIENT_EMAIL,
	C.FACM
FROM BEHAVHEALT_LIVE.DBO.Q_CLIENT_BHN AS [C]
INNER JOIN Q_PROVIDERPLACEMENT_BHN AS [PP]
	ON C.CLIENT_NUMBER = PP.CLIENT_NUMBER
WHERE PP.PROGRAM_CODE = '100013';