/*
View Name: Q_YERE_PATHWAY_FORM_DOCSERNOS
Category: View Definitions

See docs/view-definitions/q-yere-pathway-form-docsernos.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

--ALTER VIEW dbo.Q_YERE_PATHWAY_FORM_DOCSERNOS AS
SELECT YREF.CLIENTNUMBER AS [CLIENT_NUMBER],
	CAST(YREF.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YREF.DOCSERNO,
	YREF.TIEDENROLLMENT,
	'YERE Referral' AS [FORM_TYPE]
FROM DBO.PWYEREREFERRAL AS [YREF]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YREF.CLIENTNUMBER
WHERE YREF.DOCREVNO = ' 0 '
UNION ALL
SELECT HOSP.CLIENTNUMBER,
	CAST(HOSP.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	HOSP.DOCSERNO,
	HOSP.TIEDENROLLMENT,
	'YERE Hospital Visit Note' AS [FORM_TYPE]
FROM DBO.PWYEREHOSPITALVISITNOTE AS [HOSP]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = HOSP.CLIENTNUMBER
WHERE HOSP.DOCREVNO = ' 0 '
UNION ALL
SELECT YIA.CLIENTNUMBER,
	CAST(YIA.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YIA.DOCSERNO,
	YIA.TIEDENROLLMENT,
	'YERE Initial Contact' AS [FORM_TYPE]
FROM DBO.PWYEREINITIALCONTACT AS [YIA]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YIA.CLIENTNUMBER
WHERE YIA.DOCREVNO = ' 0 '
UNION ALL
SELECT YTHIRTYD.CLIENTNUMBER,
	CAST(YTHIRTYD.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YTHIRTYD.DOCSERNO,
	YTHIRTYD.TIEDENROLLMENT,
	'YERE 30-Day Follow-Up' AS [FORM_TYPE]
FROM DBO.PWYERE30DAYFOLLOWUPTP AS [YTHIRTYD]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YTHIRTYD.CLIENTNUMBER
WHERE YTHIRTYD.DOCREVNO = ' 0 '
UNION ALL
SELECT YTHREEM.CLIENTNUMBER,
	CAST(YTHREEM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YTHREEM.DOCSERNO,
	YTHREEM.TIEDENROLLMENT,
	'YERE 3-Month Follow-Up' AS [FORM_TYPE]
FROM DBO.PWYERE3MONTHFOLLOWUPTP AS [YTHREEM]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YTHREEM.CLIENTNUMBER
WHERE YTHREEM.DOCREVNO = ' 0 '
UNION ALL
SELECT YSIXM.CLIENTNUMBER,
	CAST(YSIXM.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YSIXM.DOCSERNO,
	YSIXM.TIEDENROLLMENT,
	'YERE 6-Month Follow-Up' AS [FORM_TYPE]
FROM DBO.PWYERE6MONTHFOLLOWUPTP AS [YSIXM]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YSIXM.CLIENTNUMBER
WHERE YSIXM.DOCREVNO = ' 0 '
UNION ALL
SELECT YBHS.CLIENTNUMBER,
	CAST(YBHS.PATHWAY_DATE AS DATE) AS [PATHWAY_DATE],
	YBHS.DOCSERNO,
	YBHS.TIEDENROLLMENT,
	'YERE YBHS' AS [FORM_TYPE]
FROM DBO.PWYEREBEHAVIORALHEALTHSERVICESTP AS [YBHS]
INNER JOIN DBO.Q_CLIENT_BHN AS [C]
	ON C.CLIENT_NUMBER = YBHS.CLIENTNUMBER
WHERE YBHS.DOCREVNO = ' 0 ';