/*
View Name: Q_YERE_PATHCLIENT_ENROLLMENTS
Category: View Definitions

See docs/view-definitions/q-yere-pathclient-enrollments.md for full documentation.
*/

USE BEHAVHEALT_LIVE;
GO

-- ALTER VIEW dbo.Q_YERE_PATHCLIENT_ENROLLMENTS AS
SELECT C.CLIENT_NUMBER,
	C.CLIENT_LAST,
	C.CLIENT_FIRST,
	CAST(PP.STARTINGDATE AS DATE) AS [ENROLLMENT_STARTING_DATE],
	CAST(PP.ENDINGDATE AS DATE) AS [ENROLLMENT_ENDING_DATE],
	CR.DESCRIPTION AS [DISMISSAL_REASON_DESCRIPTION],
	PEC.USERID AS [PEC_USERID],
	PEC.LASTUPDATEBY AS [PEC_LAST_UPDATE_BY],
	PP.DOCSERNO AS [PP_DOCSERNO],
	COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) AS [PC_DOCSERNO],
	PEC.PATHCLIENTDOCSERNO AS [PEC_PATHCLIENT_DOCSERNO],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'YERE Referral' 
			THEN YREF.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'YERE Hospital Visit Note' 
			THEN HOSP.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'YERE Initial Assessment' 
			THEN YIA.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'YERE 30 Day' 
			THEN YTHIRTYD.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'YERE 3 Month' 
			THEN YTHREEM.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'YERE 6 Month' 
			THEN YSIXM.TIEDENROLLMENT
			WHEN PE.SHORTDESCRIPTION = 'YERE Behavioral Health Services' 
			THEN YBHS.TIEDENROLLMENT
	END AS [TIEDENROLLMENT],
	CASE 
		WHEN 
			CASE
				WHEN PE.SHORTDESCRIPTION = 'YERE Referral' 
				THEN YREF.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE Hospital Visit Note' 
				THEN HOSP.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE Initial Assessment' 
				THEN YIA.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE 30 Day' 
				THEN YTHIRTYD.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE 3 Month' 
				THEN YTHREEM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE 6 Month' 
				THEN YSIXM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE Behavioral Health Services' 
				THEN YBHS.TIEDENROLLMENT
			END IS NULL 
		THEN NULL
		WHEN COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO) = 
			CASE
				WHEN PE.SHORTDESCRIPTION = 'YERE Referral' 
				THEN YREF.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE Hospital Visit Note' 
				THEN HOSP.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE Initial Assessment' 
				THEN YIA.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE 30 Day' 
				THEN YTHIRTYD.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE 3 Month' 
				THEN YTHREEM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE 6 Month' 
				THEN YSIXM.TIEDENROLLMENT
				WHEN PE.SHORTDESCRIPTION = 'YERE Behavioral Health Services' 
				THEN YBHS.TIEDENROLLMENT
			END 
		THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS [TIEDENROLLMENT_MATCH],
	COALESCE(PC_DOCSERNO.JOIN_TYPE, PC_START.JOIN_TYPE) AS [ENROLL_PATH_JOIN_SOURCE],
	P.PROVIDERNAME AS [AGENCY_DESCRIPTION],
	CAST(COALESCE(PC_DOCSERNO.STARTDATE, PC_START.ENDDATE) AS DATE) AS [PWY_START_DATE],
	CAST(COALESCE(PC_DOCSERNO.ENDDATE, PC_START.ENDDATE) AS DATE) AS [PWY_END_DATE],
	PE.SHORTDESCRIPTION AS [PWY_EVENT],
	CASE
		WHEN PE.SHORTDESCRIPTION = 'YERE Referral' 
		THEN YREF.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'YERE Hospital Visit Note' 
		THEN HOSP.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'YERE Initial Assessment' 
		THEN YIA.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'YERE 30 Day' 
		THEN YTHIRTYD.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'YERE 3 Month' 
		THEN YTHREEM.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'YERE 6 Month' 
		THEN YSIXM.DOCSERNO
		WHEN PE.SHORTDESCRIPTION = 'YERE Behavioral Health Services' 
		THEN YBHS.DOCSERNO
	END AS [PWY_FORMS_DOCSERNO],
	CAST(
		CASE
			WHEN PE.SHORTDESCRIPTION = 'YERE Referral' 
			THEN YREF.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'YERE Hospital Visit Note' 
			THEN HOSP.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'YERE Initial Assessment' 
			THEN YIA.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'YERE 30 Day' 
			THEN YTHIRTYD.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'YERE 3 Month' 
			THEN YTHREEM.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'YERE 6 Month' 
			THEN YSIXM.PATHWAY_DATE
			WHEN PE.SHORTDESCRIPTION = 'YERE Behavioral Health Services' 
			THEN YBHS.PATHWAY_DATE
		END AS DATE
	) AS [PATHWAY_DATE],
	DATEADD(
		DAY,
		-PE.EARLYPERIOD,
		CAST(
			PEC.STARTDATE AS DATE
			)
	) AS [EARLIEST_START_DATE],
	CAST(PEC.STARTDATE AS DATE) AS [EVENT_START_DATE],
	CAST(PEC.ENDDATE AS DATE) AS [EVENT_END_DATE],
	DATEADD(
		DAY, PE.LATEPERIOD,
		CAST(
			PEC.ENDDATE AS DATE
			)
	) AS [LATEST_END_DATE],
	CAST(PEC.DATEACCOMPLISHED AS DATE) AS [PE_DATE_ACCOMPLISHED],
	CASE
		WHEN PEC.DATEACCOMPLISHED IS NULL 
		THEN DATEDIFF(DAY, GETDATE(), PEC.ENDDATE)
	END AS [DAYS_UNTIL_FORM_DUE],
	PEC.CURRENTMESSAGE AS [CURRENT_MESSAGE],
	HR.EMPLOYEENUMBER AS [PROGRAM_WORKER_EMPLOYEE_NUMBER],
	HR.LASTNAME AS [PROGRAM_WORKER_LAST],
	HR.FIRSTNAME AS [PROGRAM_WORKER_FIRST]
FROM BEHAVHEALT_LIVE.DBO.PROVIDERPLACEMENT AS [PP]
INNER JOIN Q_CLIENT_BHN AS [C] 
	ON C.CLIENT_NUMBER = PP.CLIENTNUMBER
LEFT JOIN CLOSINGREASONS AS [CR] 
	ON PP.CLOSINGREASON = CR.CODE
LEFT JOIN (
	SELECT 
		PC.*,
		'DOCSERNO Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_DOCSERNO]
	ON PP.CLIENTNUMBER = PC_DOCSERNO.CLIENTNUMBER
	AND PC_DOCSERNO.DOCSERNO = PP.DOCSERNO
LEFT JOIN (
	SELECT 
		PC.*,
		'Enrollment/Pathway Start Date Join' AS [JOIN_TYPE]
	FROM PATHWAYCLIENT AS [PC]
	WHERE PC.DOCREVNO = ' 0 '
) AS [PC_START]
	ON PP.CLIENTNUMBER = PC_START.CLIENTNUMBER
	AND PP.STARTINGDATE = PC_START.STARTDATE
	AND PP.PATHWAY = PC_START.PARENTDOCSERNO
LEFT JOIN PATHWAYEVENTCLIENT AS [PEC]
	ON C.CLIENT_NUMBER = PEC.CLIENTNUMBER
	AND PEC.PATHCLIENTDOCSERNO = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PEC.DOCREVNO = ' 0 '
INNER JOIN PATHWAYEVENT AS [PE] 
	ON PEC.EVENTDOCSERNO = PE.DOCSERNO
	AND PE.DOCREVNO = ' 0 '
INNER JOIN PATHWAY AS [PWY] 
	ON PEC.PARENTDOCSERNO = PWY.DOCSERNO
	AND PWY.DOCREVNO = ' 0 '
LEFT JOIN Q_PROVIDER AS [P] 
	ON PP.PRIMARYPROVIDERCODE = P.PROVIDERCODE
LEFT JOIN Q_HRFORM AS [HR]
	ON HR.EMPLOYEENUMBER = PP.PROGRAMWORKER
LEFT JOIN Q_HRFORM AS [HRR]
	ON HRR.EMPLOYEENUMBER = HR.EMPSUPERVISOR
LEFT JOIN Q_YERE_REFERRAL AS [YREF] 
	ON YREF.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807125033701
--	AND YREF.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND YREF.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND YREF.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN Q_YERE_IA AS [YIA] 
	ON YIA.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807125033701
--	AND YIA.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND YIA.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND YIA.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN Q_YERE_THIRTY_DAY AS [YTHIRTYD] 
	ON YTHIRTYD.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807125033701
--	AND YTHIRTYD.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND YTHIRTYD.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND YTHIRTYD.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN Q_YERE_THREE_MONTH AS [YTHREEM] 
	ON YTHREEM.CLIENT_NUMBER = PP.CLIENTNUMBER
	AND PP.PATHWAY = 55320240807125033701
--	AND YTHREEM.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND YTHREEM.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND YTHREEM.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN Q_YERE_SIX_MONTH AS [YSIXM] 
	ON YSIXM.CLIENT_NUMBER = PP.CLIENTNUMBER
--	AND YSIXM.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND YSIXM.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND PP.PATHWAY = 55320240807125033701
	AND YSIXM.EVENT_NAME = PE.SHORTDESCRIPTION
LEFT JOIN BEHAVHEALT_LIVE.DBO.Q_YERE_BHS AS [YBHS] 
	ON YBHS.CLIENT_NUMBER = PP.CLIENTNUMBER
--	AND YBHS.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND YBHS.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND YBHS.EVENT_NAME = PE.SHORTDESCRIPTION
	AND PP.PATHWAY = 55320240807125033701
LEFT JOIN Q_YERE_HOSPITAL_VISIT AS [HOSP]
	ON HOSP.CLIENT_NUMBER = PEC.CLIENTNUMBER
--	AND HOSP.PATHWAY_DATE = PEC.DATEACCOMPLISHED
	AND HOSP.TIEDENROLLMENT = COALESCE(PC_DOCSERNO.DOCSERNO, PC_START.DOCSERNO)
	AND HOSP.EVENT_NAME = PE.SHORTDESCRIPTION
	AND PP.PATHWAY = 55320240807125033701
WHERE PP.PATHWAY = 55320240807125033701
	AND PEC.CLIENTNUMBER IS NOT NULL
	AND PP.DOCREVNO = ' 0 ';